import { expect, test } from '@playwright/test'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { backend, id, identity, node, permissions, setIdentity } from './monitoring-targets.fixture'
test('registers, updates, disables and deletes using authoritative saved versions', async ({ page }) => {
  const state = await backend(page)
  await page.goto('/monitoring-targets')
  await page.getByRole('button', { name: '新增采集配置', exact: true }).click()
  await expect(page).toHaveURL(/\/monitoring-targets\/new$/)
  await page.getByTestId('target-node').click()
  await page.getByRole('option', { name: '测试主机', exact: true }).click()
  await page.getByTestId('target-endpoint').fill('https://new.test:9443/metrics')
  await page.getByTestId('target-save').click()
  await expect(page).toHaveURL(new RegExp(`/monitoring-targets/${id}$`))
  await expect(page.getByTestId('target-endpoint')).toHaveValue('https://new.test:9443/metrics')
  expect(state.writes[0].input).toEqual({ subject: { kind: 'node', node_id: node }, monitor_kind: 'host_resources', source: { type: 'node_exporter', endpoint: 'https://new.test:9443/metrics' }, enabled: true })
  await page.getByTestId('target-enabled').click()
  await page.getByTestId('target-save').click()
  // Creation and update notices can coexist; verify the latest update notice.
  await expect(page.locator('.el-message').last()).toContainText('监测目标已保存')
  await expect(page.getByTestId('target-save')).not.toHaveClass(/is-loading/)
  expect(state.writes[1].input.version).toBe(1)
  expect(state.writes[1].input.enabled).toBe(false)
  await page.getByTestId('target-delete').click()
  await page.locator('.el-popconfirm__action .el-button--primary').click()
  await expect(page).toHaveURL(/\/monitoring-targets$/)
  expect(state.writes[2]).toEqual({ method: 'DELETE', input: { version: 2 } })
})
test('retains a conflicting draft and requires explicit reload before another write', async ({ page }) => {
  const state = await backend(page, { conflict: true })
  await page.goto(`/monitoring-targets/${id}`)
  const endpoint = page.getByTestId('target-endpoint')
  await endpoint.fill('https://draft.test:9443/metrics')
  await page.getByTestId('target-save').click()
  await expect(page.getByTestId('target-save-error')).toContainText('草稿已保留')
  await expect(endpoint).toHaveValue('https://draft.test:9443/metrics')
  await expect(page.getByTestId('target-save')).toBeDisabled()
  expect(state.writes).toHaveLength(1)
  await page.getByRole('button', { name: '重新加载配置' }).click()
  await expect(endpoint).toHaveValue('https://node.test:9443/metrics')
  await page.getByTestId('target-save').click()
  await expect(page.getByTestId('target-save')).not.toHaveClass(/is-loading/)
  expect(state.writes[1].input.version).toBe(2)
})
test('read-only access exposes no write actions', async ({ page }) => {
  await backend(page, { identity: identity(['platform.host_node.read', 'monitor.monitoring_target.read']) })
  await page.goto(`/monitoring-targets/${id}`)
  await expect(page.getByTestId('target-endpoint')).toHaveValue('https://node.test:9443/metrics')
  await expect(page.getByTestId('target-save')).toHaveCount(0)
  await expect(page.getByTestId('target-delete')).toHaveCount(0)
  await expect(page.getByRole('button', { name: '新增采集配置' })).toHaveCount(0)
})
for (const [name, value] of [
  ['tenant', identity(permissions, { type: 'tenant', tenant_id: '7' })],
  ['missing node permission', identity(['monitor.monitoring_target.read'])],
  ['service', identity(permissions, { type: 'platform' }, 'service_principal')],
  ['delegated', identity(permissions, { type: 'platform' }, 'user', { id: 'delegation' })]
]) test(`${name} never loads platform targets`, async ({ page }) => {
  const state = await backend(page, { identity: value })
  await page.goto('/monitoring-targets')
  await expect(page.getByTestId('monitoring-targets')).toHaveCount(0)
  expect(state.reads).toHaveLength(0)
})
test('identity switching clears drafts and ignores a delayed list response', async ({ page }) => {
  const state = await backend(page, { holdList: true })
  await page.goto(`/monitoring-targets/${id}`)
  await expect(page.getByTestId('target-endpoint')).toHaveValue('https://node.test:9443/metrics')
  await page.getByTestId('target-endpoint').fill('https://private-draft.test:9443/metrics')
  await setIdentity(page, identity(permissions, { type: 'tenant', tenant_id: '8' }))
  state.release()
  await expect(page.getByTestId('monitoring-targets')).toHaveCount(0)
  await setIdentity(page, identity())
  await expect(page.getByTestId('target-endpoint')).toHaveValue('https://node.test:9443/metrics')
  expect(state.writes).toHaveLength(0)
})
test('unavailable list removes old data and reports failure', async ({ page }) => {
  await backend(page, { unavailable: true })
  await page.goto('/monitoring-targets')
  await expect(page.getByRole('alert')).toContainText('无法加载监测目标')
  await expect(page.locator('.el-table tbody tr')).toHaveCount(0)
})
test('English page restores canonical pagination and fits a narrow viewport', async ({ page }) => {
  await backend(page, { locale: 'en' })
  await page.goto('/monitoring-targets?page=02&endpoint=untrusted')
  await expect(page).toHaveURL(/\/monitoring-targets$/)
  await expect(page.getByRole('heading', { name: 'Collection settings' })).toBeVisible()
  await expect(page.locator('.el-pagination__total')).toContainText('Total')
  await page.screenshot({ path: join(tmpdir(), 'addp-monitor-targets-desktop.png'), animations: 'disabled' })
  await page.setViewportSize({ width: 620, height: 700 })
  await page.getByRole('button', { name: 'Details', exact: true }).click()
  await expect(page.getByTestId('target-endpoint')).toHaveValue('https://node.test:9443/metrics')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: join(tmpdir(), 'addp-monitor-targets-narrow.png'), animations: 'disabled' })
})

test('a host handoff resolves the authoritative name and does not create configuration until save', async ({ page }) => {
  const state = await backend(page)
  await page.goto(`/monitoring-targets/new?node_id=${node}`)
  await expect(page.getByTestId('target-node')).toContainText('测试主机')
  expect(state.writes).toHaveLength(0)
  await page.getByTestId('target-endpoint').fill('https://new.test:9443/metrics')
  await page.getByTestId('target-save').click()
  await expect.poll(() => state.writes.length).toBe(1)
  expect(state.writes[0].input.subject.node_id).toBe(node)
})
test('unavailable System host evidence cannot submit a copied reference', async ({ page }) => {
  const state = await backend(page, { hostUnavailable: true })
  await page.goto(`/monitoring-targets/new?node_id=${node}`)
  await expect(page.getByRole('alert').filter({ hasText: '无法读取主机' })).toBeVisible()
  await expect(page.getByTestId('target-save')).toHaveCount(0)
  expect(state.writes).toHaveLength(0)
})

const observingIdentity = () => identity([...permissions, 'monitor.resource_observation.read'])
for (const locale of ['zh-cn', 'en']) test(`${locale} collection evidence stays beside settings and refreshes without saving a draft`, async ({ page }) => {
  const state = await backend(page, { locale, identity: observingIdentity() })
  await page.goto(`/monitoring-targets/${id}`)
  const panel = page.getByTestId('target-collection')
  const names = locale === 'en'
    ? ['Latest scrape succeeded', 'Latest scrape failed', 'Collection evidence is stale', 'No scrape evidence yet', 'Host collection is not connected']
    : ['最近抓取成功', '最近抓取失败', '采集证据已过期', '暂无抓取证据', '主机未接入采集']
  const refresh = panel.getByRole('button', { name: locale === 'en' ? 'Refresh collection status' : '刷新采集状态', exact: true })
  await expect(panel).toContainText(names[0])
  await expect(panel).toContainText(locale === 'en' ? 'does not mean every metric has data' : '不代表所有指标都有数据')
  expect(state.collectionReads).toEqual([{ node_id: node, metrics: 'node.memory.total_bytes' }])
  await page.getByTestId('target-endpoint').fill('https://draft.test:9443/metrics')
  await page.getByTestId('target-enabled').click()
  await expect(panel).toContainText(locale === 'en' ? 'the draft has not taken effect' : '草稿尚未生效')
  for (const [index, mode] of ['failed', 'stale', 'no_sample', 'not_connected'].entries()) {
    state.setCollectionMode(mode)
    await refresh.click()
    await expect(panel).toContainText(names[index + 1])
    await expect(panel).not.toContainText(names[0])
    await expect(page.getByTestId('target-endpoint')).toHaveValue('https://draft.test:9443/metrics')
  }
  await page.setViewportSize({ width: 620, height: 700 })
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  expect(state.writes).toHaveLength(0)
  await page.getByTestId('target-save').click()
  await expect(panel).toContainText(locale === 'en' ? 'saved collection settings are disabled' : '已保存的采集配置已停用')
  await expect(refresh).toHaveCount(0)
  expect(state.collectionReads).toHaveLength(5)
})

test('collection failure clears success, preserves configuration editing and can recover', async ({ page }) => {
  const state = await backend(page, { identity: observingIdentity() })
  await page.goto(`/monitoring-targets/${id}`)
  const panel = page.getByTestId('target-collection')
  await expect(panel).toContainText('最近抓取成功')
  await page.getByTestId('target-endpoint').fill('https://draft.test:9443/metrics')
  for (const [mode, text] of [['unavailable', '无法读取资源观测'], ['denied', '当前身份无权查看主机监控']]) {
    state.setCollectionMode(mode)
    await panel.getByRole('button', { name: '刷新采集状态' }).click()
    await expect(panel.getByRole('alert')).toContainText(text)
    await expect(panel).not.toContainText('最近抓取成功')
    await expect(page.getByTestId('target-save')).toBeEnabled()
    await expect(page.getByTestId('target-endpoint')).toHaveValue('https://draft.test:9443/metrics')
  }
  state.setCollectionMode('collecting')
  await panel.getByRole('button', { name: '刷新采集状态' }).click()
  await expect(panel).toContainText('最近抓取成功')
  await expect(panel.getByRole('alert')).toHaveCount(0)
  expect(state.writes).toHaveLength(0)
})

for (const mode of ['wrong-target', 'wrong-version']) test(`${mode} cannot attribute evidence to the displayed saved settings`, async ({ page }) => {
  const state = await backend(page, { identity: observingIdentity(), collectionMode: mode })
  await page.goto(`/monitoring-targets/${id}`)
  const panel = page.getByTestId('target-collection')
  await expect(panel.getByRole('alert')).toContainText('请重新加载配置')
  await expect(panel).not.toContainText('最近抓取成功')
  state.setCollectionMode('collecting')
  await page.getByRole('button', { name: '重新加载配置' }).click()
  await expect(panel).toContainText('最近抓取成功')
  expect(state.writes).toHaveLength(0)
})

for (const [name, options, text] of [
  ['no observation permission', {}, '当前身份无权查看采集结果'],
  ['disabled settings', { identity: observingIdentity(), enabled: false }, '已保存的采集配置已停用'],
  ['container settings', { identity: observingIdentity(), kind: 'container_resources' }, '暂不提供容器资源目标的采集结果']
]) test(`${name} does not query host collection`, async ({ page }) => {
  const state = await backend(page, options)
  await page.goto(`/monitoring-targets/${id}`)
  const panel = page.getByTestId('target-collection')
  await expect(panel).toContainText(text)
  await expect(panel.getByRole('button', { name: '刷新采集状态' })).toHaveCount(0)
  expect(state.collectionReads).toHaveLength(0)
  await expect(page.getByTestId('target-endpoint')).toHaveValue('https://node.test:9443/metrics')
})

test('list and new settings never request collection evidence', async ({ page }) => {
  const state = await backend(page, { identity: observingIdentity() })
  await page.goto('/monitoring-targets')
  await expect(page.locator('.el-pagination__total')).toBeVisible()
  await page.getByRole('button', { name: '新增采集配置', exact: true }).click()
  await expect(page.getByTestId('target-endpoint')).toBeVisible()
  await expect(page.getByTestId('target-collection')).toHaveCount(0)
  expect(state.collectionReads).toHaveLength(0)
})

test('revoked observation access cancels a delayed result without blocking settings', async ({ page }) => {
  const state = await backend(page, { identity: observingIdentity(), holdCollection: true })
  await page.goto(`/monitoring-targets/${id}`)
  const panel = page.getByTestId('target-collection')
  await expect(panel).toContainText('正在读取采集结果')
  await expect(page.getByTestId('target-save')).toBeEnabled()
  await setIdentity(page, identity())
  await expect(panel).toContainText('当前身份无权查看采集结果')
  state.releaseCollection()
  await expect(page.getByTestId('target-endpoint')).toHaveValue('https://node.test:9443/metrics')
  await expect(panel).not.toContainText('最近抓取成功')
  expect(state.collectionReads).toHaveLength(1)
  expect(state.writes).toHaveLength(0)
})

test('an enabled settings save refreshes evidence for the new version and ignores the previous request', async ({ page }) => {
  const state = await backend(page, { identity: observingIdentity(), holdCollection: true })
  await page.goto(`/monitoring-targets/${id}`)
  const panel = page.getByTestId('target-collection')
  await expect(panel).toContainText('正在读取采集结果')
  await page.getByTestId('target-endpoint').fill('https://updated.test:9443/metrics')
  await page.getByTestId('target-save').click()
  await expect.poll(() => state.collectionReads.length).toBe(2)
  state.releaseCollection()
  await expect(panel).toContainText('最近抓取成功')
  await expect(panel.getByRole('alert')).toHaveCount(0)
  await expect(page.getByTestId('target-endpoint')).toHaveValue('https://updated.test:9443/metrics')
  expect(state.writes).toHaveLength(1)
  expect(state.writes[0].input.version).toBe(1)
})

test('a settings reader with observation access can refresh evidence without write controls', async ({ page }) => {
  const state = await backend(page, { identity: identity(['platform.host_node.read', 'monitor.monitoring_target.read', 'monitor.resource_observation.read']) })
  await page.goto(`/monitoring-targets/${id}`)
  const panel = page.getByTestId('target-collection')
  await expect(panel).toContainText('最近抓取成功')
  state.setCollectionMode('failed')
  await panel.getByRole('button', { name: '刷新采集状态' }).click()
  await expect(panel).toContainText('最近抓取失败')
  await expect(page.getByTestId('target-save')).toHaveCount(0)
  await expect(page.getByTestId('target-delete')).toHaveCount(0)
  expect(state.writes).toHaveLength(0)
})
