import { expect, test } from '@playwright/test'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { backend, id, identity, node, permissions, setIdentity } from './monitoring-targets.fixture'
test('registers, updates, disables and deletes using authoritative saved versions', async ({ page }) => {
  const state = await backend(page)
  await page.goto('/monitoring-targets')
  await page.getByRole('button', { name: '登记监测目标', exact: true }).click()
  await expect(page).toHaveURL(/\/monitoring-targets\/new$/)
  await page.getByTestId('target-node').fill(node)
  await page.getByTestId('target-endpoint').fill('https://new.test:9443/metrics')
  await page.getByTestId('target-save').click()
  await expect(page).toHaveURL(new RegExp(`/monitoring-targets/${id}$`))
  await expect(page.getByTestId('target-endpoint')).toHaveValue('https://new.test:9443/metrics')
  expect(state.writes[0].input).toEqual({ subject: { kind: 'node', node_id: node }, monitor_kind: 'host_resources', source: { type: 'node_exporter', endpoint: 'https://new.test:9443/metrics' }, enabled: true })
  await page.getByTestId('target-enabled').click()
  await page.getByTestId('target-save').click()
  await expect(page.locator('.el-message')).toContainText('监测目标已保存')
  await expect(page.getByTestId('target-save')).not.toHaveClass(/is-loading/)
  expect(state.writes[1].input.version).toBe(1)
  expect(state.writes[1].input.enabled).toBe(false)
  await page.getByTestId('target-delete').click()
  await page.locator('.el-popconfirm__action .el-button--primary').click()
  await expect(page).toHaveURL(/\/monitoring-targets$/)
  expect(state.writes[2]).toEqual({ method: 'DELETE', input: { version: 2 } })
})
test('retains a conflicting draft and requires explicit reload before another write', async ({ page }) => {
  const state = await backend(page, { conflict: true })
  await page.goto(`/monitoring-targets/${id}`)
  const endpoint = page.getByTestId('target-endpoint')
  await endpoint.fill('https://draft.test:9443/metrics')
  await page.getByTestId('target-save').click()
  await expect(page.getByTestId('target-save-error')).toContainText('草稿已保留')
  await expect(endpoint).toHaveValue('https://draft.test:9443/metrics')
  await expect(page.getByTestId('target-save')).toBeDisabled()
  expect(state.writes).toHaveLength(1)
  await page.getByRole('button', { name: '重新加载配置' }).click()
  await expect(endpoint).toHaveValue('https://node.test:9443/metrics')
  await page.getByTestId('target-save').click()
  await expect(page.getByTestId('target-save')).not.toHaveClass(/is-loading/)
  expect(state.writes[1].input.version).toBe(2)
})
test('read-only access exposes no write actions', async ({ page }) => {
  await backend(page, { identity: identity(['platform.host_node.read', 'monitor.monitoring_target.read']) })
  await page.goto(`/monitoring-targets/${id}`)
  await expect(page.getByTestId('target-endpoint')).toHaveValue('https://node.test:9443/metrics')
  await expect(page.getByTestId('target-save')).toHaveCount(0)
  await expect(page.getByTestId('target-delete')).toHaveCount(0)
  await expect(page.getByRole('button', { name: '登记监测目标' })).toHaveCount(0)
})
for (const [name, value] of [
  ['tenant', identity(permissions, { type: 'tenant', tenant_id: '7' })],
  ['missing node permission', identity(['monitor.monitoring_target.read'])],
  ['service', identity(permissions, { type: 'platform' }, 'service_principal')],
  ['delegated', identity(permissions, { type: 'platform' }, 'user', { id: 'delegation' })]
]) test(`${name} never loads platform targets`, async ({ page }) => {
  const state = await backend(page, { identity: value })
  await page.goto('/monitoring-targets')
  await expect(page.getByTestId('monitoring-targets')).toHaveCount(0)
  expect(state.reads).toHaveLength(0)
})
test('identity switching clears drafts and ignores a delayed list response', async ({ page }) => {
  const state = await backend(page, { holdList: true })
  await page.goto(`/monitoring-targets/${id}`)
  await expect(page.getByTestId('target-endpoint')).toHaveValue('https://node.test:9443/metrics')
  await page.getByTestId('target-endpoint').fill('https://private-draft.test:9443/metrics')
  await setIdentity(page, identity(permissions, { type: 'tenant', tenant_id: '8' }))
  state.release()
  await expect(page.getByTestId('monitoring-targets')).toHaveCount(0)
  await setIdentity(page, identity())
  await expect(page.getByTestId('target-endpoint')).toHaveValue('https://node.test:9443/metrics')
  expect(state.writes).toHaveLength(0)
})
test('unavailable list removes old data and reports failure', async ({ page }) => {
  await backend(page, { unavailable: true })
  await page.goto('/monitoring-targets')
  await expect(page.getByRole('alert')).toContainText('无法加载监测目标')
  await expect(page.locator('.el-table tbody tr')).toHaveCount(0)
})
test('English page restores canonical pagination and fits a narrow viewport', async ({ page }) => {
  await backend(page, { locale: 'en' })
  await page.goto('/monitoring-targets?page=02&endpoint=untrusted')
  await expect(page).toHaveURL(/\/monitoring-targets$/)
  await expect(page.getByRole('heading', { name: 'Platform monitoring targets' })).toBeVisible()
  await expect(page.locator('.el-pagination__total')).toContainText('Total')
  await page.screenshot({ path: join(tmpdir(), 'addp-monitor-targets-desktop.png'), animations: 'disabled' })
  await page.setViewportSize({ width: 620, height: 700 })
  await page.getByRole('button', { name: 'Details', exact: true }).click()
  await expect(page.getByTestId('target-endpoint')).toHaveValue('https://node.test:9443/metrics')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: join(tmpdir(), 'addp-monitor-targets-narrow.png'), animations: 'disabled' })
})
