package authorization

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const SystemToolAuthorizationCatalogRelativePath = "system/backend/internal/authorization/tools_generated.go"

type ToolAuthorization struct {
	Name                string
	Owner               string
	RequiredScopes      []string
	RequiredPermissions []string
}

func GenerateSystemToolAuthorizationCatalog(
	repositoryRoot string,
	report AuthorizationCatalogReport,
) ([]byte, error) {
	root, err := validateRepositoryRoot(repositoryRoot)
	if err != nil {
		return nil, err
	}
	if report.SchemaVersion != AuthorizationCatalogReportSchemaVersion {
		return nil, fmt.Errorf("catalog schema_version must be %q", AuthorizationCatalogReportSchemaVersion)
	}

	permissions := make(map[string]PermissionDescriptor, len(report.Permissions))
	for _, permission := range report.Permissions {
		permissions[permission.Key] = permission
	}
	owners := make(map[string]struct{}, len(report.PermissionManifests))
	for _, manifest := range report.PermissionManifests {
		owners[manifest.OwnerModule] = struct{}{}
	}
	_, tools, issues := inspectToolManifest(root, owners, permissions)
	if len(issues) > 0 {
		canonicalizeToolIssues(issues)
		return nil, fmt.Errorf("Tool Manifest authorization validation failed: %s: %s", issues[0].Code, issues[0].Detail)
	}
	if len(tools) == 0 {
		return nil, fmt.Errorf("Tool Manifest must contain at least one Tool")
	}

	for index := range tools {
		sort.Strings(tools[index].RequiredPermissions)
	}
	sort.Slice(tools, func(i, j int) bool { return tools[i].Name < tools[j].Name })

	var source strings.Builder
	fmt.Fprintln(&source, "// Code generated by common/authorization/cmd/manifest; DO NOT EDIT.")
	fmt.Fprintln(&source, "// Source: common-python/addp_common/tools/manifest.json.")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "package authorization")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "import commonauth \"github.com/addp/common/authorization\"")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "var toolAuthorizations = map[string]commonauth.ToolAuthorization{")
	for _, tool := range tools {
		fmt.Fprintf(&source, "\t%q: {\n", tool.Name)
		fmt.Fprintf(&source, "\t\tName: %q,\n", tool.Name)
		fmt.Fprintf(&source, "\t\tOwner: %q,\n", tool.Owner)
		fmt.Fprintf(&source, "\t\tRequiredScopes: %#v,\n", tool.RequiredScopes)
		fmt.Fprintf(&source, "\t\tRequiredPermissions: %#v,\n", tool.RequiredPermissions)
		fmt.Fprintln(&source, "\t},")
	}
	fmt.Fprintln(&source, "}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "type ToolAuthorizationCatalog struct{}")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "func (ToolAuthorizationCatalog) FindToolAuthorization(name string) (commonauth.ToolAuthorization, bool) {")
	fmt.Fprintln(&source, "\ttool, ok := toolAuthorizations[name]")
	fmt.Fprintln(&source, "\tif !ok {")
	fmt.Fprintln(&source, "\t\treturn commonauth.ToolAuthorization{}, false")
	fmt.Fprintln(&source, "\t}")
	fmt.Fprintln(&source, "\ttool.RequiredScopes = append([]string(nil), tool.RequiredScopes...)")
	fmt.Fprintln(&source, "\ttool.RequiredPermissions = append([]string(nil), tool.RequiredPermissions...)")
	fmt.Fprintln(&source, "\treturn tool, true")
	fmt.Fprintln(&source, "}")

	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated System Tool authorization catalog: %w", err)
	}
	return formatted, nil
}

func WriteGeneratedSystemToolAuthorizationCatalog(repositoryRoot string, data []byte) error {
	root, err := validateRepositoryRoot(repositoryRoot)
	if err != nil {
		return err
	}
	path, err := generatedFilePath(root, SystemToolAuthorizationCatalogRelativePath)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create System Tool authorization catalog directory: %w", err)
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return fmt.Errorf("write System Tool authorization catalog: %w", err)
	}
	return nil
}

func CheckGeneratedSystemToolAuthorizationCatalog(repositoryRoot string, expected []byte) error {
	root, err := validateRepositoryRoot(repositoryRoot)
	if err != nil {
		return err
	}
	path, err := generatedFilePath(root, SystemToolAuthorizationCatalogRelativePath)
	if err != nil {
		return err
	}
	actual, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read System Tool authorization catalog: %w", err)
	}
	if !bytes.Equal(actual, expected) {
		return fmt.Errorf("generated System Tool authorization catalog is stale: run authorization-generate")
	}
	return nil
}

func canonicalizeToolIssues(issues []AuthorizationCoverageIssue) {
	sort.Slice(issues, func(i, j int) bool {
		left := issues[i]
		right := issues[j]
		return strings.Join([]string{left.ToolName, left.Code, left.Detail}, "\x00") <
			strings.Join([]string{right.ToolName, right.Code, right.Detail}, "\x00")
	})
}
