package authorization

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateSystemToolAuthorizationCatalogIsDeterministic(t *testing.T) {
	root := t.TempDir()
	writeCoverageFixture(t, root, "common-python/addp_common/tools/manifest.json", `{
  "tools": [{
    "name": "data.search",
    "owner": "manager",
    "auth": {
      "audience": "manager",
      "required_scopes": ["data.search"],
      "required_permissions": ["manager.search.execute", "manager.data_item.read"]
    }
  }]
}`)
	report := AuthorizationCatalogReport{
		SchemaVersion:       AuthorizationCatalogReportSchemaVersion,
		PermissionManifests: []PermissionManifestReference{{OwnerModule: "manager"}},
		Permissions: []PermissionDescriptor{
			{Key: "manager.data_item.read", OwnerModule: "manager", Status: "active", Delegable: true},
			{Key: "manager.search.execute", OwnerModule: "manager", Status: "active", Delegable: true},
		},
	}

	first, err := GenerateSystemToolAuthorizationCatalog(root, report)
	if err != nil {
		t.Fatal(err)
	}
	second, err := GenerateSystemToolAuthorizationCatalog(root, report)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(first, second) {
		t.Fatal("generated Tool authorization catalog is not deterministic")
	}
	for _, fragment := range []string{
		"Code generated by common/authorization/cmd/manifest",
		`"data.search": {`,
		`RequiredScopes:      []string{"data.search"}`,
		`RequiredPermissions: []string{"manager.data_item.read", "manager.search.execute"}`,
		"append([]string(nil), tool.RequiredPermissions...)",
	} {
		if !strings.Contains(string(first), fragment) {
			t.Fatalf("generated catalog missing %q:\n%s", fragment, first)
		}
	}

	if err := WriteGeneratedSystemToolAuthorizationCatalog(root, first); err != nil {
		t.Fatal(err)
	}
	if err := CheckGeneratedSystemToolAuthorizationCatalog(root, first); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(root, filepath.FromSlash(SystemToolAuthorizationCatalogRelativePath))
	if err := os.WriteFile(path, append(first, '\n'), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := CheckGeneratedSystemToolAuthorizationCatalog(root, first); err == nil {
		t.Fatal("stale generated Tool authorization catalog was accepted")
	}
}

func TestGenerateSystemToolAuthorizationCatalogRejectsInvalidMapping(t *testing.T) {
	root := t.TempDir()
	writeCoverageFixture(t, root, "common-python/addp_common/tools/manifest.json", `{
  "tools": [{
    "name": "data.search",
    "owner": "manager",
    "auth": {
      "audience": "meta",
      "required_scopes": ["data.search"],
      "required_permissions": ["manager.search.execute"]
    }
  }]
}`)
	report := AuthorizationCatalogReport{
		SchemaVersion:       AuthorizationCatalogReportSchemaVersion,
		PermissionManifests: []PermissionManifestReference{{OwnerModule: "manager"}},
		Permissions: []PermissionDescriptor{{
			Key: "manager.search.execute", OwnerModule: "manager", Status: "active", Delegable: true,
		}},
	}
	if _, err := GenerateSystemToolAuthorizationCatalog(root, report); err == nil ||
		!strings.Contains(err.Error(), "tool_audience_owner_mismatch") {
		t.Fatalf("GenerateSystemToolAuthorizationCatalog() error = %v", err)
	}
}
