// Code generated by common/authorization/cmd/manifest; DO NOT EDIT.
// Source: security/authorization/permissions.yaml (manifest_version=6).

package authorization

const (
	PermissionSecurityAssessmentCreate           = "security.assessment.create"
	PermissionSecurityAssessmentRead             = "security.assessment.read"
	PermissionSecurityAssessmentUpdate           = "security.assessment.update"
	PermissionSecurityClassificationCreate       = "security.classification.create"
	PermissionSecurityClassificationDelete       = "security.classification.delete"
	PermissionSecurityClassificationRead         = "security.classification.read"
	PermissionSecurityClassificationUpdate       = "security.classification.update"
	PermissionSecurityDetectorCreate             = "security.detector.create"
	PermissionSecurityDetectorDelete             = "security.detector.delete"
	PermissionSecurityDetectorRead               = "security.detector.read"
	PermissionSecurityDetectorUpdate             = "security.detector.update"
	PermissionSecurityEnrollmentCreate           = "security.enrollment.create"
	PermissionSecurityEnrollmentRead             = "security.enrollment.read"
	PermissionSecurityEnrollmentUpdate           = "security.enrollment.update"
	PermissionSecurityFindingRead                = "security.finding.read"
	PermissionSecurityFindingUpdate              = "security.finding.update"
	PermissionSecurityGradeCreate                = "security.grade.create"
	PermissionSecurityGradeDelete                = "security.grade.delete"
	PermissionSecurityGradeRead                  = "security.grade.read"
	PermissionSecurityGradeUpdate                = "security.grade.update"
	PermissionSecurityPolicyCreate               = "security.policy.create"
	PermissionSecurityPolicyDelete               = "security.policy.delete"
	PermissionSecurityPolicyRead                 = "security.policy.read"
	PermissionSecurityPolicyUpdate               = "security.policy.update"
	PermissionSecurityProtectionBaselineCreate   = "security.protection_baseline.create"
	PermissionSecurityProtectionBaselineDelete   = "security.protection_baseline.delete"
	PermissionSecurityProtectionBaselineRead     = "security.protection_baseline.read"
	PermissionSecurityProtectionBaselineUpdate   = "security.protection_baseline.update"
	PermissionSecurityProtectionProjectionRead   = "security.protection_projection.read"
	PermissionSecurityProtectionProjectionUpdate = "security.protection_projection.update"
	PermissionSecuritySensitiveDataTypeCreate    = "security.sensitive_data_type.create"
	PermissionSecuritySensitiveDataTypeDelete    = "security.sensitive_data_type.delete"
	PermissionSecuritySensitiveDataTypeRead      = "security.sensitive_data_type.read"
	PermissionSecuritySensitiveDataTypeUpdate    = "security.sensitive_data_type.update"
)

var permissionKeys = [...]string{
	"security.assessment.create",
	"security.assessment.read",
	"security.assessment.update",
	"security.classification.create",
	"security.classification.delete",
	"security.classification.read",
	"security.classification.update",
	"security.detector.create",
	"security.detector.delete",
	"security.detector.read",
	"security.detector.update",
	"security.enrollment.create",
	"security.enrollment.read",
	"security.enrollment.update",
	"security.finding.read",
	"security.finding.update",
	"security.grade.create",
	"security.grade.delete",
	"security.grade.read",
	"security.grade.update",
	"security.policy.create",
	"security.policy.delete",
	"security.policy.read",
	"security.policy.update",
	"security.protection_baseline.create",
	"security.protection_baseline.delete",
	"security.protection_baseline.read",
	"security.protection_baseline.update",
	"security.protection_projection.read",
	"security.protection_projection.update",
	"security.sensitive_data_type.create",
	"security.sensitive_data_type.delete",
	"security.sensitive_data_type.read",
	"security.sensitive_data_type.update",
}

// PermissionKeys returns the active owner-local Permission keys in stable order.
func PermissionKeys() []string {
	return append([]string(nil), permissionKeys[:]...)
}
