DECLARE
    table_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO table_count
    FROM USER_TABLES
    WHERE TABLE_NAME = 'ADDP_ENGINE_PROBE';

    IF table_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE ADDP_ENGINE_PROBE (
                ID INTEGER PRIMARY KEY,
                ENGINE_NAME VARCHAR(128) NOT NULL,
                PLATFORM VARCHAR(128) NOT NULL,
                CHECKED_AT TIMESTAMP(6) NOT NULL
            )
        ';
    END IF;

    SELECT COUNT(*) INTO table_count
    FROM USER_TABLES
    WHERE TABLE_NAME = 'ADDP_RELATIONAL_SAMPLE';

    IF table_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE ADDP_RELATIONAL_SAMPLE (
                ID BIGINT PRIMARY KEY,
                ITEM_CODE VARCHAR(64) NOT NULL UNIQUE,
                QUANTITY INTEGER NOT NULL,
                AMOUNT DECIMAL(12, 2) NOT NULL,
                UPDATED_AT TIMESTAMP(6) NOT NULL
            )
        ';
    END IF;
END;
/

DELETE FROM ADDP_ENGINE_PROBE WHERE ID = 1;
INSERT INTO ADDP_ENGINE_PROBE (ID, ENGINE_NAME, PLATFORM, CHECKED_AT)
VALUES (1, 'DM8 ARM64 technical fixture', 'linux/arm64 Docker', TIMESTAMP '2026-09-13 08:00:00.000000');

DELETE FROM ADDP_RELATIONAL_SAMPLE WHERE ID BETWEEN 1 AND 3;
INSERT INTO ADDP_RELATIONAL_SAMPLE (ID, ITEM_CODE, QUANTITY, AMOUNT, UPDATED_AT)
VALUES (1, 'DM8-001', 3, 12.34, TIMESTAMP '2026-09-13 08:00:00.000001');
INSERT INTO ADDP_RELATIONAL_SAMPLE (ID, ITEM_CODE, QUANTITY, AMOUNT, UPDATED_AT)
VALUES (2, 'DM8-002', 5, 56.78, TIMESTAMP '2026-09-13 08:00:00.000002');
INSERT INTO ADDP_RELATIONAL_SAMPLE (ID, ITEM_CODE, QUANTITY, AMOUNT, UPDATED_AT)
VALUES (3, 'DM8-003', 8, 90.12, TIMESTAMP '2026-09-13 08:00:00.000003');
COMMIT;

EXIT;
