<template><div class="page"><div class="page-header"><div><h2>{{ t('workbench.views') }}</h2><p>{{ t('workbench.viewsSubtitle') }}</p></div><el-button type="primary" @click="router.push('/views/new')"><el-icon><Plus /></el-icon>{{ t('workbench.createView') }}</el-button></div><el-card><el-table v-loading="loading" :data="items"><el-table-column prop="name" :label="t('workbench.name')" min-width="180"/><el-table-column prop="service_ref.service_type" :label="t('workbench.serviceType')" width="120"/><el-table-column prop="renderer_type" :label="t('workbench.renderer')" width="120"/><el-table-column prop="updated_at" :label="t('workbench.updatedAt')" min-width="180"/><el-table-column width="170"><template #default="scope"><el-button link type="primary" @click="router.push(`/views/${scope.row.id}`)">{{ t('workbench.edit') }}</el-button><el-button link type="danger" @click="remove(scope.row)">{{ t('workbench.delete') }}</el-button></template></el-table-column></el-table><el-pagination v-model:current-page="page" :page-size="20" :total="total" layout="prev, pager, next, total" @current-change="load"/></el-card></div></template>
<script setup>
import { onMounted, ref } from 'vue';import { useI18n } from 'vue-i18n';import { useRouter } from 'vue-router';import { ElMessage,ElMessageBox } from 'element-plus';import { Plus } from '@element-plus/icons-vue';import { listViews,deleteView } from '../api/views';import { navigateWorkbenchRoute } from '../utils/moduleNavigation'
const {t}=useI18n(),rawRouter=useRouter(),router={push:(location)=>navigateWorkbenchRoute(rawRouter,location)};const items=ref([]),total=ref(0),page=ref(1),loading=ref(false)
async function load(){loading.value=true;try{const {data}=await listViews({page:page.value,page_size:20});items.value=data.data||[];total.value=data.total||0}catch(e){ElMessage.error(e?.response?.data?.error||t('workbench.loadFailed'))}finally{loading.value=false}}
async function remove(row){await ElMessageBox.confirm(t('workbench.deleteConfirm'));await deleteView(row.id);ElMessage.success(t('workbench.deleted'));await load()}
onMounted(load)
</script>
<style scoped>.page{display:flex;flex-direction:column;gap:16px}.page-header{display:flex;justify-content:space-between;align-items:center}.page-header h2{margin:0;color:var(--addp-text-primary)}.page-header p{margin:6px 0 0;color:var(--addp-text-secondary)}.el-pagination{margin-top:16px;justify-content:flex-end}</style>
