// Code generated by common/authorization/cmd/manifest; DO NOT EDIT.
// Source: develop/authorization/permissions.yaml (manifest_version=5).

package authorization

const (
	PermissionDevelopDataDdlExecute            = "develop.data_ddl.execute"
	PermissionDevelopDataExternalEffectExecute = "develop.data_external_effect.execute"
	PermissionDevelopDataReadExecute           = "develop.data_read.execute"
	PermissionDevelopDataWriteExecute          = "develop.data_write.execute"
	PermissionDevelopNotebookCreate            = "develop.notebook.create"
	PermissionDevelopNotebookDelete            = "develop.notebook.delete"
	PermissionDevelopNotebookExecute           = "develop.notebook.execute"
	PermissionDevelopNotebookRead              = "develop.notebook.read"
	PermissionDevelopTaskCreate                = "develop.task.create"
	PermissionDevelopTaskDelete                = "develop.task.delete"
	PermissionDevelopTaskExecute               = "develop.task.execute"
	PermissionDevelopTaskRead                  = "develop.task.read"
	PermissionDevelopTaskUpdate                = "develop.task.update"
	PermissionDevelopTaskProviderExecute       = "develop.task_provider.execute"
	PermissionDevelopTaskProviderRead          = "develop.task_provider.read"
)

var permissionKeys = [...]string{
	"develop.data_ddl.execute",
	"develop.data_external_effect.execute",
	"develop.data_read.execute",
	"develop.data_write.execute",
	"develop.notebook.create",
	"develop.notebook.delete",
	"develop.notebook.execute",
	"develop.notebook.read",
	"develop.task.create",
	"develop.task.delete",
	"develop.task.execute",
	"develop.task.read",
	"develop.task.update",
	"develop.task_provider.execute",
	"develop.task_provider.read",
}

// PermissionKeys returns the active owner-local Permission keys in stable order.
func PermissionKeys() []string {
	return append([]string(nil), permissionKeys[:]...)
}
