// Code generated by common/authorization/cmd/manifest; DO NOT EDIT.
// Source: graph/authorization/permissions.yaml (manifest_version=1).

package authorization

const (
	PermissionGraphAnalysisExecute  = "graph.analysis.execute"
	PermissionGraphAnalysisRead     = "graph.analysis.read"
	PermissionGraphBuildTaskCancel  = "graph.build_task.cancel"
	PermissionGraphBuildTaskCreate  = "graph.build_task.create"
	PermissionGraphBuildTaskDelete  = "graph.build_task.delete"
	PermissionGraphBuildTaskExecute = "graph.build_task.execute"
	PermissionGraphBuildTaskRead    = "graph.build_task.read"
	PermissionGraphBuildTaskUpdate  = "graph.build_task.update"
	PermissionGraphGraphCreate      = "graph.graph.create"
	PermissionGraphGraphDelete      = "graph.graph.delete"
	PermissionGraphGraphRead        = "graph.graph.read"
	PermissionGraphGraphUpdate      = "graph.graph.update"
	PermissionGraphOntologyCreate   = "graph.ontology.create"
	PermissionGraphOntologyDelete   = "graph.ontology.delete"
	PermissionGraphOntologyRead     = "graph.ontology.read"
	PermissionGraphOntologyUpdate   = "graph.ontology.update"
	PermissionGraphReviewApprove    = "graph.review.approve"
	PermissionGraphReviewRead       = "graph.review.read"
	PermissionGraphReviewReject     = "graph.review.reject"
	PermissionGraphReviewUpdate     = "graph.review.update"
)

var permissionKeys = [...]string{
	"graph.analysis.execute",
	"graph.analysis.read",
	"graph.build_task.cancel",
	"graph.build_task.create",
	"graph.build_task.delete",
	"graph.build_task.execute",
	"graph.build_task.read",
	"graph.build_task.update",
	"graph.graph.create",
	"graph.graph.delete",
	"graph.graph.read",
	"graph.graph.update",
	"graph.ontology.create",
	"graph.ontology.delete",
	"graph.ontology.read",
	"graph.ontology.update",
	"graph.review.approve",
	"graph.review.read",
	"graph.review.reject",
	"graph.review.update",
}

// PermissionKeys returns the active owner-local Permission keys in stable order.
func PermissionKeys() []string {
	return append([]string(nil), permissionKeys[:]...)
}
