package format

// FormatType 是 ADDP 内稳定的文件/逻辑格式标识。
type FormatType string

const (
	FormatShapefile  FormatType = "shapefile"
	FormatGeoPackage FormatType = "geopackage"
	FormatKML        FormatType = "kml"
	FormatKMZ        FormatType = "kmz"

	FormatCSV   FormatType = "csv"
	FormatExcel FormatType = "excel"
	FormatTSV   FormatType = "tsv"

	FormatPDF      FormatType = "pdf"
	FormatDOCX     FormatType = "docx"
	FormatPPTX     FormatType = "pptx"
	FormatWPS      FormatType = "wps"
	FormatText     FormatType = "text"
	FormatMarkdown FormatType = "markdown"

	FormatImage FormatType = "image"
	FormatJPEG  FormatType = "jpeg"
	FormatPNG   FormatType = "png"
	FormatGIF   FormatType = "gif"
	FormatTIFF  FormatType = "tiff"
	FormatWebP  FormatType = "webp"
	FormatBMP   FormatType = "bmp"
	FormatSVG   FormatType = "svg"
	FormatAVIF  FormatType = "avif"
	FormatHEIC  FormatType = "heic"

	FormatSQLite   FormatType = "sqlite"
	FormatAccess   FormatType = "access"
	FormatUDBX     FormatType = "udbx"
	FormatFileGDB  FormatType = "filegdb"
	FormatPGeo     FormatType = "pgeo"
	FormatPostgres FormatType = "postgres"
	FormatMySQL    FormatType = "mysql"

	FormatJSON                 FormatType = "json"
	FormatMongoDBExtendedJSONL FormatType = "mongodb_extended_jsonl"
	FormatGeoJSON              FormatType = "geojson"
	FormatXML                  FormatType = "xml"
	FormatParquet              FormatType = "parquet"
	FormatORC                  FormatType = "orc"
	FormatAvro                 FormatType = "avro"
	FormatZIP                  FormatType = "zip"
	FormatRasterMosaic         FormatType = "raster_mosaic"
	FormatPMTiles              FormatType = "pmtiles"

	FormatVideo FormatType = "video"
	FormatAudio FormatType = "audio"
	FormatMP4   FormatType = "mp4"
	FormatMOV   FormatType = "mov"
	FormatMKV   FormatType = "mkv"
	FormatAVI   FormatType = "avi"
	FormatWebM  FormatType = "webm"
	FormatMP3   FormatType = "mp3"
	FormatWAV   FormatType = "wav"
	FormatFLAC  FormatType = "flac"
	FormatAAC   FormatType = "aac"
	FormatOGG   FormatType = "ogg"

	FormatGLB       FormatType = "glb"
	FormatGLTF      FormatType = "gltf"
	FormatOBJ       FormatType = "obj"
	FormatSTL       FormatType = "stl"
	FormatFBX       FormatType = "fbx"
	FormatIFC       FormatType = "ifc"
	FormatPLY       FormatType = "ply"
	FormatSplat     FormatType = "splat"
	FormatKSplat    FormatType = "ksplat"
	FormatLAS       FormatType = "las"
	FormatLAZ       FormatType = "laz"
	FormatCOPC      FormatType = "copc"
	FormatE57       FormatType = "e57"
	FormatPCD       FormatType = "pcd"
	FormatXYZ       FormatType = "xyz"
	FormatEPT       FormatType = "ept"
	Format3DTiles   FormatType = "3dtiles"
	FormatDWG       FormatType = "dwg"
	FormatDXF       FormatType = "dxf"
	FormatS3M       FormatType = "s3m"
	FormatOSGB      FormatType = "osgb"
	FormatOSGBScene FormatType = "osgb_scene"

	FormatUnknown FormatType = "unknown"
)
