// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ontologies": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "固定按 ontology_id 升序，仅接受 page/page_size；重复、未知参数或 OFFSET 超过 2147483647 时拒绝 | Ordered by ontology_id ascending; only page/page_size are accepted; duplicate or unknown parameters and OFFSET above 2147483647 are rejected",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ontology"
                ],
                "summary": "分页浏览本体 | List ontology heads",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "规范正整数页码 | Canonical positive page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量 | Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "本体头列表，空页为数组 | Ontology heads; empty pages are arrays",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.PaginatedResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/internal_api.HeadResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求无效 | Invalid request",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未认证 | Unauthenticated",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "禁止访问 | Forbidden",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "操作失败 | Operation failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "服务未就绪 | Module not ready",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    }
                },
                "x-addp-auth-mode": "permission",
                "x-addp-required-permissions": [
                    "ontology.revision.read"
                ]
            }
        },
        "/ontologies/{ontology_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ontology"
                ],
                "summary": "读取本体激活指针 | Get ontology activation head",
                "parameters": [
                    {
                        "type": "string",
                        "description": "本体标识 | Ontology identifier",
                        "name": "ontology_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功 | Success",
                        "schema": {
                            "$ref": "#/definitions/internal_api.HeadResponse"
                        }
                    },
                    "400": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    }
                },
                "x-addp-auth-mode": "permission",
                "x-addp-required-permissions": [
                    "ontology.revision.read"
                ]
            }
        },
        "/ontologies/{ontology_id}/projections/{generation}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ontology"
                ],
                "summary": "读取投影状态 | Get projection status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "本体标识 | Ontology identifier",
                        "name": "ontology_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "投影标识 | Projection generation",
                        "name": "generation",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功 | Success",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ProjectionResponse"
                        }
                    },
                    "400": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    }
                },
                "x-addp-auth-mode": "permission",
                "x-addp-required-permissions": [
                    "ontology.revision.read"
                ]
            }
        },
        "/ontologies/{ontology_id}/revisions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "固定按 revision 降序；不返回定义，published 不表示 active。仅接受 page/page_size，重复、未知参数或 OFFSET 超过 2147483647 时拒绝 | Ordered by revision descending; definitions are excluded and published does not mean active. Only page/page_size are accepted; duplicate or unknown parameters and OFFSET above 2147483647 are rejected",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ontology"
                ],
                "summary": "分页浏览修订历史 | List revision history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "本体标识 | Ontology identifier",
                        "name": "ontology_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "规范正整数页码 | Canonical positive page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量 | Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "修订摘要，空页为数组 | Revision summaries; empty pages are arrays",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.PaginatedResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_addp_ontology_internal_models.RevisionSummary"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求无效 | Invalid request",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未认证 | Unauthenticated",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "禁止访问 | Forbidden",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "本体不存在 | Ontology not found",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "操作失败 | Operation failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "服务未就绪 | Module not ready",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    }
                },
                "x-addp-auth-mode": "permission",
                "x-addp-required-permissions": [
                    "ontology.revision.read"
                ]
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ontology"
                ],
                "summary": "创建本体草稿 | Create ontology draft",
                "parameters": [
                    {
                        "type": "string",
                        "description": "本体标识 | Ontology identifier",
                        "name": "ontology_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "请求 | Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "成功 | Success",
                        "schema": {
                            "$ref": "#/definitions/internal_api.RevisionResponse"
                        }
                    },
                    "400": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    }
                },
                "x-addp-auth-mode": "permission",
                "x-addp-required-permissions": [
                    "ontology.revision.update"
                ]
            }
        },
        "/ontologies/{ontology_id}/revisions/{revision}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ontology"
                ],
                "summary": "读取修订 | Get revision",
                "parameters": [
                    {
                        "type": "string",
                        "description": "本体标识 | Ontology identifier",
                        "name": "ontology_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "修订号 | Revision number",
                        "name": "revision",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功 | Success",
                        "schema": {
                            "$ref": "#/definitions/internal_api.RevisionResponse"
                        }
                    },
                    "400": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    }
                },
                "x-addp-auth-mode": "permission",
                "x-addp-required-permissions": [
                    "ontology.revision.read"
                ]
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ontology"
                ],
                "summary": "保存草稿 | Save draft",
                "parameters": [
                    {
                        "type": "string",
                        "description": "本体标识 | Ontology identifier",
                        "name": "ontology_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "修订号 | Revision number",
                        "name": "revision",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "请求 | Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.SaveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功 | Success",
                        "schema": {
                            "$ref": "#/definitions/internal_api.RevisionResponse"
                        }
                    },
                    "400": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    }
                },
                "x-addp-auth-mode": "permission",
                "x-addp-required-permissions": [
                    "ontology.revision.update"
                ]
            }
        },
        "/ontologies/{ontology_id}/revisions/{revision}/projection": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "最新投影不等于当前激活版本 | The latest projection is not necessarily active",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ontology"
                ],
                "summary": "读取修订最新投影 | Get latest revision projection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "本体标识 | Ontology identifier",
                        "name": "ontology_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "修订号 | Revision number",
                        "name": "revision",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功 | Success",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ProjectionResponse"
                        }
                    },
                    "400": {
                        "description": "请求无效 | Invalid request",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未认证 | Unauthenticated",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "禁止访问 | Forbidden",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "投影不存在 | Projection not found",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "操作失败 | Operation failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "服务未就绪 | Module not ready",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    }
                },
                "x-addp-auth-mode": "permission",
                "x-addp-required-permissions": [
                    "ontology.revision.read"
                ]
            }
        },
        "/ontologies/{ontology_id}/revisions/{revision}/publish": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ontology"
                ],
                "summary": "发布并准入投影 | Publish and admit projection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "本体标识 | Ontology identifier",
                        "name": "ontology_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "修订号 | Revision number",
                        "name": "revision",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "请求 | Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.VersionRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "成功 | Success",
                        "schema": {
                            "$ref": "#/definitions/internal_api.AcceptedResponse"
                        }
                    },
                    "400": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    }
                },
                "x-addp-auth-mode": "permission",
                "x-addp-required-permissions": [
                    "ontology.revision.publish",
                    "system.execution_authorization.create"
                ]
            }
        },
        "/ontologies/{ontology_id}/revisions/{revision}/rebuild": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ontology"
                ],
                "summary": "重建失败投影 | Rebuild failed projection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "本体标识 | Ontology identifier",
                        "name": "ontology_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "修订号 | Revision number",
                        "name": "revision",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "请求 | Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.RebuildRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "成功 | Success",
                        "schema": {
                            "$ref": "#/definitions/internal_api.AcceptedResponse"
                        }
                    },
                    "400": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    }
                },
                "x-addp-auth-mode": "permission",
                "x-addp-required-permissions": [
                    "ontology.revision.publish",
                    "system.execution_authorization.create"
                ]
            }
        },
        "/ontologies/{ontology_id}/revisions/{revision}/return": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ontology"
                ],
                "summary": "退回草稿 | Return to draft",
                "parameters": [
                    {
                        "type": "string",
                        "description": "本体标识 | Ontology identifier",
                        "name": "ontology_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "修订号 | Revision number",
                        "name": "revision",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "请求 | Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.VersionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功 | Success",
                        "schema": {
                            "$ref": "#/definitions/internal_api.RevisionResponse"
                        }
                    },
                    "400": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    }
                },
                "x-addp-auth-mode": "permission",
                "x-addp-required-permissions": [
                    "ontology.revision.update"
                ]
            }
        },
        "/ontologies/{ontology_id}/revisions/{revision}/submit": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ontology"
                ],
                "summary": "提交审核 | Submit for review",
                "parameters": [
                    {
                        "type": "string",
                        "description": "本体标识 | Ontology identifier",
                        "name": "ontology_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "修订号 | Revision number",
                        "name": "revision",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "请求 | Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.VersionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功 | Success",
                        "schema": {
                            "$ref": "#/definitions/internal_api.RevisionResponse"
                        }
                    },
                    "400": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    }
                },
                "x-addp-auth-mode": "permission",
                "x-addp-required-permissions": [
                    "ontology.revision.update"
                ]
            }
        },
        "/ontologies/{ontology_id}/revisions/{revision}/withdraw": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ontology"
                ],
                "summary": "撤回修订 | Withdraw revision",
                "parameters": [
                    {
                        "type": "string",
                        "description": "本体标识 | Ontology identifier",
                        "name": "ontology_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "修订号 | Revision number",
                        "name": "revision",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "请求 | Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.VersionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功 | Success",
                        "schema": {
                            "$ref": "#/definitions/internal_api.RevisionResponse"
                        }
                    },
                    "400": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "请求失败 | Request failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    }
                },
                "x-addp-auth-mode": "permission",
                "x-addp-required-permissions": [
                    "ontology.revision.publish"
                ]
            }
        },
        "/ontologies/{ontology_id}/semantic/classes": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "只读定义，不返回草稿或业务实例。ontology_id 必须由用户明确指定。 | Definitions only, no drafts or business instances. The user must identify ontology_id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ontology"
                ],
                "summary": "列出激活本体的类 | List classes of the active ontology",
                "parameters": [
                    {
                        "type": "string",
                        "description": "本体标识 | Ontology identifier",
                        "name": "ontology_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "类与读取时激活版本 | Classes and activation binding at read time",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ClassDirectoryResponse"
                        }
                    },
                    "400": {
                        "description": "无效请求 | Invalid request",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未认证 | Unauthenticated",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "禁止访问 | Forbidden",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "不存在 | Not found",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "未激活 | Not active",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "结果过大 | Result too large",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "读取失败 | Read failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "尚未就绪 | Not ready",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    }
                },
                "x-addp-auth-mode": "delegated_tool",
                "x-addp-required-permissions": [
                    "ontology.semantic.read"
                ]
            }
        },
        "/ontologies/{ontology_id}/semantic/classes/{class_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "revision、generation、activation_version 必须来自类目录；变化时返回 409，不回退旧版本。只解释原生定义，不执行规则或验证业务数据。 | Use the class directory binding; changed activation returns 409, without historical fallback. Native definitions only; no rule execution or business-data verification.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ontology"
                ],
                "summary": "获取确定类的语义上下文 | Get a pinned class context",
                "parameters": [
                    {
                        "type": "string",
                        "description": "本体标识 | Ontology identifier",
                        "name": "ontology_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "类标识 | Class identifier",
                        "name": "class_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "目录返回的修订 | Revision returned by directory",
                        "name": "revision",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "目录返回的投影 | Generation returned by directory",
                        "name": "generation",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "目录返回的激活版本 | Activation version returned by directory",
                        "name": "activation_version",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "确定类上下文 | Pinned class context",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ClassContextResponse"
                        }
                    },
                    "400": {
                        "description": "无效请求 | Invalid request",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未认证 | Unauthenticated",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "禁止访问 | Forbidden",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "不存在 | Not found",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "未激活或版本变化 | Inactive or activation changed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "结果过大 | Result too large",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "读取失败 | Read failed",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "尚未就绪 | Not ready",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    }
                },
                "x-addp-auth-mode": "delegated_tool",
                "x-addp-required-permissions": [
                    "ontology.semantic.read"
                ]
            }
        }
    },
    "definitions": {
        "api.PaginatedResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "github_com_addp_ontology_internal_models.RevisionSummary": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "digest": {
                    "type": "string"
                },
                "initial_execution_id": {
                    "type": "string"
                },
                "initial_generation": {
                    "type": "string"
                },
                "ontology_id": {
                    "type": "string"
                },
                "published_at": {
                    "type": "string"
                },
                "revision": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "github_com_addp_ontology_internal_semantic.AbsencePolicy": {
            "type": "string",
            "enum": [
                "unknown",
                "false"
            ],
            "x-enum-varnames": [
                "AbsenceUnknown",
                "AbsenceFalse"
            ]
        },
        "github_com_addp_ontology_internal_semantic.Class": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parents": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_addp_ontology_internal_semantic.Input": {
            "type": "object",
            "properties": {
                "on_absent": {
                    "$ref": "#/definitions/github_com_addp_ontology_internal_semantic.AbsencePolicy"
                },
                "property_id": {
                    "type": "string"
                },
                "variable": {
                    "type": "string"
                }
            }
        },
        "github_com_addp_ontology_internal_semantic.Kind": {
            "type": "string",
            "enum": [
                "bool",
                "string"
            ],
            "x-enum-varnames": [
                "Boolean",
                "String"
            ]
        },
        "github_com_addp_ontology_internal_semantic.Property": {
            "type": "object",
            "properties": {
                "class_id": {
                    "type": "string"
                },
                "enum": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "kind": {
                    "$ref": "#/definitions/github_com_addp_ontology_internal_semantic.Kind"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_addp_ontology_internal_semantic.Relation": {
            "type": "object",
            "properties": {
                "from": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "inverse_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                },
                "transitive": {
                    "type": "boolean"
                }
            }
        },
        "github_com_addp_ontology_internal_semantic.Rule": {
            "type": "object",
            "properties": {
                "basis": {
                    "type": "string"
                },
                "class_id": {
                    "type": "string"
                },
                "expression": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "inputs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_addp_ontology_internal_semantic.Input"
                    }
                }
            }
        },
        "internal_api.AcceptedResponse": {
            "type": "object",
            "properties": {
                "execution_id": {
                    "type": "string"
                },
                "generation": {
                    "type": "string"
                },
                "ontology_id": {
                    "type": "string"
                },
                "revision": {
                    "type": "integer"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "internal_api.ClassContextResponse": {
            "type": "object",
            "properties": {
                "activation_version": {
                    "type": "integer"
                },
                "ancestors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_addp_ontology_internal_semantic.Class"
                    }
                },
                "class": {
                    "$ref": "#/definitions/github_com_addp_ontology_internal_semantic.Class"
                },
                "digest": {
                    "type": "string"
                },
                "generation": {
                    "type": "string"
                },
                "knowledge_kind": {
                    "type": "string"
                },
                "ontology_id": {
                    "type": "string"
                },
                "properties": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_addp_ontology_internal_semantic.Property"
                    }
                },
                "relations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_addp_ontology_internal_semantic.Relation"
                    }
                },
                "revision": {
                    "type": "integer"
                },
                "rules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_addp_ontology_internal_semantic.Rule"
                    }
                }
            }
        },
        "internal_api.ClassDirectoryResponse": {
            "type": "object",
            "properties": {
                "activation_version": {
                    "type": "integer"
                },
                "classes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_addp_ontology_internal_semantic.Class"
                    }
                },
                "digest": {
                    "type": "string"
                },
                "generation": {
                    "type": "string"
                },
                "knowledge_kind": {
                    "type": "string"
                },
                "ontology_id": {
                    "type": "string"
                },
                "revision": {
                    "type": "integer"
                }
            }
        },
        "internal_api.CreateRequest": {
            "type": "object",
            "properties": {
                "definition": {
                    "$ref": "#/definitions/internal_api.DefinitionInput"
                },
                "revision": {
                    "type": "integer"
                }
            }
        },
        "internal_api.DefinitionInput": {
            "type": "object",
            "properties": {
                "classes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_addp_ontology_internal_semantic.Class"
                    }
                },
                "properties": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_addp_ontology_internal_semantic.Property"
                    }
                },
                "relations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_addp_ontology_internal_semantic.Relation"
                    }
                },
                "rules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_addp_ontology_internal_semantic.Rule"
                    }
                }
            }
        },
        "internal_api.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "error_code": {
                    "type": "string"
                },
                "intent": {
                    "$ref": "#/definitions/internal_api.AcceptedResponse"
                }
            }
        },
        "internal_api.HeadResponse": {
            "type": "object",
            "properties": {
                "activation_version": {
                    "type": "integer"
                },
                "active_generation": {
                    "type": "string"
                },
                "active_revision": {
                    "type": "integer"
                },
                "last_revision": {
                    "type": "integer"
                },
                "ontology_id": {
                    "type": "string"
                }
            }
        },
        "internal_api.ProjectionResponse": {
            "type": "object",
            "properties": {
                "baseline_version": {
                    "type": "integer"
                },
                "digest": {
                    "type": "string"
                },
                "execution_id": {
                    "type": "string"
                },
                "generation": {
                    "type": "string"
                },
                "ontology_id": {
                    "type": "string"
                },
                "predecessor_generation": {
                    "type": "string"
                },
                "revision": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "internal_api.RebuildRequest": {
            "type": "object",
            "properties": {
                "activation_version": {
                    "type": "integer"
                },
                "failed_generation": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "internal_api.RevisionResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "digest": {
                    "type": "string"
                },
                "initial_execution_id": {
                    "type": "string"
                },
                "initial_generation": {
                    "type": "string"
                },
                "ontology_id": {
                    "type": "string"
                },
                "published_at": {
                    "type": "string"
                },
                "revision": {
                    "type": "integer"
                },
                "snapshot": {
                    "type": "object"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "internal_api.SaveRequest": {
            "type": "object",
            "properties": {
                "definition": {
                    "$ref": "#/definitions/internal_api.DefinitionInput"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "internal_api.VersionRequest": {
            "type": "object",
            "properties": {
                "version": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8195",
	BasePath:         "/api/v1/ontology",
	Schemes:          []string{},
	Title:            "ADDP Ontology API",
	Description:      "租户本体修订与投影管理 | Tenant ontology revision and projection management",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
