// Code generated by common/authorization/cmd/manifest; DO NOT EDIT.
// Source: inference/authorization/permissions.yaml (manifest_version=1).

package authorization

const (
	PermissionInferenceDeploymentCreate         = "inference.deployment.create"
	PermissionInferenceDeploymentDelete         = "inference.deployment.delete"
	PermissionInferenceDeploymentExecute        = "inference.deployment.execute"
	PermissionInferenceDeploymentRead           = "inference.deployment.read"
	PermissionInferenceDeploymentUpdate         = "inference.deployment.update"
	PermissionInferenceProfileCreate            = "inference.profile.create"
	PermissionInferenceProfileRead              = "inference.profile.read"
	PermissionInferenceProfileUpdate            = "inference.profile.update"
	PermissionInferenceProviderCreate           = "inference.provider.create"
	PermissionInferenceProviderDelete           = "inference.provider.delete"
	PermissionInferenceProviderRead             = "inference.provider.read"
	PermissionInferenceProviderUpdate           = "inference.provider.update"
	PermissionInferenceProviderCredentialUpdate = "inference.provider_credential.update"
	PermissionInferenceRuntimeExecute           = "inference.runtime.execute"
)

var permissionKeys = [...]string{
	"inference.deployment.create",
	"inference.deployment.delete",
	"inference.deployment.execute",
	"inference.deployment.read",
	"inference.deployment.update",
	"inference.profile.create",
	"inference.profile.read",
	"inference.profile.update",
	"inference.provider.create",
	"inference.provider.delete",
	"inference.provider.read",
	"inference.provider.update",
	"inference.provider_credential.update",
	"inference.runtime.execute",
}

// PermissionKeys returns the active owner-local Permission keys in stable order.
func PermissionKeys() []string {
	return append([]string(nil), permissionKeys[:]...)
}
