// Code generated by common/authorization/cmd/manifest; DO NOT EDIT.
// Source: catalog/authorization/permissions.yaml (manifest_version=7).

package authorization

const (
	PermissionCatalogAuditRead             = "catalog.audit.read"
	PermissionCatalogCollectionRead        = "catalog.collection.read"
	PermissionCatalogCollectionUpdate      = "catalog.collection.update"
	PermissionCatalogEntryCertify          = "catalog.entry.certify"
	PermissionCatalogEntryDeprecate        = "catalog.entry.deprecate"
	PermissionCatalogEntryRead             = "catalog.entry.read"
	PermissionCatalogEntryUpdate           = "catalog.entry.update"
	PermissionCatalogInventoryRead         = "catalog.inventory.read"
	PermissionCatalogReferenceRead         = "catalog.reference.read"
	PermissionCatalogSharingDecisionCreate = "catalog.sharing_decision.create"
	PermissionCatalogSourceRebind          = "catalog.source.rebind"
	PermissionCatalogStandardMappingReview = "catalog.standard_mapping.review"
)

var permissionKeys = [...]string{
	"catalog.audit.read",
	"catalog.collection.read",
	"catalog.collection.update",
	"catalog.entry.certify",
	"catalog.entry.deprecate",
	"catalog.entry.read",
	"catalog.entry.update",
	"catalog.inventory.read",
	"catalog.reference.read",
	"catalog.sharing_decision.create",
	"catalog.source.rebind",
	"catalog.standard_mapping.review",
}

// PermissionKeys returns the active owner-local Permission keys in stable order.
func PermissionKeys() []string {
	return append([]string(nil), permissionKeys[:]...)
}
