// Code generated by common/authorization/cmd/manifest; DO NOT EDIT.
// Source: manager/authorization/permissions.yaml (manifest_version=2).

package authorization

const (
	PermissionManagerContentRead           = "manager.content.read"
	PermissionManagerDataItemCreate        = "manager.data_item.create"
	PermissionManagerDataItemDelete        = "manager.data_item.delete"
	PermissionManagerDataItemRead          = "manager.data_item.read"
	PermissionManagerDataItemUpdate        = "manager.data_item.update"
	PermissionManagerDerivedArtifactCreate = "manager.derived_artifact.create"
	PermissionManagerDerivedArtifactDelete = "manager.derived_artifact.delete"
	PermissionManagerDerivedArtifactRead   = "manager.derived_artifact.read"
	PermissionManagerResourceGrantCreate   = "manager.resource_grant.create"
	PermissionManagerResourceGrantRead     = "manager.resource_grant.read"
	PermissionManagerResourceGrantRevoke   = "manager.resource_grant.revoke"
	PermissionManagerSearchExecute         = "manager.search.execute"
)

var permissionKeys = [...]string{
	"manager.content.read",
	"manager.data_item.create",
	"manager.data_item.delete",
	"manager.data_item.read",
	"manager.data_item.update",
	"manager.derived_artifact.create",
	"manager.derived_artifact.delete",
	"manager.derived_artifact.read",
	"manager.resource_grant.create",
	"manager.resource_grant.read",
	"manager.resource_grant.revoke",
	"manager.search.execute",
}

// PermissionKeys returns the active owner-local Permission keys in stable order.
func PermissionKeys() []string {
	return append([]string(nil), permissionKeys[:]...)
}
