// Code generated by common/authorization/cmd/manifest; DO NOT EDIT.
// Source: manager/authorization/permissions.yaml (manifest_version=7).

package authorization

const (
	PermissionManagerConfigurationRead     = "manager.configuration.read"
	PermissionManagerConfigurationUpdate   = "manager.configuration.update"
	PermissionManagerContentRead           = "manager.content.read"
	PermissionManagerContentIndexUpdate    = "manager.content_index.update"
	PermissionManagerDataItemCreate        = "manager.data_item.create"
	PermissionManagerDataItemRead          = "manager.data_item.read"
	PermissionManagerDataItemUpdate        = "manager.data_item.update"
	PermissionManagerDataProfileExecute    = "manager.data_profile.execute"
	PermissionManagerDerivedArtifactCreate = "manager.derived_artifact.create"
	PermissionManagerDerivedArtifactDelete = "manager.derived_artifact.delete"
	PermissionManagerDerivedArtifactRead   = "manager.derived_artifact.read"
	PermissionManagerDerivedArtifactUpdate = "manager.derived_artifact.update"
	PermissionManagerSearchExecute         = "manager.search.execute"
)

var permissionKeys = [...]string{
	"manager.configuration.read",
	"manager.configuration.update",
	"manager.content.read",
	"manager.content_index.update",
	"manager.data_item.create",
	"manager.data_item.read",
	"manager.data_item.update",
	"manager.data_profile.execute",
	"manager.derived_artifact.create",
	"manager.derived_artifact.delete",
	"manager.derived_artifact.read",
	"manager.derived_artifact.update",
	"manager.search.execute",
}

// PermissionKeys returns the active owner-local Permission keys in stable order.
func PermissionKeys() []string {
	return append([]string(nil), permissionKeys[:]...)
}
