version: "3.5"
services:
  postgresql:
    container_name: temporal-postgresql
    image: postgres:13
    environment:
      - POSTGRES_USER=temporal
      - POSTGRES_PASSWORD=temporal
    ports:
      - 15432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - temporal-network

  temporal:
    container_name: temporal
    image: temporalio/auto-setup:1.22.3
    ports:
      - 7233:7233
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
      # - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development_sql.yaml
    depends_on:
      - postgresql
    networks:
      - temporal-network

  temporal-ui:
    container_name: temporal-ui
    image: temporalio/ui:2.21.3
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    ports:
      - 8088:8080
    depends_on:
      - temporal
    networks:
      - temporal-network

networks:
  temporal-network:
    driver: bridge
    name: temporal-network
