BEGIN;

CREATE FUNCTION system.valid_distinct_positive_bigint_array(values_to_check bigint[])
RETURNS boolean
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT values_to_check IS NOT NULL
       AND cardinality(values_to_check) > 0
       AND NOT EXISTS (
           SELECT 1
           FROM unnest(values_to_check) AS value
           WHERE value IS NULL OR value <= 0
       )
       AND cardinality(values_to_check) = (
           SELECT count(DISTINCT value)::integer
           FROM unnest(values_to_check) AS value
       );
$$;

CREATE TABLE system.execution_authorizations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_access_token_id bigint NOT NULL REFERENCES system.access_tokens(id),
    execution_id uuid NOT NULL,
    audience text NOT NULL CHECK (audience = 'develop'),
    effects text[] NOT NULL CHECK (
        system.valid_distinct_text_array(effects, true)
        AND effects <@ ARRAY['read', 'write', 'ddl', 'external_effect']::text[]
    ),
    engine_ids bigint[] NOT NULL CHECK (
        system.valid_distinct_positive_bigint_array(engine_ids)
    ),
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    revoked_reason text,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (audience, execution_id),
    CHECK (expires_at > created_at),
    CHECK (
        (revoked_at IS NULL AND revoked_reason IS NULL)
        OR (revoked_at IS NOT NULL
            AND revoked_reason IS NOT NULL
            AND btrim(revoked_reason) <> '')
    ),
    CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);

CREATE INDEX idx_execution_authorizations_source_active
    ON system.execution_authorizations (source_access_token_id, expires_at)
    WHERE revoked_at IS NULL;
CREATE INDEX idx_execution_authorizations_audience_active
    ON system.execution_authorizations (audience, expires_at, id)
    WHERE revoked_at IS NULL;
CREATE INDEX idx_execution_authorizations_expiry_active
    ON system.execution_authorizations (expires_at, id)
    WHERE revoked_at IS NULL;

CREATE FUNCTION system.validate_execution_authorization()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    target_access_expires_at timestamptz;
    target_family_expires_at timestamptz;
    target_tenant_id bigint;
    invalid_engine boolean;
BEGIN
    SELECT access_token.expires_at,
           family.expires_at,
           membership.tenant_id
    INTO target_access_expires_at,
         target_family_expires_at,
         target_tenant_id
    FROM system.access_tokens access_token
    JOIN system.refresh_token_families family
      ON family.id = access_token.family_id
    JOIN system.principals principal
      ON principal.id = family.principal_id
    JOIN system.tenant_memberships membership
      ON membership.id = family.tenant_membership_id
     AND membership.principal_id = family.principal_id
    JOIN system.tenants tenant
      ON tenant.id = membership.tenant_id
    WHERE access_token.id = NEW.source_access_token_id
      AND access_token.revoked_at IS NULL
      AND access_token.expires_at > NEW.created_at
      AND family.revoked_at IS NULL
      AND family.expires_at > NEW.created_at
      AND family.auth_type IN ('first_party', 'oauth')
      AND family.context_type = 'tenant'
      AND principal.principal_type = 'user'
      AND principal.status = 'active'
      AND principal.authorization_version = family.issued_authorization_version
      AND membership.status = 'active'
      AND (membership.expires_at IS NULL OR membership.expires_at > NEW.created_at)
      AND tenant.status = 'active'
    FOR KEY SHARE OF access_token, family, principal, membership, tenant;

    IF target_tenant_id IS NULL THEN
        RAISE EXCEPTION 'execution authorization requires an active tenant user access token'
            USING ERRCODE = '23514';
    END IF;

    IF NEW.expires_at > target_access_expires_at
       OR NEW.expires_at > target_family_expires_at
       OR NEW.expires_at > NEW.created_at + interval '1 hour' THEN
        RAISE EXCEPTION 'execution authorization expiry exceeds its source authorization boundary'
            USING ERRCODE = '23514';
    END IF;

    IF to_regclass('system.engines') IS NULL THEN
        RAISE EXCEPTION 'execution authorization requires the system.engines table'
            USING ERRCODE = '23514';
    END IF;

    EXECUTE $query$
        SELECT EXISTS (
            SELECT 1
            FROM unnest($1::bigint[]) AS requested(engine_id)
            WHERE NOT EXISTS (
                SELECT 1
                FROM system.engines engine
                WHERE engine.id = requested.engine_id
                  AND engine.lifecycle_state = 'active'
                  AND (
                      engine.tenant_id = $2
                      OR (engine.tenant_id IS NULL AND engine.is_builtin = true)
                  )
            )
        )
    $query$
    INTO invalid_engine
    USING NEW.engine_ids, target_tenant_id;

    IF invalid_engine THEN
        RAISE EXCEPTION 'execution authorization contains an unavailable or cross-tenant engine'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;

CREATE FUNCTION system.validate_execution_authorization_update()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.source_access_token_id IS DISTINCT FROM OLD.source_access_token_id
       OR NEW.execution_id IS DISTINCT FROM OLD.execution_id
       OR NEW.audience IS DISTINCT FROM OLD.audience
       OR NEW.effects IS DISTINCT FROM OLD.effects
       OR NEW.engine_ids IS DISTINCT FROM OLD.engine_ids
       OR NEW.expires_at IS DISTINCT FROM OLD.expires_at
       OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'execution authorization identity and boundary are immutable'
            USING ERRCODE = '23514';
    END IF;

    IF OLD.revoked_at IS NOT NULL
       AND (NEW.revoked_at IS DISTINCT FROM OLD.revoked_at
            OR NEW.revoked_reason IS DISTINCT FROM OLD.revoked_reason) THEN
        RAISE EXCEPTION 'execution authorization revocation is immutable'
            USING ERRCODE = '23514';
    END IF;

    IF OLD.revoked_at IS NULL AND NEW.revoked_at IS NOT NULL
       AND (NEW.revoked_at < OLD.created_at
            OR NEW.revoked_reason IS NULL
            OR btrim(NEW.revoked_reason) = '') THEN
        RAISE EXCEPTION 'execution authorization revocation requires a valid timestamp and reason'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION system.revoke_access_token_delegations()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.revoked_at IS NULL AND NEW.revoked_at IS NOT NULL THEN
        UPDATE system.delegated_access_tokens
        SET revoked_at = NEW.revoked_at
        WHERE source_access_token_id = NEW.id
          AND revoked_at IS NULL;

        UPDATE system.execution_authorizations
        SET revoked_at = NEW.revoked_at,
            revoked_reason = 'source_access_token_revoked'
        WHERE source_access_token_id = NEW.id
          AND revoked_at IS NULL;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_execution_authorizations_validate
BEFORE INSERT ON system.execution_authorizations
FOR EACH ROW EXECUTE FUNCTION system.validate_execution_authorization();
CREATE TRIGGER trg_execution_authorizations_validate_update
BEFORE UPDATE ON system.execution_authorizations
FOR EACH ROW EXECUTE FUNCTION system.validate_execution_authorization_update();
CREATE TRIGGER trg_execution_authorizations_prevent_delete
BEFORE DELETE ON system.execution_authorizations
FOR EACH ROW EXECUTE FUNCTION system.prevent_token_history_delete();

INSERT INTO system.permissions (
    permission_key,
    owner_module,
    action,
    risk_level,
    delegable,
    allowed_scope_types,
    tenant_customizable,
    name_i18n_key,
    description_i18n_key,
    status
) VALUES
    (
        'develop.data_ddl.execute', 'develop', 'execute', 'critical', false,
        ARRAY['tenant', 'department', 'project_group']::text[], true,
        'permissions.develop.data_ddl.execute.name',
        'permissions.develop.data_ddl.execute.description', 'active'
    ),
    (
        'develop.data_external_effect.execute', 'develop', 'execute', 'high', false,
        ARRAY['tenant', 'department', 'project_group']::text[], true,
        'permissions.develop.data_external_effect.execute.name',
        'permissions.develop.data_external_effect.execute.description', 'active'
    ),
    (
        'develop.data_read.execute', 'develop', 'execute', 'low', false,
        ARRAY['tenant', 'department', 'project_group']::text[], true,
        'permissions.develop.data_read.execute.name',
        'permissions.develop.data_read.execute.description', 'active'
    ),
    (
        'develop.data_write.execute', 'develop', 'execute', 'high', false,
        ARRAY['tenant', 'department', 'project_group']::text[], true,
        'permissions.develop.data_write.execute.name',
        'permissions.develop.data_write.execute.description', 'active'
    ),
    (
        'system.execution_authorization.execute', 'system', 'execute', 'high', false,
        ARRAY['tenant']::text[], false,
        'permissions.system.execution_authorization.execute.name',
        'permissions.system.execution_authorization.execute.description', 'active'
    );

INSERT INTO system.role_permissions (
    role_id,
    permission_id,
    source_type,
    created_by_principal_id
)
SELECT role.id, permission.id, 'product', NULL
FROM (VALUES
    ('tenant.data_engineer', 'develop.data_read.execute'),
    ('tenant.data_engineer', 'develop.data_write.execute'),
    ('tenant.data_steward', 'develop.data_read.execute'),
    ('tenant.data_steward', 'develop.data_write.execute'),
    ('tenant.data_viewer', 'develop.data_read.execute'),
    ('tenant.develop_runtime', 'system.execution_authorization.execute')
) AS seed(role_key, permission_key)
JOIN system.roles role
  ON role.tenant_id IS NULL
 AND role.role_key = seed.role_key
 AND role.status = 'active'
JOIN system.permissions permission
  ON permission.permission_key = seed.permission_key
 AND permission.status = 'active'
ORDER BY seed.role_key, seed.permission_key;

COMMIT;
