BEGIN;

CREATE FUNCTION system.valid_scope_types(values_to_check text[])
RETURNS boolean
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT cardinality(values_to_check) > 0
       AND values_to_check <@ ARRAY['platform', 'tenant', 'department', 'project_group']::text[]
       AND cardinality(values_to_check) = (
           SELECT count(DISTINCT value)::integer FROM unnest(values_to_check) AS value
       );
$$;

CREATE FUNCTION system.valid_principal_types(values_to_check text[])
RETURNS boolean
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT cardinality(values_to_check) > 0
       AND values_to_check <@ ARRAY['user', 'service_principal']::text[]
       AND cardinality(values_to_check) = (
           SELECT count(DISTINCT value)::integer FROM unnest(values_to_check) AS value
       );
$$;

CREATE TABLE system.permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_key text NOT NULL UNIQUE CHECK (permission_key ~ '^[a-z][a-z0-9_]*\.[a-z][a-z0-9_]*\.[a-z][a-z0-9_]*$'),
    owner_module text NOT NULL CHECK (owner_module ~ '^[a-z][a-z0-9_]*$'),
    action text NOT NULL CHECK (action ~ '^[a-z][a-z0-9_]*$'),
    risk_level text NOT NULL CHECK (risk_level IN ('low', 'medium', 'high', 'critical')),
    delegable boolean NOT NULL DEFAULT false,
    allowed_scope_types text[] NOT NULL CHECK (system.valid_scope_types(allowed_scope_types)),
    tenant_customizable boolean NOT NULL DEFAULT false,
    name_i18n_key text NOT NULL CHECK (btrim(name_i18n_key) <> ''),
    description_i18n_key text NOT NULL CHECK (btrim(description_i18n_key) <> ''),
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (split_part(permission_key, '.', 3) = action)
);

CREATE TABLE system.roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint REFERENCES system.tenants(id),
    role_key text NOT NULL CHECK (role_key ~ '^[a-z][a-z0-9_]*\.[a-z][a-z0-9_]*$'),
    name text,
    description text,
    name_i18n_key text,
    description_i18n_key text,
    role_type text NOT NULL CHECK (role_type IN ('platform_builtin', 'tenant_builtin', 'tenant_custom')),
    allowed_scope_types text[] NOT NULL CHECK (system.valid_scope_types(allowed_scope_types)),
    allowed_principal_types text[] NOT NULL CHECK (system.valid_principal_types(allowed_principal_types)),
    immutable boolean NOT NULL,
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    created_by_principal_id bigint REFERENCES system.principals(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE NULLS NOT DISTINCT (tenant_id, role_key),
    CHECK (
        (role_type IN ('platform_builtin', 'tenant_builtin')
            AND tenant_id IS NULL
            AND name IS NULL
            AND description IS NULL
            AND name_i18n_key IS NOT NULL
            AND description_i18n_key IS NOT NULL
            AND btrim(name_i18n_key) <> ''
            AND btrim(description_i18n_key) <> ''
            AND immutable
            AND created_by_principal_id IS NULL)
        OR (role_type = 'tenant_custom'
            AND tenant_id IS NOT NULL
            AND name IS NOT NULL
            AND btrim(name) <> ''
            AND name_i18n_key IS NULL
            AND description_i18n_key IS NULL
            AND NOT immutable
            AND created_by_principal_id IS NOT NULL)
    ),
    CHECK (
        (role_type = 'platform_builtin'
            AND allowed_scope_types = ARRAY['platform']::text[])
        OR (role_type IN ('tenant_builtin', 'tenant_custom')
            AND NOT ('platform' = ANY(allowed_scope_types)))
    )
);

CREATE INDEX idx_roles_tenant
    ON system.roles (tenant_id)
    WHERE tenant_id IS NOT NULL;
CREATE INDEX idx_roles_created_by
    ON system.roles (created_by_principal_id)
    WHERE created_by_principal_id IS NOT NULL;

CREATE TABLE system.role_permissions (
    role_id bigint NOT NULL REFERENCES system.roles(id),
    permission_id bigint NOT NULL REFERENCES system.permissions(id),
    source_type text NOT NULL CHECK (source_type IN ('product', 'tenant')),
    created_by_principal_id bigint REFERENCES system.principals(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (role_id, permission_id),
    CHECK (
        (source_type = 'product' AND created_by_principal_id IS NULL)
        OR (source_type = 'tenant' AND created_by_principal_id IS NOT NULL)
    )
);

CREATE INDEX idx_role_permissions_permission
    ON system.role_permissions (permission_id);
CREATE INDEX idx_role_permissions_created_by
    ON system.role_permissions (created_by_principal_id)
    WHERE created_by_principal_id IS NOT NULL;

CREATE TABLE system.role_conflicts (
    role_id_low bigint NOT NULL REFERENCES system.roles(id),
    role_id_high bigint NOT NULL REFERENCES system.roles(id),
    reason text NOT NULL CHECK (btrim(reason) <> ''),
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (role_id_low, role_id_high),
    CHECK (role_id_low < role_id_high)
);

CREATE INDEX idx_role_conflicts_high
    ON system.role_conflicts (role_id_high);

CREATE TABLE system.privileged_change_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    change_type text NOT NULL CHECK (change_type IN (
        'platform_role_grant',
        'platform_role_revoke',
        'platform_identity_suspend',
        'platform_identity_deactivate'
    )),
    target_principal_id bigint NOT NULL REFERENCES system.principals(id),
    target_role_id bigint REFERENCES system.roles(id),
    scope_type text NOT NULL DEFAULT 'platform' CHECK (scope_type = 'platform'),
    reason text NOT NULL CHECK (btrim(reason) <> ''),
    requested_by_principal_id bigint NOT NULL REFERENCES system.principals(id),
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'cancelled', 'applied')),
    requested_at timestamptz NOT NULL DEFAULT now(),
    decided_at timestamptz,
    applied_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (target_principal_id <> requested_by_principal_id),
    CHECK (
        (change_type IN ('platform_role_grant', 'platform_role_revoke') AND target_role_id IS NOT NULL)
        OR (change_type IN ('platform_identity_suspend', 'platform_identity_deactivate') AND target_role_id IS NULL)
    ),
    CHECK (
        (status = 'pending' AND decided_at IS NULL AND applied_at IS NULL)
        OR (status IN ('approved', 'rejected', 'cancelled') AND decided_at IS NOT NULL AND applied_at IS NULL)
        OR (status = 'applied' AND decided_at IS NOT NULL AND applied_at IS NOT NULL)
    ),
    CHECK (decided_at IS NULL OR decided_at >= requested_at),
    CHECK (applied_at IS NULL OR applied_at >= decided_at)
);

CREATE INDEX idx_privileged_change_requests_target_status
    ON system.privileged_change_requests (target_principal_id, status, requested_at);
CREATE INDEX idx_privileged_change_requests_role
    ON system.privileged_change_requests (target_role_id)
    WHERE target_role_id IS NOT NULL;
CREATE INDEX idx_privileged_change_requests_requested_by
    ON system.privileged_change_requests (requested_by_principal_id);
CREATE UNIQUE INDEX uq_privileged_change_requests_pending_target
    ON system.privileged_change_requests (change_type, target_principal_id, target_role_id) NULLS NOT DISTINCT
    WHERE status IN ('pending', 'approved');

CREATE TABLE system.privileged_change_approvals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id bigint NOT NULL UNIQUE REFERENCES system.privileged_change_requests(id),
    reviewer_principal_id bigint NOT NULL REFERENCES system.principals(id),
    decision text NOT NULL CHECK (decision IN ('approved', 'rejected')),
    reason text NOT NULL DEFAULT '',
    decided_at timestamptz NOT NULL DEFAULT now(),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_privileged_change_approvals_reviewer
    ON system.privileged_change_approvals (reviewer_principal_id);

ALTER TABLE system.principals
    ADD COLUMN status_change_request_id bigint REFERENCES system.privileged_change_requests(id);

CREATE UNIQUE INDEX uq_principals_status_change_request
    ON system.principals (status_change_request_id)
    WHERE status_change_request_id IS NOT NULL;

CREATE TABLE system.role_assignments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    principal_id bigint NOT NULL REFERENCES system.principals(id),
    role_id bigint NOT NULL REFERENCES system.roles(id),
    scope_type text NOT NULL CHECK (scope_type IN ('platform', 'tenant', 'department', 'project_group')),
    tenant_id bigint REFERENCES system.tenants(id),
    department_id bigint,
    project_group_id bigint,
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'revoked')),
    valid_from timestamptz NOT NULL DEFAULT now(),
    valid_until timestamptz,
    source_type text NOT NULL CHECK (source_type IN ('manual', 'idp_mapping', 'bootstrap', 'break_glass')),
    created_by_principal_id bigint REFERENCES system.principals(id),
    revoked_by_principal_id bigint REFERENCES system.principals(id),
    revoked_at timestamptz,
    reason text NOT NULL DEFAULT '',
    grant_change_request_id bigint REFERENCES system.privileged_change_requests(id),
    revoke_change_request_id bigint REFERENCES system.privileged_change_requests(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (tenant_id, department_id) REFERENCES system.departments (tenant_id, id),
    FOREIGN KEY (tenant_id, project_group_id) REFERENCES system.project_groups (tenant_id, id),
    CHECK (valid_until IS NULL OR valid_until > valid_from),
    CHECK (
        (scope_type = 'platform' AND tenant_id IS NULL AND department_id IS NULL AND project_group_id IS NULL)
        OR (scope_type = 'tenant' AND tenant_id IS NOT NULL AND department_id IS NULL AND project_group_id IS NULL)
        OR (scope_type = 'department' AND tenant_id IS NOT NULL AND department_id IS NOT NULL AND project_group_id IS NULL)
        OR (scope_type = 'project_group' AND tenant_id IS NOT NULL AND department_id IS NULL AND project_group_id IS NOT NULL)
    ),
    CHECK (
        (source_type = 'bootstrap' AND created_by_principal_id IS NULL)
        OR (source_type <> 'bootstrap' AND created_by_principal_id IS NOT NULL)
    ),
    CHECK (
        (status = 'active' AND revoked_by_principal_id IS NULL AND revoked_at IS NULL AND revoke_change_request_id IS NULL)
        OR (status = 'revoked' AND revoked_by_principal_id IS NOT NULL AND revoked_at IS NOT NULL)
    )
);

CREATE INDEX idx_role_assignments_principal_status_validity
    ON system.role_assignments (principal_id, status, valid_until);
CREATE INDEX idx_role_assignments_role
    ON system.role_assignments (role_id);
CREATE INDEX idx_role_assignments_tenant
    ON system.role_assignments (tenant_id)
    WHERE tenant_id IS NOT NULL;
CREATE INDEX idx_role_assignments_department
    ON system.role_assignments (tenant_id, department_id)
    WHERE department_id IS NOT NULL;
CREATE INDEX idx_role_assignments_project_group
    ON system.role_assignments (tenant_id, project_group_id)
    WHERE project_group_id IS NOT NULL;
CREATE INDEX idx_role_assignments_created_by
    ON system.role_assignments (created_by_principal_id)
    WHERE created_by_principal_id IS NOT NULL;
CREATE INDEX idx_role_assignments_revoked_by
    ON system.role_assignments (revoked_by_principal_id)
    WHERE revoked_by_principal_id IS NOT NULL;
CREATE UNIQUE INDEX uq_role_assignments_grant_request
    ON system.role_assignments (grant_change_request_id)
    WHERE grant_change_request_id IS NOT NULL;
CREATE UNIQUE INDEX uq_role_assignments_revoke_request
    ON system.role_assignments (revoke_change_request_id)
    WHERE revoke_change_request_id IS NOT NULL;
CREATE UNIQUE INDEX uq_role_assignments_active_scope
    ON system.role_assignments (
        principal_id,
        role_id,
        scope_type,
        tenant_id,
        department_id,
        project_group_id
    ) NULLS NOT DISTINCT
    WHERE status = 'active';

CREATE FUNCTION system.validate_permission_update()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.permission_key <> OLD.permission_key
       OR NEW.owner_module <> OLD.owner_module
       OR NEW.action <> OLD.action
       OR NEW.created_at <> OLD.created_at THEN
        RAISE EXCEPTION 'permission key, owner, and action cannot change'
            USING ERRCODE = '23514';
    END IF;
    IF EXISTS (
        SELECT 1
        FROM system.role_permissions rp
        JOIN system.roles role ON role.id = rp.role_id
        WHERE rp.permission_id = OLD.id
          AND NOT (role.allowed_scope_types <@ NEW.allowed_scope_types)
    ) THEN
        RAISE EXCEPTION 'permission scope cannot exclude an existing role scope'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION system.validate_role()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'UPDATE' AND (
        NEW.tenant_id IS DISTINCT FROM OLD.tenant_id
        OR NEW.role_key <> OLD.role_key
        OR NEW.role_type <> OLD.role_type
        OR NEW.created_by_principal_id IS DISTINCT FROM OLD.created_by_principal_id
        OR NEW.created_at <> OLD.created_at
    ) THEN
        RAISE EXCEPTION 'role identity cannot change'
            USING ERRCODE = '23514';
    END IF;

    IF TG_OP = 'INSERT' AND NEW.role_type = 'tenant_custom' AND NOT EXISTS (
        SELECT 1
        FROM system.tenant_memberships tm
        JOIN system.principals p ON p.id = tm.principal_id
        WHERE tm.tenant_id = NEW.tenant_id
          AND tm.principal_id = NEW.created_by_principal_id
          AND tm.status = 'active'
          AND p.status = 'active'
          AND (tm.expires_at IS NULL OR tm.expires_at > now())
    ) THEN
        RAISE EXCEPTION 'tenant custom role creator must have an active membership in the same tenant'
            USING ERRCODE = '23514';
    END IF;

    IF TG_OP = 'UPDATE' AND EXISTS (
        SELECT 1
        FROM system.role_permissions rp
        JOIN system.permissions permission ON permission.id = rp.permission_id
        WHERE rp.role_id = OLD.id
          AND NOT (NEW.allowed_scope_types <@ permission.allowed_scope_types)
    ) THEN
        RAISE EXCEPTION 'role scope exceeds an existing permission scope'
            USING ERRCODE = '23514';
    END IF;
    IF TG_OP = 'UPDATE' AND EXISTS (
        SELECT 1
        FROM system.role_assignments assignment
        JOIN system.principals principal ON principal.id = assignment.principal_id
        WHERE assignment.role_id = OLD.id
          AND assignment.status = 'active'
          AND (
              NOT (assignment.scope_type = ANY(NEW.allowed_scope_types))
              OR NOT (principal.principal_type = ANY(NEW.allowed_principal_types))
          )
    ) THEN
        RAISE EXCEPTION 'role scope or principal type cannot exclude an active assignment'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION system.validate_role_permission()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    target_role system.roles%ROWTYPE;
    target_permission system.permissions%ROWTYPE;
BEGIN
    IF TG_OP = 'UPDATE' AND (
        NEW.role_id <> OLD.role_id
        OR NEW.permission_id <> OLD.permission_id
        OR NEW.source_type <> OLD.source_type
        OR NEW.created_by_principal_id IS DISTINCT FROM OLD.created_by_principal_id
        OR NEW.created_at <> OLD.created_at
    ) THEN
        RAISE EXCEPTION 'role permission identity cannot change'
            USING ERRCODE = '23514';
    END IF;

    SELECT * INTO target_role FROM system.roles WHERE id = NEW.role_id FOR KEY SHARE;
    SELECT * INTO target_permission FROM system.permissions WHERE id = NEW.permission_id FOR KEY SHARE;

    IF target_role.status <> 'active' OR target_permission.status <> 'active' THEN
        RAISE EXCEPTION 'role permission requires an active role and permission'
            USING ERRCODE = '23514';
    END IF;
    IF NOT (target_role.allowed_scope_types <@ target_permission.allowed_scope_types) THEN
        RAISE EXCEPTION 'role scope exceeds permission scope'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.source_type = 'product' AND target_role.role_type = 'tenant_custom' THEN
        RAISE EXCEPTION 'product role permission requires a built-in role'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.source_type = 'tenant' AND (
        target_role.role_type <> 'tenant_custom' OR NOT target_permission.tenant_customizable
    ) THEN
        RAISE EXCEPTION 'tenant role permission requires a customizable permission and tenant custom role'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.source_type = 'tenant' AND NOT EXISTS (
        SELECT 1
        FROM system.tenant_memberships tm
        JOIN system.principals p ON p.id = tm.principal_id
        WHERE tm.tenant_id = target_role.tenant_id
          AND tm.principal_id = NEW.created_by_principal_id
          AND tm.status = 'active'
          AND p.status = 'active'
          AND (tm.expires_at IS NULL OR tm.expires_at > now())
    ) THEN
        RAISE EXCEPTION 'tenant role permission creator must have an active membership in the role tenant'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION system.validate_privileged_change_request()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    target_type text;
    requester_type text;
    target_status text;
    requester_status text;
    target_role system.roles%ROWTYPE;
BEGIN
    PERFORM 1
    FROM system.principals
    WHERE id IN (NEW.target_principal_id, NEW.requested_by_principal_id)
    ORDER BY id
    FOR KEY SHARE;

    SELECT principal_type, status INTO target_type, target_status
    FROM system.principals
    WHERE id = NEW.target_principal_id;
    SELECT principal_type, status INTO requester_type, requester_status
    FROM system.principals
    WHERE id = NEW.requested_by_principal_id;

    IF NEW.status <> 'pending' OR NEW.decided_at IS NOT NULL OR NEW.applied_at IS NOT NULL THEN
        RAISE EXCEPTION 'new privileged change request must be pending'
            USING ERRCODE = '23514';
    END IF;
    IF target_type <> 'user' OR requester_type <> 'user' OR requester_status <> 'active' THEN
        RAISE EXCEPTION 'privileged change target and requester must be users'
            USING ERRCODE = '23514';
    END IF;

    IF NEW.target_role_id IS NOT NULL THEN
        SELECT * INTO target_role FROM system.roles WHERE id = NEW.target_role_id FOR KEY SHARE;
        IF target_role.role_type <> 'platform_builtin'
           OR target_role.status <> 'active'
           OR target_role.allowed_scope_types <> ARRAY['platform']::text[] THEN
            RAISE EXCEPTION 'platform role change requires an active platform built-in role'
                USING ERRCODE = '23514';
        END IF;
    END IF;

    IF NEW.change_type = 'platform_role_grant' AND (
        target_status <> 'active' OR EXISTS (
            SELECT 1
            FROM system.role_assignments assignment
            WHERE assignment.principal_id = NEW.target_principal_id
              AND assignment.role_id = NEW.target_role_id
              AND assignment.scope_type = 'platform'
              AND assignment.status = 'active'
        )
    ) THEN
        RAISE EXCEPTION 'platform role grant requires an active target without the role'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.change_type = 'platform_role_revoke' AND NOT EXISTS (
        SELECT 1
        FROM system.role_assignments assignment
        WHERE assignment.principal_id = NEW.target_principal_id
          AND assignment.role_id = NEW.target_role_id
          AND assignment.scope_type = 'platform'
          AND assignment.status = 'active'
          AND assignment.valid_from <= now()
          AND (assignment.valid_until IS NULL OR assignment.valid_until > now())
    ) THEN
        RAISE EXCEPTION 'platform role revoke requires an effective target assignment'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.change_type = 'platform_identity_suspend' AND target_status <> 'active' THEN
        RAISE EXCEPTION 'platform identity suspend requires an active target'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.change_type = 'platform_identity_deactivate' AND target_status = 'deactivated' THEN
        RAISE EXCEPTION 'platform identity deactivate requires a non-deactivated target'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.change_type IN ('platform_identity_suspend', 'platform_identity_deactivate') AND NOT EXISTS (
        SELECT 1
        FROM system.role_assignments assignment
        WHERE assignment.principal_id = NEW.target_principal_id
          AND assignment.scope_type = 'platform'
          AND assignment.status = 'active'
          AND assignment.valid_from <= now()
          AND (assignment.valid_until IS NULL OR assignment.valid_until > now())
    ) THEN
        RAISE EXCEPTION 'platform identity change requires an effective platform role assignment'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION system.validate_privileged_change_request_transition()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.change_type <> OLD.change_type
       OR NEW.target_principal_id <> OLD.target_principal_id
       OR NEW.target_role_id IS DISTINCT FROM OLD.target_role_id
       OR NEW.scope_type <> OLD.scope_type
       OR NEW.reason <> OLD.reason
       OR NEW.requested_by_principal_id <> OLD.requested_by_principal_id
       OR NEW.requested_at <> OLD.requested_at
       OR NEW.created_at <> OLD.created_at THEN
        RAISE EXCEPTION 'privileged change request identity cannot change'
            USING ERRCODE = '23514';
    END IF;

    IF NEW.status = OLD.status THEN
        IF NEW.decided_at IS DISTINCT FROM OLD.decided_at
           OR NEW.applied_at IS DISTINCT FROM OLD.applied_at THEN
            RAISE EXCEPTION 'privileged change decision timestamps cannot change without a status transition'
                USING ERRCODE = '23514';
        END IF;
        RETURN NEW;
    END IF;
    IF OLD.status = 'pending' AND NEW.status = 'cancelled' THEN
        RETURN NEW;
    END IF;
    IF OLD.status = 'pending' AND NEW.status IN ('approved', 'rejected') AND EXISTS (
        SELECT 1
        FROM system.privileged_change_approvals approval
        WHERE approval.request_id = OLD.id
          AND approval.decision = NEW.status
    ) THEN
        RETURN NEW;
    END IF;
    IF OLD.status = 'approved' AND NEW.status = 'applied' AND (
        (OLD.change_type = 'platform_role_grant' AND EXISTS (
            SELECT 1 FROM system.role_assignments assignment
            WHERE assignment.grant_change_request_id = OLD.id
        ))
        OR (OLD.change_type = 'platform_role_revoke' AND EXISTS (
            SELECT 1 FROM system.role_assignments assignment
            WHERE assignment.revoke_change_request_id = OLD.id AND assignment.status = 'revoked'
        ))
        OR (OLD.change_type = 'platform_identity_suspend' AND EXISTS (
            SELECT 1 FROM system.principals principal
            WHERE principal.id = OLD.target_principal_id
              AND principal.status = 'suspended'
              AND principal.status_change_request_id = OLD.id
        ))
        OR (OLD.change_type = 'platform_identity_deactivate' AND EXISTS (
            SELECT 1 FROM system.principals principal
            WHERE principal.id = OLD.target_principal_id
              AND principal.status = 'deactivated'
              AND principal.status_change_request_id = OLD.id
        ))
    ) THEN
        RETURN NEW;
    END IF;

    RAISE EXCEPTION 'invalid privileged change request status transition from % to %', OLD.status, NEW.status
        USING ERRCODE = '23514';
END;
$$;

CREATE FUNCTION system.prevent_privileged_change_approval_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'privileged change approval is immutable'
        USING ERRCODE = '23514';
END;
$$;

CREATE FUNCTION system.prevent_authorization_history_delete()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION '% history cannot be physically deleted', TG_TABLE_NAME
        USING ERRCODE = '23514';
END;
$$;

CREATE FUNCTION system.validate_privileged_change_approval()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    target_request system.privileged_change_requests%ROWTYPE;
    reviewer_type text;
    reviewer_status text;
BEGIN
    SELECT principal_type, status INTO reviewer_type, reviewer_status
    FROM system.principals
    WHERE id = NEW.reviewer_principal_id
    FOR KEY SHARE;

    SELECT * INTO target_request
    FROM system.privileged_change_requests
    WHERE id = NEW.request_id
    FOR UPDATE;

    IF target_request.status <> 'pending' THEN
        RAISE EXCEPTION 'privileged change request is not pending'
            USING ERRCODE = '23514';
    END IF;
    IF reviewer_type <> 'user'
       OR reviewer_status <> 'active'
       OR NEW.reviewer_principal_id = target_request.requested_by_principal_id
       OR NEW.reviewer_principal_id = target_request.target_principal_id THEN
        RAISE EXCEPTION 'privileged change reviewer must be a distinct user'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.decided_at < target_request.requested_at THEN
        RAISE EXCEPTION 'privileged change decision cannot precede the request'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION system.complete_privileged_change_approval()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE system.privileged_change_requests
    SET status = NEW.decision,
        decided_at = NEW.decided_at,
        updated_at = now()
    WHERE id = NEW.request_id;
    RETURN NEW;
END;
$$;

CREATE FUNCTION system.validate_role_assignment()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    target_principal system.principals%ROWTYPE;
    target_role system.roles%ROWTYPE;
    target_request system.privileged_change_requests%ROWTYPE;
BEGIN
    SELECT * INTO target_principal
    FROM system.principals
    WHERE id = NEW.principal_id
    FOR UPDATE;
    SELECT * INTO target_role
    FROM system.roles
    WHERE id = NEW.role_id
    FOR KEY SHARE;

    IF TG_OP = 'UPDATE' THEN
        IF OLD.status = 'revoked' THEN
            RAISE EXCEPTION 'revoked role assignment is immutable'
                USING ERRCODE = '23514';
        END IF;
        IF NEW.principal_id <> OLD.principal_id
           OR NEW.role_id <> OLD.role_id
           OR NEW.scope_type <> OLD.scope_type
           OR NEW.tenant_id IS DISTINCT FROM OLD.tenant_id
           OR NEW.department_id IS DISTINCT FROM OLD.department_id
           OR NEW.project_group_id IS DISTINCT FROM OLD.project_group_id
           OR NEW.source_type <> OLD.source_type
           OR NEW.created_by_principal_id IS DISTINCT FROM OLD.created_by_principal_id
           OR NEW.grant_change_request_id IS DISTINCT FROM OLD.grant_change_request_id
           OR NEW.valid_from <> OLD.valid_from
           OR NEW.valid_until IS DISTINCT FROM OLD.valid_until
           OR NEW.reason <> OLD.reason
           OR NEW.created_at <> OLD.created_at THEN
            RAISE EXCEPTION 'role assignment identity cannot change'
                USING ERRCODE = '23514';
        END IF;
        IF OLD.status = 'active' AND NEW.status <> 'revoked' THEN
            RAISE EXCEPTION 'role assignment status may only move from active to revoked'
                USING ERRCODE = '23514';
        END IF;
    ELSIF NEW.status <> 'active' THEN
        RAISE EXCEPTION 'new role assignment must be active'
            USING ERRCODE = '23514';
    END IF;

    IF NEW.status = 'active' THEN
        IF target_principal.status <> 'active' OR target_role.status <> 'active' THEN
            RAISE EXCEPTION 'active role assignment requires an active principal and role'
                USING ERRCODE = '23514';
        END IF;
        IF NOT (target_principal.principal_type = ANY(target_role.allowed_principal_types))
           OR NOT (NEW.scope_type = ANY(target_role.allowed_scope_types)) THEN
            RAISE EXCEPTION 'role assignment principal type or scope is not allowed by the role'
                USING ERRCODE = '23514';
        END IF;
        IF NEW.scope_type = 'platform' AND target_role.role_type <> 'platform_builtin' THEN
            RAISE EXCEPTION 'platform scope requires a platform built-in role'
                USING ERRCODE = '23514';
        END IF;
        IF NEW.scope_type <> 'platform' AND target_role.role_type = 'platform_builtin' THEN
            RAISE EXCEPTION 'platform built-in role only supports platform scope'
                USING ERRCODE = '23514';
        END IF;
        IF target_role.role_type = 'tenant_custom' AND target_role.tenant_id <> NEW.tenant_id THEN
            RAISE EXCEPTION 'tenant custom role may only be assigned in its own tenant'
                USING ERRCODE = '23514';
        END IF;

        IF NEW.scope_type <> 'platform' AND NOT EXISTS (
            SELECT 1
            FROM system.tenant_memberships tm
            WHERE tm.tenant_id = NEW.tenant_id
              AND tm.principal_id = NEW.principal_id
              AND tm.status = 'active'
              AND (tm.expires_at IS NULL OR tm.expires_at > now())
        ) THEN
            RAISE EXCEPTION 'non-platform role assignment requires an active tenant membership'
                USING ERRCODE = '23514';
        END IF;
        IF NEW.scope_type = 'department' AND NOT EXISTS (
            SELECT 1
            FROM system.department_memberships dm
            JOIN system.tenant_memberships tm ON tm.id = dm.tenant_membership_id
            JOIN system.departments d ON d.id = dm.department_id
            WHERE dm.tenant_id = NEW.tenant_id
              AND dm.department_id = NEW.department_id
              AND tm.principal_id = NEW.principal_id
              AND dm.status = 'active'
              AND d.status = 'active'
        ) THEN
            RAISE EXCEPTION 'department role assignment requires an active department membership'
                USING ERRCODE = '23514';
        END IF;
        IF NEW.scope_type = 'project_group' AND NOT EXISTS (
            SELECT 1
            FROM system.project_group_memberships pgm
            JOIN system.tenant_memberships tm ON tm.id = pgm.tenant_membership_id
            JOIN system.project_groups pg ON pg.id = pgm.project_group_id
            WHERE pgm.tenant_id = NEW.tenant_id
              AND pgm.project_group_id = NEW.project_group_id
              AND tm.principal_id = NEW.principal_id
              AND pgm.status = 'active'
              AND pg.status <> 'closed'
        ) THEN
            RAISE EXCEPTION 'project group role assignment requires an active project group membership'
                USING ERRCODE = '23514';
        END IF;

        IF TG_OP = 'INSERT' AND EXISTS (
            SELECT 1
            FROM system.role_assignments existing
            JOIN system.role_conflicts conflict
              ON (conflict.role_id_low = LEAST(existing.role_id, NEW.role_id)
                  AND conflict.role_id_high = GREATEST(existing.role_id, NEW.role_id))
            WHERE existing.principal_id = NEW.principal_id
              AND existing.status = 'active'
              AND (existing.valid_until IS NULL OR existing.valid_until > now())
        ) THEN
            RAISE EXCEPTION 'principal already has a conflicting active role'
                USING ERRCODE = '23514';
        END IF;

        IF NEW.scope_type = 'platform' AND NEW.source_type <> 'bootstrap' THEN
            IF NEW.grant_change_request_id IS NULL THEN
                RAISE EXCEPTION 'platform role assignment requires an approved grant request'
                    USING ERRCODE = '23514';
            END IF;
            SELECT * INTO target_request
            FROM system.privileged_change_requests
            WHERE id = NEW.grant_change_request_id
            FOR UPDATE;
            IF target_request.status <> 'approved'
               OR target_request.change_type <> 'platform_role_grant'
               OR target_request.target_principal_id <> NEW.principal_id
               OR target_request.target_role_id <> NEW.role_id
               OR target_request.requested_by_principal_id <> NEW.created_by_principal_id THEN
                RAISE EXCEPTION 'platform role grant request does not match the assignment'
                    USING ERRCODE = '23514';
            END IF;
        ELSIF NEW.grant_change_request_id IS NOT NULL THEN
            RAISE EXCEPTION 'grant request is only valid for non-bootstrap platform assignments'
                USING ERRCODE = '23514';
        END IF;
    END IF;

    IF NEW.status = 'revoked' THEN
        IF NEW.scope_type = 'platform' THEN
            IF NEW.revoke_change_request_id IS NULL THEN
                RAISE EXCEPTION 'platform role revocation requires an approved revoke request'
                    USING ERRCODE = '23514';
            END IF;
            SELECT * INTO target_request
            FROM system.privileged_change_requests
            WHERE id = NEW.revoke_change_request_id
            FOR UPDATE;
            IF target_request.status <> 'approved'
               OR target_request.change_type <> 'platform_role_revoke'
               OR target_request.target_principal_id <> NEW.principal_id
               OR target_request.target_role_id <> NEW.role_id
               OR target_request.requested_by_principal_id <> NEW.revoked_by_principal_id THEN
                RAISE EXCEPTION 'platform role revoke request does not match the assignment'
                    USING ERRCODE = '23514';
            END IF;
        ELSIF NEW.revoke_change_request_id IS NOT NULL THEN
            RAISE EXCEPTION 'revoke request is only valid for platform assignments'
                USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION system.apply_role_assignment_privileged_request()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    request_to_apply bigint;
BEGIN
    IF TG_OP = 'INSERT' THEN
        request_to_apply := NEW.grant_change_request_id;
    ELSIF NEW.status = 'revoked' AND OLD.status = 'active' THEN
        request_to_apply := NEW.revoke_change_request_id;
    END IF;

    IF request_to_apply IS NOT NULL THEN
        UPDATE system.privileged_change_requests
        SET status = 'applied',
            applied_at = now(),
            updated_at = now()
        WHERE id = request_to_apply;
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION system.bump_assignment_authorization_version()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    affected_principal_id bigint;
BEGIN
    IF TG_OP = 'DELETE' THEN
        affected_principal_id := OLD.principal_id;
    ELSE
        affected_principal_id := NEW.principal_id;
    END IF;
    UPDATE system.principals
    SET authorization_version = authorization_version + 1,
        updated_at = now()
    WHERE id = affected_principal_id;
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION system.bump_role_holders_authorization_version()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    affected_role_id bigint;
BEGIN
    IF TG_TABLE_NAME = 'role_permissions' THEN
        IF TG_OP = 'DELETE' THEN
            affected_role_id := OLD.role_id;
        ELSE
            affected_role_id := NEW.role_id;
        END IF;
        PERFORM 1
        FROM system.principals p
        WHERE EXISTS (
            SELECT 1 FROM system.role_assignments assignment
            WHERE assignment.role_id = affected_role_id
              AND assignment.principal_id = p.id
              AND assignment.status = 'active'
        )
        ORDER BY p.id
        FOR UPDATE;

        UPDATE system.principals p
        SET authorization_version = p.authorization_version + 1,
            updated_at = now()
        WHERE EXISTS (
            SELECT 1 FROM system.role_assignments assignment
            WHERE assignment.role_id = affected_role_id
              AND assignment.principal_id = p.id
              AND assignment.status = 'active'
        );
    ELSIF TG_TABLE_NAME = 'roles' THEN
        PERFORM 1
        FROM system.principals p
        WHERE EXISTS (
            SELECT 1 FROM system.role_assignments assignment
            WHERE assignment.role_id = NEW.id
              AND assignment.principal_id = p.id
              AND assignment.status = 'active'
        )
        ORDER BY p.id
        FOR UPDATE;

        UPDATE system.principals p
        SET authorization_version = p.authorization_version + 1,
            updated_at = now()
        WHERE EXISTS (
            SELECT 1 FROM system.role_assignments assignment
            WHERE assignment.role_id = NEW.id
              AND assignment.principal_id = p.id
              AND assignment.status = 'active'
        );
    ELSE
        PERFORM 1
        FROM system.principals p
        WHERE EXISTS (
            SELECT 1
            FROM system.role_assignments assignment
            JOIN system.role_permissions rp ON rp.role_id = assignment.role_id
            WHERE rp.permission_id = NEW.id
              AND assignment.principal_id = p.id
              AND assignment.status = 'active'
        )
        ORDER BY p.id
        FOR UPDATE;

        UPDATE system.principals p
        SET authorization_version = p.authorization_version + 1,
            updated_at = now()
        WHERE EXISTS (
            SELECT 1
            FROM system.role_assignments assignment
            JOIN system.role_permissions rp ON rp.role_id = assignment.role_id
            WHERE rp.permission_id = NEW.id
              AND assignment.principal_id = p.id
              AND assignment.status = 'active'
        );
    END IF;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION system.validate_principal_privileged_status_change()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    expected_change_type text;
    target_request system.privileged_change_requests%ROWTYPE;
    requires_approval boolean;
BEGIN
    IF NEW.status = OLD.status THEN
        IF NEW.status_change_request_id IS DISTINCT FROM OLD.status_change_request_id THEN
            RAISE EXCEPTION 'principal status request may only change with principal status'
                USING ERRCODE = '23514';
        END IF;
        RETURN NEW;
    END IF;

    NEW.authorization_version := OLD.authorization_version + 1;
    SELECT EXISTS (
        SELECT 1
        FROM system.role_assignments assignment
        WHERE assignment.principal_id = OLD.id
          AND assignment.scope_type = 'platform'
          AND assignment.status = 'active'
          AND assignment.valid_from <= now()
          AND (assignment.valid_until IS NULL OR assignment.valid_until > now())
    ) INTO requires_approval;

    IF NEW.principal_type = 'user'
       AND requires_approval
       AND NEW.status IN ('suspended', 'deactivated') THEN
        expected_change_type := CASE NEW.status
            WHEN 'suspended' THEN 'platform_identity_suspend'
            ELSE 'platform_identity_deactivate'
        END;
        IF NEW.status_change_request_id IS NULL
           OR NEW.status_change_request_id IS NOT DISTINCT FROM OLD.status_change_request_id THEN
            RAISE EXCEPTION 'governed principal status change requires a new approved request'
                USING ERRCODE = '23514';
        END IF;
        SELECT * INTO target_request
        FROM system.privileged_change_requests
        WHERE id = NEW.status_change_request_id
        FOR UPDATE;
        IF target_request.status <> 'approved'
           OR target_request.change_type <> expected_change_type
           OR target_request.target_principal_id <> NEW.id THEN
            RAISE EXCEPTION 'identity change request does not match the principal status change'
                USING ERRCODE = '23514';
        END IF;
    ELSIF NEW.status_change_request_id IS DISTINCT FROM OLD.status_change_request_id THEN
        RAISE EXCEPTION 'status change request is only valid for governed user suspension or deactivation'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION system.apply_principal_status_change_request()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.status <> OLD.status
       AND NEW.status_change_request_id IS DISTINCT FROM OLD.status_change_request_id
       AND NEW.status_change_request_id IS NOT NULL THEN
        UPDATE system.privileged_change_requests
        SET status = 'applied',
            applied_at = now(),
            updated_at = now()
        WHERE id = NEW.status_change_request_id;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_roles_validate
BEFORE INSERT OR UPDATE ON system.roles
FOR EACH ROW EXECUTE FUNCTION system.validate_role();
CREATE TRIGGER trg_roles_updated_at
BEFORE UPDATE ON system.roles
FOR EACH ROW EXECUTE FUNCTION system.set_updated_at();
CREATE TRIGGER trg_roles_authorization_version
AFTER UPDATE ON system.roles
FOR EACH ROW EXECUTE FUNCTION system.bump_role_holders_authorization_version();
CREATE TRIGGER trg_roles_prevent_delete
BEFORE DELETE ON system.roles
FOR EACH ROW EXECUTE FUNCTION system.prevent_authorization_history_delete();

CREATE TRIGGER trg_permissions_updated_at
BEFORE UPDATE ON system.permissions
FOR EACH ROW EXECUTE FUNCTION system.set_updated_at();
CREATE TRIGGER trg_permissions_validate_update
BEFORE UPDATE ON system.permissions
FOR EACH ROW EXECUTE FUNCTION system.validate_permission_update();
CREATE TRIGGER trg_permissions_authorization_version
AFTER UPDATE ON system.permissions
FOR EACH ROW EXECUTE FUNCTION system.bump_role_holders_authorization_version();
CREATE TRIGGER trg_permissions_prevent_delete
BEFORE DELETE ON system.permissions
FOR EACH ROW EXECUTE FUNCTION system.prevent_authorization_history_delete();

CREATE TRIGGER trg_role_permissions_validate
BEFORE INSERT OR UPDATE ON system.role_permissions
FOR EACH ROW EXECUTE FUNCTION system.validate_role_permission();
CREATE TRIGGER trg_role_permissions_authorization_version
AFTER INSERT OR UPDATE OR DELETE ON system.role_permissions
FOR EACH ROW EXECUTE FUNCTION system.bump_role_holders_authorization_version();

CREATE TRIGGER trg_privileged_change_requests_validate
BEFORE INSERT ON system.privileged_change_requests
FOR EACH ROW EXECUTE FUNCTION system.validate_privileged_change_request();
CREATE TRIGGER trg_privileged_change_requests_transition
BEFORE UPDATE ON system.privileged_change_requests
FOR EACH ROW EXECUTE FUNCTION system.validate_privileged_change_request_transition();
CREATE TRIGGER trg_privileged_change_requests_updated_at
BEFORE UPDATE ON system.privileged_change_requests
FOR EACH ROW EXECUTE FUNCTION system.set_updated_at();
CREATE TRIGGER trg_privileged_change_requests_prevent_delete
BEFORE DELETE ON system.privileged_change_requests
FOR EACH ROW EXECUTE FUNCTION system.prevent_authorization_history_delete();

CREATE TRIGGER trg_privileged_change_approvals_validate
BEFORE INSERT ON system.privileged_change_approvals
FOR EACH ROW EXECUTE FUNCTION system.validate_privileged_change_approval();
CREATE TRIGGER trg_privileged_change_approvals_complete
AFTER INSERT ON system.privileged_change_approvals
FOR EACH ROW EXECUTE FUNCTION system.complete_privileged_change_approval();
CREATE TRIGGER trg_privileged_change_approvals_immutable
BEFORE UPDATE OR DELETE ON system.privileged_change_approvals
FOR EACH ROW EXECUTE FUNCTION system.prevent_privileged_change_approval_mutation();

CREATE TRIGGER trg_role_assignments_validate
BEFORE INSERT OR UPDATE ON system.role_assignments
FOR EACH ROW EXECUTE FUNCTION system.validate_role_assignment();
CREATE TRIGGER trg_role_assignments_updated_at
BEFORE UPDATE ON system.role_assignments
FOR EACH ROW EXECUTE FUNCTION system.set_updated_at();
CREATE TRIGGER trg_role_assignments_apply_privileged_request
AFTER INSERT OR UPDATE ON system.role_assignments
FOR EACH ROW EXECUTE FUNCTION system.apply_role_assignment_privileged_request();
CREATE TRIGGER trg_role_assignments_authorization_version
AFTER INSERT OR UPDATE OR DELETE ON system.role_assignments
FOR EACH ROW EXECUTE FUNCTION system.bump_assignment_authorization_version();
CREATE TRIGGER trg_role_assignments_prevent_delete
BEFORE DELETE ON system.role_assignments
FOR EACH ROW EXECUTE FUNCTION system.prevent_authorization_history_delete();

CREATE TRIGGER trg_principals_validate_privileged_status_change
BEFORE UPDATE OF status, status_change_request_id ON system.principals
FOR EACH ROW EXECUTE FUNCTION system.validate_principal_privileged_status_change();
CREATE TRIGGER trg_principals_apply_status_change_request
AFTER UPDATE OF status, status_change_request_id ON system.principals
FOR EACH ROW EXECUTE FUNCTION system.apply_principal_status_change_request();

COMMIT;
