ALTER TABLE system.tenant_memberships
    DROP CONSTRAINT tenant_memberships_source_type_check;

ALTER TABLE system.tenant_memberships
    ADD CONSTRAINT tenant_memberships_source_type_check
    CHECK (source_type IN ('manual', 'invitation', 'idp_jit', 'directory_sync', 'bootstrap'));

CREATE TABLE system.tenant_invitations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL REFERENCES system.tenants(id),
    email text NOT NULL CHECK (btrim(email) <> ''),
    normalized_email text NOT NULL CHECK (btrim(normalized_email) <> ''),
    secret_hash char(64) NOT NULL UNIQUE CHECK (secret_hash ~ '^[0-9a-f]{64}$'),
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'revoked', 'expired')),
    expires_at timestamptz NOT NULL,
    accepted_at timestamptz,
    accepted_by_principal_id bigint REFERENCES system.principals(id),
    revoked_at timestamptz,
    revoked_by_principal_id bigint REFERENCES system.principals(id),
    expired_at timestamptz,
    created_by_principal_id bigint NOT NULL REFERENCES system.principals(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT tenant_invitations_expiry_check CHECK (expires_at > created_at),
    CONSTRAINT tenant_invitations_lifecycle_check CHECK (
        (status = 'pending'
            AND accepted_at IS NULL AND accepted_by_principal_id IS NULL
            AND revoked_at IS NULL AND revoked_by_principal_id IS NULL
            AND expired_at IS NULL)
        OR
        (status = 'accepted'
            AND accepted_at IS NOT NULL AND accepted_by_principal_id IS NOT NULL
            AND revoked_at IS NULL AND revoked_by_principal_id IS NULL
            AND expired_at IS NULL)
        OR
        (status = 'revoked'
            AND accepted_at IS NULL AND accepted_by_principal_id IS NULL
            AND revoked_at IS NOT NULL AND revoked_by_principal_id IS NOT NULL
            AND expired_at IS NULL)
        OR
        (status = 'expired'
            AND accepted_at IS NULL AND accepted_by_principal_id IS NULL
            AND revoked_at IS NULL AND revoked_by_principal_id IS NULL
            AND expired_at IS NOT NULL)
    )
);

CREATE UNIQUE INDEX uq_tenant_invitations_pending_email
    ON system.tenant_invitations (tenant_id, normalized_email)
    WHERE status = 'pending';
CREATE INDEX idx_tenant_invitations_tenant_status_created_at
    ON system.tenant_invitations (tenant_id, status, created_at DESC);
CREATE INDEX idx_tenant_invitations_expires_at
    ON system.tenant_invitations (expires_at)
    WHERE status = 'pending';
CREATE INDEX idx_tenant_invitations_accepted_by
    ON system.tenant_invitations (accepted_by_principal_id)
    WHERE accepted_by_principal_id IS NOT NULL;
CREATE INDEX idx_tenant_invitations_revoked_by
    ON system.tenant_invitations (revoked_by_principal_id)
    WHERE revoked_by_principal_id IS NOT NULL;
CREATE INDEX idx_tenant_invitations_created_by
    ON system.tenant_invitations (created_by_principal_id);

CREATE TABLE system.enrollment_tickets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash char(64) NOT NULL UNIQUE CHECK (token_hash ~ '^[0-9a-f]{64}$'),
    principal_id bigint NOT NULL REFERENCES system.principals(id),
    invitation_id bigint NOT NULL REFERENCES system.tenant_invitations(id),
    issued_authorization_version bigint NOT NULL CHECK (issued_authorization_version > 0),
    authenticated_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    consumed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT enrollment_tickets_expiry_check CHECK (expires_at > created_at),
    CONSTRAINT enrollment_tickets_authenticated_at_check CHECK (authenticated_at <= created_at),
    CONSTRAINT enrollment_tickets_consumed_at_check CHECK (consumed_at IS NULL OR consumed_at >= created_at)
);

CREATE INDEX idx_enrollment_tickets_principal_created_at
    ON system.enrollment_tickets (principal_id, created_at DESC);
CREATE INDEX idx_enrollment_tickets_invitation_created_at
    ON system.enrollment_tickets (invitation_id, created_at DESC);
CREATE INDEX idx_enrollment_tickets_expires_at
    ON system.enrollment_tickets (expires_at)
    WHERE consumed_at IS NULL;

CREATE FUNCTION system.validate_tenant_invitation_transition()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.tenant_id IS DISTINCT FROM OLD.tenant_id
       OR NEW.email IS DISTINCT FROM OLD.email
       OR NEW.normalized_email IS DISTINCT FROM OLD.normalized_email
       OR NEW.secret_hash IS DISTINCT FROM OLD.secret_hash
       OR NEW.expires_at IS DISTINCT FROM OLD.expires_at
       OR NEW.created_by_principal_id IS DISTINCT FROM OLD.created_by_principal_id
       OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'tenant invitation identity, recipient, secret, expiry and creator are immutable';
    END IF;

    IF OLD.status <> 'pending' THEN
        RAISE EXCEPTION 'terminal tenant invitation is immutable';
    END IF;
    IF NEW.status NOT IN ('accepted', 'revoked', 'expired') THEN
        RAISE EXCEPTION 'invalid tenant invitation status transition from % to %', OLD.status, NEW.status;
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION system.validate_enrollment_ticket_transition()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.token_hash IS DISTINCT FROM OLD.token_hash
       OR NEW.principal_id IS DISTINCT FROM OLD.principal_id
       OR NEW.invitation_id IS DISTINCT FROM OLD.invitation_id
       OR NEW.issued_authorization_version IS DISTINCT FROM OLD.issued_authorization_version
       OR NEW.authenticated_at IS DISTINCT FROM OLD.authenticated_at
       OR NEW.expires_at IS DISTINCT FROM OLD.expires_at
       OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'enrollment ticket identity, binding, authorization version and expiry are immutable';
    END IF;
    IF OLD.consumed_at IS NOT NULL OR NEW.consumed_at IS NULL THEN
        RAISE EXCEPTION 'enrollment ticket can only be consumed once';
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION system.prevent_invitation_enrollment_delete()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'tenant invitation and enrollment history cannot be physically deleted';
END;
$$;

CREATE TRIGGER trg_tenant_invitations_transition
BEFORE UPDATE ON system.tenant_invitations
FOR EACH ROW EXECUTE FUNCTION system.validate_tenant_invitation_transition();
CREATE TRIGGER trg_tenant_invitations_updated_at
BEFORE UPDATE ON system.tenant_invitations
FOR EACH ROW EXECUTE FUNCTION system.set_updated_at();
CREATE TRIGGER trg_tenant_invitations_prevent_delete
BEFORE DELETE ON system.tenant_invitations
FOR EACH ROW EXECUTE FUNCTION system.prevent_invitation_enrollment_delete();
CREATE TRIGGER trg_tenant_invitations_prevent_truncate
BEFORE TRUNCATE ON system.tenant_invitations
FOR EACH STATEMENT EXECUTE FUNCTION system.prevent_invitation_enrollment_delete();

CREATE TRIGGER trg_enrollment_tickets_transition
BEFORE UPDATE ON system.enrollment_tickets
FOR EACH ROW EXECUTE FUNCTION system.validate_enrollment_ticket_transition();
CREATE TRIGGER trg_enrollment_tickets_prevent_delete
BEFORE DELETE ON system.enrollment_tickets
FOR EACH ROW EXECUTE FUNCTION system.prevent_invitation_enrollment_delete();
CREATE TRIGGER trg_enrollment_tickets_prevent_truncate
BEFORE TRUNCATE ON system.enrollment_tickets
FOR EACH STATEMENT EXECUTE FUNCTION system.prevent_invitation_enrollment_delete();

REVOKE DELETE, TRUNCATE ON system.tenant_invitations FROM PUBLIC;
REVOKE DELETE, TRUNCATE ON system.enrollment_tickets FROM PUBLIC;
