BEGIN;

ALTER TABLE system.mfa_challenges
    ADD COLUMN purpose text NOT NULL DEFAULT 'login' CHECK (purpose IN ('login', 'step_up')),
    ADD COLUMN source_family_id bigint REFERENCES system.refresh_token_families(id),
    ADD CONSTRAINT ck_mfa_challenge_purpose_family CHECK (
        (purpose = 'login' AND source_family_id IS NULL)
        OR (purpose = 'step_up' AND source_family_id IS NOT NULL)
    );

ALTER TABLE system.mfa_challenges ALTER COLUMN purpose DROP DEFAULT;

CREATE INDEX idx_mfa_challenges_source_family_pending
    ON system.mfa_challenges (source_family_id)
    WHERE source_family_id IS NOT NULL AND consumed_at IS NULL;

CREATE OR REPLACE FUNCTION system.validate_mfa_challenge_transition()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.token_hash IS DISTINCT FROM OLD.token_hash
       OR NEW.principal_id IS DISTINCT FROM OLD.principal_id
       OR NEW.issued_authorization_version IS DISTINCT FROM OLD.issued_authorization_version
       OR NEW.authentication_methods IS DISTINCT FROM OLD.authentication_methods
       OR NEW.authenticated_at IS DISTINCT FROM OLD.authenticated_at
       OR NEW.expires_at IS DISTINCT FROM OLD.expires_at
       OR NEW.created_at IS DISTINCT FROM OLD.created_at
       OR NEW.purpose IS DISTINCT FROM OLD.purpose
       OR NEW.source_family_id IS DISTINCT FROM OLD.source_family_id THEN
        RAISE EXCEPTION 'MFA challenge identity and authentication binding are immutable';
    END IF;
    IF OLD.consumed_at IS NOT NULL THEN
        RAISE EXCEPTION 'consumed MFA challenge is immutable';
    END IF;
    IF NEW.failed_attempts NOT IN (OLD.failed_attempts, OLD.failed_attempts + 1) THEN
        RAISE EXCEPTION 'MFA challenge failed attempts must increase one at a time';
    END IF;
    IF NEW.failed_attempts = OLD.failed_attempts AND NEW.consumed_at IS NULL THEN
        RAISE EXCEPTION 'MFA challenge update must consume it or record a failed attempt';
    END IF;
    IF NEW.failed_attempts = 5 AND NEW.consumed_at IS NULL THEN
        RAISE EXCEPTION 'MFA challenge must terminate after five failed attempts';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TABLE system.mfa_enrollments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash char(64) NOT NULL UNIQUE CHECK (token_hash ~ '^[0-9a-f]{64}$'),
    principal_id bigint NOT NULL REFERENCES system.users(id),
    source_family_id bigint NOT NULL REFERENCES system.refresh_token_families(id),
    issued_authorization_version bigint NOT NULL CHECK (issued_authorization_version > 0),
    secret_ciphertext bytea NOT NULL CHECK (octet_length(secret_ciphertext) >= 16),
    secret_nonce bytea NOT NULL CHECK (octet_length(secret_nonce) = 12),
    key_version integer NOT NULL CHECK (key_version > 0),
    expires_at timestamptz NOT NULL,
    failed_attempts integer NOT NULL DEFAULT 0 CHECK (failed_attempts BETWEEN 0 AND 5),
    consumed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (expires_at > created_at),
    CHECK (consumed_at IS NULL OR consumed_at >= created_at)
);

CREATE INDEX idx_mfa_enrollments_principal_created_at
    ON system.mfa_enrollments (principal_id, created_at DESC);
CREATE INDEX idx_mfa_enrollments_source_family_pending
    ON system.mfa_enrollments (source_family_id)
    WHERE consumed_at IS NULL;
CREATE INDEX idx_mfa_enrollments_expires_at
    ON system.mfa_enrollments (expires_at)
    WHERE consumed_at IS NULL;

CREATE FUNCTION system.validate_mfa_enrollment_transition()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.token_hash IS DISTINCT FROM OLD.token_hash
       OR NEW.principal_id IS DISTINCT FROM OLD.principal_id
       OR NEW.source_family_id IS DISTINCT FROM OLD.source_family_id
       OR NEW.issued_authorization_version IS DISTINCT FROM OLD.issued_authorization_version
       OR NEW.secret_ciphertext IS DISTINCT FROM OLD.secret_ciphertext
       OR NEW.secret_nonce IS DISTINCT FROM OLD.secret_nonce
       OR NEW.key_version IS DISTINCT FROM OLD.key_version
       OR NEW.expires_at IS DISTINCT FROM OLD.expires_at
       OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'MFA enrollment identity and secret facts are immutable';
    END IF;
    IF OLD.consumed_at IS NOT NULL THEN
        RAISE EXCEPTION 'consumed MFA enrollment is immutable';
    END IF;
    IF NEW.failed_attempts NOT IN (OLD.failed_attempts, OLD.failed_attempts + 1) THEN
        RAISE EXCEPTION 'MFA enrollment failed attempts must increase one at a time';
    END IF;
    IF NEW.failed_attempts = OLD.failed_attempts AND NEW.consumed_at IS NULL THEN
        RAISE EXCEPTION 'MFA enrollment update must consume it or record a failed attempt';
    END IF;
    IF NEW.failed_attempts = 5 AND NEW.consumed_at IS NULL THEN
        RAISE EXCEPTION 'MFA enrollment must terminate after five failed attempts';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_mfa_enrollments_transition
BEFORE UPDATE ON system.mfa_enrollments
FOR EACH ROW EXECUTE FUNCTION system.validate_mfa_enrollment_transition();
CREATE TRIGGER trg_mfa_enrollments_prevent_delete
BEFORE DELETE ON system.mfa_enrollments
FOR EACH ROW EXECUTE FUNCTION system.prevent_iam_security_fact_delete();
CREATE TRIGGER trg_mfa_enrollments_prevent_truncate
BEFORE TRUNCATE ON system.mfa_enrollments
FOR EACH STATEMENT EXECUTE FUNCTION system.prevent_iam_security_fact_delete();

REVOKE DELETE, TRUNCATE ON system.mfa_enrollments FROM PUBLIC;

COMMIT;
