BEGIN;

CREATE FUNCTION system.audit_details_are_safe(details jsonb)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
STRICT
AS $$
    WITH RECURSIVE json_nodes(value) AS (
        SELECT details
        UNION ALL
        SELECT child.value
        FROM json_nodes node
        CROSS JOIN LATERAL (
            SELECT object_value AS value
            FROM jsonb_each(node.value) AS object_entry(object_key, object_value)
            WHERE jsonb_typeof(node.value) = 'object'
            UNION ALL
            SELECT array_value AS value
            FROM jsonb_array_elements(node.value) AS array_entry(array_value)
            WHERE jsonb_typeof(node.value) = 'array'
        ) child
    ), normalized_keys AS (
        SELECT lower(regexp_replace(object_key, '[^a-zA-Z0-9]', '', 'g')) AS key
        FROM json_nodes node
        CROSS JOIN LATERAL jsonb_object_keys(node.value) AS object_key
        WHERE jsonb_typeof(node.value) = 'object'
    )
    SELECT NOT EXISTS (
        SELECT 1
        FROM normalized_keys
        WHERE key = ANY (ARRAY[
            'password',
            'passwordhash',
            'mfasecret',
            'clientsecret',
            'accesstoken',
            'refreshtoken',
            'delegatedaccesstoken',
            'resourceaccessticket',
            'authorizationcode',
            'devicecode',
            'usercode',
            'codeverifier',
            'codechallenge',
            'pkceverifier',
            'pkcechallenge',
            'state',
            'cookie',
            'setcookie',
            'authorization',
            'authorizationheader',
            'requestbody',
            'query',
            'queryparams',
            'rawquery',
            'errordetail',
            'errorstack'
        ]::text[])
    );
$$;

CREATE FUNCTION system.oauth_audit_details_are_safe(details jsonb)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
STRICT
AS $$
    SELECT details - ARRAY['client_id', 'grant_type', 'decision', 'scope', 'error_code']::text[] = '{}'::jsonb
       AND NOT EXISTS (
           SELECT 1
           FROM jsonb_each(details) entry
           WHERE jsonb_typeof(entry.value) NOT IN ('string', 'null')
       );
$$;

CREATE TABLE system.audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    principal_id bigint REFERENCES system.principals(id),
    principal_type text CHECK (principal_type IN ('user', 'service_principal')),
    context_type text CHECK (context_type IN ('platform', 'tenant')),
    tenant_id bigint REFERENCES system.tenants(id),
    event_name text NOT NULL CHECK (
        event_name ~ '^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$'
    ),
    result text NOT NULL CHECK (result IN ('succeeded', 'failed', 'denied', 'ignored')),
    risk_level text NOT NULL CHECK (risk_level IN ('low', 'medium', 'high', 'critical')),
    module_name text NOT NULL CHECK (
        module_name ~ '^[a-z][a-z0-9_]*$'
    ),
    http_method text CHECK (
        http_method IN ('GET', 'HEAD', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS')
    ),
    resource_path text CHECK (resource_path IS NULL OR btrim(resource_path) <> ''),
    http_status integer CHECK (http_status BETWEEN 100 AND 599),
    request_id text CHECK (request_id IS NULL OR btrim(request_id) <> ''),
    ip_address inet,
    user_agent text,
    entity_type text CHECK (entity_type IS NULL OR btrim(entity_type) <> ''),
    entity_id text CHECK (entity_id IS NULL OR btrim(entity_id) <> ''),
    details jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (
        jsonb_typeof(details) = 'object'
        AND system.audit_details_are_safe(details)
    ),
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (
        (principal_id IS NULL AND principal_type IS NULL)
        OR (principal_id IS NOT NULL AND principal_type IS NOT NULL)
    ),
    CHECK (
        (context_type IS NOT NULL AND context_type = 'tenant' AND tenant_id IS NOT NULL)
        OR (context_type IS NOT NULL AND context_type = 'platform' AND tenant_id IS NULL)
        OR (context_type IS NULL AND tenant_id IS NULL)
    ),
    CHECK (
        (http_method IS NULL AND resource_path IS NULL AND http_status IS NULL)
        OR (http_method IS NOT NULL AND resource_path IS NOT NULL AND http_status IS NOT NULL)
    ),
    CHECK (
        entity_type IS DISTINCT FROM 'oauth_security_event'
        OR (
            entity_id IS NOT NULL
            AND entity_id = event_name
            AND module_name = 'system'
            AND system.oauth_audit_details_are_safe(details)
        )
    ),
    CHECK (
        event_name <> 'oauth.token.refresh_reuse_detected'
        OR risk_level IN ('high', 'critical')
    )
);

CREATE INDEX idx_audit_logs_created_at
    ON system.audit_logs (created_at DESC, id DESC);
CREATE INDEX idx_audit_logs_tenant_created_at
    ON system.audit_logs (tenant_id, created_at DESC, id DESC)
    WHERE tenant_id IS NOT NULL;
CREATE INDEX idx_audit_logs_principal_created_at
    ON system.audit_logs (principal_id, created_at DESC, id DESC)
    WHERE principal_id IS NOT NULL;
CREATE INDEX idx_audit_logs_event_created_at
    ON system.audit_logs (event_name, created_at DESC, id DESC);
CREATE INDEX idx_audit_logs_request_id
    ON system.audit_logs (request_id)
    WHERE request_id IS NOT NULL;
CREATE INDEX idx_audit_logs_entity
    ON system.audit_logs (entity_type, entity_id, created_at DESC)
    WHERE entity_type IS NOT NULL AND entity_id IS NOT NULL;
CREATE INDEX idx_audit_logs_high_risk_created_at
    ON system.audit_logs (risk_level, created_at DESC, id DESC)
    WHERE risk_level IN ('high', 'critical');

CREATE FUNCTION system.validate_audit_log_principal()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    actual_principal_type text;
BEGIN
    IF NEW.principal_id IS NULL THEN
        RETURN NEW;
    END IF;

    SELECT principal_type INTO actual_principal_type
    FROM system.principals
    WHERE id = NEW.principal_id
    FOR KEY SHARE;

    IF actual_principal_type IS DISTINCT FROM NEW.principal_type THEN
        RAISE EXCEPTION 'audit principal % must have type %, found %',
            NEW.principal_id, actual_principal_type, NEW.principal_type
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION system.prevent_audit_log_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'audit logs are append-only'
        USING ERRCODE = '42501';
END;
$$;

CREATE TRIGGER trg_audit_logs_validate_principal
BEFORE INSERT ON system.audit_logs
FOR EACH ROW EXECUTE FUNCTION system.validate_audit_log_principal();

CREATE TRIGGER trg_audit_logs_prevent_update_delete
BEFORE UPDATE OR DELETE ON system.audit_logs
FOR EACH ROW EXECUTE FUNCTION system.prevent_audit_log_mutation();

CREATE TRIGGER trg_audit_logs_prevent_truncate
BEFORE TRUNCATE ON system.audit_logs
FOR EACH STATEMENT EXECUTE FUNCTION system.prevent_audit_log_mutation();

REVOKE UPDATE, DELETE, TRUNCATE ON system.audit_logs FROM PUBLIC;

COMMIT;
