BEGIN;

CREATE TABLE system.principals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    principal_type text NOT NULL CHECK (principal_type IN ('user', 'service_principal')),
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'deactivated')),
    authorization_version bigint NOT NULL DEFAULT 1 CHECK (authorization_version > 0),
    deactivated_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK ((status = 'deactivated') = (deactivated_at IS NOT NULL))
);

CREATE TABLE system.users (
    id bigint PRIMARY KEY REFERENCES system.principals(id),
    display_name text NOT NULL CHECK (btrim(display_name) <> ''),
    primary_email text,
    locale text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE system.tenants (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text NOT NULL UNIQUE CHECK (code = lower(btrim(code)) AND code <> ''),
    name text NOT NULL CHECK (btrim(name) <> ''),
    description text NOT NULL DEFAULT '',
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'closed')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- Engine 是 Execution Authorization 的资源事实。必须在后续 IAM 约束首次引用前，
-- 由同一版本化 migration 路径建立，不能依赖启动后的 GORM AutoMigrate。
CREATE TABLE system.engines (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint,
    name varchar(255) NOT NULL,
    engine_type text NOT NULL,
    engine_origin text NOT NULL DEFAULT 'general',
    connection_info json NOT NULL,
    description text,
    created_by bigint,
    is_builtin boolean DEFAULT false,
    capabilities jsonb,
    connection_status varchar(20) DEFAULT 'unknown',
    last_check_at timestamptz,
    check_message text,
    created_at timestamptz,
    updated_at timestamptz,
    lifecycle_state varchar(20) NOT NULL DEFAULT 'active',
    deletion_scan_task_id varchar(64),
    deletion_execute_task_id varchar(64),
    deletion_error text,
    deletion_requested_at timestamptz,
    deletion_requested_by bigint,
    external_artifact_policy varchar(20) NOT NULL DEFAULT 'delete'
);

CREATE INDEX idx_engines_connection_status ON system.engines (connection_status);
CREATE INDEX idx_engines_engine_type ON system.engines (engine_type);
CREATE INDEX idx_engines_is_builtin ON system.engines (is_builtin);
CREATE INDEX idx_engines_lifecycle_state ON system.engines (lifecycle_state);
CREATE INDEX idx_engines_name ON system.engines (name);
CREATE UNIQUE INDEX idx_engines_tenant_engine_unique ON system.engines (tenant_id, id);
CREATE INDEX idx_engines_tenant_id ON system.engines (tenant_id);

CREATE TABLE system.local_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL UNIQUE REFERENCES system.users(id),
    username text NOT NULL CHECK (btrim(username) <> ''),
    normalized_username text NOT NULL UNIQUE CHECK (normalized_username = btrim(normalized_username) AND normalized_username <> ''),
    password_hash text NOT NULL CHECK (password_hash <> ''),
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'locked', 'disabled')),
    locked_until timestamptz,
    password_changed_at timestamptz NOT NULL,
    last_authenticated_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (status = 'locked' OR locked_until IS NULL)
);

CREATE TABLE system.tenant_memberships (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL REFERENCES system.tenants(id),
    principal_id bigint NOT NULL REFERENCES system.principals(id),
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'ended')),
    source_type text NOT NULL CHECK (source_type IN ('manual', 'idp_jit', 'directory_sync', 'bootstrap')),
    source_ref text,
    joined_at timestamptz NOT NULL,
    expires_at timestamptz,
    ended_at timestamptz,
    created_by_principal_id bigint REFERENCES system.principals(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, principal_id),
    UNIQUE (tenant_id, id),
    CHECK (expires_at IS NULL OR expires_at > joined_at),
    CHECK ((status = 'ended') = (ended_at IS NOT NULL))
);

CREATE INDEX idx_tenant_memberships_principal_status
    ON system.tenant_memberships (principal_id, status);
CREATE INDEX idx_tenant_memberships_tenant_status_created
    ON system.tenant_memberships (tenant_id, status, created_at);
CREATE INDEX idx_tenant_memberships_created_by
    ON system.tenant_memberships (created_by_principal_id)
    WHERE created_by_principal_id IS NOT NULL;

CREATE TABLE system.service_principals (
    id bigint PRIMARY KEY REFERENCES system.principals(id),
    name text NOT NULL CHECK (btrim(name) <> ''),
    description text NOT NULL DEFAULT '',
    owner_scope text NOT NULL CHECK (owner_scope IN ('platform', 'tenant')),
    owner_tenant_id bigint REFERENCES system.tenants(id),
    created_by_principal_id bigint NOT NULL REFERENCES system.principals(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (
        (owner_scope = 'platform' AND owner_tenant_id IS NULL)
        OR (owner_scope = 'tenant' AND owner_tenant_id IS NOT NULL)
    )
);

CREATE INDEX idx_service_principals_owner_tenant
    ON system.service_principals (owner_tenant_id)
    WHERE owner_tenant_id IS NOT NULL;
CREATE INDEX idx_service_principals_created_by
    ON system.service_principals (created_by_principal_id);

CREATE FUNCTION system.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE FUNCTION system.validate_principal_subtype()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    expected_type text := TG_ARGV[0];
    actual_type text;
BEGIN
    SELECT principal_type INTO actual_type
    FROM system.principals
    WHERE id = NEW.id
    FOR KEY SHARE;

    IF actual_type IS DISTINCT FROM expected_type THEN
        RAISE EXCEPTION 'principal % must have type %, found %', NEW.id, expected_type, actual_type
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION system.prevent_principal_type_change()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.principal_type <> OLD.principal_type
       AND (EXISTS (SELECT 1 FROM system.users WHERE id = OLD.id)
            OR EXISTS (SELECT 1 FROM system.service_principals WHERE id = OLD.id)) THEN
        RAISE EXCEPTION 'principal type cannot change after subtype creation'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION system.validate_service_principal_owner()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.owner_scope = 'tenant' AND NOT EXISTS (
        SELECT 1
        FROM system.tenant_memberships tm
        WHERE tm.tenant_id = NEW.owner_tenant_id
          AND tm.principal_id = NEW.id
          AND tm.status = 'active'
          AND (tm.expires_at IS NULL OR tm.expires_at > now())
    ) THEN
        RAISE EXCEPTION 'tenant-owned service principal must have an active membership in its owner tenant'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION system.bump_membership_authorization_version()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    affected_principal_id bigint;
BEGIN
    IF TG_OP = 'DELETE' THEN
        affected_principal_id := OLD.principal_id;
    ELSE
        affected_principal_id := NEW.principal_id;
    END IF;
    UPDATE system.principals
    SET authorization_version = authorization_version + 1,
        updated_at = now()
    WHERE id = affected_principal_id;
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION system.prevent_membership_identity_change()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.tenant_id <> OLD.tenant_id OR NEW.principal_id <> OLD.principal_id THEN
        RAISE EXCEPTION 'tenant membership identity cannot change'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_users_validate_principal_type
BEFORE INSERT OR UPDATE ON system.users
FOR EACH ROW EXECUTE FUNCTION system.validate_principal_subtype('user');

CREATE TRIGGER trg_service_principals_validate_principal_type
BEFORE INSERT OR UPDATE ON system.service_principals
FOR EACH ROW EXECUTE FUNCTION system.validate_principal_subtype('service_principal');

CREATE TRIGGER trg_principals_prevent_type_change
BEFORE UPDATE OF principal_type ON system.principals
FOR EACH ROW EXECUTE FUNCTION system.prevent_principal_type_change();

CREATE TRIGGER trg_service_principals_validate_owner
BEFORE INSERT OR UPDATE OF owner_scope, owner_tenant_id ON system.service_principals
FOR EACH ROW EXECUTE FUNCTION system.validate_service_principal_owner();

CREATE TRIGGER trg_tenant_memberships_authorization_version
AFTER INSERT OR UPDATE OR DELETE ON system.tenant_memberships
FOR EACH ROW EXECUTE FUNCTION system.bump_membership_authorization_version();

CREATE TRIGGER trg_tenant_memberships_prevent_identity_change
BEFORE UPDATE OF tenant_id, principal_id ON system.tenant_memberships
FOR EACH ROW EXECUTE FUNCTION system.prevent_membership_identity_change();

CREATE TRIGGER trg_principals_updated_at
BEFORE UPDATE ON system.principals
FOR EACH ROW EXECUTE FUNCTION system.set_updated_at();
CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON system.users
FOR EACH ROW EXECUTE FUNCTION system.set_updated_at();
CREATE TRIGGER trg_local_accounts_updated_at
BEFORE UPDATE ON system.local_accounts
FOR EACH ROW EXECUTE FUNCTION system.set_updated_at();
CREATE TRIGGER trg_tenants_updated_at
BEFORE UPDATE ON system.tenants
FOR EACH ROW EXECUTE FUNCTION system.set_updated_at();
CREATE TRIGGER trg_tenant_memberships_updated_at
BEFORE UPDATE ON system.tenant_memberships
FOR EACH ROW EXECUTE FUNCTION system.set_updated_at();
CREATE TRIGGER trg_service_principals_updated_at
BEFORE UPDATE ON system.service_principals
FOR EACH ROW EXECUTE FUNCTION system.set_updated_at();

COMMIT;
