BEGIN;

CREATE FUNCTION system.valid_distinct_text_array(values_to_check text[], require_nonempty boolean)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT values_to_check IS NOT NULL
       AND (NOT require_nonempty OR cardinality(values_to_check) > 0)
       AND NOT EXISTS (
           SELECT 1 FROM unnest(values_to_check) AS value
           WHERE value IS NULL OR btrim(value) = ''
       )
       AND cardinality(values_to_check) = (
           SELECT count(DISTINCT value)::integer FROM unnest(values_to_check) AS value
       );
$$;

CREATE TABLE system.context_selection_tickets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash char(64) NOT NULL UNIQUE CHECK (token_hash ~ '^[0-9a-f]{64}$'),
    principal_id bigint NOT NULL REFERENCES system.principals(id),
    issued_authorization_version bigint NOT NULL CHECK (issued_authorization_version > 0),
    client_id text NOT NULL DEFAULT 'addp-web' CHECK (client_id = 'addp-web'),
    authentication_methods text[] NOT NULL CHECK (system.valid_distinct_text_array(authentication_methods, true)),
    assurance_level text NOT NULL CHECK (assurance_level IN ('aal1', 'aal2', 'aal3')),
    authenticated_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    consumed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (authenticated_at <= created_at),
    CHECK (expires_at > created_at),
    CHECK (consumed_at IS NULL OR (consumed_at >= created_at AND consumed_at <= expires_at))
);

CREATE INDEX idx_context_selection_tickets_principal_pending
    ON system.context_selection_tickets (principal_id, expires_at)
    WHERE consumed_at IS NULL;
CREATE INDEX idx_context_selection_tickets_pending_expiry
    ON system.context_selection_tickets (expires_at)
    WHERE consumed_at IS NULL;

CREATE TABLE system.context_selection_ticket_options (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id bigint NOT NULL REFERENCES system.context_selection_tickets(id),
    context_type text NOT NULL CHECK (context_type IN ('platform', 'tenant')),
    tenant_membership_id bigint REFERENCES system.tenant_memberships(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE NULLS NOT DISTINCT (ticket_id, context_type, tenant_membership_id),
    CHECK (
        (context_type = 'platform' AND tenant_membership_id IS NULL)
        OR (context_type = 'tenant' AND tenant_membership_id IS NOT NULL)
    )
);

CREATE INDEX idx_context_selection_ticket_options_membership
    ON system.context_selection_ticket_options (tenant_membership_id)
    WHERE tenant_membership_id IS NOT NULL;

CREATE TABLE system.refresh_token_families (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    protocol_request_id uuid,
    principal_id bigint NOT NULL REFERENCES system.principals(id),
    context_type text NOT NULL CHECK (context_type IN ('platform', 'tenant')),
    tenant_membership_id bigint REFERENCES system.tenant_memberships(id),
    issued_authorization_version bigint NOT NULL CHECK (issued_authorization_version > 0),
    client_id text NOT NULL CHECK (btrim(client_id) <> ''),
    auth_type text NOT NULL CHECK (auth_type IN ('first_party', 'oauth')),
    audiences text[] NOT NULL CHECK (system.valid_distinct_text_array(audiences, true)),
    scopes text[] NOT NULL CHECK (system.valid_distinct_text_array(scopes, false)),
    authentication_methods text[] NOT NULL CHECK (system.valid_distinct_text_array(authentication_methods, true)),
    assurance_level text NOT NULL CHECK (assurance_level IN ('aal1', 'aal2', 'aal3', 'not_applicable')),
    authenticated_at timestamptz NOT NULL,
    step_up_expires_at timestamptz,
    oidc_subject text,
    oidc_acr text,
    oidc_amr text[],
    oidc_claims_schema_version smallint,
    oidc_claims jsonb,
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    revoked_reason text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (protocol_request_id),
    CHECK (
        (context_type = 'platform' AND tenant_membership_id IS NULL)
        OR (context_type = 'tenant' AND tenant_membership_id IS NOT NULL)
    ),
    CHECK (
        (auth_type = 'first_party'
            AND protocol_request_id IS NULL
            AND client_id = 'addp-web'
            AND audiences = ARRAY['addp.api']::text[]
            AND cardinality(scopes) = 0)
        OR (auth_type = 'oauth'
            AND protocol_request_id IS NOT NULL
            AND client_id <> 'addp-web'
            AND cardinality(scopes) > 0)
    ),
    CHECK (authenticated_at <= created_at),
    CHECK (expires_at > created_at),
    CHECK (step_up_expires_at IS NULL OR (step_up_expires_at >= authenticated_at AND step_up_expires_at <= expires_at)),
    CHECK (
        (revoked_at IS NULL AND revoked_reason IS NULL)
        OR (revoked_at IS NOT NULL AND revoked_reason IS NOT NULL AND btrim(revoked_reason) <> '')
    ),
    CHECK (revoked_at IS NULL OR revoked_at >= created_at),
    CHECK (
        (oidc_subject IS NULL
            AND oidc_acr IS NULL
            AND oidc_amr IS NULL
            AND oidc_claims_schema_version IS NULL
            AND oidc_claims IS NULL)
        OR (auth_type = 'oauth'
            AND oidc_subject IS NOT NULL
            AND btrim(oidc_subject) <> ''
            AND oidc_acr IS NOT NULL
            AND btrim(oidc_acr) <> ''
            AND oidc_amr IS NOT NULL
            AND system.valid_distinct_text_array(oidc_amr, true)
            AND oidc_claims_schema_version IS NOT NULL
            AND oidc_claims_schema_version > 0
            AND oidc_claims IS NOT NULL
            AND jsonb_typeof(oidc_claims) = 'object')
    )
);

CREATE INDEX idx_refresh_token_families_principal_active
    ON system.refresh_token_families (principal_id, expires_at)
    WHERE revoked_at IS NULL;
CREATE INDEX idx_refresh_token_families_membership_active
    ON system.refresh_token_families (tenant_membership_id, expires_at)
    WHERE tenant_membership_id IS NOT NULL AND revoked_at IS NULL;

CREATE TABLE system.access_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash char(64) NOT NULL UNIQUE CHECK (token_hash ~ '^[0-9a-f]{64}$'),
    family_id bigint NOT NULL REFERENCES system.refresh_token_families(id),
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (expires_at > created_at),
    CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);

CREATE UNIQUE INDEX uq_access_tokens_current_family
    ON system.access_tokens (family_id)
    WHERE revoked_at IS NULL;
CREATE INDEX idx_access_tokens_active_expiry
    ON system.access_tokens (expires_at)
    WHERE revoked_at IS NULL;

CREATE TABLE system.refresh_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash char(64) NOT NULL UNIQUE CHECK (token_hash ~ '^[0-9a-f]{64}$'),
    family_id bigint NOT NULL REFERENCES system.refresh_token_families(id),
    issued_access_token_id bigint NOT NULL UNIQUE REFERENCES system.access_tokens(id),
    parent_token_id bigint REFERENCES system.refresh_tokens(id),
    replaced_by_token_id bigint REFERENCES system.refresh_tokens(id),
    expires_at timestamptz NOT NULL,
    used_at timestamptz,
    reuse_detected_at timestamptz,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (expires_at > created_at),
    CHECK (parent_token_id IS NULL OR parent_token_id <> id),
    CHECK (replaced_by_token_id IS NULL OR replaced_by_token_id <> id),
    CHECK (used_at IS NULL OR used_at >= created_at),
    CHECK (reuse_detected_at IS NULL OR (used_at IS NOT NULL AND reuse_detected_at >= used_at)),
    CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);

CREATE INDEX idx_refresh_tokens_family
    ON system.refresh_tokens (family_id);
CREATE UNIQUE INDEX uq_refresh_tokens_parent
    ON system.refresh_tokens (parent_token_id)
    WHERE parent_token_id IS NOT NULL;
CREATE UNIQUE INDEX uq_refresh_tokens_replacement
    ON system.refresh_tokens (replaced_by_token_id)
    WHERE replaced_by_token_id IS NOT NULL;
CREATE UNIQUE INDEX uq_refresh_tokens_current_family
    ON system.refresh_tokens (family_id)
    WHERE used_at IS NULL AND revoked_at IS NULL;
CREATE INDEX idx_refresh_tokens_active_expiry
    ON system.refresh_tokens (expires_at)
    WHERE revoked_at IS NULL;

CREATE TABLE system.delegated_access_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash char(64) NOT NULL UNIQUE CHECK (token_hash ~ '^[0-9a-f]{64}$'),
    source_access_token_id bigint NOT NULL REFERENCES system.access_tokens(id),
    audience text NOT NULL CHECK (audience ~ '^[a-z][a-z0-9_]*$'),
    scopes text[] NOT NULL CHECK (system.valid_distinct_text_array(scopes, true)),
    agent_run_id text NOT NULL CHECK (btrim(agent_run_id) <> ''),
    tool_call_id text NOT NULL CHECK (btrim(tool_call_id) <> ''),
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (agent_run_id, tool_call_id),
    CHECK (expires_at > created_at),
    CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);

CREATE INDEX idx_delegated_access_tokens_source
    ON system.delegated_access_tokens (source_access_token_id);
CREATE INDEX idx_delegated_access_tokens_audience_active
    ON system.delegated_access_tokens (audience, expires_at)
    WHERE revoked_at IS NULL;
CREATE INDEX idx_delegated_access_tokens_run
    ON system.delegated_access_tokens (agent_run_id);

CREATE TABLE system.resource_access_tickets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash char(64) NOT NULL UNIQUE CHECK (token_hash ~ '^[0-9a-f]{64}$'),
    family_id bigint NOT NULL REFERENCES system.refresh_token_families(id),
    owner text NOT NULL CHECK (owner ~ '^[a-z][a-z0-9_]*$'),
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (expires_at > created_at),
    CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);

CREATE UNIQUE INDEX uq_resource_access_tickets_active_owner
    ON system.resource_access_tickets (family_id, owner)
    WHERE revoked_at IS NULL;
CREATE INDEX idx_resource_access_tickets_owner_active
    ON system.resource_access_tickets (owner, expires_at)
    WHERE revoked_at IS NULL;

CREATE FUNCTION system.validate_context_selection_ticket()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    target_principal system.principals%ROWTYPE;
BEGIN
    SELECT * INTO target_principal
    FROM system.principals
    WHERE id = NEW.principal_id
    FOR KEY SHARE;

    IF target_principal.principal_type <> 'user'
       OR target_principal.status <> 'active'
       OR NEW.issued_authorization_version <> target_principal.authorization_version
       OR NEW.consumed_at IS NOT NULL THEN
        RAISE EXCEPTION 'context selection ticket requires an active user at the current authorization version'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION system.validate_context_selection_ticket_update()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.token_hash <> OLD.token_hash
       OR NEW.principal_id <> OLD.principal_id
       OR NEW.issued_authorization_version <> OLD.issued_authorization_version
       OR NEW.client_id <> OLD.client_id
       OR NEW.authentication_methods <> OLD.authentication_methods
       OR NEW.assurance_level <> OLD.assurance_level
       OR NEW.authenticated_at <> OLD.authenticated_at
       OR NEW.expires_at <> OLD.expires_at
       OR NEW.created_at <> OLD.created_at THEN
        RAISE EXCEPTION 'context selection ticket facts are immutable'
            USING ERRCODE = '23514';
    END IF;
    IF OLD.consumed_at IS NOT NULL OR NEW.consumed_at IS NULL THEN
        RAISE EXCEPTION 'context selection ticket may only be consumed once'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION system.validate_context_selection_option()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    target_ticket system.context_selection_tickets%ROWTYPE;
BEGIN
    SELECT * INTO target_ticket
    FROM system.context_selection_tickets
    WHERE id = NEW.ticket_id
    FOR UPDATE;

    IF target_ticket.consumed_at IS NOT NULL OR target_ticket.expires_at <= now() THEN
        RAISE EXCEPTION 'context selection ticket is not pending'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.context_type = 'platform' AND (
        target_ticket.assurance_level NOT IN ('aal2', 'aal3') OR NOT EXISTS (
            SELECT 1
            FROM system.role_assignments assignment
            WHERE assignment.principal_id = target_ticket.principal_id
              AND assignment.scope_type = 'platform'
              AND assignment.status = 'active'
              AND assignment.valid_from <= now()
              AND (assignment.valid_until IS NULL OR assignment.valid_until > now())
        )
    ) THEN
        RAISE EXCEPTION 'platform context option requires aal2 and an effective platform role'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.context_type = 'tenant' AND NOT EXISTS (
        SELECT 1
        FROM system.tenant_memberships membership
        JOIN system.tenants tenant ON tenant.id = membership.tenant_id
        WHERE membership.id = NEW.tenant_membership_id
          AND membership.principal_id = target_ticket.principal_id
          AND membership.status = 'active'
          AND tenant.status = 'active'
          AND (membership.expires_at IS NULL OR membership.expires_at > now())
    ) THEN
        RAISE EXCEPTION 'tenant context option requires an active membership for the ticket principal'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION system.validate_token_family()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    target_principal system.principals%ROWTYPE;
BEGIN
    SELECT * INTO target_principal
    FROM system.principals
    WHERE id = NEW.principal_id
    FOR UPDATE;

    IF NEW.revoked_at IS NOT NULL
       OR target_principal.status <> 'active'
       OR NEW.issued_authorization_version <> target_principal.authorization_version THEN
        RAISE EXCEPTION 'token family requires an active principal at the current authorization version'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.context_type = 'platform' THEN
        IF target_principal.principal_type = 'user' AND NEW.assurance_level NOT IN ('aal2', 'aal3') THEN
            RAISE EXCEPTION 'platform user token family requires aal2'
                USING ERRCODE = '23514';
        END IF;
        IF NOT EXISTS (
            SELECT 1
            FROM system.role_assignments assignment
            WHERE assignment.principal_id = NEW.principal_id
              AND assignment.scope_type = 'platform'
              AND assignment.status = 'active'
              AND assignment.valid_from <= now()
              AND (assignment.valid_until IS NULL OR assignment.valid_until > now())
        ) THEN
            RAISE EXCEPTION 'platform token family requires an effective platform role'
                USING ERRCODE = '23514';
        END IF;
    ELSIF NOT EXISTS (
        SELECT 1
        FROM system.tenant_memberships membership
        JOIN system.tenants tenant ON tenant.id = membership.tenant_id
        WHERE membership.id = NEW.tenant_membership_id
          AND membership.principal_id = NEW.principal_id
          AND membership.status = 'active'
          AND tenant.status = 'active'
          AND (membership.expires_at IS NULL OR membership.expires_at > now())
    ) THEN
        RAISE EXCEPTION 'tenant token family requires an active membership for the principal'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION system.validate_token_family_update()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.protocol_request_id IS DISTINCT FROM OLD.protocol_request_id
       OR NEW.principal_id <> OLD.principal_id
       OR NEW.context_type <> OLD.context_type
       OR NEW.tenant_membership_id IS DISTINCT FROM OLD.tenant_membership_id
       OR NEW.issued_authorization_version <> OLD.issued_authorization_version
       OR NEW.client_id <> OLD.client_id
       OR NEW.auth_type <> OLD.auth_type
       OR NEW.audiences <> OLD.audiences
       OR NEW.scopes <> OLD.scopes
       OR NEW.authentication_methods <> OLD.authentication_methods
       OR NEW.assurance_level <> OLD.assurance_level
       OR NEW.authenticated_at <> OLD.authenticated_at
       OR NEW.step_up_expires_at IS DISTINCT FROM OLD.step_up_expires_at
       OR NEW.oidc_subject IS DISTINCT FROM OLD.oidc_subject
       OR NEW.oidc_acr IS DISTINCT FROM OLD.oidc_acr
       OR NEW.oidc_amr IS DISTINCT FROM OLD.oidc_amr
       OR NEW.oidc_claims_schema_version IS DISTINCT FROM OLD.oidc_claims_schema_version
       OR NEW.oidc_claims IS DISTINCT FROM OLD.oidc_claims
       OR NEW.expires_at <> OLD.expires_at
       OR NEW.created_at <> OLD.created_at THEN
        RAISE EXCEPTION 'token family identity, context, authentication, and final expiry are immutable'
            USING ERRCODE = '23514';
    END IF;
    IF OLD.revoked_at IS NOT NULL
       OR NEW.revoked_at IS NULL
       OR NEW.revoked_reason IS NULL THEN
        RAISE EXCEPTION 'token family may only transition once from active to revoked'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION system.validate_access_token()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    target_family system.refresh_token_families%ROWTYPE;
BEGIN
    SELECT * INTO target_family
    FROM system.refresh_token_families
    WHERE id = NEW.family_id
    FOR KEY SHARE;

    IF NEW.revoked_at IS NOT NULL
       OR target_family.revoked_at IS NOT NULL
       OR target_family.expires_at <= now()
       OR NEW.expires_at > target_family.expires_at THEN
        RAISE EXCEPTION 'access token requires an active family and bounded expiry'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION system.validate_access_token_update()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.token_hash <> OLD.token_hash
       OR NEW.family_id <> OLD.family_id
       OR NEW.expires_at <> OLD.expires_at
       OR NEW.created_at <> OLD.created_at
       OR OLD.revoked_at IS NOT NULL
       OR NEW.revoked_at IS NULL THEN
        RAISE EXCEPTION 'access token facts are immutable and revocation is one-way'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION system.validate_refresh_token()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    target_family system.refresh_token_families%ROWTYPE;
    target_access system.access_tokens%ROWTYPE;
    parent_token system.refresh_tokens%ROWTYPE;
BEGIN
    SELECT * INTO target_family
    FROM system.refresh_token_families
    WHERE id = NEW.family_id
    FOR KEY SHARE;
    SELECT * INTO target_access
    FROM system.access_tokens
    WHERE id = NEW.issued_access_token_id
    FOR KEY SHARE;

    IF NEW.used_at IS NOT NULL OR NEW.reuse_detected_at IS NOT NULL OR NEW.revoked_at IS NOT NULL OR NEW.replaced_by_token_id IS NOT NULL THEN
        RAISE EXCEPTION 'new refresh token must be current and unused'
            USING ERRCODE = '23514';
    END IF;
    IF target_family.revoked_at IS NOT NULL
       OR target_family.expires_at <= now()
       OR target_access.family_id <> NEW.family_id
       OR target_access.revoked_at IS NOT NULL
       OR NEW.expires_at > target_family.expires_at THEN
        RAISE EXCEPTION 'refresh token requires an active family and matching access token'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.parent_token_id IS NOT NULL THEN
        SELECT * INTO parent_token
        FROM system.refresh_tokens
        WHERE id = NEW.parent_token_id
        FOR UPDATE;
        IF parent_token.family_id <> NEW.family_id
           OR parent_token.used_at IS NULL
           OR parent_token.replaced_by_token_id IS NOT NULL THEN
            RAISE EXCEPTION 'refresh token parent must be a used unreplaced token in the same family'
                USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION system.validate_refresh_token_update()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    replacement system.refresh_tokens%ROWTYPE;
BEGIN
    IF NEW.token_hash <> OLD.token_hash
       OR NEW.family_id <> OLD.family_id
       OR NEW.issued_access_token_id <> OLD.issued_access_token_id
       OR NEW.parent_token_id IS DISTINCT FROM OLD.parent_token_id
       OR NEW.expires_at <> OLD.expires_at
       OR NEW.created_at <> OLD.created_at
       OR (OLD.used_at IS NOT NULL AND NEW.used_at IS DISTINCT FROM OLD.used_at)
       OR (OLD.reuse_detected_at IS NOT NULL AND NEW.reuse_detected_at IS DISTINCT FROM OLD.reuse_detected_at)
       OR (OLD.revoked_at IS NOT NULL AND NEW.revoked_at IS DISTINCT FROM OLD.revoked_at)
       OR (OLD.replaced_by_token_id IS NOT NULL AND NEW.replaced_by_token_id IS DISTINCT FROM OLD.replaced_by_token_id) THEN
        RAISE EXCEPTION 'refresh token identity and terminal facts are immutable'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.replaced_by_token_id IS NOT NULL AND OLD.replaced_by_token_id IS NULL THEN
        SELECT * INTO replacement
        FROM system.refresh_tokens
        WHERE id = NEW.replaced_by_token_id
        FOR KEY SHARE;
        IF replacement.family_id <> NEW.family_id OR replacement.parent_token_id <> NEW.id THEN
            RAISE EXCEPTION 'refresh token replacement must be the matching child in the same family'
                USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION system.validate_delegated_access_token()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    source_token system.access_tokens%ROWTYPE;
    source_family system.refresh_token_families%ROWTYPE;
    source_principal_type text;
BEGIN
    SELECT * INTO source_token
    FROM system.access_tokens
    WHERE id = NEW.source_access_token_id
    FOR KEY SHARE;
    SELECT * INTO source_family
    FROM system.refresh_token_families
    WHERE id = source_token.family_id
    FOR KEY SHARE;
    SELECT principal_type INTO source_principal_type
    FROM system.principals
    WHERE id = source_family.principal_id
    FOR KEY SHARE;

    IF NEW.revoked_at IS NOT NULL
       OR source_principal_type <> 'user'
       OR source_token.revoked_at IS NOT NULL
       OR source_family.revoked_at IS NOT NULL
       OR NEW.expires_at > source_token.expires_at
       OR NEW.expires_at > source_family.expires_at THEN
        RAISE EXCEPTION 'delegated access token requires an active user source token and bounded expiry'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION system.validate_delegated_access_token_update()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.token_hash <> OLD.token_hash
       OR NEW.source_access_token_id <> OLD.source_access_token_id
       OR NEW.audience <> OLD.audience
       OR NEW.scopes <> OLD.scopes
       OR NEW.agent_run_id <> OLD.agent_run_id
       OR NEW.tool_call_id <> OLD.tool_call_id
       OR NEW.expires_at <> OLD.expires_at
       OR NEW.created_at <> OLD.created_at
       OR OLD.revoked_at IS NOT NULL
       OR NEW.revoked_at IS NULL THEN
        RAISE EXCEPTION 'delegated access token facts are immutable and revocation is one-way'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION system.validate_resource_access_ticket()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    target_family system.refresh_token_families%ROWTYPE;
BEGIN
    SELECT * INTO target_family
    FROM system.refresh_token_families
    WHERE id = NEW.family_id
    FOR KEY SHARE;

    IF NEW.revoked_at IS NOT NULL
       OR target_family.auth_type <> 'first_party'
       OR target_family.revoked_at IS NOT NULL
       OR target_family.expires_at <= now()
       OR NEW.expires_at > target_family.expires_at THEN
        RAISE EXCEPTION 'resource access ticket requires an active first-party family and bounded expiry'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION system.validate_resource_access_ticket_update()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.token_hash <> OLD.token_hash
       OR NEW.family_id <> OLD.family_id
       OR NEW.owner <> OLD.owner
       OR NEW.expires_at <> OLD.expires_at
       OR NEW.created_at <> OLD.created_at
       OR OLD.revoked_at IS NOT NULL
       OR NEW.revoked_at IS NULL THEN
        RAISE EXCEPTION 'resource access ticket facts are immutable and revocation is one-way'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION system.revoke_access_token_delegations()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.revoked_at IS NULL AND NEW.revoked_at IS NOT NULL THEN
        UPDATE system.delegated_access_tokens
        SET revoked_at = NEW.revoked_at
        WHERE source_access_token_id = NEW.id
          AND revoked_at IS NULL;
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION system.revoke_token_family_derivatives()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.revoked_at IS NULL AND NEW.revoked_at IS NOT NULL THEN
        UPDATE system.refresh_tokens
        SET revoked_at = NEW.revoked_at
        WHERE family_id = NEW.id
          AND revoked_at IS NULL;

        UPDATE system.access_tokens
        SET revoked_at = NEW.revoked_at
        WHERE family_id = NEW.id
          AND revoked_at IS NULL;

        UPDATE system.resource_access_tickets
        SET revoked_at = NEW.revoked_at
        WHERE family_id = NEW.id
          AND revoked_at IS NULL;
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION system.prevent_token_history_delete()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION '% history cannot be physically deleted', TG_TABLE_NAME
        USING ERRCODE = '23514';
END;
$$;

CREATE TRIGGER trg_context_selection_tickets_validate
BEFORE INSERT ON system.context_selection_tickets
FOR EACH ROW EXECUTE FUNCTION system.validate_context_selection_ticket();
CREATE TRIGGER trg_context_selection_tickets_validate_update
BEFORE UPDATE ON system.context_selection_tickets
FOR EACH ROW EXECUTE FUNCTION system.validate_context_selection_ticket_update();
CREATE TRIGGER trg_context_selection_tickets_prevent_delete
BEFORE DELETE ON system.context_selection_tickets
FOR EACH ROW EXECUTE FUNCTION system.prevent_token_history_delete();
CREATE TRIGGER trg_context_selection_ticket_options_validate
BEFORE INSERT ON system.context_selection_ticket_options
FOR EACH ROW EXECUTE FUNCTION system.validate_context_selection_option();
CREATE TRIGGER trg_context_selection_ticket_options_immutable
BEFORE UPDATE OR DELETE ON system.context_selection_ticket_options
FOR EACH ROW EXECUTE FUNCTION system.prevent_token_history_delete();

CREATE TRIGGER trg_refresh_token_families_validate
BEFORE INSERT ON system.refresh_token_families
FOR EACH ROW EXECUTE FUNCTION system.validate_token_family();
CREATE TRIGGER trg_refresh_token_families_validate_update
BEFORE UPDATE ON system.refresh_token_families
FOR EACH ROW EXECUTE FUNCTION system.validate_token_family_update();
CREATE TRIGGER trg_refresh_token_families_updated_at
BEFORE UPDATE ON system.refresh_token_families
FOR EACH ROW EXECUTE FUNCTION system.set_updated_at();
CREATE TRIGGER trg_refresh_token_families_revoke_derivatives
AFTER UPDATE ON system.refresh_token_families
FOR EACH ROW EXECUTE FUNCTION system.revoke_token_family_derivatives();
CREATE TRIGGER trg_refresh_token_families_prevent_delete
BEFORE DELETE ON system.refresh_token_families
FOR EACH ROW EXECUTE FUNCTION system.prevent_token_history_delete();

CREATE TRIGGER trg_access_tokens_validate
BEFORE INSERT ON system.access_tokens
FOR EACH ROW EXECUTE FUNCTION system.validate_access_token();
CREATE TRIGGER trg_access_tokens_validate_update
BEFORE UPDATE ON system.access_tokens
FOR EACH ROW EXECUTE FUNCTION system.validate_access_token_update();
CREATE TRIGGER trg_access_tokens_revoke_delegations
AFTER UPDATE ON system.access_tokens
FOR EACH ROW EXECUTE FUNCTION system.revoke_access_token_delegations();
CREATE TRIGGER trg_access_tokens_prevent_delete
BEFORE DELETE ON system.access_tokens
FOR EACH ROW EXECUTE FUNCTION system.prevent_token_history_delete();

CREATE TRIGGER trg_refresh_tokens_validate
BEFORE INSERT ON system.refresh_tokens
FOR EACH ROW EXECUTE FUNCTION system.validate_refresh_token();
CREATE TRIGGER trg_refresh_tokens_validate_update
BEFORE UPDATE ON system.refresh_tokens
FOR EACH ROW EXECUTE FUNCTION system.validate_refresh_token_update();
CREATE TRIGGER trg_refresh_tokens_prevent_delete
BEFORE DELETE ON system.refresh_tokens
FOR EACH ROW EXECUTE FUNCTION system.prevent_token_history_delete();

CREATE TRIGGER trg_delegated_access_tokens_validate
BEFORE INSERT ON system.delegated_access_tokens
FOR EACH ROW EXECUTE FUNCTION system.validate_delegated_access_token();
CREATE TRIGGER trg_delegated_access_tokens_validate_update
BEFORE UPDATE ON system.delegated_access_tokens
FOR EACH ROW EXECUTE FUNCTION system.validate_delegated_access_token_update();
CREATE TRIGGER trg_delegated_access_tokens_prevent_delete
BEFORE DELETE ON system.delegated_access_tokens
FOR EACH ROW EXECUTE FUNCTION system.prevent_token_history_delete();

CREATE TRIGGER trg_resource_access_tickets_validate
BEFORE INSERT ON system.resource_access_tickets
FOR EACH ROW EXECUTE FUNCTION system.validate_resource_access_ticket();
CREATE TRIGGER trg_resource_access_tickets_validate_update
BEFORE UPDATE ON system.resource_access_tickets
FOR EACH ROW EXECUTE FUNCTION system.validate_resource_access_ticket_update();
CREATE TRIGGER trg_resource_access_tickets_prevent_delete
BEFORE DELETE ON system.resource_access_tickets
FOR EACH ROW EXECUTE FUNCTION system.prevent_token_history_delete();

COMMIT;
