BEGIN;

ALTER TABLE system.mfa_credentials
    DROP CONSTRAINT mfa_credentials_user_id_method_key;

CREATE UNIQUE INDEX uq_mfa_credentials_active_user_method
    ON system.mfa_credentials (user_id, method)
    WHERE status = 'active';

CREATE TABLE system.iam_recovery_attempts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    secret_hash char(64) CHECK (secret_hash IS NULL OR secret_hash ~ '^[0-9a-f]{64}$'),
    status text NOT NULL DEFAULT 'prepared' CHECK (status IN ('prepared', 'completed', 'expired')),
    prepared_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    completed_at timestamptz,
    expired_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (expires_at > prepared_at),
    CHECK (
        (status = 'prepared' AND secret_hash IS NOT NULL AND completed_at IS NULL AND expired_at IS NULL)
        OR (status = 'completed' AND secret_hash IS NULL AND completed_at IS NOT NULL AND expired_at IS NULL)
        OR (status = 'expired' AND secret_hash IS NULL AND completed_at IS NULL AND expired_at IS NOT NULL)
    ),
    CHECK (completed_at IS NULL OR completed_at >= prepared_at),
    CHECK (expired_at IS NULL OR expired_at >= prepared_at)
);

CREATE UNIQUE INDEX uq_iam_recovery_attempts_prepared
    ON system.iam_recovery_attempts ((true))
    WHERE status = 'prepared';

CREATE INDEX idx_iam_recovery_attempts_prepared_expiry
    ON system.iam_recovery_attempts (expires_at)
    WHERE status = 'prepared';

CREATE FUNCTION system.guard_iam_recovery_attempt_update()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.status <> 'prepared' THEN
        RAISE EXCEPTION 'terminal IAM recovery attempt cannot be changed';
    END IF;
    IF NEW.status NOT IN ('completed', 'expired') THEN
        RAISE EXCEPTION 'IAM recovery attempt only allows prepared to completed or expired';
    END IF;
    IF NEW.id <> OLD.id
       OR NEW.prepared_at IS DISTINCT FROM OLD.prepared_at
       OR NEW.expires_at IS DISTINCT FROM OLD.expires_at
       OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'IAM recovery attempt identity is immutable';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_iam_recovery_attempts_guard_update
BEFORE UPDATE ON system.iam_recovery_attempts
FOR EACH ROW EXECUTE FUNCTION system.guard_iam_recovery_attempt_update();

CREATE FUNCTION system.reject_iam_recovery_attempt_removal()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'IAM recovery attempts are immutable security facts';
END;
$$;

CREATE TRIGGER trg_iam_recovery_attempts_reject_delete
BEFORE DELETE ON system.iam_recovery_attempts
FOR EACH ROW EXECUTE FUNCTION system.reject_iam_recovery_attempt_removal();

CREATE TRIGGER trg_iam_recovery_attempts_reject_truncate
BEFORE TRUNCATE ON system.iam_recovery_attempts
FOR EACH STATEMENT EXECUTE FUNCTION system.reject_iam_recovery_attempt_removal();

COMMIT;
