FROM python:3.10-slim

WORKDIR /app

# 安装依赖
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 复制代码
COPY spatial ./spatial
COPY api_server.py .

# 暴露端口
EXPOSE 5000

# 启动服务
CMD ["python", "api_server.py"]
