// Code generated by common/authorization/cmd/manifest; DO NOT EDIT.
// Source: standard/authorization/permissions.yaml (manifest_version=5).

package authorization

const (
	PermissionStandardCatalogRead              = "standard.catalog.read"
	PermissionStandardCodeSetCreate            = "standard.code_set.create"
	PermissionStandardCodeSetDelete            = "standard.code_set.delete"
	PermissionStandardCodeSetPublish           = "standard.code_set.publish"
	PermissionStandardCodeSetRead              = "standard.code_set.read"
	PermissionStandardCodeSetUpdate            = "standard.code_set.update"
	PermissionStandardDimensionHierarchyCreate = "standard.dimension_hierarchy.create"
	PermissionStandardDimensionHierarchyDelete = "standard.dimension_hierarchy.delete"
	PermissionStandardDimensionHierarchyRead   = "standard.dimension_hierarchy.read"
	PermissionStandardDimensionHierarchyUpdate = "standard.dimension_hierarchy.update"
	PermissionStandardDocumentCreate           = "standard.document.create"
	PermissionStandardDocumentDelete           = "standard.document.delete"
	PermissionStandardDocumentRead             = "standard.document.read"
	PermissionStandardDocumentUpdate           = "standard.document.update"
	PermissionStandardDomainCreate             = "standard.domain.create"
	PermissionStandardDomainDelete             = "standard.domain.delete"
	PermissionStandardDomainRead               = "standard.domain.read"
	PermissionStandardDomainUpdate             = "standard.domain.update"
	PermissionStandardElementCreate            = "standard.element.create"
	PermissionStandardElementDelete            = "standard.element.delete"
	PermissionStandardElementPublish           = "standard.element.publish"
	PermissionStandardElementRead              = "standard.element.read"
	PermissionStandardElementUpdate            = "standard.element.update"
	PermissionStandardGlossaryApprove          = "standard.glossary.approve"
	PermissionStandardGlossaryCreate           = "standard.glossary.create"
	PermissionStandardGlossaryDelete           = "standard.glossary.delete"
	PermissionStandardGlossaryOffline          = "standard.glossary.offline"
	PermissionStandardGlossaryRead             = "standard.glossary.read"
	PermissionStandardGlossaryUpdate           = "standard.glossary.update"
	PermissionStandardMetricApprove            = "standard.metric.approve"
	PermissionStandardMetricCreate             = "standard.metric.create"
	PermissionStandardMetricDelete             = "standard.metric.delete"
	PermissionStandardMetricOffline            = "standard.metric.offline"
	PermissionStandardMetricRead               = "standard.metric.read"
	PermissionStandardMetricUpdate             = "standard.metric.update"
	PermissionStandardUnitCreate               = "standard.unit.create"
	PermissionStandardUnitDelete               = "standard.unit.delete"
	PermissionStandardUnitRead                 = "standard.unit.read"
	PermissionStandardUnitUpdate               = "standard.unit.update"
)

var permissionKeys = [...]string{
	"standard.catalog.read",
	"standard.code_set.create",
	"standard.code_set.delete",
	"standard.code_set.publish",
	"standard.code_set.read",
	"standard.code_set.update",
	"standard.dimension_hierarchy.create",
	"standard.dimension_hierarchy.delete",
	"standard.dimension_hierarchy.read",
	"standard.dimension_hierarchy.update",
	"standard.document.create",
	"standard.document.delete",
	"standard.document.read",
	"standard.document.update",
	"standard.domain.create",
	"standard.domain.delete",
	"standard.domain.read",
	"standard.domain.update",
	"standard.element.create",
	"standard.element.delete",
	"standard.element.publish",
	"standard.element.read",
	"standard.element.update",
	"standard.glossary.approve",
	"standard.glossary.create",
	"standard.glossary.delete",
	"standard.glossary.offline",
	"standard.glossary.read",
	"standard.glossary.update",
	"standard.metric.approve",
	"standard.metric.create",
	"standard.metric.delete",
	"standard.metric.offline",
	"standard.metric.read",
	"standard.metric.update",
	"standard.unit.create",
	"standard.unit.delete",
	"standard.unit.read",
	"standard.unit.update",
}

// PermissionKeys returns the active owner-local Permission keys in stable order.
func PermissionKeys() []string {
	return append([]string(nil), permissionKeys[:]...)
}
