-- 004_create_embeddings.sql
--
-- no-op.
--
-- manager.embeddings 曾经以 bucket/object_key/fingerprint/modality 保存旧向量记录；
-- 向量化收敛为 artifact state 后，结果表只表达 data item 的当前向量化状态。
--
-- 当前表结构由 013_recreate_embeddings_as_artifact_state.sql 定义，运行时由
-- manager/backend/internal/repository/database.go 中的 ensureEmbeddingArtifactStateSchema
-- 兜底重建。不再保留旧 DDL，避免新环境先创建旧语义再迁移。
