-- 005_rename_document_embeddings_to_embeddings.sql
--
-- no-op.
--
-- 历史版本曾从 manager.document_embeddings 重命名到 manager.embeddings。
-- 当前 clean break 后不再保留 document_embeddings，也不再保留旧 fingerprint +
-- modality 结构。
--
-- 当前 manager.embeddings artifact state 结构由
-- 013_recreate_embeddings_as_artifact_state.sql 统一定义。
