-- 006_create_embedding_tasks.sql
--
-- no-op.
--
-- embedding_tasks 曾经是向量化执行记录表；任务体系收敛后，
-- 执行记录统一进入 common.task_executions，manager.embedding_tasks
-- 只作为向量化任务定义表。
--
-- 当前任务定义型表结构由 012_alter_embedding_tasks_to_task_def.sql 定义。
-- 不再保留旧执行记录型 DDL，避免新环境先创建旧语义再删除。
