// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/check-tasks": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CheckTask"
                ],
                "summary": "获取检查任务列表 | List check tasks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CheckTask"
                ],
                "summary": "创建检查任务 | Create check task",
                "parameters": [
                    {
                        "description": "任务信息 | Task info",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/check-tasks/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CheckTask"
                ],
                "summary": "获取检查任务详情 | Get check task detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "任务ID | Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CheckTask"
                ],
                "summary": "更新检查任务 | Update check task",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "任务ID | Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新信息 | Update info",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CheckTask"
                ],
                "summary": "删除检查任务 | Delete check task",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "任务ID | Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/check-tasks/{id}/run": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CheckTask"
                ],
                "summary": "执行检查任务 | Run check task",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "任务ID | Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "任务已有活动 execution | Task already has an active execution",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/executions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Execution"
                ],
                "summary": "获取执行记录列表 | List execution records",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/executions/{execution_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Execution"
                ],
                "summary": "获取执行记录详情 | Get execution record detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "执行ID | Execution ID",
                        "name": "execution_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/issues": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Issue"
                ],
                "summary": "获取问题工单列表 | List quality issues",
                "parameters": [
                    {
                        "type": "string",
                        "description": "状态 | Status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "引擎ID | Engine ID",
                        "name": "engine_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    }
                }
            }
        },
        "/issues/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Issue"
                ],
                "summary": "获取问题工单详情 | Get issue detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "工单ID | Issue ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/issues/{id}/status": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Issue"
                ],
                "summary": "更新问题工单状态 | Update issue status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "工单ID | Issue ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "状态信息 | Status info",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/rule-applications": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RuleApplication"
                ],
                "summary": "获取规则应用列表 | List rule applications",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "引擎ID | Engine ID",
                        "name": "engine_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Schema名称 | Schema name",
                        "name": "schema_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "表名 | Table name",
                        "name": "table_name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RuleApplication"
                ],
                "summary": "创建规则应用 | Create rule application",
                "parameters": [
                    {
                        "description": "规则应用信息 | Rule application info",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/rule-applications/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RuleApplication"
                ],
                "summary": "获取规则应用详情 | Get rule application detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "规则应用ID | Rule application ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RuleApplication"
                ],
                "summary": "更新规则应用 | Update rule application",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "规则应用ID | Rule application ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新信息 | Update info",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RuleApplication"
                ],
                "summary": "删除规则应用 | Delete rule application",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "规则应用ID | Rule application ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tasks": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "按标准 TaskProvider 协议列出 Quality 检查任务；task_type 仅支持 check。| List Quality check tasks through the standard TaskProvider protocol; task_type only supports check.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CheckTask"
                ],
                "summary": "列出 TaskProvider 质量检查任务 | List TaskProvider quality check tasks",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务类型，固定为 check | Task type, fixed to check",
                        "name": "task_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "任务列表 | Task list",
                        "schema": {
                            "$ref": "#/definitions/internal_api.taskProviderTaskListResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误 | Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "任务已有活动 execution | Task already has an active execution",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误 | Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/tasks/{task_type}/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "按标准 TaskProvider 协议获取 Quality 检查任务详情；task_type 仅支持 check。| Get Quality check task detail through the standard TaskProvider protocol; task_type only supports check.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CheckTask"
                ],
                "summary": "获取 TaskProvider 质量检查任务详情 | Get TaskProvider quality check task detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务类型，固定为 check | Task type, fixed to check",
                        "name": "task_type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "检查任务ID | Check task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "任务详情 | Task detail",
                        "schema": {
                            "$ref": "#/definitions/internal_api.taskProviderTaskListItem"
                        }
                    },
                    "400": {
                        "description": "请求参数错误 | Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "任务不存在 | Task not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/tasks/{task_type}/{id}/execute": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "按标准 TaskProvider 协议执行 Quality 检查任务；task_type 仅支持 check，parameters 当前不支持覆盖。| Execute a Quality check task through the standard TaskProvider protocol; task_type only supports check and parameters overrides are not supported.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CheckTask"
                ],
                "summary": "执行 TaskProvider 质量检查任务 | Execute TaskProvider quality check task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务类型，固定为 check | Task type, fixed to check",
                        "name": "task_type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "检查任务ID | Check task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "TaskProvider 执行请求 | TaskProvider execution request",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_api.qualityTaskProviderExecuteRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "执行ID | Execution ID",
                        "schema": {
                            "$ref": "#/definitions/internal_api.qualityTaskProviderExecuteResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误 | Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误 | Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_api.qualityTaskProviderExecuteRequest": {
            "type": "object",
            "properties": {
                "parameters": {
                    "type": "object",
                    "additionalProperties": true
                },
                "parent_execution_id": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "trigger_type": {
                    "type": "string"
                }
            }
        },
        "internal_api.qualityTaskProviderExecuteResponse": {
            "type": "object",
            "properties": {
                "execution_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "pending"
                    ],
                    "example": "pending"
                }
            }
        },
        "internal_api.taskProviderTaskListItem": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "last_execution_id": {
                    "type": "string"
                },
                "last_execution_status": {
                    "type": "string"
                },
                "last_run_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "next_run_at": {
                    "type": "string"
                },
                "task_type": {
                    "type": "string"
                },
                "tenant_id": {
                    "type": "integer"
                }
            }
        },
        "internal_api.taskProviderTaskListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_api.taskProviderTaskListItem"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8182",
	BasePath:         "/api/v1/quality",
	Schemes:          []string{},
	Title:            "ADDP Quality API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
