package registry

// Format 是 ADDP 内稳定的文件/逻辑格式标识。
type Format string

const (
	FormatUnknown    Format = "unknown"
	FormatCSV        Format = "csv"
	FormatDOCX       Format = "docx"
	FormatExcel      Format = "excel"
	FormatGIF        Format = "gif"
	FormatAAC        Format = "aac"
	FormatAVI        Format = "avi"
	FormatAVIF       Format = "avif"
	FormatAudio      Format = "audio"
	FormatBMP        Format = "bmp"
	FormatFLAC       Format = "flac"
	FormatHEIC       Format = "heic"
	FormatImage      Format = "image"
	FormatJPEG       Format = "jpeg"
	FormatJSON       Format = "json"
	FormatMarkdown   Format = "markdown"
	FormatMKV        Format = "mkv"
	FormatMOV        Format = "mov"
	FormatMP3        Format = "mp3"
	FormatMP4        Format = "mp4"
	FormatORC        Format = "orc"
	FormatOGG        Format = "ogg"
	FormatParquet    Format = "parquet"
	FormatPDF        Format = "pdf"
	FormatPNG        Format = "png"
	FormatPPTX       Format = "pptx"
	FormatShapefile  Format = "shapefile"
	FormatSQLite     Format = "sqlite"
	FormatGeoPackage Format = "geopackage"
	FormatKML        Format = "kml"
	FormatKMZ        Format = "kmz"
	FormatText       Format = "text"
	FormatTIFF       Format = "tiff"
	FormatTSV        Format = "tsv"
	FormatSVG        Format = "svg"
	FormatVideo      Format = "video"
	FormatWAV        Format = "wav"
	FormatWebM       Format = "webm"
	FormatWebP       Format = "webp"
	FormatWPS        Format = "wps"
	FormatZIP        Format = "zip"
	FormatAvro       Format = "avro"
	FormatPostgres   Format = "postgres"
	FormatMySQL      Format = "mysql"
	FormatXML        Format = "xml"
)
