package ply

import (
	"bytes"
	"context"
	"encoding/binary"
	"io"
	"math"
	"testing"

	"github.com/addp/common/contentio"
	"github.com/addp/common/datatype"
	"github.com/addp/common/format"
)

func TestPLYDescriptor(t *testing.T) {
	descriptor := NewPlugin().Descriptor()
	if descriptor.Format != format.FormatPLY {
		t.Fatalf("Format = %q, want %q", descriptor.Format, format.FormatPLY)
	}
	if descriptor.DataType != datatype.Model3D {
		t.Fatalf("DataType = %q, want %q", descriptor.DataType, datatype.Model3D)
	}
	if !format.HasLayout(descriptor.Layouts, format.LayoutSingle) {
		t.Fatalf("Layouts = %#v, want single", descriptor.Layouts)
	}
}

func TestDescribeModel3DReadsAsciiMeshPLYHeader(t *testing.T) {
	content := []byte(`ply
format ascii 1.0
element vertex 8
property float x
property float y
property float z
element face 12
property list uchar int vertex_indices
end_header
`)
	result, err := NewPlugin().DescribeModel3D(context.Background(), bytes.NewReader(content), nil)
	if err != nil {
		t.Fatalf("DescribeModel3D() error = %v", err)
	}
	if result == nil || result.Model3D == nil {
		t.Fatalf("DescribeModel3D() = %#v, want model info", result)
	}
	if result.Model3D.ModelKind != datatype.Model3DKindMeshScene {
		t.Fatalf("ModelKind = %q, want mesh_scene", result.Model3D.ModelKind)
	}
	if result.Model3D.VertexCount == nil || *result.Model3D.VertexCount != 8 {
		t.Fatalf("VertexCount = %v, want 8", result.Model3D.VertexCount)
	}
	if result.FormatInfo["encoding"] != "ascii" || result.FormatInfo["face_count"] != int64(12) {
		t.Fatalf("format_info = %#v, want ascii face count", result.FormatInfo)
	}
	if result.FormatInfo["layout"] != "mesh" {
		t.Fatalf("layout = %#v, want mesh", result.FormatInfo["layout"])
	}
}

func TestDescribePointCloudReadsVertexOnlyPLYHeader(t *testing.T) {
	content := []byte(`ply
format ascii 1.0
element vertex 3
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
property float intensity
end_header
`)
	result, err := NewPlugin().DescribePointCloud(context.Background(), bytes.NewReader(content), nil)
	if err != nil {
		t.Fatalf("DescribePointCloud() error = %v", err)
	}
	if result == nil || result.PointCloud == nil {
		t.Fatalf("DescribePointCloud() = %#v, want point cloud info", result)
	}
	if result.PointCloud.PointCloudKind != datatype.PointCloudKindRawPointCloud {
		t.Fatalf("PointCloudKind = %q, want raw_point_cloud", result.PointCloud.PointCloudKind)
	}
	if result.PointCloud.PointCount == nil || *result.PointCloud.PointCount != 3 {
		t.Fatalf("PointCount = %v, want 3", result.PointCloud.PointCount)
	}
	if result.PointCloud.HasColor == nil || !*result.PointCloud.HasColor {
		t.Fatalf("HasColor = %v, want true", result.PointCloud.HasColor)
	}
	if result.PointCloud.HasIntensity == nil || !*result.PointCloud.HasIntensity {
		t.Fatalf("HasIntensity = %v, want true", result.PointCloud.HasIntensity)
	}
	if result.FormatInfo["layout"] != "point_cloud" {
		t.Fatalf("layout = %#v, want point_cloud", result.FormatInfo["layout"])
	}
}

func TestDescribeGaussianSplatReadsPLYHeader(t *testing.T) {
	var content bytes.Buffer
	content.WriteString(`ply
format binary_little_endian 1.0
comment Generated by P3BJet GaussianSplats
element vertex 2
property float x
property float y
property float z
property float f_dc_0
property float f_dc_1
property float f_dc_2
property float opacity
property float scale_0
property float scale_1
property float scale_2
property float rot_0
property float rot_1
property float rot_2
property float rot_3
end_header
`)
	writePLYGaussianVertex(&content, -2, 3, 100)
	writePLYGaussianVertex(&content, 5, -7, 120)
	result, err := NewPlugin().DescribeGaussianSplat(context.Background(), format.GaussianSplatDescribeInput{
		Reader: bytes.NewReader(content.Bytes()),
	}, nil)
	if err != nil {
		t.Fatalf("DescribeGaussianSplat() error = %v", err)
	}
	if result == nil || result.GaussianSplat == nil {
		t.Fatalf("DescribeGaussianSplat() = %#v, want Gaussian splat info", result)
	}
	if result.GaussianSplat.Representation != datatype.GaussianSplatRepresentation3DGS {
		t.Fatalf("Representation = %q, want 3d_gaussian_splatting", result.GaussianSplat.Representation)
	}
	if result.GaussianSplat.SplatCount == nil || *result.GaussianSplat.SplatCount != 2 {
		t.Fatalf("SplatCount = %v, want 2", result.GaussianSplat.SplatCount)
	}
	if result.GaussianSplat.HasScale == nil || !*result.GaussianSplat.HasScale {
		t.Fatalf("HasScale = %v, want true", result.GaussianSplat.HasScale)
	}
	assertPLYBounds(t, result.GaussianSplat.Bounds3D, -2, -7, 100, 5, 3, 120)
	if result.FormatInfo["encoding"] != "binary_little_endian" {
		t.Fatalf("format_info = %#v, want binary_little_endian", result.FormatInfo)
	}
	if result.FormatInfo["is_gaussian_splat"] != true {
		t.Fatalf("is_gaussian_splat = %#v, want true", result.FormatInfo["is_gaussian_splat"])
	}
	if result.FormatInfo["layout"] != "gaussian_splat" {
		t.Fatalf("layout = %#v, want gaussian_splat", result.FormatInfo["layout"])
	}
}

func TestDescribeGaussianSplatSkipsExactBoundsForLargeTraditionalPLY(t *testing.T) {
	content := []byte(`ply
format binary_little_endian 1.0
element vertex 100001
property float x
property float y
property float z
property float f_dc_0
property float f_dc_1
property float f_dc_2
property float opacity
property float scale_0
property float scale_1
property float scale_2
property float rot_0
property float rot_1
property float rot_2
property float rot_3
end_header
`)
	result, err := NewPlugin().DescribeGaussianSplat(context.Background(), format.GaussianSplatDescribeInput{
		Reader: bytes.NewReader(content),
	}, nil)
	if err != nil {
		t.Fatalf("DescribeGaussianSplat() error = %v", err)
	}
	if result == nil || result.GaussianSplat == nil {
		t.Fatalf("DescribeGaussianSplat() = %#v, want Gaussian splat info", result)
	}
	if result.GaussianSplat.SplatCount == nil || *result.GaussianSplat.SplatCount != 100001 {
		t.Fatalf("SplatCount = %v, want 100001", result.GaussianSplat.SplatCount)
	}
	if result.GaussianSplat.Bounds3D != nil {
		t.Fatalf("Bounds3D = %#v, want nil for large traditional PLY meta scan", result.GaussianSplat.Bounds3D)
	}
}

func TestDescribeGaussianSplatSamplesLargeBinaryPLYBounds(t *testing.T) {
	var content bytes.Buffer
	content.WriteString(`ply
format binary_little_endian 1.0
comment Generated by P3BJet GaussianSplats
element vertex 100001
property float x
property float y
property float z
property float f_dc_0
property float f_dc_1
property float f_dc_2
property float opacity
property float scale_0
property float scale_1
property float scale_2
property float rot_0
property float rot_1
property float rot_2
property float rot_3
end_header
`)
	writePLYGaussianVertex(&content, -2, 3, 100)
	for i := int64(1); i < maxExactPLYBoundsVertices; i++ {
		writePLYGaussianVertex(&content, 0, 0, 110)
	}
	writePLYGaussianVertex(&content, 5, -7, 120)
	reader := plyMemoryRangeReader{content: content.Bytes()}

	result, err := NewPlugin().DescribeGaussianSplat(context.Background(), format.GaussianSplatDescribeInput{
		Reader:      bytes.NewReader(content.Bytes()),
		RangeReader: reader,
		Ref:         contentio.NewRef("site.ply", contentio.RoleMain),
		SizeBytes:   int64(content.Len()),
	}, nil)
	if err != nil {
		t.Fatalf("DescribeGaussianSplat() error = %v", err)
	}
	if result == nil || result.GaussianSplat == nil {
		t.Fatalf("DescribeGaussianSplat() = %#v, want Gaussian splat info", result)
	}
	assertPLYBounds(t, result.GaussianSplat.SampledBounds3D, -2, -7, 100, 5, 3, 120)
	if result.GaussianSplat.Bounds3D != nil {
		t.Fatalf("Bounds3D = %#v, want nil for sampled large PLY", result.GaussianSplat.Bounds3D)
	}
	if result.GaussianSplat.SampledBoundsMethod != "sampled_binary_vertices" {
		t.Fatalf("SampledBoundsMethod = %q, want sampled_binary_vertices", result.GaussianSplat.SampledBoundsMethod)
	}
	if result.GaussianSplat.SampledBoundsSampleCount == nil || *result.GaussianSplat.SampledBoundsSampleCount != plySampledBoundsSampleCount {
		t.Fatalf("SampledBoundsSampleCount = %v, want %d", result.GaussianSplat.SampledBoundsSampleCount, plySampledBoundsSampleCount)
	}
}

func TestDescribeGaussianSplatReadsCompressedPLYHeader(t *testing.T) {
	var content bytes.Buffer
	content.WriteString(`ply
format binary_little_endian 1.0
comment Generated by SuperSplat 2.6.2
element chunk 2
property float min_x
property float min_y
property float min_z
property float max_x
property float max_y
property float max_z
element vertex 8
property uint packed_position
property uint packed_rotation
property uint packed_scale
property uint packed_color
element sh 666816
property uchar f_rest_0
property uchar f_rest_1
property uchar f_rest_2
property uchar f_rest_3
property uchar f_rest_4
property uchar f_rest_5
property uchar f_rest_6
property uchar f_rest_7
property uchar f_rest_8
property uchar f_rest_9
property uchar f_rest_10
property uchar f_rest_11
property uchar f_rest_12
property uchar f_rest_13
property uchar f_rest_14
property uchar f_rest_15
property uchar f_rest_16
property uchar f_rest_17
property uchar f_rest_18
property uchar f_rest_19
property uchar f_rest_20
property uchar f_rest_21
property uchar f_rest_22
property uchar f_rest_23
property uchar f_rest_24
property uchar f_rest_25
property uchar f_rest_26
property uchar f_rest_27
property uchar f_rest_28
property uchar f_rest_29
property uchar f_rest_30
property uchar f_rest_31
property uchar f_rest_32
property uchar f_rest_33
property uchar f_rest_34
property uchar f_rest_35
property uchar f_rest_36
property uchar f_rest_37
property uchar f_rest_38
property uchar f_rest_39
property uchar f_rest_40
property uchar f_rest_41
property uchar f_rest_42
property uchar f_rest_43
property uchar f_rest_44
end_header
`)
	writeCompressedPLYChunk(&content, -10, -20, -30, 1, 2, 3)
	writeCompressedPLYChunk(&content, -5, -25, -1, 10, 12, 30)
	result, err := NewPlugin().DescribeGaussianSplat(context.Background(), format.GaussianSplatDescribeInput{
		Reader: bytes.NewReader(content.Bytes()),
	}, nil)
	if err != nil {
		t.Fatalf("DescribeGaussianSplat() error = %v", err)
	}
	if result == nil || result.GaussianSplat == nil {
		t.Fatalf("DescribeGaussianSplat() = %#v, want compressed Gaussian splat info", result)
	}
	if result.GaussianSplat.SplatCount == nil || *result.GaussianSplat.SplatCount != 8 {
		t.Fatalf("SplatCount = %v, want 8", result.GaussianSplat.SplatCount)
	}
	if result.GaussianSplat.SHDegree == nil || *result.GaussianSplat.SHDegree != 3 {
		t.Fatalf("SHDegree = %v, want 3", result.GaussianSplat.SHDegree)
	}
	if result.GaussianSplat.HasScale == nil || !*result.GaussianSplat.HasScale {
		t.Fatalf("HasScale = %v, want true", result.GaussianSplat.HasScale)
	}
	assertPLYBounds(t, result.GaussianSplat.Bounds3D, -10, -25, -30, 10, 12, 30)
	if result.FormatInfo["is_compressed_splat"] != true {
		t.Fatalf("is_compressed_splat = %#v, want true", result.FormatInfo["is_compressed_splat"])
	}
	if result.FormatInfo["layout"] != "gaussian_splat" {
		t.Fatalf("layout = %#v, want gaussian_splat", result.FormatInfo["layout"])
	}
}

func TestSniffFormatRecognizesPLY(t *testing.T) {
	if !NewPlugin().SniffFormat([]byte("ply\nformat ascii 1.0\n")) {
		t.Fatal("SniffFormat(PLY) = false, want true")
	}
}

type plyMemoryRangeReader struct {
	content []byte
}

func (r plyMemoryRangeReader) Open(context.Context, contentio.Ref) (io.ReadCloser, error) {
	return io.NopCloser(bytes.NewReader(r.content)), nil
}

func (r plyMemoryRangeReader) Stat(_ context.Context, ref contentio.Ref) (*contentio.Stat, error) {
	return &contentio.Stat{Ref: ref, Size: int64(len(r.content)), Exists: true}, nil
}

func (r plyMemoryRangeReader) OpenRange(_ context.Context, _ contentio.Ref, offset, length int64) (io.ReadCloser, error) {
	if offset < 0 {
		offset = 0
	}
	if length < 0 {
		length = 0
	}
	start := minInt64(offset, int64(len(r.content)))
	end := minInt64(start+length, int64(len(r.content)))
	return io.NopCloser(bytes.NewReader(r.content[start:end])), nil
}

func minInt64(a, b int64) int64 {
	if a < b {
		return a
	}
	return b
}

func writePLYGaussianVertex(buffer *bytes.Buffer, x, y, z float32) {
	values := []float32{
		x, y, z,
		0, 0, 0,
		1,
		1, 1, 1,
		1, 0, 0, 0,
	}
	for _, value := range values {
		binary.Write(buffer, binary.LittleEndian, value)
	}
}

func writeCompressedPLYChunk(buffer *bytes.Buffer, minX, minY, minZ, maxX, maxY, maxZ float32) {
	for _, value := range []float32{minX, minY, minZ, maxX, maxY, maxZ} {
		binary.Write(buffer, binary.LittleEndian, value)
	}
}

func assertPLYBounds(t *testing.T, bounds *datatype.Bounds3D, minX, minY, minZ, maxX, maxY, maxZ float64) {
	t.Helper()
	if bounds == nil || bounds.MinX == nil || bounds.MinY == nil || bounds.MinZ == nil ||
		bounds.MaxX == nil || bounds.MaxY == nil || bounds.MaxZ == nil {
		t.Fatalf("Bounds3D = %#v, want complete bounds", bounds)
	}
	got := []float64{*bounds.MinX, *bounds.MinY, *bounds.MinZ, *bounds.MaxX, *bounds.MaxY, *bounds.MaxZ}
	want := []float64{minX, minY, minZ, maxX, maxY, maxZ}
	for i := range got {
		if math.Abs(got[i]-want[i]) > 0.000001 {
			t.Fatalf("Bounds3D = %#v, want [%v %v %v]-[%v %v %v]", bounds, minX, minY, minZ, maxX, maxY, maxZ)
		}
	}
}
