// Code generated by common/authorization/cmd/manifest; DO NOT EDIT.
// Source: quality/authorization/permissions.yaml (manifest_version=3).

package authorization

const (
	PermissionQualityCatalogRead               = "quality.catalog.read"
	PermissionQualityCheckTaskCreate           = "quality.check_task.create"
	PermissionQualityCheckTaskDelete           = "quality.check_task.delete"
	PermissionQualityCheckTaskExecute          = "quality.check_task.execute"
	PermissionQualityCheckTaskRead             = "quality.check_task.read"
	PermissionQualityCheckTaskUpdate           = "quality.check_task.update"
	PermissionQualityIssueRead                 = "quality.issue.read"
	PermissionQualityIssueUpdate               = "quality.issue.update"
	PermissionQualityMaterializationGateCreate = "quality.materialization_gate.create"
	PermissionQualityMaterializationGateDelete = "quality.materialization_gate.delete"
	PermissionQualityMaterializationGateRead   = "quality.materialization_gate.read"
	PermissionQualityMaterializationGateUpdate = "quality.materialization_gate.update"
	PermissionQualityRuleApplicationCreate     = "quality.rule_application.create"
	PermissionQualityRuleApplicationDelete     = "quality.rule_application.delete"
	PermissionQualityRuleApplicationRead       = "quality.rule_application.read"
	PermissionQualityRuleApplicationUpdate     = "quality.rule_application.update"
	PermissionQualityTaskProviderExecute       = "quality.task_provider.execute"
	PermissionQualityTaskProviderRead          = "quality.task_provider.read"
)

var permissionKeys = [...]string{
	"quality.catalog.read",
	"quality.check_task.create",
	"quality.check_task.delete",
	"quality.check_task.execute",
	"quality.check_task.read",
	"quality.check_task.update",
	"quality.issue.read",
	"quality.issue.update",
	"quality.materialization_gate.create",
	"quality.materialization_gate.delete",
	"quality.materialization_gate.read",
	"quality.materialization_gate.update",
	"quality.rule_application.create",
	"quality.rule_application.delete",
	"quality.rule_application.read",
	"quality.rule_application.update",
	"quality.task_provider.execute",
	"quality.task_provider.read",
}

// PermissionKeys returns the active owner-local Permission keys in stable order.
func PermissionKeys() []string {
	return append([]string(nil), permissionKeys[:]...)
}
