import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'

const readSource = relativePath => readFileSync(new URL(relativePath, import.meta.url), 'utf8')

describe('Security product information architecture', () => {
  it('separates low-change classification foundations from sensitive data definitions', () => {
    const router = readSource('../src/router/index.js')
    const layout = readSource('../src/components/Layout.vue')
    const classificationGrading = readSource('../src/views/ClassificationGrading.vue')
    const foundations = readSource('../src/views/FoundationList.vue')
    const definitions = readSource('../src/views/SensitiveDataDefinitions.vue')
    const sensitiveTypes = readSource('../src/views/SensitiveDataTypeList.vue')
    const detectors = readSource('../src/views/DetectorBindings.vue')
    const baselines = readSource('../src/views/ProtectionBaselineBindings.vue')

    expect(router).toContain("path: 'classification-grading'")
    expect(router).toContain("path: 'sensitive-data-definitions'")
    expect(router).toContain("component: () => import('../views/Login.vue')")
    expect(router).toContain("component: () => import('../views/ClassificationGrading.vue')")
    expect(router).toContain("component: () => import('../views/SensitiveDataDefinitions.vue')")
    expect(router).toContain("component: () => import('../views/ProtectionEnrollmentList.vue')")
    expect(router).not.toContain("import Login from '../views/Login.vue'")
    expect(router).not.toContain("import ClassificationGrading from '../views/ClassificationGrading.vue'")
    expect(router).not.toContain("import SensitiveDataDefinitions from '../views/SensitiveDataDefinitions.vue'")
    expect(router).not.toContain("import ProtectionEnrollmentList from '../views/ProtectionEnrollmentList.vue'")
    expect(router).not.toContain("path: 'protection-baselines'")
    expect(router).toContain("redirect: '/sensitive-data-definitions'")
    expect(router).not.toContain("['classifications', 'classification']")
    expect(router).not.toContain("['grades', 'grade']")
    expect(router).not.toContain("['sensitive-data-types', 'sensitiveDataType']")
    expect(layout).toContain('index="/classification-grading"')
    expect(layout).toContain('index="/sensitive-data-definitions"')
    expect(layout).not.toContain('index="/protection-baselines"')
    expect(layout).not.toContain('index="/classifications"')
    expect(layout).not.toContain('index="/grades"')
    expect(layout).not.toContain('index="/sensitive-data-types"')
    expect(classificationGrading).toContain('resolveCanonicalTabRouteState')
    expect(classificationGrading).toContain("defaultTab: 'classifications'")
    expect(classificationGrading).toContain("path: '/classification-grading'")
    expect(classificationGrading).toContain('<FoundationList')
    expect(foundations).toContain('<el-form ref="formRef" :model="form" :rules="formRules"')
    expect(foundations).toContain(':prop="field.key"')
    expect(foundations).toContain(':required="field.required"')
    expect(foundations).toContain('createRequiredRule')
    expect(foundations).toContain('createRequiredNumberRangeRule')
    expect(foundations).toContain('@open="clearDialogValidation"')
    expect(foundations).toContain('@opened="focusDialogPrimaryControl"')
    expect(foundations).toContain('await formRef.value?.validate().catch(() => false)')
    expect(foundations).not.toContain("ElMessage.warning(t('security.common.requiredField'")
    expect(definitions).toContain('<SensitiveDataTypeList />')
    expect(definitions).not.toContain('FoundationList')
    expect(definitions).not.toContain('resolveCanonicalTabRouteState')
    expect(sensitiveTypes).toContain('<DetectorBindings')
    expect(sensitiveTypes).toContain('<ProtectionBaselineBindings')
    expect(sensitiveTypes).toContain('payload.default_protection')
    expect(sensitiveTypes).toContain('<el-form-item :label="t(\'security.fields.keep_prefix\')" prop="default_keep_prefix" required>')
    expect(sensitiveTypes).toContain('<el-form-item :label="t(\'security.fields.keep_suffix\')" prop="default_keep_suffix" required>')
    expect(sensitiveTypes).toContain('<el-form ref="formRef" :model="form" :rules="formRules"')
    expect(sensitiveTypes).toContain('prop="code" required')
    expect(sensitiveTypes).toContain('prop="name" required')
    expect(sensitiveTypes).toContain('prop="security_classification_id" required')
    expect(sensitiveTypes).toContain('prop="default_security_grade_id" required')
    expect(sensitiveTypes).toContain('prop="default_effect" required')
    expect(sensitiveTypes).toContain('prop="default_keep_prefix"')
    expect(sensitiveTypes).toContain('prop="default_invalid_value_effect" required')
    expect(sensitiveTypes).toContain('createRequiredRule')
    expect(sensitiveTypes).toContain('createNonNegativeIntegerRule')
    expect(sensitiveTypes).toContain('await formRef.value?.validate().catch(() => false)')
    expect(sensitiveTypes).not.toContain("ElMessage.warning(t('security.sensitiveType.required'))")
    expect(sensitiveTypes).toContain(':sensitive-type-id="Number(selectedType.id)"')
    expect(sensitiveTypes).toContain('detectorDrawerRevision.value += 1')
    expect(detectors).toContain('detectorCapabilityAPI.list()')
    expect(detectors).toContain('discoveryQualityAPI.get({ sensitive_data_type_id: props.sensitiveTypeId })')
    expect(detectors).toContain('quality.sensitive_confirmation_rate')
    expect(detectors).toContain('security.discoveryQuality.manualSignalsDescription')
    expect(detectors).toContain('security.detector.${action}')
    expect(detectors).toContain('confidence_threshold: form.confidence_percent / 100')
    expect(detectors).toContain('security.detector.parallelHint')
    expect(detectors).toContain('componentProps.capability.method_i18n_key')
    expect(detectors).toContain('componentProps.capability.privacy_i18n_key')
    expect(detectors).toContain('componentProps.capability.limitations_i18n_key')
    expect(detectors).toContain('<el-form ref="formRef" :model="form" :rules="formRules"')
    expect(detectors).toContain('prop="capability_key" required')
    expect(detectors).toContain('prop="confidence_percent" required')
    expect(detectors).toContain('createRequiredRule')
    expect(detectors).toContain('createRequiredNumberRangeRule')
    expect(detectors).not.toContain("Number.isFinite(value) && value >= 1 && value <= 100")
    expect(detectors).toContain('@open="clearDialogValidation"')
    expect(detectors).toContain('@opened="focusDialogPrimaryControl"')
    expect(detectors).toContain('await formRef.value?.validate().catch(() => false)')
    expect(detectors).not.toContain("ElMessage.warning(t('security.detector.required'))")
    expect(baselines).toContain('security.baseline.mappingHint')
    expect(baselines).toContain('isInitialBaseline(row)')
    expect(baselines).toContain('security.baseline.effectImpactTitle')
    expect(baselines).toContain('security.baseline.effectImpact.${form.effect}')
    expect(baselines).toContain("algorithm: mask ? 'addp.mask.keep_prefix_suffix/v2' : ''")
    expect(baselines).toContain('<el-form-item :label="t(\'security.fields.keep_prefix\')" prop="keep_prefix" required>')
    expect(baselines).toContain('<el-form-item :label="t(\'security.fields.keep_suffix\')" prop="keep_suffix" required>')
    expect(baselines).toContain('<el-form ref="formRef" :model="form" :rules="formRules"')
    expect(baselines).toContain('prop="security_grade_id" required')
    expect(baselines).toContain('prop="effect" required')
    expect(baselines).toContain('prop="keep_prefix"')
    expect(baselines).toContain('prop="invalid_value_effect" required')
    expect(baselines).toContain('createRequiredRule')
    expect(baselines).toContain('createNonNegativeIntegerRule')
    expect(baselines).toContain('await formRef.value?.validate().catch(() => false)')
    expect(baselines).not.toContain("ElMessage.warning(t('security.baseline.required'))")
    expect(baselines).not.toContain('keep_prefix_suffix/v1')
    expect(baselines).not.toContain('form.keep_prefix + form.keep_suffix >= 11')
    expect(baselines).not.toContain(':max="10"')
  })

  it('uses user-facing names and relation selectors instead of numeric IDs', () => {
    const zhCn = JSON.parse(readSource('../src/i18n/zh-cn.json'))
    const en = JSON.parse(readSource('../src/i18n/en.json'))
    const sensitiveTypes = readSource('../src/views/SensitiveDataTypeList.vue')

    expect(zhCn.security.resources.classificationGrading).toBe('分类分级体系')
    expect(zhCn.security.resources.sensitiveDataDefinition).toBe('敏感数据定义')
    expect(zhCn.security.resources.protectionEnrollment).toBe('受保护资源')
    expect(zhCn.security.fields.security_classification_id).toBe('所属分类')
    expect(zhCn.security.fields.default_security_grade_id).toBe('自动发现初始等级')
    expect(zhCn.security.fields.invalid_value_effect).toBe('不符合格式时')
    expect(zhCn.security.baseline.effectImpact.mask).toContain('保留字段结构')
    expect(zhCn.security.baseline.effectImpact.suppress).toContain('删除该字段及其值')
    expect(zhCn.security.baseline.effectImpact.deny).toContain('拒绝整个数据请求')
    expect(zhCn.security.options.effects.suppress).toBe('移除字段')
    expect(zhCn.security.enrollment.effects.suppress).toBe('移除')
    expect(zhCn.security.sensitiveType.required).toBeUndefined()
    expect(zhCn.security.baseline.required).toBeUndefined()
    expect(JSON.stringify(zhCn)).not.toContain('抑制字段')
    expect(en.security.options.effects.suppress).toBe('Remove field')
    expect(en.security.enrollment.effects.suppress).toBe('Remove')
    expect(en.security.sensitiveType.required).toBeUndefined()
    expect(en.security.baseline.required).toBeUndefined()
    expect(zhCn.security.detector.required).toBeUndefined()
    expect(zhCn.security.detector.confidenceThresholdRange).toContain('1% 到 100%')
    expect(en.security.detector.required).toBeUndefined()
    expect(en.security.detector.confidenceThresholdRange).toContain('1% to 100%')
    expect(sensitiveTypes).toContain('form.security_classification_id')
    expect(sensitiveTypes).toContain('form.default_security_grade_id')
    expect(sensitiveTypes).not.toContain('protection_threshold')
    expect(zhCn.security.detectorCapabilities.phoneMetadata.method).toContain('末级名称')
    expect(zhCn.security.detectorCapabilities.phoneMetadata.limitations).toContain('不能验证字段中的值')
    expect(zhCn.security.detectorCapabilities.emailMetadata.method).toContain('emailaddress')
    expect(zhCn.security.detectorCapabilities.emailMetadata.limitations).toContain('email_verified')
    expect(zhCn.security.detectorCapabilities.identityDocumentNumberMetadata.name).toContain('身份证件号码')
    expect(zhCn.security.detectorCapabilities.identityDocumentNumberMetadata.method).toContain('identitydocumentnumber')
    expect(zhCn.security.detectorCapabilities.identityDocumentNumberMetadata.privacy).toContain('不读取、保存或记录证件号码')
    expect(zhCn.security.detectorCapabilities.identityDocumentNumberMetadata.limitations).toContain('user_id')
    expect(zhCn.security.detectorCapabilities.phoneDocument.privacy).toContain('不保存或记录原始号码')
    expect(zhCn.security.discoveryQuality.insufficientSamples).toBe('样本不足')
    expect(zhCn.security.discoveryQuality.manualSignalsDescription).toContain('不能直接归因')
  })

  it('uses one safe confirmation contract for every destructive definition deletion', () => {
    const confirmation = readSource('../src/utils/confirmation.mjs')
    const deletionSurfaces = [
      readSource('../src/views/FoundationList.vue'),
      readSource('../src/views/SensitiveDataTypeList.vue'),
      readSource('../src/views/DetectorBindings.vue'),
      readSource('../src/views/ProtectionBaselineBindings.vue')
    ]

    expect(confirmation).toContain("customClass: 'addp-message-box'")
    expect(confirmation).toContain("confirmButtonClass: 'el-button--danger'")
    expect(confirmation).toContain('autofocus: false')
    expect(confirmation).toContain("querySelectorAll('.el-message-box__btns button')")
    expect(confirmation).toContain("!button.classList.contains('el-button--danger')")

    for (const surface of deletionSurfaces) {
      expect(surface).toContain('confirmDangerousAction(ElMessageBox.confirm')
      expect(surface).toContain("confirmButtonText: t('security.common.delete')")
      expect(surface).toContain("cancelButtonText: t('security.common.cancel')")
    }
  })

  it('re-enrolls released resources through a new enrollment lifecycle', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')
    const enrollmentReEnrollment = readSource('../src/composables/useProtectionEnrollmentReEnrollment.mjs')
    const resourceList = readSource('../src/components/protection-enrollment/EnrollmentResourceList.vue')
    const lifecycleDialog = readSource('../src/components/protection-enrollment/EnrollmentLifecycleActionDialog.vue')
    const api = readSource('../src/api/security.js')
    const zhCn = JSON.parse(readSource('../src/i18n/zh-cn.json'))

    expect(api).toContain('/re-enrollments`')
    expect(enrollment).toContain('<EnrollmentResourceList')
    expect(enrollment).toContain('@re-enroll="openReEnrollment"')
    expect(enrollment).not.toContain('class="list-scope-bar"')
    expect(resourceList).toContain("row.state === 'released'")
    expect(resourceList).toContain("emit('reEnroll', row)")
    expect(resourceList).toContain('class="list-scope-bar"')
    expect(enrollment).toContain('useProtectionEnrollmentReEnrollment({')
    expect(enrollment).not.toContain('async function reloadReEnrollmentBaseline(')
    expect(enrollment).not.toContain('async function submitReEnrollment(')
    expect(enrollment).toContain('reloadReEnrollmentBaseline')
    expect(enrollment).toContain(':conflict="reEnrollmentConflict"')
    expect(enrollment).toContain('ref="reEnrollmentDialogRef"')
    expect(enrollment).toContain('mode="re-enroll"')
    expect(enrollment).not.toContain('ref="reEnrollmentCancelButton"')
    expect(lifecycleDialog).toContain(':disabled="conflict"')
    expect(lifecycleDialog).toContain('defineExpose({ focusPrimary })')
    expect(enrollment).toContain('getEnrollment: id => protectionEnrollmentAPI.get(id)')
    expect(enrollment).toContain('createReEnrollment: (id, payload) => protectionEnrollmentAPI.reEnroll(id, payload)')
    expect(enrollmentReEnrollment).toContain('isResourceVersionConflict(error)')
    expect(enrollmentReEnrollment).toContain('isProtectionEnrollmentAlreadyActive(error)')
    expect(enrollmentReEnrollment).toContain('const sourceVersion = Number(result?.source_enrollment_version)')
    expect(enrollment).toContain("listScope.value = 'current'")
    expect(zhCn.security.enrollment.reEnroll).toBe('重新纳入')
    expect(zhCn.security.enrollment.reEnrollWarning).toContain('新的保护记录')
    expect(zhCn.security.enrollment.reEnrollWarning).toContain('原退出记录')
    expect(zhCn.security.enrollment.reEnrollmentVersionConflict).toContain('重新纳入意图已保留')
    expect(zhCn.security.enrollment.enrollmentAlreadyActive).toContain('已切换到当前受保护资源')
  })

  it('keeps protected-resource collection refresh lifecycle in one composable', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')
    const collection = readSource('../src/composables/useProtectionEnrollmentCollection.mjs')
    const workspace = readSource('../src/composables/useProtectionEnrollmentWorkspace.mjs')

    expect(enrollment).toContain("useProtectionEnrollmentCollection({")
    expect(enrollment).toContain('onRowsLoaded: context => syncDetailEnrollmentRows(context)')
    expect(workspace).toContain('resources.startVisibilityTracking()')
    expect(enrollment).toContain('disposeEnrollmentCollection()')
    expect(enrollment).not.toContain('AUTO_REFRESH_FAST_INTERVAL_MS')
    expect(enrollment).not.toContain("document.addEventListener('visibilitychange'")
    expect(collection).toContain('const AUTO_REFRESH_FAST_INTERVAL_MS = 2000')
    expect(collection).toContain('const AUTO_REFRESH_TIMEOUT_MS = 120000')
    expect(collection).toContain('rows.value.some(needsEnrollmentRefresh)')
    expect(collection).toContain("await load({ background: true, silent: true, syncFindings: true })")
  })

  it('keeps protected-resource creation in one guarded session composable', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')
    const creation = readSource('../src/composables/useProtectionEnrollmentCreation.mjs')
    const createDrawer = readSource('../src/components/protection-enrollment/EnrollmentCreateDrawer.vue')

    expect(enrollment).toContain('useProtectionEnrollmentCreation({')
    expect(enrollment).toContain('createEnrollment: payload => protectionEnrollmentAPI.create(payload)')
    expect(enrollment).toContain("defineAsyncComponent(() => import('../components/protection-enrollment/EnrollmentCreateDrawer.vue'))")
    expect(enrollment).toContain('<EnrollmentCreateDrawer')
    expect(enrollment).toContain(':before-close="beforeCreateClose"')
    expect(createDrawer).toContain(':before-close="beforeClose"')
    expect(createDrawer).toContain('import { ResourceTreePicker } from \'@common-ui\'')
    expect(createDrawer).toContain('<ResourceTreePicker')
    expect(enrollment).not.toContain('let selectedItemRequest = 0')
    expect(enrollment).not.toContain('async function handleResourceSelect(')
    expect(enrollment).not.toContain('async function createEnrollment(')
    expect(enrollment).not.toContain('async function handleCreateClosed(')
    expect(creation).toContain('let itemRequest = 0')
    expect(creation).toContain('let submitRequest = 0')
    expect(creation).toContain('if (disposed || saving.value || selectedItemLoading.value)')
    expect(creation).toContain('await Promise.resolve(validation).catch(() => false)')
    expect(creation).toContain('scheduleAutoRefresh({ reset: true })')
  })

  it('keeps protected-resource governance read models in one composable', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')
    const governance = readSource('../src/composables/useProtectionEnrollmentGovernance.mjs')

    expect(enrollment).toContain('useProtectionEnrollmentGovernance({')
    expect(enrollment).toContain('loadGovernance: loadGovernanceData')
    expect(enrollment).toContain('reset: resetGovernance')
    expect(enrollment).not.toContain('async function loadFindings(')
    expect(enrollment).not.toContain('let findingsRequest = 0')
    expect(governance).toContain("const GOVERNANCE_KINDS = ['findings', 'assessments', 'policies', 'exemptions']")
    expect(governance).toContain('source_snapshot_hash: sourceSnapshotHash')
    expect(governance).toContain('requestVersions[kind]')
    expect(governance).toContain('async function loadGovernance(')
  })

  it('keeps protected-resource detail entry and synchronization in one session composable', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')
    const detail = readSource('../src/composables/useProtectionEnrollmentDetail.mjs')
    const detailDrawer = readSource('../src/components/protection-enrollment/EnrollmentDetailDrawer.vue')

    expect(enrollment).toContain('useProtectionEnrollmentDetail({')
    expect(enrollment).toContain("defineAsyncComponent(() => import('../components/protection-enrollment/EnrollmentDetailDrawer.vue'))")
    expect(enrollment).toContain('<EnrollmentDetailDrawer')
    expect(enrollment).toContain('ref="detailDrawerRef"')
    expect(enrollment).toContain('openAuthorization: openAccessRequestAuthorization')
    expect(enrollment).toContain('openFinding: openReviewQueueResource')
    expect(enrollment).toContain('@close="closeDetail"')
    expect(enrollment).not.toContain('async function openAccessRequestAuthorization(')
    expect(enrollment).not.toContain('async function openReviewQueueResource(')
    expect(enrollment).not.toContain('async function openDetail(')
    expect(enrollment).not.toContain('async function syncLoadedEnrollmentRows(')
    expect(detail).toContain('let sessionRequest = 0')
    expect(detail).toContain('async function openAuthorization(')
    expect(detail).toContain('async function openFinding(')
    expect(detail).toContain('async function syncLoadedRows(')
    expect(detail).toContain('discoveryRefreshMarker(latest) !== previousMarker')
    expect(detail).toContain("review_state: 'pending'")
    expect(detail).toContain('drawerRef.value?.focusExemption?.()')
    expect(detailDrawer).toContain('defineExpose({ focusExemption })')
  })

  it('keeps protected-resource reference data in one deduplicated catalog', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')
    const catalog = readSource('../src/composables/useProtectionReferenceCatalog.mjs')

    expect(enrollment).toContain('useProtectionReferenceCatalog({')
    expect(enrollment).toContain('loadDefinitions: loadFindingDefinitions')
    expect(enrollment).toContain("listEngines: () => listResourceTreeEngines('/api/v1/meta')")
    expect(enrollment).toContain('setProtectionBaselines(context.baselines)')
    expect(enrollment).toContain('disposeProtectionReferenceCatalog()')
    expect(enrollment).not.toContain('async function loadFindingDefinitions()')
    expect(enrollment).not.toContain('async function loadDetectorCapabilities()')
    expect(enrollment).not.toContain('async function loadEngines()')
    expect(catalog).toContain('let definitionsPromise = null')
    expect(catalog).toContain('let detectorCapabilitiesPromise = null')
    expect(catalog).toContain('let enginesPromise = null')
    expect(catalog).toContain('let definitionsLoaded = false')
    expect(catalog).toContain('requestedBaselineRevision === baselineRevision')
  })

  it('keeps protected-resource route transitions and initialization in one lifecycle composable', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')
    const workspace = readSource('../src/composables/useProtectionEnrollmentWorkspace.mjs')

    expect(enrollment).toContain('useProtectionEnrollmentWorkspace({')
    expect(enrollment).toContain('handleRouteChange: handleWorkspaceRouteChange')
    expect(enrollment).toContain('await handleWorkspaceRouteChange(routeQuery)')
    expect(enrollment).toContain('await mountWorkspace()')
    expect(enrollment).toContain('disposeProtectionEnrollmentWorkspace()')
    expect(enrollment).not.toContain('let workspaceMounted = false')
    expect(enrollment).not.toContain('async function navigateWorkspace(')
    expect(enrollment).not.toContain('async function loadRoutedReviewQueue(')
    expect(enrollment).not.toContain('async function manualRefresh(')
    expect(workspace).toContain('let transitionRevision = 0')
    expect(workspace).toContain("isCurrent(request, 'review-queue')")
    expect(workspace).toContain("isCurrent(request, 'resources')")
    expect(workspace).toContain('resolveProtectionEnrollmentWorkspaceRouteState')
  })

  it('keeps protected-resource labels and policy presentation in one reactive model', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')
    const presentation = readSource('../src/composables/useProtectionEnrollmentPresentation.mjs')

    expect(enrollment).toContain('useProtectionEnrollmentPresentation({')
    expect(enrollment).toContain('assessmentProtectionSummary,')
    expect(enrollment).toContain('activeGradesForType')
    expect(enrollment).not.toContain('function resourceName(')
    expect(enrollment).not.toContain('function discoveryPresentation(')
    expect(enrollment).not.toContain('function evidenceAuditDescription(')
    expect(enrollment).not.toContain('function assessmentProtectionSummary(')
    expect(enrollment).not.toContain('function activeGradesForType(')
    expect(presentation).toContain('const manualAssessments = computed(')
    expect(presentation).toContain('function presentationState(')
    expect(presentation).toContain('function outletRuleDescription(')
    expect(presentation).toContain('function canConfigurePolicy(')
  })

  it('validates every required protected-resource action field inline', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')
    const enrollmentRelease = readSource('../src/composables/useProtectionEnrollmentRelease.mjs')
    const enrollmentCreation = readSource('../src/composables/useProtectionEnrollmentCreation.mjs')
    const accessRequestReview = readSource('../src/composables/useProtectionAccessRequestReview.mjs')
    const findingReview = readSource('../src/composables/useProtectionFindingReview.mjs')
    const assessmentChange = readSource('../src/composables/useProtectionAssessmentChange.mjs')
    const assessmentWorkspace = readSource('../src/composables/useProtectionAssessmentWorkspace.mjs')
    const exemptionRevocation = readSource('../src/composables/useProtectionExemptionRevocation.mjs')
    const enrollmentCreateDrawer = readSource('../src/components/protection-enrollment/EnrollmentCreateDrawer.vue')
    const accessRequestDecisionDialog = readSource('../src/components/protection-enrollment/AccessRequestDecisionDialog.vue')
    const accessRequestDecisionForm = readSource('../src/components/protection-enrollment/AccessRequestDecisionForm.vue')
    const findingReviewDialog = readSource('../src/components/protection-enrollment/FindingReviewDialog.vue')
    const findingReviewForm = readSource('../src/components/protection-enrollment/FindingReviewForm.vue')
    const protectionPolicyForm = readSource('../src/components/protection-enrollment/ProtectionPolicyForm.vue')
    const protectionPolicyDialog = readSource('../src/components/protection-enrollment/ProtectionPolicyDialog.vue')
    const assessmentChangeDialog = readSource('../src/components/protection-enrollment/AssessmentChangeDialog.vue')
    const exemptionRevokeDialog = readSource('../src/components/protection-enrollment/ExemptionRevokeDialog.vue')
    const enrollmentReleaseDialog = readSource('../src/components/protection-enrollment/EnrollmentReleaseDialog.vue')
    const manualAssessmentDialog = readSource('../src/components/protection-enrollment/ManualAssessmentDialog.vue')
    const formSurfaces = [enrollment, enrollmentCreateDrawer, accessRequestDecisionForm, findingReviewForm, protectionPolicyForm, assessmentChangeDialog, exemptionRevokeDialog, enrollmentReleaseDialog, manualAssessmentDialog].join('\n')
    const localeMessages = [
      JSON.parse(readSource('../src/i18n/zh-cn.json')),
      JSON.parse(readSource('../src/i18n/en.json'))
    ]

    expect(enrollment).toContain('ref="accessRequestDecisionDialogRef"')
    expect(enrollment).toContain(':rules="accessRequestDecisionRules"')
    expect(accessRequestReview).toContain('Promise.resolve(validation).catch(() => false)')
    expect(enrollment).toContain('ref="manualAssessmentDialogRef"')
    expect(enrollment).toContain(':rules="manualAssessmentRules"')
    expect(assessmentWorkspace).toContain('Promise.resolve(validation).catch(() => false)')
    for (const formName of ['assessmentRevision', 'assessmentRevoke']) {
      expect(enrollment).toContain(`ref="${formName}DialogRef"`)
      expect(enrollment).toContain(`:rules="${formName}Rules"`)
    }
    expect(assessmentChange).toContain('Promise.resolve(validation).catch(() => false)')
    expect(enrollment).toContain('ref="exemptionRevokeDialogRef"')
    expect(enrollment).toContain(':rules="exemptionRevokeRules"')
    expect(exemptionRevocation).toContain('Promise.resolve(validation).catch(() => false)')
    expect(enrollment).toContain('ref="reviewDialogRef"')
    expect(enrollment).toContain(':rules="reviewRules"')
    expect(findingReview).toContain('Promise.resolve(validation).catch(() => false)')
    expect(enrollment).toContain('ref="releaseDialogRef"')
    expect(enrollment).toContain(':rules="releaseRules"')
    expect(enrollmentRelease).toContain('Promise.resolve(validation).catch(() => false)')
    const policyChange = readSource('../src/composables/useProtectionPolicyChange.mjs')
    expect(enrollment).toContain('ref="policyDialogRef"')
    expect(enrollment).toContain(':rules="policyRules"')
    expect(enrollment).toContain('ref="policyRestoreDialogRef"')
    expect(enrollment).toContain(':rules="policyRestoreRules"')
    expect(policyChange).toContain('Promise.resolve(validation).catch(() => false)')

    expect(formSurfaces).toContain('prop="componentKey" required')
    expect(formSurfaces).toContain('prop="sensitiveDataTypeID" required')
    expect(formSurfaces).toContain('prop="securityGradeID" required')
    expect(formSurfaces).toContain('prop="effect" required')
    expect(formSurfaces).toContain('prop="reason" required')
    expect(enrollment).toContain('ref="createDrawerRef"')
    expect(enrollment).toContain(':rules="createFormRules"')
    expect(enrollmentCreateDrawer).toContain('class="enrollment-resource-field"')
    expect(enrollmentCreateDrawer).toContain('prop="resource" required')
    expect(enrollmentCreateDrawer).toContain('defineExpose({ validate, validateField })')
    expect(enrollmentCreation).toContain('await Promise.resolve(validation).catch(() => false)')
    expect(accessRequestReview).toContain("createRequiredRule(t('security.common.requiredField'")
    expect(enrollment).toContain("defineAsyncComponent(() => import('../components/protection-enrollment/AccessRequestDecisionDialog.vue'))")
    expect(enrollment).toContain("defineAsyncComponent(() => import('../components/protection-enrollment/FindingReviewDialog.vue'))")
    expect(enrollment).toContain("defineAsyncComponent(() => import('../components/protection-enrollment/ProtectionPolicyDialog.vue'))")
    expect(enrollment).toContain("defineAsyncComponent(() => import('../components/protection-enrollment/AssessmentChangeDialog.vue'))")
    expect(enrollment).toContain("defineAsyncComponent(() => import('../components/protection-enrollment/ExemptionRevokeDialog.vue'))")
    expect(enrollment).toContain("defineAsyncComponent(() => import('../components/protection-enrollment/EnrollmentReleaseDialog.vue'))")
    expect(enrollment).toContain("defineAsyncComponent(() => import('../components/protection-enrollment/ManualAssessmentDialog.vue'))")
    expect(enrollment).toContain('<AccessRequestDecisionDialog')
    expect(accessRequestDecisionDialog).toContain("import AccessRequestDecisionForm from './AccessRequestDecisionForm.vue'")
    expect(accessRequestDecisionDialog).toContain('<AccessRequestDecisionForm')
    expect(enrollment).toContain('<FindingReviewDialog')
    expect(findingReviewDialog).toContain("import FindingReviewForm from './FindingReviewForm.vue'")
    expect(findingReviewDialog).toContain('<FindingReviewForm')
    expect(enrollment).toContain('<ProtectionPolicyDialog')
    expect(protectionPolicyDialog).toContain("import ProtectionPolicyForm from './ProtectionPolicyForm.vue'")
    expect(protectionPolicyDialog).toContain('<ProtectionPolicyForm')
    expect(enrollment).toContain('<AssessmentChangeDialog')
    expect(enrollment).toContain('<ExemptionRevokeDialog')
    expect(enrollment).toContain('<EnrollmentReleaseDialog')
    expect(enrollment).toContain('<ManualAssessmentDialog')
    expect(enrollment).not.toContain('<el-form ref="accessRequestDecisionFormRef"')
    expect(enrollment).not.toContain('<el-form ref="reviewFormRef"')
    expect(enrollment).not.toContain('<el-form ref="policyFormRef"')
    expect(enrollment).not.toContain('<el-form ref="assessmentRevisionFormRef"')
    expect(enrollment).not.toContain('<el-form ref="assessmentRevokeFormRef"')
    expect(enrollment).not.toContain('<el-form ref="exemptionRevokeFormRef"')
    expect(enrollment).not.toContain('<el-form ref="releaseFormRef"')
    expect(enrollment).not.toContain('<el-form ref="manualAssessmentFormRef"')
    expect(accessRequestDecisionForm).toContain('defineExpose({ validate, clearValidate })')
    expect(accessRequestDecisionDialog).toContain('defineExpose({ validate, clearValidate, focusPrimary })')
    expect(findingReviewForm).toContain('defineExpose({ validate, focusRationale })')
    expect(findingReviewDialog).toContain('defineExpose({ validate, focusPrimary })')
    expect(protectionPolicyForm).toContain('defineExpose({ validate, clearValidate })')
    expect(protectionPolicyDialog).toContain('defineExpose({ validate, clearValidate, focusPrimary })')
    expect(assessmentChangeDialog).toContain('defineExpose({ validate, clearValidate, focusPrimary })')
    expect(exemptionRevokeDialog).toContain('defineExpose({ validate, clearValidate, focusPrimary })')
    expect(enrollmentReleaseDialog).toContain('defineExpose({ validate, clearValidate, focusPrimary })')
    expect(manualAssessmentDialog).toContain('defineExpose({ validate, clearValidate, focusPrimary })')
    expect(manualAssessmentDialog).toContain('@open="clearValidate"')
    expect(manualAssessmentDialog).toContain('@opened="focusPrimary"')
    expect(manualAssessmentDialog).not.toContain('function focusPrimary() {\n  clearValidate()')
    expect(enrollment).not.toContain("ElMessage.warning(t('security.enrollment.resourceRequired'))")
    expect(enrollment).not.toContain("ElMessage.warning(t('security.accessRequest.decisionRationaleRequired'))")
    expect(enrollment).not.toContain("ElMessage.warning(t('security.finding.rationaleRequired'))")
    expect(enrollment).not.toContain("ElMessage.warning(t('security.finding.adjustmentRequired'))")
    expect(enrollment).not.toContain("ElMessage.warning(t('security.assessment.required'))")
    expect(enrollment).not.toContain("ElMessage.warning(t('security.assessment.revisionRequired'))")
    expect(enrollment).not.toContain("ElMessage.warning(t('security.assessment.revokeRationaleRequired'))")
    expect(enrollment).not.toContain("ElMessage.warning(t('security.exemption.rationaleRequired'))")
    expect(enrollment).not.toContain("ElMessage.warning(t('security.policy.required'))")
    expect(enrollment).not.toContain("ElMessage.warning(t('security.policy.rationaleRequired'))")
    expect(enrollment).not.toContain("ElMessage.warning(t('security.enrollment.releaseReasonRequired'))")
    expect(enrollment).not.toContain('async function validateRequiredForm(')

    for (const messages of localeMessages) {
      expect(messages.security.common.requiredField).toBeTruthy()
      expect(messages.security.accessRequest.decisionRationaleRequired).toBeUndefined()
      expect(messages.security.finding.rationaleRequired).toBeUndefined()
      expect(messages.security.finding.adjustmentRequired).toBeUndefined()
      expect(messages.security.assessment.required).toBeUndefined()
      expect(messages.security.assessment.revisionRequired).toBeUndefined()
      expect(messages.security.assessment.revokeRationaleRequired).toBeUndefined()
      expect(messages.security.exemption.rationaleRequired).toBeUndefined()
      expect(messages.security.policy.required).toBeUndefined()
      expect(messages.security.policy.rationaleRequired).toBeUndefined()
      expect(messages.security.enrollment.releaseReasonRequired).toBeUndefined()
    }
  })

  it('recovers an enrollment release only after an explicit latest-state reload', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')
    const enrollmentRelease = readSource('../src/composables/useProtectionEnrollmentRelease.mjs')
    const releaseDialog = readSource('../src/components/protection-enrollment/EnrollmentReleaseDialog.vue')
    const zhCn = JSON.parse(readSource('../src/i18n/zh-cn.json'))

    expect(enrollment).toContain('useProtectionEnrollmentRelease({')
    expect(enrollment).not.toContain('async function reloadReleaseBaseline(')
    expect(enrollment).not.toContain('async function releaseEnrollment(')
    expect(enrollmentRelease).toContain('isResourceVersionConflict(error)')
    expect(enrollmentRelease).toContain('isNoSupportedFindingsReleaseUnavailable(error)')
    expect(enrollmentRelease).toContain("basis.value === 'no_supported_findings' && !isZeroFindingDiscovery(latest)")
    expect(enrollment).toContain('reloadReleaseBaseline')
    expect(enrollment).toContain(':conflict="releaseConflict"')
    expect(releaseDialog).toContain(':disabled="conflict"')
    expect(releaseDialog).toContain('<el-form-item :label="t(\'security.enrollment.releaseReasonLabel\')" prop="reason" required>')
    expect(releaseDialog).toContain("props.basis === 'no_supported_findings'")
    expect(enrollment).toContain('getEnrollment: id => protectionEnrollmentAPI.get(id)')
    expect(enrollment).toContain('releaseEnrollment: (id, payload) => protectionEnrollmentAPI.release(id, payload)')
    expect(zhCn.security.enrollment.releaseVersionConflict).toContain('退出依据和原因已保留')
    expect(zhCn.security.enrollment.reloadLatestForRelease).toBe('放弃当前输入并加载最新受保护资源')
  })

  it('reconfirms rediscovery only after explicitly loading the latest enrollment', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')
    const enrollmentRediscovery = readSource('../src/composables/useProtectionEnrollmentRediscovery.mjs')
    const detailDrawer = readSource('../src/components/protection-enrollment/EnrollmentDetailDrawer.vue')
    const lifecycleDialog = readSource('../src/components/protection-enrollment/EnrollmentLifecycleActionDialog.vue')
    const zhCn = JSON.parse(readSource('../src/i18n/zh-cn.json'))

    expect(enrollment).toContain('useProtectionEnrollmentRediscovery({')
    expect(enrollment).not.toContain('async function reloadRediscoveryBaseline(')
    expect(enrollment).not.toContain('async function submitRediscovery(')
    expect(enrollment).toContain('@rediscover="openRediscovery"')
    expect(detailDrawer).toContain("@click=\"emit('rediscover', enrollment)\"")
    expect(enrollment).toContain('reloadRediscoveryBaseline')
    expect(enrollment).toContain(':conflict="rediscoveryConflict"')
    expect(enrollment).toContain('ref="rediscoveryDialogRef"')
    expect(enrollment).toContain('mode="rediscover"')
    expect(enrollment).not.toContain('ref="rediscoveryCancelButton"')
    expect(enrollment).toContain("defineAsyncComponent(() => import('../components/protection-enrollment/EnrollmentLifecycleActionDialog.vue'))")
    expect(enrollment).toContain('<EnrollmentLifecycleActionDialog')
    expect(lifecycleDialog).toContain("['re-enroll', 'rediscover'].includes(value)")
    expect(enrollment).toContain('getEnrollment: id => protectionEnrollmentAPI.get(id)')
    expect(enrollment).toContain('createDiscoveryExecution: (id, payload) => protectionEnrollmentAPI.rediscover(id, payload)')
    expect(enrollmentRediscovery).toContain('isResourceVersionConflict(error)')
    expect(enrollmentRediscovery).toContain('isDiscoveryExecutionInProgress(error)')
    expect(enrollmentRediscovery).toContain('const enrollmentVersion = Number(execution?.enrollment_version)')
    expect(enrollmentRediscovery).toContain("watchDiscovery(source.id, baselineMarker)")
    expect(zhCn.security.enrollment.rediscoveryVersionConflict).toContain('重新发现意图已保留')
    expect(zhCn.security.enrollment.discoveryExecutionInProgress).toContain('正在等待或执行')
  })

  it('only presents components that remain eligible for manual designation', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')
    const assessmentWorkspace = readSource('../src/composables/useProtectionAssessmentWorkspace.mjs')
    const manualAssessmentDialog = readSource('../src/components/protection-enrollment/ManualAssessmentDialog.vue')

    expect(manualAssessmentDialog).toContain('v-for="option in componentOptions"')
    expect(manualAssessmentDialog).not.toContain(':disabled="Boolean(option.assessment_id)"')
    expect(enrollment).toContain('useProtectionAssessmentWorkspace({')
    expect(enrollment).not.toContain('async function openManualAssessment(')
    expect(enrollment).not.toContain('async function submitManualAssessment(')
    expect(enrollment).toContain('loadComponents: enrollmentID => protectionEnrollmentAPI.components(enrollmentID)')
    expect(enrollment).toContain('createAssessment: payload => assessmentAPI.create(payload)')
    expect(enrollment).toContain(':active-grades-for-type="activeGradesForType"')
    expect(manualAssessmentDialog).toContain('activeGradesForType(form.sensitiveDataTypeID)')
    expect(assessmentWorkspace).toContain('Array.isArray(response?.data) ? response.data : []')
    expect(assessmentWorkspace).toContain('enrollment_version: Number(enrollment.version)')
  })

  it('renders the backend-provided finding explanation as one control flow', () => {
    const detailDrawer = readSource('../src/components/protection-enrollment/EnrollmentDetailDrawer.vue')
    const governanceSection = readSource('../src/components/protection-enrollment/EnrollmentGovernanceSection.vue')
    const findingList = readSource('../src/components/protection-enrollment/EnrollmentFindingList.vue')
    const zhCn = JSON.parse(readSource('../src/i18n/zh-cn.json'))

    expect(detailDrawer).toContain("import EnrollmentGovernanceSection from './EnrollmentGovernanceSection.vue'")
    expect(governanceSection).toContain("import EnrollmentFindingList from './EnrollmentFindingList.vue'")
    expect(findingList).toContain("security.finding.explanationStages.detection")
    expect(findingList).toContain("security.finding.explanationStages.governance")
    expect(findingList).toContain("security.finding.explanationStages.execution")
    expect(findingList).toContain('finding.explanation.outlets')
    expect(findingList).toContain(':icon="QuestionFilled"')
    expect(findingList).toContain('<el-popover')
    expect(findingList).toContain('trigger="click"')
    expect(findingList).toContain('<dl class="recognition-rule-details">')
    expect(findingList).toContain('security.finding.ruleAudit.viewDetails')
    expect(findingList).toContain('container: finding-card / inline-size')
    expect(findingList).toContain('@container finding-card (max-width: 920px)')
    expect(findingList).toContain('.explanation-stage:nth-child(3)')
    expect(findingList).toContain("capabilityText(finding, 'method_i18n_key')")
    expect(zhCn.security.finding.ruleAudit.details).toBe('识别说明')
    expect(zhCn.security.finding.ruleAudit.viewDetails).toBe('查看识别说明')
    expect(zhCn.security.finding.ruleAudit.viewMethod).toBeUndefined()
    expect(findingList).not.toContain('finding.detector_version }}</el-descriptions-item>')
    expect(zhCn.security.finding.explanationStages.execution).toBe('出口规则')
    expect(zhCn.security.finding.outletAcknowledged).toBe('已同步')
    expect(zhCn.security.finding.outletWaiting).toBe('待同步')
  })

  it('keeps protected-resource detail rendering in async domain components', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')
    const detailDrawer = readSource('../src/components/protection-enrollment/EnrollmentDetailDrawer.vue')
    const governanceSection = readSource('../src/components/protection-enrollment/EnrollmentGovernanceSection.vue')
    const assessmentList = readSource('../src/components/protection-enrollment/EnrollmentAssessmentList.vue')
    const exemptionSection = readSource('../src/components/protection-enrollment/EnrollmentExemptionSection.vue')

    expect(enrollment).toContain("defineAsyncComponent(() => import('../components/protection-enrollment/EnrollmentDetailDrawer.vue'))")
    expect(detailDrawer).toContain("import EnrollmentGovernanceSection from './EnrollmentGovernanceSection.vue'")
    expect(detailDrawer).toContain("import EnrollmentExemptionSection from './EnrollmentExemptionSection.vue'")
    expect(detailDrawer).toContain('<EnrollmentGovernanceSection')
    expect(detailDrawer).toContain('<EnrollmentExemptionSection')
    expect(detailDrawer).not.toContain("import EnrollmentFindingList from './EnrollmentFindingList.vue'")
    expect(detailDrawer).not.toContain("import EnrollmentAssessmentList from './EnrollmentAssessmentList.vue'")
    expect(governanceSection).toContain("import EnrollmentFindingList from './EnrollmentFindingList.vue'")
    expect(governanceSection).toContain("import EnrollmentAssessmentList from './EnrollmentAssessmentList.vue'")
    expect(governanceSection).toContain('<EnrollmentFindingList')
    expect(governanceSection).toContain('<EnrollmentAssessmentList')
    expect(governanceSection).toContain('class="finding-section"')
    expect(governanceSection).toContain("emit('review', { finding, decision })")
    expect(detailDrawer).toContain("@review=\"emit('review', $event.finding, $event.decision)\"")
    expect(enrollment).not.toContain('class="finding-card"')
    expect(enrollment).not.toContain('class="manual-assessment-card"')
    expect(enrollment).not.toContain('class="exemption-card"')
    expect(detailDrawer).not.toContain('class="finding-section"')
    expect(assessmentList).toContain('class="manual-assessment-card"')
    expect(exemptionSection).toContain('class="exemption-card"')
    expect(exemptionSection).toContain('defineExpose({ focusFocused })')
  })

  it('passes protected-resource detail dependencies through grouped contracts', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')
    const detailDrawer = readSource('../src/components/protection-enrollment/EnrollmentDetailDrawer.vue')
    const governanceSection = readSource('../src/components/protection-enrollment/EnrollmentGovernanceSection.vue')

    expect(enrollment).toContain(':refresh-state="detailRefreshState"')
    expect(enrollment).toContain(':governance="detailGovernance"')
    expect(enrollment).toContain(':permissions="detailPermissions"')
    expect(enrollment).toContain(':presentation="detailPresentation"')
    expect(enrollment).toContain('focusedExemptionId: focusedExemptionID.value')
    expect(enrollment).not.toContain(':can-read-findings="canReadFindings"')
    expect(enrollment).not.toContain(':assessment-protection-summary="assessmentProtectionSummary"')
    expect(enrollment).toContain('resource: Object.freeze({')
    expect(enrollment).toContain('governance: Object.freeze({')
    expect(enrollment).toContain('exemption: Object.freeze({')
    expect(enrollment).toContain('owner: Object.freeze({')
    expect(detailDrawer).toContain('refreshState: { type: Object, required: true }')
    expect(detailDrawer).toContain('governance: { type: Object, required: true }')
    expect(detailDrawer).toContain('permissions: { type: Object, required: true }')
    expect(detailDrawer).toContain('presentation: { type: Object, required: true }')
    expect(detailDrawer).toContain('presentation.resource.name(enrollment)')
    expect(detailDrawer).toContain(':presentation="presentation.governance"')
    expect(detailDrawer).toContain('presentation.exemption.assessmentComponent')
    expect(detailDrawer).toContain('presentation.owner.effectDescription(owner)')
    expect(detailDrawer).not.toContain('presentation.resourceName(enrollment)')
    expect(governanceSection).not.toContain('presentation.resource.')
    expect(governanceSection).not.toContain('presentation.exemption.')
    expect(governanceSection).not.toContain('presentation.owner.')
    expect(detailDrawer).not.toContain('canReadFindings: {')
    expect(detailDrawer).not.toContain('assessmentProtectionSummary: {')
  })

  it('keeps the pending review queue as a recoverable subview of protected resources', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')
    const workspace = readSource('../src/composables/useProtectionEnrollmentWorkspace.mjs')
    const presentation = readSource('../src/composables/useProtectionEnrollmentPresentation.mjs')
    const reviewSession = readSource('../src/composables/useProtectionFindingReview.mjs')
    const reviewQueueState = readSource('../src/composables/useProtectionFindingReviewQueue.mjs')
    const reviewQueue = readSource('../src/components/protection-enrollment/FindingReviewQueueWorkspace.vue')
    const resourceIdentity = readSource('../src/components/protection-enrollment/EnrollmentResourceIdentity.vue')
    const reviewDialog = readSource('../src/components/protection-enrollment/FindingReviewDialog.vue')
    const reviewForm = readSource('../src/components/protection-enrollment/FindingReviewForm.vue')
    const zhCn = JSON.parse(readSource('../src/i18n/zh-cn.json'))

    expect(workspace).toContain("WORKSPACE_TABS = ['resources', 'review-queue']")
    expect(reviewQueueState).toContain("snapshot_scope: 'current'")
    expect(reviewQueueState).toContain("review_state: 'pending'")
    expect(workspace).toContain('resolveCanonicalTabRouteState')
    expect(workspace).toContain('resolveFindingReviewQueueRouteState')
    expect(enrollment).toContain('useProtectionFindingReviewQueue({')
    expect(enrollment).not.toContain('async function loadReviewQueue(')
    expect(enrollment).toContain('useProtectionFindingReview({')
    expect(enrollment).not.toContain('async function submitFindingReview(')
    expect(enrollment).not.toContain('function prepareFindingReview(')
    expect(reviewSession).toContain('buildFindingReviewPayload(form)')
    expect(reviewSession).toContain('const reviewContext = context')
    expect(reviewSession).toContain('continueAfterReview(reviewedFinding, reviewContext)')
    expect(reviewQueueState).toContain('resolveReviewQueueFilters(routeQuery)')
    expect(reviewQueueState).toContain('let queueRequest = 0')
    expect(reviewQueueState).toContain('resolvePendingReviewContinuation({')
    expect(enrollment).toContain('nextReviewQueueFinding(reviewedFinding)')
    expect(enrollment).toContain('nextDetailReviewFinding')
    expect(enrollment).toContain('security.finding.reviewSavedAndContinued')
    expect(presentation).toContain('security.finding.reviewRemainingQueue')
    expect(presentation).toContain('security.finding.reviewRemainingResource')
    expect(enrollment).toContain("defineAsyncComponent(() => import('../components/protection-enrollment/FindingReviewQueueWorkspace.vue'))")
    expect(enrollment).toContain("defineAsyncComponent(() => import('../components/protection-enrollment/FindingReviewDialog.vue'))")
    expect(reviewDialog).toContain("import FindingReviewForm from './FindingReviewForm.vue'")
    expect(enrollment).toContain('<FindingReviewQueueWorkspace')
    expect(enrollment).toContain('<EnrollmentResourceList')
    expect(reviewQueue).toContain('<EnrollmentResourceIdentity')
    expect(enrollment).not.toContain('class="review-queue-intro"')
    expect(enrollment).not.toContain('class="resource-cell"')
    expect(reviewQueue).toContain('class="review-queue-intro"')
    expect(reviewQueue).toContain("emit('review', row, 'confirm')")
    expect(reviewQueue).toContain("emit('review', row, 'reject')")
    expect(reviewQueue).toContain("emit('openResource', row)")
    expect(reviewQueue).toContain("emit('filterChange')")
    expect(reviewQueue).toContain("emit('pageChange')")
    expect(resourceIdentity).toContain('class="resource-cell"')
    expect(enrollment).toContain('v-model:basis-expanded="reviewBasisExpanded"')
    expect(reviewForm).toContain('security.finding.reviewBasis.actualMatch')
    expect(reviewForm).toContain('evidenceAuditDescription(finding)')
    expect(reviewForm).toContain('outletRuleDescription(finding, outlet.consumer_owner)')
    expect(enrollment).toContain('reviewFinding: (id, payload) => findingAPI.review(id, payload)')
    expect(zhCn.security.enrollment.workspaces.reviewQueue).toBe('待复核候选')
    expect(zhCn.security.reviewQueue.description).toContain('提交复核后候选会自动移出')
    expect(zhCn.security.finding.reviewRemainingQueue).toContain('当前筛选')
    expect(zhCn.security.finding.reviewRemainingResource).toContain('当前资源')
    expect(zhCn.security.finding.reviewBasis.title).toBe('判定依据')
    expect(zhCn.security.finding.reviewBasis.currentEnforcement).toBe('当前出口规则')
  })

  it('presents owner acknowledgement as synchronized rules rather than request execution', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')
    const detailDrawer = readSource('../src/components/protection-enrollment/EnrollmentDetailDrawer.vue')
    const presentation = readSource('../src/composables/useProtectionEnrollmentPresentation.mjs')
    const zhCn = JSON.parse(readSource('../src/i18n/zh-cn.json'))
    const en = JSON.parse(readSource('../src/i18n/en.json'))

    expect(zhCn.security.enrollment.progress).toBe('保护规则同步')
    expect(zhCn.security.enrollment.ownerStates.active).toBe('字段规则已同步')
    expect(zhCn.security.enrollment.states.active).toBe('保护规则同步完成')
    expect(zhCn.security.enrollment.stateDescriptions.active).toContain('具体请求仍按运行时能力执行或保守拒绝')
    expect(zhCn.security.enrollment.ownerProtectionHint).toContain('已同步表示 Owner 已持久保存当前保护投影')
    expect(zhCn.security.enrollment.ownerEffectRequirements).toBe('已同步规则：{rules}')
    expect(en.security.enrollment.ownerStates.active).toBe('Field rules synchronized')
    expect(en.security.enrollment.ownerProtectionHint).toContain('Each request still validates')
    expect(detailDrawer).toContain("security.enrollment.ownerProtectionHint")
    expect(presentation).toContain("security.enrollment.ownerEffectRequirements")
    expect(presentation).toContain('Array.isArray(owner.rules)')
    expect(presentation).not.toContain('Array.isArray(owner.effects)')
    expect(zhCn.security.enrollment.stateDescriptions.active).not.toContain('均已执行字段级保护')
  })

  it('keeps plaintext access on the request and approval route only', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')
    const accessReview = readSource('../src/composables/useProtectionAccessRequestReview.mjs')
    const enrollmentDetail = readSource('../src/composables/useProtectionEnrollmentDetail.mjs')
    const detailDrawer = readSource('../src/components/protection-enrollment/EnrollmentDetailDrawer.vue')
    const exemptionRevocation = readSource('../src/composables/useProtectionExemptionRevocation.mjs')
    const reviewWorkspace = readSource('../src/components/protection-enrollment/AccessRequestReviewWorkspace.vue')
    const exemptionSection = readSource('../src/components/protection-enrollment/EnrollmentExemptionSection.vue')
    const exemptionRevokeDialog = readSource('../src/components/protection-enrollment/ExemptionRevokeDialog.vue')
    const accessRequestDecisionDialog = readSource('../src/components/protection-enrollment/AccessRequestDecisionDialog.vue')
    const api = readSource('../src/api/security.js')
    const zhCn = JSON.parse(readSource('../src/i18n/zh-cn.json'))

    expect(enrollment).toContain('protectionAccessRequestAPI.reviewQueue')
    expect(enrollment).toContain('protectionAccessRequestAPI.decide')
    expect(enrollment).toContain("defineAsyncComponent(() => import('../components/protection-enrollment/AccessRequestReviewWorkspace.vue'))")
    expect(enrollment).toContain('<AccessRequestReviewWorkspace')
    expect(enrollment).not.toContain('class="access-review-card"')
    expect(reviewWorkspace).toContain('class="access-review-card"')
    expect(enrollment).toContain('v-model="accessRequestDecisionDialog"')
    expect(enrollment).toContain('@decide="openAccessRequestDecision"')
    expect(reviewWorkspace).toContain("emit('decide', row, 'approve')")
    expect(reviewWorkspace).toContain("emit('decide', row, 'reject')")
    expect(enrollment).toContain('accessRequestDecisionConflict')
    expect(enrollment).toContain('reloadAccessRequestDecisionBaseline')
    expect(enrollment).toContain(':conflict="accessRequestDecisionConflict"')
    expect(accessRequestDecisionDialog).toContain(':disabled="conflict"')
    expect(enrollment).toContain('submitAccessRequestDecision')
    expect(enrollment).not.toContain('async function reloadAccessRequestDecisionBaseline(')
    expect(enrollment).not.toContain('async function submitAccessRequestDecision(')
    expect(accessReview).toContain("latest?.state !== 'pending' || !latest.can_decide")
    expect(accessReview).toContain('isProtectionAccessRequestExpired(error)')
    expect(accessReview).toContain('Promise.resolve(validation).catch(() => false)')
    expect(accessReview).toContain('await Promise.all([loadQueue(1), refreshCollection({ background: true })])')
    expect(accessReview).toContain('function focusDecisionDialogPrimary()')
    expect(accessRequestDecisionDialog).toContain('ref="cancelButton"')
    expect(accessRequestDecisionDialog).toContain('@opened="focusPrimary"')
    expect(enrollment).not.toContain('ElMessageBox.prompt')
    expect(api).toContain('client.get(`/security/protection-access-requests/${id}`)')
    expect(reviewWorkspace).toContain('row.can_decide')
    expect(reviewWorkspace).toContain('v-else-if="row.decision_unavailable_reason"')
    expect(enrollment).toContain('decisionConfirmLabel: accessRequestDecisionConfirmLabel')
    expect(accessReview).toContain('security.accessRequest.confirmActions.${decision.value}')
    expect(enrollment).toContain('useProtectionAccessRequestReview({')
    expect(enrollment).not.toContain('function accessRequestQueueParams(')
    expect(enrollment).not.toContain('async function loadAccessRequestQueue(')
    expect(accessReview).toContain('scope: scope.value')
    expect(accessReview).toContain('authorization_state: scope.value')
    expect(accessReview).toContain('requester_search: filters.requesterSearch')
    expect(accessReview).toContain('resource_search: filters.resourceSearch')
    expect(accessReview).toContain('created_from: range[0] instanceof Date')
    expect(accessReview).toContain('created_to: range[1] instanceof Date')
    expect(accessReview).toContain('let queueRequest = 0')
    expect(enrollment).toContain('v-model:page="accessRequestPage"')
    expect(enrollment).toContain('v-model:page-size="accessRequestPageSize"')
    expect(reviewWorkspace).toContain("scope === 'pending'")
    expect(reviewWorkspace).toContain("scope === 'history'")
    expect(reviewWorkspace).toContain('row.decision_rationale')
    expect(reviewWorkspace).toContain('row.requester?.display_name')
    expect(reviewWorkspace).toContain('row.reviewer.display_name')
    expect(reviewWorkspace).toContain('row.authorization_state')
    expect(reviewWorkspace).toContain('row.authorized_until')
    expect(reviewWorkspace).toContain('row.enrollment_id')
    expect(reviewWorkspace).toContain("emit('openAuthorization', row)")
    expect(enrollment).toContain('openAuthorization: openAccessRequestAuthorization')
    expect(enrollmentDetail).toContain('return await activate(row, accessRequest?.exemption_id, request)')
    expect(enrollment).toContain('focusedExemptionId: focusedExemptionID.value')
    expect(detailDrawer).toContain(':focused-exemption-id="governance.focusedExemptionId"')
    expect(exemptionSection).toContain("String(exemption.id) === String(focusedExemptionId)")
    expect(enrollment).toContain('v-model="exemptionRevokeDialog"')
    expect(enrollment).toContain('@revoke="openExemptionRevoke"')
    expect(exemptionSection).toContain("emit('revoke', exemption)")
    expect(enrollment).toContain('exemptionRevokeConflict')
    expect(enrollment).toContain('reloadExemptionRevokeBaseline')
    expect(enrollment).toContain(':conflict="exemptionRevokeConflict"')
    expect(exemptionRevokeDialog).toContain(':disabled="conflict"')
    expect(enrollment).toContain('submitExemptionRevoke')
    expect(enrollment).toContain('useProtectionExemptionRevocation({')
    expect(enrollment).not.toContain('async function reloadExemptionRevokeBaseline(')
    expect(enrollment).not.toContain('async function submitExemptionRevoke(')
    expect(enrollment).toContain('getExemption: id => protectionExemptionAPI.get(id)')
    expect(enrollment).toContain('revokeExemption: (id, payload) => protectionExemptionAPI.revoke(id, payload)')
    expect(exemptionRevocation).toContain("latest?.effective_state !== 'active'")
    expect(exemptionRevocation).toContain('isResourceVersionConflict(error)')
    expect(enrollment).not.toContain("t('security.exemption.revokePrompt'")
    expect(api).toContain('client.get(`/security/protection-exemptions/${id}`)')
    expect(reviewWorkspace).toContain('authorizationStateType')
    expect(reviewWorkspace).toContain('releaseActorLabel(row.requester?.id)')
    expect(reviewWorkspace).toContain('releaseActorLabel(row.reviewer.id)')
    expect(reviewWorkspace).not.toContain('row.decided_by')
    expect(zhCn.security.accessRequest.unavailableReasons.self_approval_forbidden).toBe('需由另一名审批人处理')
    expect(zhCn.security.accessRequest.scopes.pending).toBe('待审批')
    expect(zhCn.security.accessRequest.scopes.history).toBe('审批记录')
    expect(zhCn.security.accessRequest.filters.resourcePlaceholder).toContain('资源')
    expect(zhCn.security.accessRequest.filters.requesterPlaceholder).toContain('用户 ID')
    expect(zhCn.security.accessRequest.filters.allAuthorizationStates).toBe('全部授权状态')
    expect(zhCn.security.accessRequest.createdAt).toBe('申请时间')
    expect(zhCn.security.accessRequest.authorizationState).toBe('当前授权')
    expect(zhCn.security.accessRequest.authorizationStates.active).toBe('生效中')
    expect(zhCn.security.accessRequest.authorizationStates.not_granted).toBe('未产生授权')
    expect(zhCn.security.accessRequest.viewAuthorization).toBe('查看授权')
    expect(zhCn.security.accessRequest.approveHint).toContain('当前字段和数据预览出口')
    expect(zhCn.security.accessRequest.rejectHint).toContain('审批结论不可反转')
    expect(zhCn.security.accessRequest.decisionVersionConflict).toContain('当前审批动作和意见已保留')
    expect(zhCn.security.accessRequest.reloadLatestForDecision).toContain('放弃当前输入')
    expect(zhCn.security.accessRequest.expiredBeforeDecision).toContain('已过期')
    expect(zhCn.security.exemption.revokeHint).toContain('立即恢复执行当前字段保护规则')
    expect(zhCn.security.exemption.revokeVersionConflict).toContain('当前撤销依据已保留')
    expect(zhCn.security.exemption.reloadLatestForRevoke).toContain('放弃当前输入')
    expect(zhCn.security.exemption.alreadyInactive).toContain('无需重复撤销')
    expect(enrollment).not.toContain('openCreateExemption')
    expect(enrollment).not.toContain('openRenewExemption')
    expect(api).not.toContain('protectionExemptionAPI.create')
    expect(api).not.toContain('protectionExemptionAPI.renew')
    expect(zhCn.security.exemption.title).toBe('临时原值授权')
  })

  it('keeps resource-specific tightening inside protected resources', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')
    const governance = readSource('../src/composables/useProtectionEnrollmentGovernance.mjs')
    const policyChange = readSource('../src/composables/useProtectionPolicyChange.mjs')
    const policyDialog = readSource('../src/components/protection-enrollment/ProtectionPolicyDialog.vue')
    const api = readSource('../src/api/security.js')
    const zhCn = JSON.parse(readSource('../src/i18n/zh-cn.json'))

    expect(enrollment).toContain('listPolicies: params => protectionPolicyAPI.list(params)')
    expect(governance).toContain("kind: 'policies'")
    expect(enrollment).toContain('useProtectionPolicyChange({')
    expect(enrollment).not.toContain('async function reloadPolicyBaseline(')
    expect(enrollment).not.toContain('async function savePolicy(')
    expect(enrollment).not.toContain('async function reloadPolicyRestoreBaseline(')
    expect(enrollment).not.toContain('async function submitPolicyRestore(')
    expect(policyChange).toContain("consumer_owner: 'manager'")
    expect(policyChange).toContain("action: 'preview'")
    expect(enrollment).toContain('stricterEffects: stricterPolicyEffects')
    expect(enrollment).toContain('policyVersionConflict')
    expect(enrollment).toContain('reloadPolicyBaseline')
    expect(enrollment).toContain(':conflict="policyVersionConflict"')
    expect(policyDialog).toContain(':disabled="conflict"')
    expect(policyDialog).toContain('@open="clearValidate"')
    expect(policyDialog).toContain("props.mode !== 'restore'")
    expect(enrollment).toContain('getPolicy: id => protectionPolicyAPI.get(id)')
    expect(enrollment).toContain('getAssessment: id => assessmentAPI.get(id)')
    expect(enrollment).toContain('listBaselines: () => protectionBaselineAPI.list()')
    expect(enrollment).toContain('v-model="policyRestoreDialog"')
    expect(enrollment).toContain('openRestore: openPolicyRestore')
    expect(enrollment).toContain('policyRestoreConflict')
    expect(enrollment).toContain('reloadPolicyRestoreBaseline')
    expect(enrollment).toContain(':conflict="policyRestoreConflict"')
    expect(enrollment).toContain('submitPolicyRestore')
    expect(enrollment).not.toContain("t('security.policy.restorePrompt'")
    expect(enrollment).toContain(':active-grades-for-type="activeGradesForType"')
    expect(api).toContain("client.post('/security/protection-policies'")
    expect(api).toContain('client.get(`/security/protection-policies/${id}`)')
    expect(zhCn.security.policy.hint).toContain('不能放宽')
    expect(zhCn.security.policy.hint).toContain('申请与审批')
    expect(zhCn.security.policy.versionConflict).toContain('当前选择和依据已保留')
    expect(zhCn.security.policy.reloadLatest).toContain('放弃当前输入')
    expect(zhCn.security.policy.restoreHint).toContain('回落到当前默认保护')
    expect(zhCn.security.policy.restoreVersionConflict).toContain('当前恢复依据已保留')
    expect(zhCn.security.policy.reloadLatestForRestore).toContain('放弃当前输入')
  })

  it('revises every formal assessment through the protected-resource aggregate', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')
    const assessmentChange = readSource('../src/composables/useProtectionAssessmentChange.mjs')
    const assessmentChangeDialog = readSource('../src/components/protection-enrollment/AssessmentChangeDialog.vue')
    const assessmentHistoryDialog = readSource('../src/components/protection-enrollment/AssessmentHistoryDialog.vue')
    const assessmentWorkspace = readSource('../src/composables/useProtectionAssessmentWorkspace.mjs')
    const findingList = readSource('../src/components/protection-enrollment/EnrollmentFindingList.vue')
    const assessmentList = readSource('../src/components/protection-enrollment/EnrollmentAssessmentList.vue')
    const api = readSource('../src/api/security.js')
    const zhCn = JSON.parse(readSource('../src/i18n/zh-cn.json'))

    expect(enrollment).toContain('@revise="openAssessmentRevision"')
    expect(enrollment).toContain('@history="openAssessmentHistory"')
    expect(findingList).toContain("emit('revise', assessmentForFinding(finding))")
    expect(findingList).toContain("emit('history', assessmentForFinding(finding))")
    expect(assessmentList).toContain("emit('revise', assessment)")
    expect(assessmentList).toContain("emit('history', assessment)")
    expect(enrollment).toContain("defineAsyncComponent(() => import('../components/protection-enrollment/AssessmentHistoryDialog.vue'))")
    expect(enrollment).toContain('<AssessmentHistoryDialog')
    expect(enrollment).not.toContain('assessmentHistory.history')
    expect(assessmentHistoryDialog).toContain('assessment.history')
    expect(assessmentHistoryDialog).toContain('function isCurrentRevision(revision)')
    expect(assessmentHistoryDialog).toContain('props.assessment?.current_revision')
    expect(enrollment).not.toContain('async function openAssessmentHistory(')
    expect(assessmentWorkspace).toContain('async function openHistory(assessment)')
    expect(assessmentWorkspace).toContain('request !== historyRequest || disposed')
    expect(enrollment).toContain('assessmentRevisionConflict')
    expect(enrollment).toContain('reloadAssessmentRevisionBaseline')
    expect(enrollment).toContain(':conflict="assessmentRevisionConflict"')
    expect(enrollment).toContain('v-model="assessmentRevokeDialog"')
    expect(enrollment).toContain('@revoke-assessment="openAssessmentRevoke"')
    expect(assessmentList).toContain("emit('revoke', assessment)")
    expect(enrollment).toContain('assessmentRevokeConflict')
    expect(enrollment).toContain('reloadAssessmentRevokeBaseline')
    expect(enrollment).toContain(':conflict="assessmentRevokeConflict"')
    expect(assessmentChangeDialog).toContain(':disabled="conflict"')
    expect(enrollment).toContain('submitAssessmentRevoke')
    expect(enrollment).toContain('useProtectionAssessmentChange({')
    expect(enrollment).not.toContain('async function submitAssessmentRevision(')
    expect(enrollment).not.toContain('async function submitAssessmentRevoke(')
    expect(assessmentChange).toContain("latest?.current?.conclusion !== 'sensitive'")
    expect(enrollment).not.toContain("t('security.assessment.revokePrompt'")
    expect(assessmentChangeDialog).toContain('activeGradesForType(form.sensitiveDataTypeID)')
    expect(enrollment).toContain('reviseAssessment: (id, payload) => assessmentAPI.revise(id, payload)')
    expect(enrollment).toContain('revokeAssessment: (id, payload) => assessmentAPI.revoke(id, payload)')
    expect(assessmentChange).toContain('version: assessment.version')
    expect(assessmentChange).toContain('buildAssessmentRevisionPayload({')
    expect(api).toContain('client.post(`/security/assessments/${id}/revisions`')
    expect(api).toContain('client.get(`/security/assessments/${id}`)')
    expect(api).not.toContain('client.put(`/security/assessments/${id}`')
    expect(zhCn.security.assessment.reviseConclusion).toBe('调整结论')
    expect(zhCn.security.assessment.history).toBe('修订记录')
    expect(zhCn.security.assessment.historyHint).toContain('不可变修订')
    expect(zhCn.security.assessment.versionConflict).toContain('当前输入已保留')
    expect(zhCn.security.assessment.reloadLatest).toContain('放弃当前输入')
    expect(zhCn.security.assessment.revokeHint).toContain('不可变的非敏感结论')
    expect(zhCn.security.assessment.revokeVersionConflict).toContain('当前撤销依据已保留')
    expect(zhCn.security.assessment.reloadLatestForRevoke).toContain('放弃当前输入')
    expect(zhCn.security.assessment.alreadyRevoked).toContain('无需重复操作')
    expect(zhCn.security.assessment.reviseHint).toContain('不可变修订')
    expect(zhCn.security.assessment.reviseHint).toContain('重新编译各数据出口规则')
  })
})
