import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'

const readSource = relativePath => readFileSync(new URL(relativePath, import.meta.url), 'utf8')

describe('Security product information architecture', () => {
  it('separates low-change classification foundations from sensitive data definitions', () => {
    const router = readSource('../src/router/index.js')
    const layout = readSource('../src/components/Layout.vue')
    const classificationGrading = readSource('../src/views/ClassificationGrading.vue')
    const foundations = readSource('../src/views/FoundationList.vue')
    const definitions = readSource('../src/views/SensitiveDataDefinitions.vue')
    const sensitiveTypes = readSource('../src/views/SensitiveDataTypeList.vue')
    const detectors = readSource('../src/views/DetectorBindings.vue')
    const baselines = readSource('../src/views/ProtectionBaselineBindings.vue')

    expect(router).toContain("path: 'classification-grading'")
    expect(router).toContain("path: 'sensitive-data-definitions'")
    expect(router).toContain("component: () => import('../views/Login.vue')")
    expect(router).toContain("component: () => import('../views/ClassificationGrading.vue')")
    expect(router).toContain("component: () => import('../views/SensitiveDataDefinitions.vue')")
    expect(router).toContain("component: () => import('../views/ProtectionEnrollmentList.vue')")
    expect(router).not.toContain("import Login from '../views/Login.vue'")
    expect(router).not.toContain("import ClassificationGrading from '../views/ClassificationGrading.vue'")
    expect(router).not.toContain("import SensitiveDataDefinitions from '../views/SensitiveDataDefinitions.vue'")
    expect(router).not.toContain("import ProtectionEnrollmentList from '../views/ProtectionEnrollmentList.vue'")
    expect(router).not.toContain("path: 'protection-baselines'")
    expect(router).toContain("redirect: '/sensitive-data-definitions'")
    expect(router).not.toContain("['classifications', 'classification']")
    expect(router).not.toContain("['grades', 'grade']")
    expect(router).not.toContain("['sensitive-data-types', 'sensitiveDataType']")
    expect(layout).toContain('index="/classification-grading"')
    expect(layout).toContain('index="/sensitive-data-definitions"')
    expect(layout).not.toContain('index="/protection-baselines"')
    expect(layout).not.toContain('index="/classifications"')
    expect(layout).not.toContain('index="/grades"')
    expect(layout).not.toContain('index="/sensitive-data-types"')
    expect(classificationGrading).toContain('resolveCanonicalTabRouteState')
    expect(classificationGrading).toContain("defaultTab: 'classifications'")
    expect(classificationGrading).toContain("path: '/classification-grading'")
    expect(classificationGrading).toContain('<FoundationList')
    expect(foundations).toContain('<el-form ref="formRef" :model="form" :rules="formRules"')
    expect(foundations).toContain(':prop="field.key"')
    expect(foundations).toContain(':required="field.required"')
    expect(foundations).toContain('createRequiredRule')
    expect(foundations).toContain('createRequiredNumberRangeRule')
    expect(foundations).toContain('@open="clearDialogValidation"')
    expect(foundations).toContain('@opened="focusDialogPrimaryControl"')
    expect(foundations).toContain('await formRef.value?.validate().catch(() => false)')
    expect(foundations).not.toContain("ElMessage.warning(t('security.common.requiredField'")
    expect(definitions).toContain('<SensitiveDataTypeList />')
    expect(definitions).not.toContain('FoundationList')
    expect(definitions).not.toContain('resolveCanonicalTabRouteState')
    expect(sensitiveTypes).toContain('<DetectorBindings')
    expect(sensitiveTypes).toContain('<ProtectionBaselineBindings')
    expect(sensitiveTypes).toContain('payload.default_protection')
    expect(sensitiveTypes).toContain('<el-form-item :label="t(\'security.fields.keep_prefix\')" prop="default_keep_prefix" required>')
    expect(sensitiveTypes).toContain('<el-form-item :label="t(\'security.fields.keep_suffix\')" prop="default_keep_suffix" required>')
    expect(sensitiveTypes).toContain('<el-form ref="formRef" :model="form" :rules="formRules"')
    expect(sensitiveTypes).toContain('prop="code" required')
    expect(sensitiveTypes).toContain('prop="name" required')
    expect(sensitiveTypes).toContain('prop="security_classification_id" required')
    expect(sensitiveTypes).toContain('prop="default_security_grade_id" required')
    expect(sensitiveTypes).toContain('prop="default_effect" required')
    expect(sensitiveTypes).toContain('prop="default_keep_prefix"')
    expect(sensitiveTypes).toContain('prop="default_invalid_value_effect" required')
    expect(sensitiveTypes).toContain('createRequiredRule')
    expect(sensitiveTypes).toContain('createNonNegativeIntegerRule')
    expect(sensitiveTypes).toContain('await formRef.value?.validate().catch(() => false)')
    expect(sensitiveTypes).not.toContain("ElMessage.warning(t('security.sensitiveType.required'))")
    expect(sensitiveTypes).toContain(':sensitive-type-id="Number(selectedType.id)"')
    expect(sensitiveTypes).toContain('detectorDrawerRevision.value += 1')
    expect(detectors).toContain('detectorCapabilityAPI.list()')
    expect(detectors).toContain('discoveryQualityAPI.get({ sensitive_data_type_id: props.sensitiveTypeId })')
    expect(detectors).toContain('quality.sensitive_confirmation_rate')
    expect(detectors).toContain('security.discoveryQuality.manualSignalsDescription')
    expect(detectors).toContain('security.detector.${action}')
    expect(detectors).toContain('confidence_threshold: form.confidence_percent / 100')
    expect(detectors).toContain('security.detector.parallelHint')
    expect(detectors).toContain('componentProps.capability.method_i18n_key')
    expect(detectors).toContain('componentProps.capability.privacy_i18n_key')
    expect(detectors).toContain('componentProps.capability.limitations_i18n_key')
    expect(detectors).toContain('<el-form ref="formRef" :model="form" :rules="formRules"')
    expect(detectors).toContain('prop="capability_key" required')
    expect(detectors).toContain('prop="confidence_percent" required')
    expect(detectors).toContain('createRequiredRule')
    expect(detectors).toContain('createRequiredNumberRangeRule')
    expect(detectors).not.toContain("Number.isFinite(value) && value >= 1 && value <= 100")
    expect(detectors).toContain('@open="clearDialogValidation"')
    expect(detectors).toContain('@opened="focusDialogPrimaryControl"')
    expect(detectors).toContain('await formRef.value?.validate().catch(() => false)')
    expect(detectors).not.toContain("ElMessage.warning(t('security.detector.required'))")
    expect(baselines).toContain('security.baseline.mappingHint')
    expect(baselines).toContain('isInitialBaseline(row)')
    expect(baselines).toContain('security.baseline.effectImpactTitle')
    expect(baselines).toContain('security.baseline.effectImpact.${form.effect}')
    expect(baselines).toContain("algorithm: mask ? 'addp.mask.keep_prefix_suffix/v2' : ''")
    expect(baselines).toContain('<el-form-item :label="t(\'security.fields.keep_prefix\')" prop="keep_prefix" required>')
    expect(baselines).toContain('<el-form-item :label="t(\'security.fields.keep_suffix\')" prop="keep_suffix" required>')
    expect(baselines).toContain('<el-form ref="formRef" :model="form" :rules="formRules"')
    expect(baselines).toContain('prop="security_grade_id" required')
    expect(baselines).toContain('prop="effect" required')
    expect(baselines).toContain('prop="keep_prefix"')
    expect(baselines).toContain('prop="invalid_value_effect" required')
    expect(baselines).toContain('createRequiredRule')
    expect(baselines).toContain('createNonNegativeIntegerRule')
    expect(baselines).toContain('await formRef.value?.validate().catch(() => false)')
    expect(baselines).not.toContain("ElMessage.warning(t('security.baseline.required'))")
    expect(baselines).not.toContain('keep_prefix_suffix/v1')
    expect(baselines).not.toContain('form.keep_prefix + form.keep_suffix >= 11')
    expect(baselines).not.toContain(':max="10"')
  })

  it('uses user-facing names and relation selectors instead of numeric IDs', () => {
    const zhCn = JSON.parse(readSource('../src/i18n/zh-cn.json'))
    const en = JSON.parse(readSource('../src/i18n/en.json'))
    const sensitiveTypes = readSource('../src/views/SensitiveDataTypeList.vue')

    expect(zhCn.security.resources.classificationGrading).toBe('分类分级体系')
    expect(zhCn.security.resources.sensitiveDataDefinition).toBe('敏感数据定义')
    expect(zhCn.security.resources.protectionEnrollment).toBe('受保护资源')
    expect(zhCn.security.fields.security_classification_id).toBe('所属分类')
    expect(zhCn.security.fields.default_security_grade_id).toBe('自动发现初始等级')
    expect(zhCn.security.fields.invalid_value_effect).toBe('不符合格式时')
    expect(zhCn.security.baseline.effectImpact.mask).toContain('保留字段结构')
    expect(zhCn.security.baseline.effectImpact.suppress).toContain('删除该字段及其值')
    expect(zhCn.security.baseline.effectImpact.deny).toContain('拒绝整个数据请求')
    expect(zhCn.security.options.effects.suppress).toBe('移除字段')
    expect(zhCn.security.enrollment.effects.suppress).toBe('移除')
    expect(zhCn.security.sensitiveType.required).toBeUndefined()
    expect(zhCn.security.baseline.required).toBeUndefined()
    expect(JSON.stringify(zhCn)).not.toContain('抑制字段')
    expect(en.security.options.effects.suppress).toBe('Remove field')
    expect(en.security.enrollment.effects.suppress).toBe('Remove')
    expect(en.security.sensitiveType.required).toBeUndefined()
    expect(en.security.baseline.required).toBeUndefined()
    expect(zhCn.security.detector.required).toBeUndefined()
    expect(zhCn.security.detector.confidenceThresholdRange).toContain('1% 到 100%')
    expect(en.security.detector.required).toBeUndefined()
    expect(en.security.detector.confidenceThresholdRange).toContain('1% to 100%')
    expect(sensitiveTypes).toContain('form.security_classification_id')
    expect(sensitiveTypes).toContain('form.default_security_grade_id')
    expect(sensitiveTypes).not.toContain('protection_threshold')
    expect(zhCn.security.detectorCapabilities.phoneMetadata.method).toContain('末级名称')
    expect(zhCn.security.detectorCapabilities.phoneMetadata.limitations).toContain('不能验证字段中的值')
    expect(zhCn.security.detectorCapabilities.emailMetadata.method).toContain('emailaddress')
    expect(zhCn.security.detectorCapabilities.emailMetadata.limitations).toContain('email_verified')
    expect(zhCn.security.detectorCapabilities.identityDocumentNumberMetadata.name).toContain('身份证件号码')
    expect(zhCn.security.detectorCapabilities.identityDocumentNumberMetadata.method).toContain('identitydocumentnumber')
    expect(zhCn.security.detectorCapabilities.identityDocumentNumberMetadata.privacy).toContain('不读取、保存或记录证件号码')
    expect(zhCn.security.detectorCapabilities.identityDocumentNumberMetadata.limitations).toContain('user_id')
    expect(zhCn.security.detectorCapabilities.phoneDocument.privacy).toContain('不保存或记录原始号码')
    expect(zhCn.security.discoveryQuality.insufficientSamples).toBe('样本不足')
    expect(zhCn.security.discoveryQuality.manualSignalsDescription).toContain('不能直接归因')
  })

  it('uses one safe confirmation contract for every destructive definition deletion', () => {
    const confirmation = readSource('../src/utils/confirmation.mjs')
    const deletionSurfaces = [
      readSource('../src/views/FoundationList.vue'),
      readSource('../src/views/SensitiveDataTypeList.vue'),
      readSource('../src/views/DetectorBindings.vue'),
      readSource('../src/views/ProtectionBaselineBindings.vue')
    ]

    expect(confirmation).toContain("customClass: 'addp-message-box'")
    expect(confirmation).toContain("confirmButtonClass: 'el-button--danger'")
    expect(confirmation).toContain('autofocus: false')
    expect(confirmation).toContain("querySelectorAll('.el-message-box__btns button')")
    expect(confirmation).toContain("!button.classList.contains('el-button--danger')")

    for (const surface of deletionSurfaces) {
      expect(surface).toContain('confirmDangerousAction(ElMessageBox.confirm')
      expect(surface).toContain("confirmButtonText: t('security.common.delete')")
      expect(surface).toContain("cancelButtonText: t('security.common.cancel')")
    }
  })

  it('re-enrolls released resources through a new enrollment lifecycle', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')
    const api = readSource('../src/api/security.js')
    const zhCn = JSON.parse(readSource('../src/i18n/zh-cn.json'))

    expect(api).toContain('/re-enrollments`')
    expect(enrollment).toContain("row.state === 'released'")
    expect(enrollment).toContain('@click="openReEnrollment(row)"')
    expect(enrollment).toContain('reloadReEnrollmentBaseline')
    expect(enrollment).toContain(':disabled="reEnrollmentConflict"')
    expect(enrollment).toContain('protectionEnrollmentAPI.get(reEnrollmentSource.value.id)')
    expect(enrollment).toContain('result.source_enrollment_version')
    expect(enrollment).toContain("listScope.value = 'current'")
    expect(zhCn.security.enrollment.reEnroll).toBe('重新纳入')
    expect(zhCn.security.enrollment.reEnrollWarning).toContain('新的保护记录')
    expect(zhCn.security.enrollment.reEnrollWarning).toContain('原退出记录')
    expect(zhCn.security.enrollment.reEnrollmentVersionConflict).toContain('重新纳入意图已保留')
    expect(zhCn.security.enrollment.enrollmentAlreadyActive).toContain('已切换到当前受保护资源')
  })

  it('validates every required protected-resource action field inline', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')
    const accessRequestDecisionForm = readSource('../src/components/protection-enrollment/AccessRequestDecisionForm.vue')
    const findingReviewForm = readSource('../src/components/protection-enrollment/FindingReviewForm.vue')
    const protectionPolicyForm = readSource('../src/components/protection-enrollment/ProtectionPolicyForm.vue')
    const formSurfaces = [enrollment, accessRequestDecisionForm, findingReviewForm, protectionPolicyForm].join('\n')
    const localeMessages = [
      JSON.parse(readSource('../src/i18n/zh-cn.json')),
      JSON.parse(readSource('../src/i18n/en.json'))
    ]

    for (const formName of [
      'accessRequestDecision',
      'review',
      'manualAssessment',
      'assessmentRevision',
      'assessmentRevoke',
      'exemptionRevoke',
      'policy',
      'policyRestore',
      'release'
    ]) {
      expect(enrollment).toContain(`ref="${formName}FormRef"`)
      expect(enrollment).toContain(`:rules="${formName}Rules"`)
      expect(enrollment).toContain(`validateRequiredForm(${formName}FormRef)`)
    }

    expect(formSurfaces).toContain('prop="componentKey" required')
    expect(formSurfaces).toContain('prop="sensitiveDataTypeID" required')
    expect(formSurfaces).toContain('prop="securityGradeID" required')
    expect(formSurfaces).toContain('prop="effect" required')
    expect(formSurfaces).toContain('prop="reason" required')
    expect(enrollment).toContain('ref="createFormRef"')
    expect(enrollment).toContain(':rules="createFormRules"')
    expect(enrollment).toContain('class="enrollment-resource-field"')
    expect(enrollment).toContain('prop="resource" required')
    expect(enrollment).toContain('await createFormRef.value?.validate().catch(() => false)')
    expect(enrollment).toContain("createRequiredRule(t('security.common.requiredField'")
    expect(enrollment).toContain("defineAsyncComponent(() => import('../components/protection-enrollment/AccessRequestDecisionForm.vue'))")
    expect(enrollment).toContain("defineAsyncComponent(() => import('../components/protection-enrollment/FindingReviewForm.vue'))")
    expect(enrollment).toContain("defineAsyncComponent(() => import('../components/protection-enrollment/ProtectionPolicyForm.vue'))")
    expect(enrollment).toContain('<AccessRequestDecisionForm')
    expect(enrollment).toContain('<FindingReviewForm')
    expect(enrollment).toContain('<ProtectionPolicyForm')
    expect(enrollment).not.toContain('<el-form ref="accessRequestDecisionFormRef"')
    expect(enrollment).not.toContain('<el-form ref="reviewFormRef"')
    expect(enrollment).not.toContain('<el-form ref="policyFormRef"')
    expect(accessRequestDecisionForm).toContain('defineExpose({ validate, clearValidate })')
    expect(findingReviewForm).toContain('defineExpose({ validate, focusRationale })')
    expect(protectionPolicyForm).toContain('defineExpose({ validate, clearValidate })')
    expect(enrollment).not.toContain("ElMessage.warning(t('security.enrollment.resourceRequired'))")
    expect(enrollment).not.toContain("ElMessage.warning(t('security.accessRequest.decisionRationaleRequired'))")
    expect(enrollment).not.toContain("ElMessage.warning(t('security.finding.rationaleRequired'))")
    expect(enrollment).not.toContain("ElMessage.warning(t('security.finding.adjustmentRequired'))")
    expect(enrollment).not.toContain("ElMessage.warning(t('security.assessment.required'))")
    expect(enrollment).not.toContain("ElMessage.warning(t('security.assessment.revisionRequired'))")
    expect(enrollment).not.toContain("ElMessage.warning(t('security.assessment.revokeRationaleRequired'))")
    expect(enrollment).not.toContain("ElMessage.warning(t('security.exemption.rationaleRequired'))")
    expect(enrollment).not.toContain("ElMessage.warning(t('security.policy.required'))")
    expect(enrollment).not.toContain("ElMessage.warning(t('security.policy.rationaleRequired'))")
    expect(enrollment).not.toContain("ElMessage.warning(t('security.enrollment.releaseReasonRequired'))")

    for (const messages of localeMessages) {
      expect(messages.security.common.requiredField).toBeTruthy()
      expect(messages.security.accessRequest.decisionRationaleRequired).toBeUndefined()
      expect(messages.security.finding.rationaleRequired).toBeUndefined()
      expect(messages.security.finding.adjustmentRequired).toBeUndefined()
      expect(messages.security.assessment.required).toBeUndefined()
      expect(messages.security.assessment.revisionRequired).toBeUndefined()
      expect(messages.security.assessment.revokeRationaleRequired).toBeUndefined()
      expect(messages.security.exemption.rationaleRequired).toBeUndefined()
      expect(messages.security.policy.required).toBeUndefined()
      expect(messages.security.policy.rationaleRequired).toBeUndefined()
      expect(messages.security.enrollment.releaseReasonRequired).toBeUndefined()
    }
  })

  it('recovers an enrollment release only after an explicit latest-state reload', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')
    const zhCn = JSON.parse(readSource('../src/i18n/zh-cn.json'))

    expect(enrollment).toContain('isResourceVersionConflict(error)')
    expect(enrollment).toContain('isNoSupportedFindingsReleaseUnavailable(error)')
    expect(enrollment).toContain('reloadReleaseBaseline')
    expect(enrollment).toContain(':disabled="releaseConflict"')
    expect(enrollment).toContain('<el-form-item :label="t(\'security.enrollment.releaseReasonLabel\')" prop="reason" required>')
    expect(enrollment).toContain('protectionEnrollmentAPI.get(releasing.value.id)')
    expect(zhCn.security.enrollment.releaseVersionConflict).toContain('退出依据和原因已保留')
    expect(zhCn.security.enrollment.reloadLatestForRelease).toBe('放弃当前输入并加载最新受保护资源')
  })

  it('reconfirms rediscovery only after explicitly loading the latest enrollment', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')
    const zhCn = JSON.parse(readSource('../src/i18n/zh-cn.json'))

    expect(enrollment).toContain('@click="openRediscovery(detailRow)"')
    expect(enrollment).toContain('reloadRediscoveryBaseline')
    expect(enrollment).toContain(':disabled="rediscoveryConflict"')
    expect(enrollment).toContain('protectionEnrollmentAPI.get(rediscoveryEnrollment.value.id)')
    expect(enrollment).toContain('execution?.enrollment_version')
    expect(zhCn.security.enrollment.rediscoveryVersionConflict).toContain('重新发现意图已保留')
    expect(zhCn.security.enrollment.discoveryExecutionInProgress).toContain('正在等待或执行')
  })

  it('only presents components that remain eligible for manual designation', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')

    expect(enrollment).toContain('v-for="option in componentOptions"')
    expect(enrollment).not.toContain(':disabled="Boolean(option.assessment_id)"')
  })

  it('renders the backend-provided finding explanation as one control flow', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')
    const findingList = readSource('../src/components/protection-enrollment/EnrollmentFindingList.vue')
    const zhCn = JSON.parse(readSource('../src/i18n/zh-cn.json'))

    expect(enrollment).toContain("defineAsyncComponent(() => import('../components/protection-enrollment/EnrollmentFindingList.vue'))")
    expect(findingList).toContain("security.finding.explanationStages.detection")
    expect(findingList).toContain("security.finding.explanationStages.governance")
    expect(findingList).toContain("security.finding.explanationStages.execution")
    expect(findingList).toContain('finding.explanation.outlets')
    expect(findingList).toContain(':icon="QuestionFilled"')
    expect(findingList).toContain('<el-popover')
    expect(findingList).toContain('trigger="click"')
    expect(findingList).toContain('<dl class="recognition-rule-details">')
    expect(findingList).toContain('security.finding.ruleAudit.viewDetails')
    expect(findingList).toContain('container: finding-card / inline-size')
    expect(findingList).toContain('@container finding-card (max-width: 920px)')
    expect(findingList).toContain('.explanation-stage:nth-child(3)')
    expect(findingList).toContain("capabilityText(finding, 'method_i18n_key')")
    expect(zhCn.security.finding.ruleAudit.details).toBe('识别说明')
    expect(zhCn.security.finding.ruleAudit.viewDetails).toBe('查看识别说明')
    expect(zhCn.security.finding.ruleAudit.viewMethod).toBeUndefined()
    expect(findingList).not.toContain('finding.detector_version }}</el-descriptions-item>')
    expect(zhCn.security.finding.explanationStages.execution).toBe('出口规则')
    expect(zhCn.security.finding.outletAcknowledged).toBe('已同步')
    expect(zhCn.security.finding.outletWaiting).toBe('待同步')
  })

  it('keeps protected-resource detail rendering in async domain components', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')
    const assessmentList = readSource('../src/components/protection-enrollment/EnrollmentAssessmentList.vue')
    const exemptionSection = readSource('../src/components/protection-enrollment/EnrollmentExemptionSection.vue')

    expect(enrollment).toContain("defineAsyncComponent(() => import('../components/protection-enrollment/EnrollmentAssessmentList.vue'))")
    expect(enrollment).toContain("defineAsyncComponent(() => import('../components/protection-enrollment/EnrollmentExemptionSection.vue'))")
    expect(enrollment).toContain('<EnrollmentAssessmentList')
    expect(enrollment).toContain('<EnrollmentExemptionSection')
    expect(enrollment).not.toContain('class="finding-card"')
    expect(enrollment).not.toContain('class="manual-assessment-card"')
    expect(enrollment).not.toContain('class="exemption-card"')
    expect(assessmentList).toContain('class="manual-assessment-card"')
    expect(exemptionSection).toContain('class="exemption-card"')
    expect(exemptionSection).toContain('defineExpose({ focusFocused })')
  })

  it('keeps the pending review queue as a recoverable subview of protected resources', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')
    const reviewForm = readSource('../src/components/protection-enrollment/FindingReviewForm.vue')
    const zhCn = JSON.parse(readSource('../src/i18n/zh-cn.json'))

    expect(enrollment).toContain("WORKSPACE_TABS = ['resources', 'review-queue']")
    expect(enrollment).toContain("snapshot_scope: 'current'")
    expect(enrollment).toContain("review_state: 'pending'")
    expect(enrollment).toContain('resolveCanonicalTabRouteState')
    expect(enrollment).toContain('resolveReviewQueueFilters')
    expect(enrollment).toContain('nextQueueReviewFinding')
    expect(enrollment).toContain('nextDetailReviewFinding')
    expect(enrollment).toContain('security.finding.reviewSavedAndContinued')
    expect(enrollment).toContain('security.finding.reviewRemainingQueue')
    expect(enrollment).toContain('security.finding.reviewRemainingResource')
    expect(enrollment).toContain("defineAsyncComponent(() => import('../components/protection-enrollment/FindingReviewForm.vue'))")
    expect(enrollment).toContain('v-model:basis-expanded="reviewBasisExpanded"')
    expect(reviewForm).toContain('security.finding.reviewBasis.actualMatch')
    expect(reviewForm).toContain('evidenceAuditDescription(finding)')
    expect(reviewForm).toContain('outletRuleDescription(finding, outlet.consumer_owner)')
    expect(enrollment).toContain('findingAPI.review(reviewedFinding.id, payload)')
    expect(zhCn.security.enrollment.workspaces.reviewQueue).toBe('待复核候选')
    expect(zhCn.security.reviewQueue.description).toContain('提交复核后候选会自动移出')
    expect(zhCn.security.finding.reviewRemainingQueue).toContain('当前筛选')
    expect(zhCn.security.finding.reviewRemainingResource).toContain('当前资源')
    expect(zhCn.security.finding.reviewBasis.title).toBe('判定依据')
    expect(zhCn.security.finding.reviewBasis.currentEnforcement).toBe('当前出口规则')
  })

  it('presents owner acknowledgement as synchronized rules rather than request execution', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')
    const zhCn = JSON.parse(readSource('../src/i18n/zh-cn.json'))
    const en = JSON.parse(readSource('../src/i18n/en.json'))

    expect(zhCn.security.enrollment.progress).toBe('保护规则同步')
    expect(zhCn.security.enrollment.ownerStates.active).toBe('字段规则已同步')
    expect(zhCn.security.enrollment.states.active).toBe('保护规则同步完成')
    expect(zhCn.security.enrollment.stateDescriptions.active).toContain('具体请求仍按运行时能力执行或保守拒绝')
    expect(zhCn.security.enrollment.ownerProtectionHint).toContain('已同步表示 Owner 已持久保存当前保护投影')
    expect(zhCn.security.enrollment.ownerEffectRequirements).toBe('已同步规则：{rules}')
    expect(en.security.enrollment.ownerStates.active).toBe('Field rules synchronized')
    expect(en.security.enrollment.ownerProtectionHint).toContain('Each request still validates')
    expect(enrollment).toContain("security.enrollment.ownerProtectionHint")
    expect(enrollment).toContain("security.enrollment.ownerEffectRequirements")
    expect(enrollment).toContain('Array.isArray(owner.rules)')
    expect(enrollment).not.toContain('Array.isArray(owner.effects)')
    expect(zhCn.security.enrollment.stateDescriptions.active).not.toContain('均已执行字段级保护')
  })

  it('keeps plaintext access on the request and approval route only', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')
    const reviewWorkspace = readSource('../src/components/protection-enrollment/AccessRequestReviewWorkspace.vue')
    const exemptionSection = readSource('../src/components/protection-enrollment/EnrollmentExemptionSection.vue')
    const api = readSource('../src/api/security.js')
    const zhCn = JSON.parse(readSource('../src/i18n/zh-cn.json'))

    expect(enrollment).toContain('protectionAccessRequestAPI.reviewQueue')
    expect(enrollment).toContain('protectionAccessRequestAPI.decide')
    expect(enrollment).toContain("defineAsyncComponent(() => import('../components/protection-enrollment/AccessRequestReviewWorkspace.vue'))")
    expect(enrollment).toContain('<AccessRequestReviewWorkspace')
    expect(enrollment).not.toContain('class="access-review-card"')
    expect(reviewWorkspace).toContain('class="access-review-card"')
    expect(enrollment).toContain('v-model="accessRequestDecisionDialog"')
    expect(enrollment).toContain('@decide="openAccessRequestDecision"')
    expect(reviewWorkspace).toContain("emit('decide', row, 'approve')")
    expect(reviewWorkspace).toContain("emit('decide', row, 'reject')")
    expect(enrollment).toContain('accessRequestDecisionConflict')
    expect(enrollment).toContain('reloadAccessRequestDecisionBaseline')
    expect(enrollment).toContain(':disabled="accessRequestDecisionConflict"')
    expect(enrollment).toContain('submitAccessRequestDecision')
    expect(enrollment).toContain("latest?.state !== 'pending' || !latest.can_decide")
    expect(enrollment).toContain('isProtectionAccessRequestExpired(error)')
    expect(enrollment).not.toContain('ElMessageBox.prompt')
    expect(api).toContain('client.get(`/security/protection-access-requests/${id}`)')
    expect(reviewWorkspace).toContain('row.can_decide')
    expect(reviewWorkspace).toContain('v-else-if="row.decision_unavailable_reason"')
    expect(enrollment).toContain('security.accessRequest.confirmActions.${accessRequestDecision}')
    expect(enrollment).toContain('scope: accessRequestScope.value')
    expect(enrollment).toContain('authorization_state: accessRequestScope.value')
    expect(enrollment).toContain('requester_search: accessRequestFilters.requesterSearch')
    expect(enrollment).toContain('resource_search: accessRequestFilters.resourceSearch')
    expect(enrollment).toContain('created_from: range[0] instanceof Date')
    expect(enrollment).toContain('created_to: range[1] instanceof Date')
    expect(enrollment).toContain('v-model:page="accessRequestPage"')
    expect(enrollment).toContain('v-model:page-size="accessRequestPageSize"')
    expect(reviewWorkspace).toContain("scope === 'pending'")
    expect(reviewWorkspace).toContain("scope === 'history'")
    expect(reviewWorkspace).toContain('row.decision_rationale')
    expect(reviewWorkspace).toContain('row.requester?.display_name')
    expect(reviewWorkspace).toContain('row.reviewer.display_name')
    expect(reviewWorkspace).toContain('row.authorization_state')
    expect(reviewWorkspace).toContain('row.authorized_until')
    expect(reviewWorkspace).toContain('row.enrollment_id')
    expect(reviewWorkspace).toContain("emit('openAuthorization', row)")
    expect(enrollment).toContain('openAccessRequestAuthorization(row)')
    expect(enrollment).toContain("await openDetail(enrollment, row.exemption_id)")
    expect(enrollment).toContain(':focused-exemption-id="focusedExemptionID"')
    expect(exemptionSection).toContain("String(exemption.id) === String(focusedExemptionId)")
    expect(enrollment).toContain('v-model="exemptionRevokeDialog"')
    expect(enrollment).toContain('@revoke="openExemptionRevoke"')
    expect(exemptionSection).toContain("emit('revoke', exemption)")
    expect(enrollment).toContain('exemptionRevokeConflict')
    expect(enrollment).toContain('reloadExemptionRevokeBaseline')
    expect(enrollment).toContain(':disabled="exemptionRevokeConflict"')
    expect(enrollment).toContain('submitExemptionRevoke')
    expect(enrollment).toContain("latest?.effective_state !== 'active'")
    expect(enrollment).not.toContain("t('security.exemption.revokePrompt'")
    expect(api).toContain('client.get(`/security/protection-exemptions/${id}`)')
    expect(reviewWorkspace).toContain('authorizationStateType')
    expect(reviewWorkspace).toContain('releaseActorLabel(row.requester?.id)')
    expect(reviewWorkspace).toContain('releaseActorLabel(row.reviewer.id)')
    expect(reviewWorkspace).not.toContain('row.decided_by')
    expect(zhCn.security.accessRequest.unavailableReasons.self_approval_forbidden).toBe('需由另一名审批人处理')
    expect(zhCn.security.accessRequest.scopes.pending).toBe('待审批')
    expect(zhCn.security.accessRequest.scopes.history).toBe('审批记录')
    expect(zhCn.security.accessRequest.filters.resourcePlaceholder).toContain('资源')
    expect(zhCn.security.accessRequest.filters.requesterPlaceholder).toContain('用户 ID')
    expect(zhCn.security.accessRequest.filters.allAuthorizationStates).toBe('全部授权状态')
    expect(zhCn.security.accessRequest.createdAt).toBe('申请时间')
    expect(zhCn.security.accessRequest.authorizationState).toBe('当前授权')
    expect(zhCn.security.accessRequest.authorizationStates.active).toBe('生效中')
    expect(zhCn.security.accessRequest.authorizationStates.not_granted).toBe('未产生授权')
    expect(zhCn.security.accessRequest.viewAuthorization).toBe('查看授权')
    expect(zhCn.security.accessRequest.approveHint).toContain('当前字段和数据预览出口')
    expect(zhCn.security.accessRequest.rejectHint).toContain('审批结论不可反转')
    expect(zhCn.security.accessRequest.decisionVersionConflict).toContain('当前审批动作和意见已保留')
    expect(zhCn.security.accessRequest.reloadLatestForDecision).toContain('放弃当前输入')
    expect(zhCn.security.accessRequest.expiredBeforeDecision).toContain('已过期')
    expect(zhCn.security.exemption.revokeHint).toContain('立即恢复执行当前字段保护规则')
    expect(zhCn.security.exemption.revokeVersionConflict).toContain('当前撤销依据已保留')
    expect(zhCn.security.exemption.reloadLatestForRevoke).toContain('放弃当前输入')
    expect(zhCn.security.exemption.alreadyInactive).toContain('无需重复撤销')
    expect(enrollment).not.toContain('openCreateExemption')
    expect(enrollment).not.toContain('openRenewExemption')
    expect(api).not.toContain('protectionExemptionAPI.create')
    expect(api).not.toContain('protectionExemptionAPI.renew')
    expect(zhCn.security.exemption.title).toBe('临时原值授权')
  })

  it('keeps resource-specific tightening inside protected resources', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')
    const api = readSource('../src/api/security.js')
    const zhCn = JSON.parse(readSource('../src/i18n/zh-cn.json'))

    expect(enrollment).toContain("protectionPolicyAPI.list({ enrollment_id: row.id")
    expect(enrollment).toContain("consumer_owner: 'manager'")
    expect(enrollment).toContain("action: 'preview'")
    expect(enrollment).toContain('stricterPolicyEffects(policyAssessment)')
    expect(enrollment).toContain('policyVersionConflict')
    expect(enrollment).toContain('reloadPolicyBaseline')
    expect(enrollment).toContain(':disabled="policyVersionConflict"')
    expect(enrollment).toContain('@open="clearPolicyValidation"')
    expect(enrollment).not.toContain('@opened="clearPolicyValidation"')
    expect(enrollment).toContain('protectionPolicyAPI.get(policy.id)')
    expect(enrollment).toContain('assessmentAPI.get(assessment.id)')
    expect(enrollment).toContain('protectionBaselineAPI.list()')
    expect(enrollment).toContain('v-model="policyRestoreDialog"')
    expect(enrollment).toContain('openPolicyRestore(assessment)')
    expect(enrollment).toContain('policyRestoreConflict')
    expect(enrollment).toContain('reloadPolicyRestoreBaseline')
    expect(enrollment).toContain(':disabled="policyRestoreConflict"')
    expect(enrollment).toContain('submitPolicyRestore')
    expect(enrollment).not.toContain("t('security.policy.restorePrompt'")
    expect(enrollment).toContain('activeGradesForType(manualAssessmentForm.sensitiveDataTypeID)')
    expect(api).toContain("client.post('/security/protection-policies'")
    expect(api).toContain('client.get(`/security/protection-policies/${id}`)')
    expect(zhCn.security.policy.hint).toContain('不能放宽')
    expect(zhCn.security.policy.hint).toContain('申请与审批')
    expect(zhCn.security.policy.versionConflict).toContain('当前选择和依据已保留')
    expect(zhCn.security.policy.reloadLatest).toContain('放弃当前输入')
    expect(zhCn.security.policy.restoreHint).toContain('回落到当前默认保护')
    expect(zhCn.security.policy.restoreVersionConflict).toContain('当前恢复依据已保留')
    expect(zhCn.security.policy.reloadLatestForRestore).toContain('放弃当前输入')
  })

  it('revises every formal assessment through the protected-resource aggregate', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')
    const findingList = readSource('../src/components/protection-enrollment/EnrollmentFindingList.vue')
    const assessmentList = readSource('../src/components/protection-enrollment/EnrollmentAssessmentList.vue')
    const api = readSource('../src/api/security.js')
    const zhCn = JSON.parse(readSource('../src/i18n/zh-cn.json'))

    expect(enrollment).toContain('@revise="openAssessmentRevision"')
    expect(enrollment).toContain('@history="openAssessmentHistory"')
    expect(findingList).toContain("emit('revise', assessmentForFinding(finding))")
    expect(findingList).toContain("emit('history', assessmentForFinding(finding))")
    expect(assessmentList).toContain("emit('revise', assessment)")
    expect(assessmentList).toContain("emit('history', assessment)")
    expect(enrollment).toContain('assessmentHistory.history')
    expect(enrollment).toContain('isCurrentAssessmentRevision(revision)')
    expect(enrollment).toContain('assessmentRevisionConflict')
    expect(enrollment).toContain('reloadAssessmentRevisionBaseline')
    expect(enrollment).toContain(':disabled="assessmentRevisionConflict"')
    expect(enrollment).toContain('v-model="assessmentRevokeDialog"')
    expect(enrollment).toContain('@revoke="openAssessmentRevoke"')
    expect(assessmentList).toContain("emit('revoke', assessment)")
    expect(enrollment).toContain('assessmentRevokeConflict')
    expect(enrollment).toContain('reloadAssessmentRevokeBaseline')
    expect(enrollment).toContain(':disabled="assessmentRevokeConflict"')
    expect(enrollment).toContain('submitAssessmentRevoke')
    expect(enrollment).toContain("latest?.current?.conclusion !== 'sensitive'")
    expect(enrollment).not.toContain("t('security.assessment.revokePrompt'")
    expect(enrollment).toContain('activeGradesForType(assessmentRevisionForm.sensitiveDataTypeID)')
    expect(enrollment).toContain('version: revisingAssessment.value.version')
    expect(enrollment).toContain('assessmentAPI.revise(revisingAssessment.value.id')
    expect(api).toContain('client.post(`/security/assessments/${id}/revisions`')
    expect(api).toContain('client.get(`/security/assessments/${id}`)')
    expect(api).not.toContain('client.put(`/security/assessments/${id}`')
    expect(zhCn.security.assessment.reviseConclusion).toBe('调整结论')
    expect(zhCn.security.assessment.history).toBe('修订记录')
    expect(zhCn.security.assessment.historyHint).toContain('不可变修订')
    expect(zhCn.security.assessment.versionConflict).toContain('当前输入已保留')
    expect(zhCn.security.assessment.reloadLatest).toContain('放弃当前输入')
    expect(zhCn.security.assessment.revokeHint).toContain('不可变的非敏感结论')
    expect(zhCn.security.assessment.revokeVersionConflict).toContain('当前撤销依据已保留')
    expect(zhCn.security.assessment.reloadLatestForRevoke).toContain('放弃当前输入')
    expect(zhCn.security.assessment.alreadyRevoked).toContain('无需重复操作')
    expect(zhCn.security.assessment.reviseHint).toContain('不可变修订')
    expect(zhCn.security.assessment.reviseHint).toContain('重新编译各数据出口规则')
  })
})
