import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'

const readSource = relativePath => readFileSync(new URL(relativePath, import.meta.url), 'utf8')

describe('Security product information architecture', () => {
  it('separates low-change classification foundations from sensitive data definitions', () => {
    const router = readSource('../src/router/index.js')
    const layout = readSource('../src/components/Layout.vue')
    const classificationGrading = readSource('../src/views/ClassificationGrading.vue')
    const definitions = readSource('../src/views/SensitiveDataDefinitions.vue')
    const sensitiveTypes = readSource('../src/views/SensitiveDataTypeList.vue')
    const detectors = readSource('../src/views/DetectorBindings.vue')
    const baselines = readSource('../src/views/ProtectionBaselineList.vue')

    expect(router).toContain("path: 'classification-grading'")
    expect(router).toContain("path: 'sensitive-data-definitions'")
    expect(router).toContain("redirect: '/sensitive-data-definitions'")
    expect(router).not.toContain("['classifications', 'classification']")
    expect(router).not.toContain("['grades', 'grade']")
    expect(router).not.toContain("['sensitive-data-types', 'sensitiveDataType']")
    expect(layout).toContain('index="/classification-grading"')
    expect(layout).toContain('index="/sensitive-data-definitions"')
    expect(layout).not.toContain('index="/classifications"')
    expect(layout).not.toContain('index="/grades"')
    expect(layout).not.toContain('index="/sensitive-data-types"')
    expect(classificationGrading).toContain('resolveCanonicalTabRouteState')
    expect(classificationGrading).toContain("defaultTab: 'classifications'")
    expect(classificationGrading).toContain("path: '/classification-grading'")
    expect(classificationGrading).toContain('<FoundationList')
    expect(definitions).toContain('<SensitiveDataTypeList />')
    expect(definitions).not.toContain('FoundationList')
    expect(definitions).not.toContain('resolveCanonicalTabRouteState')
    expect(sensitiveTypes).toContain('<DetectorBindings')
    expect(sensitiveTypes).toContain(':sensitive-type-id="Number(selectedType.id)"')
    expect(sensitiveTypes).toContain('detectorDrawerRevision.value += 1')
    expect(detectors).toContain('detectorCapabilityAPI.list()')
    expect(detectors).toContain('discoveryQualityAPI.get({ sensitive_data_type_id: props.sensitiveTypeId })')
    expect(detectors).toContain('quality.sensitive_confirmation_rate')
    expect(detectors).toContain('security.discoveryQuality.manualSignalsDescription')
    expect(detectors).toContain('security.detector.${action}')
    expect(detectors).toContain('confidence_threshold: form.confidence_percent / 100')
    expect(detectors).toContain('security.detector.parallelHint')
    expect(detectors).toContain('componentProps.capability.method_i18n_key')
    expect(detectors).toContain('componentProps.capability.privacy_i18n_key')
    expect(detectors).toContain('componentProps.capability.limitations_i18n_key')
    expect(baselines).toContain('security.baseline.mappingHint')
  })

  it('uses user-facing names and relation selectors instead of numeric IDs', () => {
    const zhCn = JSON.parse(readSource('../src/i18n/zh-cn.json'))
    const sensitiveTypes = readSource('../src/views/SensitiveDataTypeList.vue')

    expect(zhCn.security.resources.classificationGrading).toBe('分类分级体系')
    expect(zhCn.security.resources.sensitiveDataDefinition).toBe('敏感数据定义')
    expect(zhCn.security.resources.protectionBaseline).toBe('默认保护规则')
    expect(zhCn.security.resources.protectionEnrollment).toBe('受保护资源')
    expect(zhCn.security.fields.security_classification_id).toBe('所属分类')
    expect(zhCn.security.fields.default_security_grade_id).toBe('自动发现初始等级')
    expect(zhCn.security.fields.invalid_value_effect).toBe('不符合格式时')
    expect(sensitiveTypes).toContain('form.security_classification_id')
    expect(sensitiveTypes).toContain('form.default_security_grade_id')
    expect(sensitiveTypes).not.toContain('protection_threshold')
    expect(zhCn.security.detectorCapabilities.phoneMetadata.method).toContain('末级名称')
    expect(zhCn.security.detectorCapabilities.phoneMetadata.limitations).toContain('不能验证字段中的值')
    expect(zhCn.security.detectorCapabilities.emailMetadata.method).toContain('emailaddress')
    expect(zhCn.security.detectorCapabilities.emailMetadata.limitations).toContain('email_verified')
    expect(zhCn.security.detectorCapabilities.phoneDocument.privacy).toContain('不保存或记录原始号码')
    expect(zhCn.security.discoveryQuality.insufficientSamples).toBe('样本不足')
    expect(zhCn.security.discoveryQuality.manualSignalsDescription).toContain('不能直接归因')
  })

  it('re-enrolls released resources through a new enrollment lifecycle', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')
    const api = readSource('../src/api/security.js')
    const zhCn = JSON.parse(readSource('../src/i18n/zh-cn.json'))

    expect(api).toContain('/re-enrollments`')
    expect(enrollment).toContain("row.state === 'released'")
    expect(enrollment).toContain('protectionEnrollmentAPI.reEnroll(row.id')
    expect(enrollment).toContain("listScope.value = 'current'")
    expect(zhCn.security.enrollment.reEnroll).toBe('重新纳入')
    expect(zhCn.security.enrollment.reEnrollWarning).toContain('新的保护记录')
    expect(zhCn.security.enrollment.reEnrollWarning).toContain('原退出记录')
  })

  it('only presents components that remain eligible for manual designation', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')

    expect(enrollment).toContain('v-for="option in componentOptions"')
    expect(enrollment).not.toContain(':disabled="Boolean(option.assessment_id)"')
  })

  it('renders the backend-provided finding explanation as one control flow', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')
    const zhCn = JSON.parse(readSource('../src/i18n/zh-cn.json'))

    expect(enrollment).toContain("security.finding.explanationStages.detection")
    expect(enrollment).toContain("security.finding.explanationStages.governance")
    expect(enrollment).toContain("security.finding.explanationStages.execution")
    expect(enrollment).toContain('finding.explanation.outlets')
    expect(enrollment).toContain(':icon="QuestionFilled"')
    expect(enrollment).toContain('<el-popover')
    expect(enrollment).toContain('trigger="click"')
    expect(enrollment).toContain('<dl class="recognition-rule-details">')
    expect(enrollment).toContain('security.finding.ruleAudit.viewDetails')
    expect(enrollment).toContain('container: finding-card / inline-size')
    expect(enrollment).toContain('@container finding-card (max-width: 920px)')
    expect(enrollment).toContain('.explanation-stage:nth-child(3)')
    expect(enrollment).toContain("capabilityText(finding, 'method_i18n_key')")
    expect(zhCn.security.finding.ruleAudit.details).toBe('识别说明')
    expect(zhCn.security.finding.ruleAudit.viewDetails).toBe('查看识别说明')
    expect(zhCn.security.finding.ruleAudit.viewMethod).toBeUndefined()
    expect(enrollment).not.toContain('finding.detector_version }}</el-descriptions-item>')
    expect(zhCn.security.finding.explanationStages.execution).toBe('出口规则')
    expect(zhCn.security.finding.outletAcknowledged).toBe('已安装')
    expect(zhCn.security.finding.outletWaiting).toBe('待安装')
  })

  it('keeps the pending review queue as a recoverable subview of protected resources', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')
    const zhCn = JSON.parse(readSource('../src/i18n/zh-cn.json'))

    expect(enrollment).toContain("WORKSPACE_TABS = ['resources', 'review-queue']")
    expect(enrollment).toContain("snapshot_scope: 'current'")
    expect(enrollment).toContain("review_state: 'pending'")
    expect(enrollment).toContain('resolveCanonicalTabRouteState')
    expect(enrollment).toContain('resolveReviewQueueFilters')
    expect(enrollment).toContain('nextQueueReviewFinding')
    expect(enrollment).toContain('nextDetailReviewFinding')
    expect(enrollment).toContain('security.finding.reviewSavedAndContinued')
    expect(enrollment).toContain('security.finding.reviewRemainingQueue')
    expect(enrollment).toContain('security.finding.reviewRemainingResource')
    expect(enrollment).toContain('v-model="reviewBasisExpanded"')
    expect(enrollment).toContain('security.finding.reviewBasis.actualMatch')
    expect(enrollment).toContain('evidenceAuditDescription(reviewingFinding)')
    expect(enrollment).toContain('outletRuleDescription(reviewingFinding, outlet.consumer_owner)')
    expect(enrollment).toContain('findingAPI.review(reviewedFinding.id, payload)')
    expect(zhCn.security.enrollment.workspaces.reviewQueue).toBe('待复核候选')
    expect(zhCn.security.reviewQueue.description).toContain('提交复核后候选会自动移出')
    expect(zhCn.security.finding.reviewRemainingQueue).toContain('当前筛选')
    expect(zhCn.security.finding.reviewRemainingResource).toContain('当前资源')
    expect(zhCn.security.finding.reviewBasis.title).toBe('判定依据')
    expect(zhCn.security.finding.reviewBasis.currentEnforcement).toBe('当前出口规则')
  })

  it('presents owner acknowledgement as installed rules rather than request execution', () => {
    const enrollment = readSource('../src/views/ProtectionEnrollmentList.vue')
    const zhCn = JSON.parse(readSource('../src/i18n/zh-cn.json'))
    const en = JSON.parse(readSource('../src/i18n/en.json'))

    expect(zhCn.security.enrollment.progress).toBe('保护规则同步')
    expect(zhCn.security.enrollment.ownerStates.active).toBe('字段规则已安装')
    expect(zhCn.security.enrollment.states.active).toBe('保护规则同步完成')
    expect(zhCn.security.enrollment.stateDescriptions.active).toContain('具体请求仍按运行时能力执行或保守拒绝')
    expect(zhCn.security.enrollment.ownerProtectionHint).toContain('已安装表示 Owner 已持久保存当前保护投影')
    expect(zhCn.security.enrollment.ownerEffectRequirements).toBe('已安装规则：{rules}')
    expect(en.security.enrollment.ownerStates.active).toBe('Field rules installed')
    expect(en.security.enrollment.ownerProtectionHint).toContain('Each request still validates')
    expect(enrollment).toContain("security.enrollment.ownerProtectionHint")
    expect(enrollment).toContain("security.enrollment.ownerEffectRequirements")
    expect(enrollment).toContain('Array.isArray(owner.rules)')
    expect(enrollment).not.toContain('Array.isArray(owner.effects)')
    expect(zhCn.security.enrollment.stateDescriptions.active).not.toContain('均已执行字段级保护')
  })
})
