worker_processes 1;
pid /tmp/nginx.pid;
error_log /dev/stderr crit;
events { worker_connections 128; }
http {
  access_log off;
  client_body_temp_path /tmp/client;
  proxy_temp_path /tmp/proxy;
  fastcgi_temp_path /tmp/fastcgi;
  uwsgi_temp_path /tmp/uwsgi;
  scgi_temp_path /tmp/scgi;
  client_max_body_size 8k;
  client_body_timeout 5s;
  client_header_timeout 5s;
  send_timeout 5s;
  proxy_connect_timeout 2s;
  proxy_send_timeout 5s;
  proxy_read_timeout 5s;
  proxy_set_header Authorization $http_authorization;
  proxy_set_header Host $proxy_host;
  proxy_set_header Connection "";
  proxy_http_version 1.1;
  server {
    listen 9444 ssl;
    ssl_certificate /tls/server.crt;
    ssl_certificate_key /tls/server.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    location = /api/v1/system/oauth/token {
      if ($request_method != POST) { return 405; }
      if ($args != "") { return 400; }
      proxy_pass @@GATEWAY_URL@@;
    }
    location = /api/v1/monitor/platform/metrics_discovery {
      if ($request_method != GET) { return 405; }
      if ($args != "") { return 400; }
      proxy_pass @@GATEWAY_URL@@;
    }
    location / { return 404; }
  }
}
