services:
  node-exporter:
    ports:
      - target: 9100
        published: "${ADDP_NODE_METRICS_PUBLISH_PORT:-9100}"
        host_ip: ${ADDP_NODE_METRICS_PUBLISH_IP:-127.0.0.1}
        protocol: tcp
