// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/executions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orchestrator"
                ],
                "summary": "获取所有执行列表 | List all executions",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码 | Page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量 | Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "当前身份未绑定租户 | Current identity is not bound to a tenant",
                        "schema": {
                            "$ref": "#/definitions/github_com_addp_orchestrator_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/executions/{execution_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "按 execution_id 查询 Orchestrator 编排统一执行记录。| Get an Orchestrator execution record by execution_id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orchestrator"
                ],
                "summary": "获取 Orchestrator 编排执行状态 | Get Orchestrator execution status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "执行 UUID | Execution UUID",
                        "name": "execution_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/execution.TaskExecution"
                        }
                    },
                    "403": {
                        "description": "当前身份未绑定租户 | Current identity is not bound to a tenant",
                        "schema": {
                            "$ref": "#/definitions/github_com_addp_orchestrator_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/orch-executions/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orchestrator"
                ],
                "summary": "获取执行详情 | Get execution detail",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "当前身份未绑定租户 | Current identity is not bound to a tenant",
                        "schema": {
                            "$ref": "#/definitions/github_com_addp_orchestrator_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "执行不存在 | Execution not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_addp_orchestrator_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/orchestrations": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orchestrator"
                ],
                "summary": "获取编排列表 | List orchestrations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "当前身份未绑定租户 | Current identity is not bound to a tenant",
                        "schema": {
                            "$ref": "#/definitions/github_com_addp_orchestrator_internal_models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "严格解析编排定义并拒绝未知字段，统一校验 Step、DAG、模板依赖、任务引用、递归引用和调度表达式 | Strictly parse the orchestration definition, reject unknown fields, and validate steps, DAG, template dependencies, task references, recursive references, and schedule expressions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orchestrator"
                ],
                "summary": "创建编排 | Create orchestration",
                "parameters": [
                    {
                        "description": "编排定义，steps 必须使用 provider/task_type/task_id 任务引用 | Orchestration definition, steps must use provider/task_type/task_id task references",
                        "name": "orchestration",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_addp_orchestrator_internal_models.OrchestrationDefinitionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "编排定义或执行参数无效 | Invalid orchestration definition or execution parameters",
                        "schema": {
                            "$ref": "#/definitions/github_com_addp_orchestrator_internal_models.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "当前身份未绑定租户 | Current identity is not bound to a tenant",
                        "schema": {
                            "$ref": "#/definitions/github_com_addp_orchestrator_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/orchestrations/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orchestrator"
                ],
                "summary": "获取编排详情 | Get orchestration detail",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "当前身份未绑定租户 | Current identity is not bound to a tenant",
                        "schema": {
                            "$ref": "#/definitions/github_com_addp_orchestrator_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "编排不存在 | Orchestration not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_addp_orchestrator_internal_models.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "严格解析编排定义并拒绝未知字段，统一校验 Step、DAG、模板依赖、任务引用、递归引用和调度表达式 | Strictly parse the orchestration definition, reject unknown fields, and validate steps, DAG, template dependencies, task references, recursive references, and schedule expressions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orchestrator"
                ],
                "summary": "更新编排 | Update orchestration",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "编排 ID | Orchestration ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "编排定义，steps 必须使用 provider/task_type/task_id 任务引用 | Orchestration definition, steps must use provider/task_type/task_id task references",
                        "name": "orchestration",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_addp_orchestrator_internal_models.OrchestrationDefinitionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "编排定义或执行参数无效 | Invalid orchestration definition or execution parameters",
                        "schema": {
                            "$ref": "#/definitions/github_com_addp_orchestrator_internal_models.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "当前身份未绑定租户 | Current identity is not bound to a tenant",
                        "schema": {
                            "$ref": "#/definitions/github_com_addp_orchestrator_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "编排不存在 | Orchestration not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_addp_orchestrator_internal_models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orchestrator"
                ],
                "summary": "删除编排 | Delete orchestration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "当前身份未绑定租户 | Current identity is not bound to a tenant",
                        "schema": {
                            "$ref": "#/definitions/github_com_addp_orchestrator_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "编排不存在 | Orchestration not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_addp_orchestrator_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/orchestrations/{id}/execute": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orchestrator"
                ],
                "summary": "执行编排 | Execute orchestration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "当前身份未绑定租户 | Current identity is not bound to a tenant",
                        "schema": {
                            "$ref": "#/definitions/github_com_addp_orchestrator_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "编排不存在 | Orchestration not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_addp_orchestrator_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/orchestrations/{id}/executions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orchestrator"
                ],
                "summary": "获取执行列表 | List executions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "当前身份未绑定租户 | Current identity is not bound to a tenant",
                        "schema": {
                            "$ref": "#/definitions/github_com_addp_orchestrator_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "编排不存在 | Orchestration not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_addp_orchestrator_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/task-providers": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "从 System 任务提供者注册表获取可编排任务提供者 | List task providers from System task provider registry",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orchestrator"
                ],
                "summary": "列出任务提供者 | List task providers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/tasks": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "动态调用目标模块任务列表接口并标准化返回格式；module_name=orchestrator 时返回本模块已保存的编排任务。| Proxy and normalize module task list; when module_name=orchestrator, return saved orchestration tasks.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orchestrator"
                ],
                "summary": "列出模块任务 | List module tasks",
                "parameters": [
                    {
                        "type": "string",
                        "description": "模块名；为空或 orchestrator 时返回编排任务 | Module name; empty or orchestrator returns orchestration tasks",
                        "name": "module_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "任务类型；Orchestrator 固定为 orchestration | Task type; orchestration for Orchestrator",
                        "name": "task_type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码 | Page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "每页数量 | Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "当前身份未绑定租户 | Current identity is not bound to a tenant",
                        "schema": {
                            "$ref": "#/definitions/github_com_addp_orchestrator_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/tasks/{task_type}/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "按标准 TaskProvider 路径获取 Orchestrator 编排任务详情；task_type 仅支持 orchestration。| Get Orchestrator task detail through the standard TaskProvider path; task_type only supports orchestration.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orchestrator"
                ],
                "summary": "获取 TaskProvider 编排任务详情 | Get TaskProvider orchestration task detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务类型，固定为 orchestration | Task type, fixed to orchestration",
                        "name": "task_type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "编排 ID | Orchestration ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_addp_orchestrator_internal_models.ProviderOrchestrationTask"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "当前身份未绑定租户 | Current identity is not bound to a tenant",
                        "schema": {
                            "$ref": "#/definitions/github_com_addp_orchestrator_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/tasks/{task_type}/{id}/execute": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "按标准 TaskProvider 协议执行 Orchestrator 编排任务；task_type 仅支持 orchestration。| Execute an Orchestrator task through the standard TaskProvider protocol; task_type only supports orchestration.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orchestrator"
                ],
                "summary": "执行 TaskProvider 编排任务 | Execute TaskProvider orchestration task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务类型，固定为 orchestration | Task type, fixed to orchestration",
                        "name": "task_type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "编排 ID | Orchestration ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "TaskProvider 执行请求 | TaskProvider execution request",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_api.orchestrationTaskProviderExecuteRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/internal_api.orchestrationTaskProviderExecuteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "当前身份未绑定租户 | Current identity is not bound to a tenant",
                        "schema": {
                            "$ref": "#/definitions/github_com_addp_orchestrator_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "execution.TaskExecution": {
            "type": "object",
            "properties": {
                "bytes_read": {
                    "description": "Transfer 读取字节数",
                    "type": "integer"
                },
                "bytes_written": {
                    "description": "Transfer 写入字节数",
                    "type": "integer"
                },
                "completed_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "current_step": {
                    "description": "当前步骤（Orchestrator/Workflow）",
                    "type": "string"
                },
                "error_details": {
                    "description": "错误详情（仅失败时有值）",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.JSONMap"
                        }
                    ]
                },
                "execution_config": {
                    "description": "JSONB 字段",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.JSONMap"
                        }
                    ]
                },
                "execution_id": {
                    "description": "执行标识",
                    "type": "string"
                },
                "execution_time_ms": {
                    "description": "性能指标",
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "metadata": {
                    "description": "模块特有扩展数据（结果、断点、步骤结果等）",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.JSONMap"
                        }
                    ]
                },
                "module": {
                    "description": "模块标识",
                    "type": "string"
                },
                "parent_execution_id": {
                    "description": "父执行（Orchestrator 子步骤追踪父编排）",
                    "type": "string"
                },
                "progress": {
                    "description": "0-100",
                    "type": "integer"
                },
                "records_read": {
                    "description": "Transfer 读取记录数",
                    "type": "integer"
                },
                "records_written": {
                    "description": "Transfer 写入记录数",
                    "type": "integer"
                },
                "rows_affected": {
                    "description": "SQL 影响行数",
                    "type": "integer"
                },
                "source": {
                    "description": "触发来源模块",
                    "type": "string"
                },
                "source_task_id": {
                    "description": "关联原始任务",
                    "type": "string"
                },
                "source_task_name": {
                    "description": "任务名称（冗余，便于查询）",
                    "type": "string"
                },
                "started_at": {
                    "description": "时间戳",
                    "type": "string"
                },
                "status": {
                    "description": "执行状态",
                    "type": "string"
                },
                "task_type": {
                    "description": "provider 声明的稳定任务类型",
                    "type": "string"
                },
                "tenant_id": {
                    "type": "integer"
                },
                "trigger_type": {
                    "description": "触发信息",
                    "type": "string"
                },
                "triggered_by": {
                    "description": "触发用户ID",
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_addp_orchestrator_internal_models.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "请求参数错误"
                }
            }
        },
        "github_com_addp_orchestrator_internal_models.OrchestrationDefinitionRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "schedule": {
                    "type": "string"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_addp_orchestrator_internal_models.Step"
                    }
                }
            }
        },
        "github_com_addp_orchestrator_internal_models.ProviderOrchestrationTask": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "last_execution_id": {
                    "type": "string"
                },
                "last_execution_status": {
                    "type": "string"
                },
                "last_run_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "next_run_at": {
                    "type": "string"
                },
                "schedule": {
                    "type": "string"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_addp_orchestrator_internal_models.Step"
                    }
                },
                "task_type": {
                    "type": "string"
                },
                "tenant_id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_addp_orchestrator_internal_models.Step": {
            "type": "object",
            "properties": {
                "depends_on": {
                    "description": "依赖步骤 ID 列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "description": "唯一ID",
                    "type": "string"
                },
                "name": {
                    "description": "步骤名称",
                    "type": "string"
                },
                "parameters": {
                    "description": "请求参数",
                    "type": "object",
                    "additionalProperties": true
                },
                "provider": {
                    "description": "任务引用（引用已有的 TaskProvider 任务定义）",
                    "type": "string"
                },
                "task_id": {
                    "description": "具体任务定义 ID",
                    "type": "integer"
                },
                "task_type": {
                    "description": "TaskProvider task type, e.g. \"scan\" | \"workflow\" | \"orchestration\"",
                    "type": "string"
                },
                "timeout": {
                    "description": "超时秒数",
                    "type": "integer"
                }
            }
        },
        "internal_api.orchestrationTaskProviderExecuteRequest": {
            "type": "object",
            "properties": {
                "parameters": {
                    "type": "object",
                    "additionalProperties": true
                },
                "parent_execution_id": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "trigger_type": {
                    "type": "string"
                }
            }
        },
        "internal_api.orchestrationTaskProviderExecuteResponse": {
            "type": "object",
            "properties": {
                "execution_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "models.JSONMap": {
            "type": "object",
            "additionalProperties": true
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8084",
	BasePath:         "/api/v1/orchestrator",
	Schemes:          []string{},
	Title:            "ADDP Orchestrator API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
