const STANDARD_TEXTURE_COMPRESSION = Object.freeze({
  DXT1_RGB: 33776,
  DXT1_RGBA: 33777,
  DXT3: 33778,
  DXT5: 33779,
  WEBP: 38000,
  CRN: 38001,
  KTX2: 38002,
  CRN_DXT5: 50000
})

const S3M_TEXTURE_FORMAT = Object.freeze({
  NONE: 0,
  RGB: 10,
  BGR: 11,
  DXT1: 17,
  DXT3: 19,
  DXT5: 21,
  WEBP: 25,
  CRN_DXT5: 26,
  STANDARD_CRN: 27,
  KTX2: 31
})

export function mapStandardTextureCompression(compressType) {
  switch (compressType) {
    case STANDARD_TEXTURE_COMPRESSION.DXT1_RGB:
    case STANDARD_TEXTURE_COMPRESSION.DXT1_RGBA:
      return S3M_TEXTURE_FORMAT.DXT1
    case STANDARD_TEXTURE_COMPRESSION.DXT3:
      return S3M_TEXTURE_FORMAT.DXT3
    case STANDARD_TEXTURE_COMPRESSION.DXT5:
      return S3M_TEXTURE_FORMAT.DXT5
    case STANDARD_TEXTURE_COMPRESSION.WEBP:
      return S3M_TEXTURE_FORMAT.WEBP
    case STANDARD_TEXTURE_COMPRESSION.CRN:
      return S3M_TEXTURE_FORMAT.STANDARD_CRN
    case STANDARD_TEXTURE_COMPRESSION.KTX2:
      return S3M_TEXTURE_FORMAT.KTX2
    case STANDARD_TEXTURE_COMPRESSION.CRN_DXT5:
      return S3M_TEXTURE_FORMAT.CRN_DXT5
    default:
      return S3M_TEXTURE_FORMAT.NONE
  }
}

export function standardTextureInternalFormat(compressType, pixelFormat) {
  switch (compressType) {
    case STANDARD_TEXTURE_COMPRESSION.DXT1_RGB:
      return STANDARD_TEXTURE_COMPRESSION.DXT1_RGB
    case STANDARD_TEXTURE_COMPRESSION.DXT1_RGBA:
      return STANDARD_TEXTURE_COMPRESSION.DXT1_RGBA
    case STANDARD_TEXTURE_COMPRESSION.DXT3:
      return STANDARD_TEXTURE_COMPRESSION.DXT3
    case STANDARD_TEXTURE_COMPRESSION.DXT5:
      return STANDARD_TEXTURE_COMPRESSION.DXT5
    default:
      return pixelFormat === S3M_TEXTURE_FORMAT.RGB || pixelFormat === S3M_TEXTURE_FORMAT.BGR
        ? STANDARD_TEXTURE_COMPRESSION.DXT1_RGB
        : STANDARD_TEXTURE_COMPRESSION.DXT5
  }
}
