<template>
  <div class="page-shell" v-loading="loading">
    <div class="page-header"><div class="header-left"><el-button :icon="ArrowLeft" @click="goBack">{{ t('standard.common.back') }}</el-button><h2>{{ revision.name || metric.code || t('standard.metric.detailTitle') }}</h2><el-tag v-if="revision.status" :type="statusType(revision.status)">R{{ revision.revision_no }} · {{ statusLabel(revision.status) }}</el-tag></div><div class="actions"><el-button v-if="revisionEditable" type="primary" :loading="saving" @click="saveRevision">{{ t('standard.common.save') }}</el-button><el-button v-if="revisionEditable" type="warning" @click="act('submit')">{{ t('standard.revision.submit') }}</el-button><el-button v-if="reviewing && canPublish" @click="act('return')">{{ t('standard.revision.return') }}</el-button><el-button v-if="reviewing && canPublish" type="success" @click="act('publish')">{{ t('standard.revision.publish') }}</el-button><el-button v-if="!metric.draft_revision && canUpdate" @click="newDraft">{{ t('standard.revision.newDraft') }}</el-button><el-button v-if="revision.status==='published' && canPublish" type="danger" @click="act('withdraw')">{{ t('standard.revision.withdraw') }}</el-button></div></div>
    <el-row :gutter="16"><el-col :xs="24" :lg="16">
      <el-card shadow="never" class="section"><template #header><div class="card-header"><span>{{ t('standard.common.governanceInfo') }}</span><el-button v-if="identityEditable" type="primary" size="small" :loading="savingIdentity" @click="saveIdentity">{{ t('standard.common.save') }}</el-button></div></template>
        <el-form :model="metric" label-width="140px" :disabled="!identityEditable"><el-row :gutter="12"><el-col :span="12"><el-form-item :label="t('standard.metric.codeLabel')"><el-input :model-value="metric.code" disabled /></el-form-item></el-col><el-col :span="12"><el-form-item :label="t('standard.metric.categoryLabel')"><el-tree-select v-model="metric.category_id" :data="categoryTree" :props="{label:'name',value:'id',children:'children'}" clearable style="width:100%" /></el-form-item></el-col></el-row><el-row :gutter="12"><el-col :span="12"><el-form-item :label="t('standard.common.scopeLabel')"><el-select v-model="metric.scope_type" style="width:100%"><el-option v-for="scope in editableScopes" :key="scope" :value="scope" :label="scopeLabel(scope)" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item v-if="requiresOwnerDomain(metric.scope_type)" :label="t('standard.common.ownerDomainLabel')" required><el-select v-model="metric.owner_domain_id" style="width:100%"><el-option v-for="domain in domains" :key="domain.id" :value="domain.id" :label="domain.name" /></el-select></el-form-item></el-col></el-row><el-form-item :label="t('standard.common.stewardId')"><el-input-number v-model="metric.steward_id" :min="1" controls-position="right" style="width:100%" /></el-form-item><el-form-item :label="t('standard.common.tags')"><el-select v-model="metric.tags" multiple filterable allow-create default-first-option style="width:100%" /></el-form-item></el-form>
      </el-card>
      <el-card shadow="never" class="section"><template #header>{{ t('standard.metric.definitionSection') }}</template>
        <el-form :model="revision" label-width="140px" :disabled="!revisionEditable"><el-row :gutter="12"><el-col :span="12"><el-form-item :label="t('standard.metric.nameLabel')"><el-input v-model="revision.name" /></el-form-item></el-col><el-col :span="12"><el-form-item :label="t('standard.metric.typeLabel')"><el-select v-model="revision.metric_type" style="width:100%"><el-option v-for="type in metricTypes" :key="type" :value="type" :label="typeLabel(type)" /></el-select></el-form-item></el-col></el-row>
          <el-form-item :label="t('standard.metric.definitionLabel')"><el-input v-model="revision.definition" type="textarea" :rows="3" /></el-form-item><el-form-item :label="t('standard.metric.statisticalCaliber')"><el-input v-model="revision.statistical_caliber" type="textarea" :rows="4" /></el-form-item><el-form-item :label="t('standard.metric.semanticFormula')"><el-input v-model="revision.semantic_formula" type="textarea" :rows="2" /></el-form-item><el-form-item :label="t('standard.metric.unitLabel')"><el-select v-model="revision.unit_id" clearable filterable style="width:100%"><el-option v-for="unit in units" :key="unit.id" :value="unit.id" :label="`${unit.name} (${unit.symbol || '-'})`" /></el-select></el-form-item>
          <el-form-item v-if="revision.metric_type!=='atomic'" :label="t('standard.metric.dependencies')"><el-select v-model="dependencyIDs" multiple filterable style="width:100%"><el-option v-for="item in dependencyCandidates" :key="item.id" :value="item.id" :disabled="item.id===metric.id" :label="`${displayRevision(item)?.name || item.code} (${item.code})`" /></el-select></el-form-item>
          <el-row :gutter="12"><el-col :span="12"><el-form-item :label="t('standard.revision.effectiveFrom')"><el-date-picker v-model="revision.effective_from" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" style="width:100%" /></el-form-item></el-col><el-col :span="12"><el-form-item :label="t('standard.revision.effectiveTo')"><el-date-picker v-model="revision.effective_to" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" style="width:100%" /></el-form-item></el-col></el-row><el-form-item :label="t('standard.revision.changeSummary')"><el-input v-model="revision.change_summary" /></el-form-item>
        </el-form>
      </el-card>
      <DocumentPanel v-if="metric.id" entity-type="metric" :entity-id="metric.id" v-model:entity-version="metric.version" />
    </el-col><el-col :xs="24" :lg="8"><el-card shadow="never" class="section"><template #header>{{ t('standard.revision.history') }}</template><el-timeline><el-timeline-item v-for="item in revisions" :key="item.id"><div class="history-row"><el-link @click="selectRevision(item)">R{{ item.revision_no }} · {{ item.name }}</el-link><el-tag size="small" :type="statusType(item.status)">{{ statusLabel(item.status) }}</el-tag></div><small>{{ item.change_summary }}</small></el-timeline-item></el-timeline></el-card></el-col></el-row>
    <el-dialog v-model="draftDialog" :title="t('standard.revision.newDraft')" width="480px"><el-form label-position="top"><el-form-item :label="t('standard.revision.changeSummary')" required><el-input v-model="draftSummary" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="draftDialog=false">{{ t('standard.common.cancel') }}</el-button><el-button type="primary" @click="createDraft">{{ t('standard.common.confirm') }}</el-button></template></el-dialog>
  </div>
</template>

<script setup>
import {computed,onMounted,reactive,ref,watch} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {useI18n} from 'vue-i18n'
import {ElMessage} from 'element-plus'
import {ArrowLeft} from '@element-plus/icons-vue'
import {domainAPI,metricAPI,metricCategoryAPI,unitAPI} from '../api/standard'
import DocumentPanel from '../components/DocumentPanel.vue'
import {useStandardPermissions} from '../composables/useStandardPermissions'
import {navigateStandardRoute} from '@/utils/moduleNavigation'
import {getStandardErrorMessage} from '../utils/apiError'
import {EDITABLE_STANDARD_SCOPES,buildStandardOwnership,requiresOwnerDomain,standardScopeLabelKey} from '../utils/standardScope'
const route=useRoute(),router=useRouter(),{t}=useI18n(),{canUpdate,canPublish}=useStandardPermissions('metric')
const metricTypes=['atomic','derived','composite'],editableScopes=EDITABLE_STANDARD_SCOPES
const metric=ref({}),revisions=ref([]),domains=ref([]),categories=ref([]),units=ref([]),dependencyCandidates=ref([]),revision=reactive({}),dependencyIDs=ref([]),loading=ref(false),saving=ref(false),savingIdentity=ref(false),draftDialog=ref(false),draftSummary=ref('')
const identityEditable=computed(()=>canUpdate.value&&metric.value.lifecycle_state!=='deleting'),revisionEditable=computed(()=>canUpdate.value&&revision.status==='draft'&&metric.value.draft_revision_id===revision.id),reviewing=computed(()=>revision.status==='in_review'&&metric.value.draft_revision_id===revision.id)
const scopeLabel=scope=>scope?t(standardScopeLabelKey(scope)):'-',typeLabel=type=>type?t(`standard.metric.${type}`):'-',statusLabel=status=>status?t(`standard.revision.status.${status}`):'-',statusType=status=>({draft:'info',in_review:'warning',published:'success',withdrawn:'danger'}[status]||'info'),displayRevision=item=>item.draft_revision||item.current_revision
const buildTree=(list,parent=null)=>list.filter(item=>(item.parent_id||null)===parent).map(item=>({...item,children:buildTree(list,item.id)})),categoryTree=computed(()=>buildTree(categories.value)),flatten=nodes=>nodes.flatMap(node=>[node,...flatten(node.children||[])])
const setRevision=value=>{Object.keys(revision).forEach(key=>delete revision[key]);Object.assign(revision,structuredClone(value||{}));dependencyIDs.value=(revision.dependencies||[]).map(item=>item.dependency_definition_id)}
const load=async()=>{loading.value=true;try{const [aggregate,history,domainRows,categoryRows,unitRows,candidates]=await Promise.all([metricAPI.get(route.params.id),metricAPI.listRevisions(route.params.id),domainAPI.list(),metricCategoryAPI.list(),unitAPI.list(),metricAPI.list({page_size:500})]);metric.value=aggregate;metric.value.tags||=[];revisions.value=history||[];domains.value=flatten(domainRows||[]);categories.value=categoryRows||[];units.value=unitRows||[];dependencyCandidates.value=candidates.data||[];setRevision(aggregate.draft_revision||aggregate.current_revision||history?.[0])}catch(error){ElMessage.error(getStandardErrorMessage(error,t,'standard.common.loadFailed'));goBack()}finally{loading.value=false}}
const goBack=()=>navigateStandardRoute(router,'/metrics')
const saveIdentity=async()=>{if(requiresOwnerDomain(metric.value.scope_type)&&!metric.value.owner_domain_id){ElMessage.warning(t('standard.common.ownerDomainRequired'));return};savingIdentity.value=true;try{metric.value=await metricAPI.update(metric.value.id,{version:metric.value.version,category_id:metric.value.category_id,...buildStandardOwnership(metric.value.scope_type,metric.value.owner_domain_id),steward_id:metric.value.steward_id||null,tags:metric.value.tags||[]});ElMessage.success(t('standard.common.saveSuccess'))}catch(error){ElMessage.error(getStandardErrorMessage(error,t))}finally{savingIdentity.value=false}}
const revisionPayload=()=>({version:metric.value.version,metric_type:revision.metric_type,name:revision.name,definition:revision.definition,statistical_caliber:revision.statistical_caliber,semantic_formula:revision.semantic_formula||'',unit_id:revision.unit_id||null,dependencies:revision.metric_type==='atomic'?[]:dependencyIDs.value.map(metric_definition_id=>({metric_definition_id,relation_kind:revision.metric_type==='derived'?'base':'component'})),change_summary:revision.change_summary,effective_from:revision.effective_from||null,effective_to:revision.effective_to||null})
const saveRevision=async()=>{if(revision.metric_type==='derived'&&dependencyIDs.value.length!==1){ElMessage.warning(t('standard.metric.derivedDependencyRequired'));return};if(revision.metric_type==='composite'&&!dependencyIDs.value.length){ElMessage.warning(t('standard.metric.compositeDependencyRequired'));return};saving.value=true;try{metric.value=await metricAPI.updateRevision(metric.value.id,revision.id,revisionPayload());ElMessage.success(t('standard.common.saveSuccess'));await load()}catch(error){ElMessage.error(getStandardErrorMessage(error,t))}finally{saving.value=false}}
const act=async action=>{try{metric.value=await metricAPI[`${action}Revision`](metric.value.id,revision.id,metric.value.version);ElMessage.success(t('standard.common.operationSuccess'));await load()}catch(error){ElMessage.error(getStandardErrorMessage(error,t))}}
const newDraft=()=>{draftSummary.value='';draftDialog.value=true},createDraft=async()=>{if(!draftSummary.value.trim()){ElMessage.warning(t('standard.revision.changeSummaryRequired'));return};try{metric.value=await metricAPI.createRevision(metric.value.id,{version:metric.value.version,change_summary:draftSummary.value.trim()});draftDialog.value=false;await load()}catch(error){ElMessage.error(getStandardErrorMessage(error,t))}},selectRevision=item=>setRevision(item)
watch(()=>metric.value.scope_type,scope=>{if(!requiresOwnerDomain(scope)&&metric.value)metric.value.owner_domain_id=null})
onMounted(load)
</script>

<style scoped>.page-shell{min-height:100%;padding:20px;background:var(--addp-bg-secondary);color:var(--addp-text-primary)}.page-header,.header-left,.actions,.card-header,.history-row{display:flex;align-items:center}.page-header,.card-header,.history-row{justify-content:space-between}.page-header{margin-bottom:16px}.header-left,.actions{gap:10px}.section{margin-bottom:16px}.page-shell :deep(.el-card){background:var(--addp-bg-primary);border-color:var(--addp-border-color)}</style>
