<template>
  <div class="page-shell">
    <div class="page-header"><h2>{{ t('standard.metric.title') }}</h2><div class="header-actions"><el-button v-if="canCreate||canUpdate||canDelete" @click="categoryDialog=true">{{ t('standard.metric.categoryManageBtn') }}</el-button><el-button v-if="canCreate" type="primary" :icon="Plus" @click="openCreate">{{ t('standard.metric.create') }}</el-button></div></div>
    <el-card shadow="never" class="filter-card"><el-row :gutter="12">
      <el-col :span="6"><el-input v-model="filters.keyword" :prefix-icon="Search" clearable :placeholder="t('standard.metric.searchPlaceholder')" @change="search" /></el-col>
      <el-col :span="4"><el-select v-model="filters.metric_type" clearable :placeholder="t('standard.metric.typeLabel')" style="width:100%" @change="search"><el-option v-for="type in metricTypes" :key="type" :value="type" :label="typeLabel(type)" /></el-select></el-col>
      <el-col :span="4"><el-select v-model="filters.scope_type" clearable :placeholder="t('standard.common.selectScope')" style="width:100%" @change="search"><el-option v-for="scope in scopeOptions" :key="scope" :value="scope" :label="scopeLabel(scope)" /></el-select></el-col>
      <el-col :span="5"><el-select v-model="filters.owner_domain_id" clearable :placeholder="t('standard.common.selectDomain')" style="width:100%" @change="search"><el-option v-for="domain in domains" :key="domain.id" :value="domain.id" :label="domain.name" /></el-select></el-col>
      <el-col :span="4"><el-select v-model="filters.status" clearable :placeholder="t('standard.common.selectStatus')" style="width:100%" @change="search"><el-option v-for="status in statuses" :key="status" :value="status" :label="statusLabel(status)" /></el-select></el-col>
    </el-row></el-card>
    <el-card shadow="never">
      <el-table :data="metrics" v-loading="loading" stripe>
        <el-table-column :label="t('standard.metric.nameLabel')" min-width="140"><template #default="{row}"><el-link type="primary" @click="detail(row.id)">{{ workingRevision(row)?.name || row.code }}</el-link></template></el-table-column>
        <el-table-column :label="t('standard.metric.codeLabel')" prop="code" width="135" />
        <el-table-column :label="t('standard.metric.typeLabel')" width="100"><template #default="{row}"><el-tag size="small">{{ typeLabel(workingRevision(row)?.metric_type) }}</el-tag></template></el-table-column>
        <el-table-column :label="t('standard.common.scopeLabel')" width="105"><template #default="{row}">{{ scopeLabel(row.scope_type) }}</template></el-table-column>
        <el-table-column :label="t('standard.common.ownerDomainLabel')" width="120"><template #default="{row}">{{ domainName(row.owner_domain_id) }}</template></el-table-column>
        <el-table-column :label="t('standard.revision.number')" width="75"><template #default="{row}">{{ workingRevision(row) ? `R${workingRevision(row).revision_no}` : '-' }}</template></el-table-column>
        <el-table-column :label="t('standard.common.status')" width="95"><template #default="{row}"><el-tag :type="statusType(workingRevision(row)?.status)" size="small">{{ statusLabel(workingRevision(row)?.status) }}</el-tag></template></el-table-column>
        <el-table-column :label="t('standard.common.actions')" width="125" fixed="right"><template #default="{row}"><el-button link type="primary" @click="detail(row.id)">{{ t('standard.common.detail') }}</el-button><el-button v-if="canDelete" link type="danger" @click="remove(row)">{{ t('standard.common.delete') }}</el-button></template></el-table-column>
      </el-table>
      <el-pagination v-if="total" class="pagination" :total="total" :page-size="filters.page_size" :current-page="filters.page" layout="total, prev, pager, next" @current-change="page=>{filters.page=page;load()}" />
    </el-card>
    <el-dialog v-model="dialog" :title="t('standard.metric.createTitle')" width="700px">
      <el-form ref="formRef" :model="form" :rules="rules" label-width="140px">
        <el-row :gutter="12"><el-col :span="12"><el-form-item :label="t('standard.metric.codeLabel')" prop="code"><el-input v-model="form.code" /></el-form-item></el-col><el-col :span="12"><el-form-item :label="t('standard.metric.nameLabel')" prop="name"><el-input v-model="form.name" /></el-form-item></el-col></el-row>
        <el-row :gutter="12"><el-col :span="12"><el-form-item :label="t('standard.metric.typeLabel')" prop="metric_type"><el-select v-model="form.metric_type" style="width:100%"><el-option v-for="type in metricTypes" :key="type" :value="type" :label="typeLabel(type)" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item :label="t('standard.metric.categoryLabel')"><el-tree-select v-model="form.category_id" :data="categoryTree" :props="{label:'name',value:'id',children:'children'}" clearable style="width:100%" /></el-form-item></el-col></el-row>
        <el-row :gutter="12"><el-col :span="12"><el-form-item :label="t('standard.common.scopeLabel')" prop="scope_type"><el-select v-model="form.scope_type" style="width:100%"><el-option v-for="scope in editableScopes" :key="scope" :value="scope" :label="scopeLabel(scope)" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item v-if="requiresOwnerDomain(form.scope_type)" :label="t('standard.common.ownerDomainLabel')" prop="owner_domain_id"><el-select v-model="form.owner_domain_id" style="width:100%"><el-option v-for="domain in domains" :key="domain.id" :value="domain.id" :label="domain.name" /></el-select></el-form-item></el-col></el-row>
        <el-row :gutter="12"><el-col :span="12"><el-form-item :label="t('standard.metric.unitLabel')"><el-select v-model="form.unit_id" clearable filterable style="width:100%"><el-option v-for="unit in units" :key="unit.id" :value="unit.id" :label="`${unit.name} (${unit.symbol || '-'})`" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item :label="t('standard.common.stewardId')"><el-input-number v-model="form.steward_id" :min="1" controls-position="right" style="width:100%" /></el-form-item></el-col></el-row>
        <el-form-item :label="t('standard.common.tags')"><el-select v-model="form.tags" multiple filterable allow-create default-first-option style="width:100%" :placeholder="t('standard.metric.tagsPlaceholder')" /></el-form-item>
        <el-form-item :label="t('standard.metric.definitionLabel')" prop="definition"><el-input v-model="form.definition" type="textarea" :rows="2" /></el-form-item>
        <el-form-item :label="t('standard.metric.statisticalCaliber')" prop="statistical_caliber"><el-input v-model="form.statistical_caliber" type="textarea" :rows="3" /></el-form-item>
        <el-form-item :label="t('standard.metric.semanticFormula')"><el-input v-model="form.semantic_formula" type="textarea" :rows="2" /></el-form-item>
        <el-form-item v-if="form.metric_type !== 'atomic'" :label="t('standard.metric.dependencies')" prop="dependency_ids"><el-select v-model="form.dependency_ids" multiple filterable style="width:100%"><el-option v-for="item in dependencyCandidates" :key="item.id" :value="item.id" :label="`${workingRevision(item)?.name || item.code} (${item.code})`" /></el-select></el-form-item>
        <el-form-item :label="t('standard.revision.changeSummary')" prop="change_summary"><el-input v-model="form.change_summary" /></el-form-item>
      </el-form>
      <template #footer><el-button @click="dialog=false">{{ t('standard.common.cancel') }}</el-button><el-button type="primary" :loading="creating" @click="create">{{ t('standard.common.confirm') }}</el-button></template>
    </el-dialog>
    <el-dialog v-model="categoryDialog" :title="t('standard.metric.categoryManage')" width="720px">
      <el-form v-if="canCreate||canUpdate" :model="categoryForm" label-width="100px">
        <el-row :gutter="12"><el-col :span="12"><el-form-item :label="t('standard.metric.nameLabel')" required><el-input v-model="categoryForm.name" /></el-form-item></el-col><el-col :span="12"><el-form-item :label="t('standard.metric.codeLabel')" required><el-input v-model="categoryForm.code" :disabled="Boolean(editingCategory)" /></el-form-item></el-col></el-row>
        <el-row :gutter="12"><el-col :span="12"><el-form-item :label="t('standard.metric.categoryLabel')"><el-select v-model="categoryForm.parent_id" clearable style="width:100%" :placeholder="t('standard.metric.categoryParentPlaceholder')"><el-option v-for="item in categories" :key="item.id" :value="item.id" :label="item.name" :disabled="item.id===editingCategory?.id" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item :label="t('standard.common.sortOrder')"><el-input-number v-model="categoryForm.sort_order" :min="0" controls-position="right" style="width:100%" /></el-form-item></el-col></el-row>
        <el-form-item :label="t('standard.common.description')"><el-input v-model="categoryForm.description" /></el-form-item>
        <el-form-item><el-button type="primary" :loading="savingCategory" @click="saveCategory">{{ editingCategory ? t('standard.common.save') : t('standard.metric.addCategory') }}</el-button><el-button v-if="editingCategory" @click="resetCategoryForm">{{ t('standard.common.cancel') }}</el-button></el-form-item>
      </el-form>
      <el-table :data="categories" stripe><el-table-column prop="name" :label="t('standard.metric.nameLabel')" /><el-table-column prop="code" :label="t('standard.metric.codeLabel')" /><el-table-column :label="t('standard.metric.categoryLabel')"><template #default="{row}">{{ categories.find(item=>item.id===row.parent_id)?.name||'-' }}</template></el-table-column><el-table-column :label="t('standard.common.actions')" width="130"><template #default="{row}"><el-button v-if="canUpdate" link type="primary" @click="editCategory(row)">{{ t('standard.common.edit') }}</el-button><el-button v-if="canDelete" link type="danger" @click="deleteCategory(row)">{{ t('standard.common.delete') }}</el-button></template></el-table-column></el-table>
    </el-dialog>
  </div>
</template>

<script setup>
import {computed,onMounted,reactive,ref,watch} from 'vue'
import {useRouter} from 'vue-router'
import {useI18n} from 'vue-i18n'
import {ElMessage,ElMessageBox} from 'element-plus'
import {Plus,Search} from '@element-plus/icons-vue'
import {domainAPI,metricAPI,metricCategoryAPI,unitAPI} from '../api/standard'
import {useStandardPermissions} from '../composables/useStandardPermissions'
import {getStandardErrorMessage,isCanceledInteraction} from '../utils/apiError'
import {navigateStandardRoute} from '@/utils/moduleNavigation'
import {EDITABLE_STANDARD_SCOPES,buildStandardOwnership,requiresOwnerDomain,standardScopeLabelKey} from '../utils/standardScope'
const router=useRouter(),{t}=useI18n(),{canCreate,canUpdate,canDelete}=useStandardPermissions('metric')
const metricTypes=['atomic','derived','composite'],statuses=['draft','in_review','published','withdrawn'],scopeOptions=['platform','tenant_common','domain'],editableScopes=EDITABLE_STANDARD_SCOPES
const metrics=ref([]),domains=ref([]),categories=ref([]),units=ref([]),dependencyCandidates=ref([]),total=ref(0),loading=ref(false),creating=ref(false),dialog=ref(false),formRef=ref()
const categoryDialog=ref(false),savingCategory=ref(false),editingCategory=ref(null),categoryForm=reactive({name:'',code:'',description:'',parent_id:null,sort_order:0})
const filters=reactive({keyword:'',metric_type:'',scope_type:'',owner_domain_id:null,status:'',page:1,page_size:20})
const blank=()=>({code:'',name:'',metric_type:'atomic',category_id:null,scope_type:'tenant_common',owner_domain_id:null,steward_id:null,tags:[],unit_id:null,definition:'',statistical_caliber:'',semantic_formula:'',dependency_ids:[],change_summary:''});const form=reactive(blank())
const rules=computed(()=>({code:[{required:true,message:t('standard.metric.codeRequired')}],name:[{required:true,message:t('standard.metric.nameRequired')}],metric_type:[{required:true,message:t('standard.metric.typeRequired')}],definition:[{required:true,message:t('standard.metric.definitionRequired')}],statistical_caliber:[{required:true,message:t('standard.metric.caliberRequired')}],scope_type:[{required:true,message:t('standard.common.selectScope')}],owner_domain_id:requiresOwnerDomain(form.scope_type)?[{required:true,message:t('standard.common.ownerDomainRequired')}]:[],dependency_ids:form.metric_type==='derived'?[{validator:(_,v,done)=>v?.length===1?done():done(new Error(t('standard.metric.derivedDependencyRequired')))}]:form.metric_type==='composite'?[{validator:(_,v,done)=>v?.length?done():done(new Error(t('standard.metric.compositeDependencyRequired')))}]:[],change_summary:[{required:true,message:t('standard.revision.changeSummaryRequired')}]}))
const workingRevision=row=>row.draft_revision||row.current_revision
const typeLabel=type=>type?t(`standard.metric.${type}`):'-',statusLabel=status=>status?t(`standard.revision.status.${status}`):'-',statusType=status=>({draft:'info',in_review:'warning',published:'success',withdrawn:'danger'}[status]||'info'),scopeLabel=scope=>scope?t(standardScopeLabelKey(scope)):'-'
const flatten=nodes=>nodes.flatMap(node=>[node,...flatten(node.children||[])]),domainName=id=>domains.value.find(item=>item.id===id)?.name||'-',buildTree=(list,parent=null)=>list.filter(item=>(item.parent_id||null)===parent).map(item=>({...item,children:buildTree(list,item.id)})),categoryTree=computed(()=>buildTree(categories.value))
const load=async()=>{loading.value=true;try{const params=Object.fromEntries(Object.entries(filters).filter(([,v])=>v!==''&&v!=null));const result=await metricAPI.list(params);metrics.value=result.data||[];total.value=result.total||0}catch(error){ElMessage.error(getStandardErrorMessage(error,t,'standard.common.loadFailed'))}finally{loading.value=false}}
const loadReferences=async()=>{try{const [domainRows,categoryRows,unitRows,candidates]=await Promise.all([domainAPI.list(),metricCategoryAPI.list(),unitAPI.list(),metricAPI.list({page_size:500})]);domains.value=flatten(domainRows||[]);categories.value=categoryRows||[];units.value=unitRows||[];dependencyCandidates.value=candidates.data||[]}catch{domains.value=[];categories.value=[];units.value=[];dependencyCandidates.value=[]}}
const search=()=>{filters.page=1;load()},detail=id=>navigateStandardRoute(router,`/metrics/${id}`),openCreate=()=>{Object.assign(form,blank());dialog.value=true}
const resetCategoryForm=()=>{editingCategory.value=null;Object.assign(categoryForm,{name:'',code:'',description:'',parent_id:null,sort_order:0})}
const editCategory=row=>{editingCategory.value=row;Object.assign(categoryForm,{name:row.name,code:row.code,description:row.description||'',parent_id:row.parent_id||null,sort_order:row.sort_order||0})}
const saveCategory=async()=>{if(!categoryForm.name.trim()||!categoryForm.code.trim())return; savingCategory.value=true;try{if(editingCategory.value){await metricCategoryAPI.update(editingCategory.value.id,{version:editingCategory.value.version,name:categoryForm.name.trim(),description:categoryForm.description.trim(),parent_id:categoryForm.parent_id,sort_order:categoryForm.sort_order})}else{await metricCategoryAPI.create({...categoryForm,name:categoryForm.name.trim(),code:categoryForm.code.trim(),description:categoryForm.description.trim()})}categories.value=await metricCategoryAPI.list();resetCategoryForm();ElMessage.success(t('standard.common.saveSuccess'))}catch(error){ElMessage.error(getStandardErrorMessage(error,t))}finally{savingCategory.value=false}}
const deleteCategory=async row=>{try{await ElMessageBox.confirm(t('standard.metric.confirmDeleteCategory',{name:row.name}),t('standard.common.hint'),{type:'warning'});await metricCategoryAPI.delete(row.id);categories.value=await metricCategoryAPI.list();if(editingCategory.value?.id===row.id)resetCategoryForm();ElMessage.success(t('standard.common.deleteSuccess'))}catch(error){if(!isCanceledInteraction(error))ElMessage.error(getStandardErrorMessage(error,t,'standard.common.deleteFailed'))}}
const create=async()=>{if(!await formRef.value.validate().catch(()=>false))return;creating.value=true;try{const relation_kind=form.metric_type==='derived'?'base':'component';const row=await metricAPI.create({...form,...buildStandardOwnership(form.scope_type,form.owner_domain_id),dependencies:form.dependency_ids.map(metric_definition_id=>({metric_definition_id,relation_kind}))});dialog.value=false;ElMessage.success(t('standard.common.createSuccess'));detail(row.id)}catch(error){ElMessage.error(getStandardErrorMessage(error,t))}finally{creating.value=false}}
const remove=async row=>{try{await ElMessageBox.confirm(t('standard.metric.confirmDelete',{name:workingRevision(row)?.name||row.code}),t('standard.common.hint'),{type:'warning'});await metricAPI.delete(row.id);ElMessage.success(t('standard.common.deleteSuccess'));load()}catch(error){if(!isCanceledInteraction(error))ElMessage.error(getStandardErrorMessage(error,t,'standard.common.deleteFailed'))}}
watch(()=>form.scope_type,scope=>{if(!requiresOwnerDomain(scope))form.owner_domain_id=null});watch(()=>form.metric_type,()=>{form.dependency_ids=[]})
onMounted(()=>{loadReferences();load()})
</script>

<style scoped>.page-shell{min-height:100%;padding:20px;background:var(--addp-bg-secondary);color:var(--addp-text-primary)}.page-header,.header-actions{display:flex;justify-content:space-between;align-items:center}.header-actions{gap:8px}.page-header{margin-bottom:16px}.filter-card{margin-bottom:12px}.pagination{display:flex;justify-content:flex-end;margin-top:16px}.page-shell :deep(.el-card){background:var(--addp-bg-primary);border-color:var(--addp-border-color)}</style>
