FROM localhost:5001/alpine:latest

# Automatic architecture detection
ARG TARGETARCH

WORKDIR /app

# Install ca-certificates for HTTPS requests
RUN apk add --no-cache ca-certificates

# 复制本地编译好的二进制文件（自动选择正确架构）
COPY transfer/backend/worker-${TARGETARCH} ./worker

# 运行
CMD ["./worker"]
