// Code generated by common/authorization/cmd/manifest; DO NOT EDIT.
// Source: system/authorization/permissions.yaml (manifest_version=7).

package authorization

const (
	PermissionAuditEventExport                 = "audit.event.export"
	PermissionAuditEventRead                   = "audit.event.read"
	PermissionAuditTenantEventExport           = "audit.tenant_event.export"
	PermissionAuditTenantEventRead             = "audit.tenant_event.read"
	PermissionIamLocalAccountReset             = "iam.local_account.reset"
	PermissionIamPlatformIdentityChangeApprove = "iam.platform_identity_change.approve"
	PermissionIamPlatformIdentityChangeCreate  = "iam.platform_identity_change.create"
	PermissionIamPlatformIdentityChangeRead    = "iam.platform_identity_change.read"
	PermissionIamPlatformIdentityChangeReject  = "iam.platform_identity_change.reject"
	PermissionIamTenantInvitationCreate        = "iam.tenant_invitation.create"
	PermissionIamTenantInvitationRead          = "iam.tenant_invitation.read"
	PermissionIamTenantInvitationRevoke        = "iam.tenant_invitation.revoke"
	PermissionIamTenantMembershipClose         = "iam.tenant_membership.close"
	PermissionIamTenantMembershipRead          = "iam.tenant_membership.read"
	PermissionIamTenantMembershipRestore       = "iam.tenant_membership.restore"
	PermissionIamTenantMembershipSuspend       = "iam.tenant_membership.suspend"
	PermissionIamTenantMembershipUpdate        = "iam.tenant_membership.update"
	PermissionIamTenantRoleCreate              = "iam.tenant_role.create"
	PermissionIamTenantRoleDelete              = "iam.tenant_role.delete"
	PermissionIamTenantRoleRead                = "iam.tenant_role.read"
	PermissionIamTenantRoleUpdate              = "iam.tenant_role.update"
	PermissionIamTenantRoleAssignmentCreate    = "iam.tenant_role_assignment.create"
	PermissionIamTenantRoleAssignmentRead      = "iam.tenant_role_assignment.read"
	PermissionIamTenantRoleAssignmentRevoke    = "iam.tenant_role_assignment.revoke"
	PermissionIamUserCreate                    = "iam.user.create"
	PermissionIamUserReactivate                = "iam.user.reactivate"
	PermissionIamUserRead                      = "iam.user.read"
	PermissionIamUserSuspend                   = "iam.user.suspend"
	PermissionIamUserUpdate                    = "iam.user.update"
	PermissionPlatformTenantClose              = "platform.tenant.close"
	PermissionPlatformTenantCreate             = "platform.tenant.create"
	PermissionPlatformTenantInitialize         = "platform.tenant.initialize"
	PermissionPlatformTenantRead               = "platform.tenant.read"
	PermissionPlatformTenantRestore            = "platform.tenant.restore"
	PermissionPlatformTenantSuspend            = "platform.tenant.suspend"
	PermissionPlatformTenantUpdate             = "platform.tenant.update"
	PermissionSystemApiKeyCreate               = "system.api_key.create"
	PermissionSystemApiKeyRead                 = "system.api_key.read"
	PermissionSystemApiKeyRevoke               = "system.api_key.revoke"
	PermissionSystemApplicationCreate          = "system.application.create"
	PermissionSystemApplicationDelete          = "system.application.delete"
	PermissionSystemApplicationRead            = "system.application.read"
	PermissionSystemApplicationUpdate          = "system.application.update"
	PermissionSystemCleanupExecute             = "system.cleanup.execute"
	PermissionSystemCleanupRead                = "system.cleanup.read"
	PermissionSystemEngineCreate               = "system.engine.create"
	PermissionSystemEngineDelete               = "system.engine.delete"
	PermissionSystemEngineExecute              = "system.engine.execute"
	PermissionSystemEngineRead                 = "system.engine.read"
	PermissionSystemEngineUpdate               = "system.engine.update"
)

var permissionKeys = [...]string{
	"audit.event.export",
	"audit.event.read",
	"audit.tenant_event.export",
	"audit.tenant_event.read",
	"iam.local_account.reset",
	"iam.platform_identity_change.approve",
	"iam.platform_identity_change.create",
	"iam.platform_identity_change.read",
	"iam.platform_identity_change.reject",
	"iam.tenant_invitation.create",
	"iam.tenant_invitation.read",
	"iam.tenant_invitation.revoke",
	"iam.tenant_membership.close",
	"iam.tenant_membership.read",
	"iam.tenant_membership.restore",
	"iam.tenant_membership.suspend",
	"iam.tenant_membership.update",
	"iam.tenant_role.create",
	"iam.tenant_role.delete",
	"iam.tenant_role.read",
	"iam.tenant_role.update",
	"iam.tenant_role_assignment.create",
	"iam.tenant_role_assignment.read",
	"iam.tenant_role_assignment.revoke",
	"iam.user.create",
	"iam.user.reactivate",
	"iam.user.read",
	"iam.user.suspend",
	"iam.user.update",
	"platform.tenant.close",
	"platform.tenant.create",
	"platform.tenant.initialize",
	"platform.tenant.read",
	"platform.tenant.restore",
	"platform.tenant.suspend",
	"platform.tenant.update",
	"system.api_key.create",
	"system.api_key.read",
	"system.api_key.revoke",
	"system.application.create",
	"system.application.delete",
	"system.application.read",
	"system.application.update",
	"system.cleanup.execute",
	"system.cleanup.read",
	"system.engine.create",
	"system.engine.delete",
	"system.engine.execute",
	"system.engine.read",
	"system.engine.update",
}

// PermissionKeys returns the active owner-local Permission keys in stable order.
func PermissionKeys() []string {
	return append([]string(nil), permissionKeys[:]...)
}
