// Code generated by common/authorization/cmd/manifest; DO NOT EDIT.
// Source: common-python/addp_common/tools/manifest.json.

package authorization

import commonauth "github.com/addp/common/authorization"

var toolAuthorizations = map[string]commonauth.ToolAuthorization{
	"data.preview": {
		Name:                "data.preview",
		Owner:               "manager",
		RequiredScopes:      []string{"data.preview"},
		RequiredPermissions: []string{"manager.data_item.read"},
	},
	"data.search": {
		Name:                "data.search",
		Owner:               "manager",
		RequiredScopes:      []string{"data.search"},
		RequiredPermissions: []string{"manager.search.execute"},
	},
	"engine.list": {
		Name:                "engine.list",
		Owner:               "system",
		RequiredScopes:      []string{"engine.list"},
		RequiredPermissions: []string{"system.engine.read"},
	},
	"execution.get": {
		Name:                "execution.get",
		Owner:               "develop",
		RequiredScopes:      []string{"execution.get"},
		RequiredPermissions: []string{"develop.task.read"},
	},
	"notebook.draft.generate": {
		Name:                "notebook.draft.generate",
		Owner:               "copilot",
		RequiredScopes:      []string{"notebook.draft.generate"},
		RequiredPermissions: []string{"copilot.notebook.execute"},
	},
	"query.draft.generate": {
		Name:                "query.draft.generate",
		Owner:               "copilot",
		RequiredScopes:      []string{"query.draft.generate"},
		RequiredPermissions: []string{"copilot.sql.execute"},
	},
	"resource.ancestors.get": {
		Name:                "resource.ancestors.get",
		Owner:               "meta",
		RequiredScopes:      []string{"resource.ancestors.get"},
		RequiredPermissions: []string{"meta.catalog.read"},
	},
	"transfer.draft.generate": {
		Name:                "transfer.draft.generate",
		Owner:               "copilot",
		RequiredScopes:      []string{"transfer.draft.generate"},
		RequiredPermissions: []string{"copilot.transfer.execute"},
	},
	"workflow.draft.generate": {
		Name:                "workflow.draft.generate",
		Owner:               "copilot",
		RequiredScopes:      []string{"workflow.draft.generate"},
		RequiredPermissions: []string{"copilot.workflow.execute"},
	},
	"workflow.operators.list": {
		Name:                "workflow.operators.list",
		Owner:               "develop",
		RequiredScopes:      []string{"workflow.operators.list"},
		RequiredPermissions: []string{"develop.task.read"},
	},
	"workflow.run": {
		Name:                "workflow.run",
		Owner:               "develop",
		RequiredScopes:      []string{"workflow.run"},
		RequiredPermissions: []string{"develop.task.execute"},
	},
	"workflow.validate": {
		Name:                "workflow.validate",
		Owner:               "develop",
		RequiredScopes:      []string{"workflow.validate"},
		RequiredPermissions: []string{"develop.task.execute"},
	},
}

type ToolAuthorizationCatalog struct{}

func (ToolAuthorizationCatalog) FindToolAuthorization(name string) (commonauth.ToolAuthorization, bool) {
	tool, ok := toolAuthorizations[name]
	if !ok {
		return commonauth.ToolAuthorization{}, false
	}
	tool.RequiredScopes = append([]string(nil), tool.RequiredScopes...)
	tool.RequiredPermissions = append([]string(nil), tool.RequiredPermissions...)
	return tool, true
}
