# Code generated by common/authorization/cmd/manifest; DO NOT EDIT.
# Source: agent/authorization/permissions.yaml (manifest_version=1).

from typing import Final

AGENT_RUN_CANCEL: Final[str] = "agent.run.cancel"
AGENT_RUN_CREATE: Final[str] = "agent.run.create"
AGENT_RUN_EXECUTE: Final[str] = "agent.run.execute"
AGENT_RUN_READ: Final[str] = "agent.run.read"
AGENT_SESSION_CREATE: Final[str] = "agent.session.create"
AGENT_SESSION_DELETE: Final[str] = "agent.session.delete"
AGENT_SESSION_READ: Final[str] = "agent.session.read"

PERMISSION_KEYS: Final[tuple[str, ...]] = (
    "agent.run.cancel",
    "agent.run.create",
    "agent.run.execute",
    "agent.run.read",
    "agent.session.create",
    "agent.session.delete",
    "agent.session.read",
)
