FROM localhost:5001/alpine:latest

RUN apk --no-cache add ca-certificates tzdata curl

WORKDIR /app

# 从项目根目录的 dist/ 复制预编译的二进制
ARG BUILD_ARCH=arm64
ARG GOOS=linux
ARG BUILD_TYPE=release
COPY dist/${BUILD_TYPE}-${GOOS}-${BUILD_ARCH}/service ./server

RUN chmod +x ./server

ENV TZ=Asia/Shanghai

EXPOSE 8086

CMD ["./server"]
