# Code generated by common/authorization/cmd/manifest; DO NOT EDIT.
# Source: copilot/authorization/permissions.yaml (manifest_version=2).

from typing import Final

COPILOT_SQL_EXECUTE: Final[str] = "copilot.sql.execute"
COPILOT_WORKFLOW_EXECUTE: Final[str] = "copilot.workflow.execute"

PERMISSION_KEYS: Final[tuple[str, ...]] = (
    "copilot.sql.execute",
    "copilot.workflow.execute",
)
