import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { createLatestRequestCoordinator } from '../../../common-frontend/basic/src/utils/latestRequest.js'

const queryEditor = await readFile(new URL('../src/views/QueryEditor.vue', import.meta.url), 'utf8')

const coordinator = createLatestRequestCoordinator()
const duckdbRequest = coordinator.begin('mode:duckdb')
const dorisRequest = coordinator.begin('engine:17')

assert.equal(coordinator.isCurrent(duckdbRequest, 'engine:17'), false)
assert.equal(coordinator.isCurrent(dorisRequest, 'engine:17'), true)

coordinator.invalidate()
assert.equal(coordinator.isCurrent(dorisRequest, 'engine:17'), false)

const switchTargetSource = queryEditor.slice(
  queryEditor.indexOf('async function requestQueryTargetChange'),
  queryEditor.indexOf('const executeQuery = async')
)
const executeQuerySource = queryEditor.slice(
  queryEditor.indexOf('const executeQuery = async'),
  queryEditor.indexOf('const formatQuery =')
)
const queryParameterPanelStart = queryEditor.indexOf('class="query-parameter-panel"')
const queryParameterPanelSource = queryEditor.slice(
	  queryParameterPanelStart,
	  queryEditor.indexOf('</component>', queryParameterPanelStart)
)

assert.match(queryEditor, /:model-value="selectedQueryTarget"/)
assert.match(queryEditor, /@change="requestQueryTargetChange"/)
assert.match(queryEditor, /:disabled="executing \|\| loadingSampleQuery \|\| switchingQueryTarget \|\| savingForEngineSwitch"/)
assert.match(switchTargetSource, /!isDirty\.value/)
assert.match(switchTargetSource, /await applyQueryTargetSwitch\(targetValue\)/)
assert.match(queryEditor, /async function applyQueryTargetSwitch/)
assert.match(queryEditor, /queryContent\.value = ''/)
assert.match(queryEditor, /queryParameters\.value = \[\]/)
assert.doesNotMatch(switchTargetSource, /await loadSampleQuery\(\{ replace: true \}\)/)
assert.match(queryEditor, /bypassUnsavedRouteConfirm\.value = true/)
assert.match(queryEditor, /if \(bypassUnsavedRouteConfirm\.value\) return true/)
assert.match(queryEditor, /develop\.query\.clearAndSwitch/)
assert.match(queryEditor, /develop\.query\.saveAndClear/)
assert.match(queryEditor, /mode="any"/)
assert.match(queryEditor, /:engine-id="catalogTreeEngineValue"/)
assert.match(queryEditor, /:engine-multiple="catalogTreeEngineMultiple"/)
assert.match(queryEditor, /listResourceTreeEngines\('\/api\/v1\/meta'\)/)
assert.match(queryEditor, /supportedTypes\.has\(String\(source\.engine_type/)
assert.match(queryEditor, /:selectable-filter="isQueryCatalogSelectionAllowed"/)
assert.match(queryEditor, /isQueryCatalogSelectionAllowed/)
assert.match(queryEditor, /getResourceFields\('\/api\/v1\/meta'/)
assert.match(queryEditor, /const itemId = selection\?\.identity\?\.item_id \|\| parsed\.itemId/)
assert.match(queryEditor, /if \(!itemId\) return/)
assert.match(queryEditor, /kind: 'field'/)
assert.match(queryEditor, /insertText: fieldInsertionText\(name\)/)
assert.match(queryEditor, /:completions="completionSuggestions"/)
assert.match(queryEditor, /@node-click="rememberCatalogNode"/)
assert.match(queryEditor, /@node-expand="rememberCatalogNode"/)
assert.match(queryEditor, /getResourceTreeNode\('\/api\/v1\/meta'/)
assert.match(queryEditor, /engine_id: parsed\.engineId/)
assert.match(queryEditor, /federatedIdentifier\(sourceName\)/)
assert.match(queryEditor, /preflightQuery/)
assert.match(queryEditor, /develop\.query\.queryDiagnostics/)
assert.match(queryEditor, /triggerCompletion/)
assert.match(queryEditor, /showCompletions/)
assert.match(queryEditor, /refreshQueryDiagnostics/)
assert.match(queryEditor, /generateQueryTemplate/)
assert.match(queryEditor, /develop\.query\.queryParameters/)
assert.match(queryParameterPanelSource, /v-for="\(parameter, index\) in queryParameters"/)
assert.match(queryParameterPanelSource, /parameterTypes\.\$\{type\}/)
assert.match(queryParameterPanelSource, /parameter\.type !== 'relation'/)
assert.match(queryEditor, /parameter\?\.type === 'relation'[\s\S]*String\(parameter\?\.name/)
assert.doesNotMatch(queryEditor, /input\.[A-Za-z_$]/)
assert.doesNotMatch(queryEditor, /\|\| hasRelationParameters \|\| switchingQueryTarget/)
assert.doesNotMatch(queryEditor, /relation_inputs|addp_input|input_locators/)
const monacoEditorSource = await readFile(new URL('../src/components/MonacoEditor.vue', import.meta.url), 'utf8')
assert.match(monacoEditorSource, /editor\.getContribution\('editor\.contrib\.suggestController'\)/)
assert.match(monacoEditorSource, /contrib\/suggest\/browser\/suggestController\.js/)
assert.doesNotMatch(monacoEditorSource, /editor\.trigger\('keyboard', 'editor\.action\.triggerSuggest'/)
assert.match(monacoEditorSource, /contextInsertText/)
assert.match(monacoEditorSource, /sortText: item\.kind === 'field'/)
assert.match(monacoEditorSource, /item\.kind === 'field'/)
assert.match(monacoEditorSource, /CompletionItemKind\.Field/)
assert.match(monacoEditorSource, /monaco\.languages\.register\(\{ id: 'mql' \}\)/)
assert.match(monacoEditorSource, /window\.setTimeout\(triggerSuggest, 0\)/)
assert.doesNotMatch(queryEditor, /:disabled="[^"]*catalogSelection\?\.identity\?\.locator[^"]*"/)
assert.match(queryEditor, /ElMessage\.warning\(t\('develop\.query\.selectResourceForQueryTemplate'\)\)/)
assert.match(queryEditor, /@node-dblclick="insertCatalogItemAtCursor"/)
assert.match(queryEditor, /insertCatalogItemAtCursor/)
assert.match(queryEditor, /editorRef\.value\?\.insertText\(/)
assert.doesNotMatch(queryEditor, /insertCatalogPath/)
assert.doesNotMatch(queryEditor, /insertResourcePath/)
assert.match(executeQuerySource, /if \(loadingSampleQuery\.value \|\| executing\.value\) return/)
assert.match(queryEditor, /sampleRequests\.isCurrent\(request, `\$\{selectedQueryTarget\.value\}:\$\{locator\}`\)/)
assert.match(queryEditor, /createExecution\(\{/)
assert.match(queryEditor, /query_parameters: queryParameters\.value\.map\(queryParameterPayload\)/)
assert.match(queryEditor, /parameters,/)
assert.match(queryEditor, /<ExecutionParameterForm/)
assert.match(queryEditor, /queryParameterReference\(currentQueryLanguage\.value, parameter\?\.name\)/)
assert.match(queryEditor, /editorRef\.value\?\.getSelection\(\)/)
assert.match(queryEditor, /v-loading="loadingSampleQuery"/)
assert.match(queryEditor, /:aria-busy="loadingSampleQuery"/)

console.log('query target switch tests passed')
