import { test, expect } from '@playwright/test'
import { applicationPath, installMetricApplicationBackend } from './fixtures/metricApplication.js'

async function choose(page, field, label) {
  await field.locator('.el-select__wrapper').click()
  const id = await field.getByRole('combobox').getAttribute('aria-controls')
  await page.locator(`#${id}`).getByRole('option', { name: label, exact: true }).click()
}

test('canvas selection, title, layout and formatting edit one draft without changing its publication', async ({ page, context }) => {
  const backend = await installMetricApplicationBackend(context, { rebound: true })
  await page.goto(applicationPath)
  const cards = page.getByTestId('runtime-component')
  const inspector = page.getByTestId('component-inspector')
  await expect(cards.first().locator('tbody tr')).toHaveCount(2)
  const initialRequests = backend.requests.length
  await cards.first().click()
  await inspector.getByRole('textbox', { name: '组件标题', exact: true }).fill('新的结果标题')
  await expect(cards.first().locator('.component-title')).toContainText('新的结果标题')
  await inspector.getByRole('button', { name: '整行', exact: true }).click()
  await expect(cards.first()).toHaveCSS('grid-column-end', 'span 12')
  await inspector.getByRole('button', { name: '后移', exact: true }).click()
  await expect(cards.first().locator('.component-title')).toContainText('活动次数')
  expect(backend.requests).toHaveLength(initialRequests)
  await inspector.getByRole('button', { name: '字段与展示设置', exact: true }).click()
  const editor = page.getByTestId('application-component-editor')
  await expect(editor.getByRole('tab', { name: '2. 配置展示' })).toHaveAttribute('aria-selected', 'true')
  // The persisted table's numeric presentation has the only precision input.
  await editor.getByPlaceholder('小数位', { exact: true }).fill('2')
  await page.getByRole('dialog').getByRole('button', { name: '应用组件配置', exact: true }).click()
  await expect(cards.nth(1).locator('tbody tr')).toHaveCount(2)
  await expect(cards.nth(1).locator('tbody tr').first()).toContainText('0.25')
  expect(backend.requests).toHaveLength(initialRequests)
  await page.getByRole('button', { name: '保存草稿', exact: true }).click()
  await expect.poll(() => backend.writes.length).toBe(1)
  expect(backend.draft.snapshot.components[0].title).toBe('新的结果标题')
  expect(backend.draft.snapshot.components[0].renderer_config.field_presentations.find(p => p.field === 'value').precision).toBe(2)
  expect(backend.draft.snapshot.page.placements[0].component_id).toBe('component-72')
  expect(backend.published).toEqual(backend.originalPublished)
  await page.reload()
  await expect(page.getByTestId('application-component').first()).toContainText('活动次数')
  expect(backend.unexpected).toEqual([])
})

for (const locale of ['zh-cn', 'en']) {
test(`new application goes from a service through query inputs to a saved draft (${locale})`, async ({ page, context }) => {
  const backend = await installMetricApplicationBackend(context, { rebound: true, locale, configure(draft, descriptors) {
    descriptors[71].output_contract.fields.find(f => f.name === 'value').comment = '重叠比例'
  } })
  await page.goto('/workbench/applications/new')
  await expect(page.getByTestId('application-start')).toBeVisible()
  await expect(page.getByTestId('component-inspector')).toHaveCount(0)
  await page.getByTestId('start-table').click()
  const editor = page.getByTestId('application-component-editor')
  await choose(page, editor.locator('.el-form-item').filter({ hasText: locale === 'en' ? 'Data service' : '数据服务' }), '定向重叠率服务')
  await page.getByRole('dialog').getByRole('button', { name: locale === 'en' ? 'Next step' : '下一步', exact: true }).click()
  await expect(editor.getByRole('tab', { name: locale === 'en' ? '2. Configure display' : '2. 配置展示' })).toHaveAttribute('aria-selected', 'true')
  const formats = editor.getByTestId('field-formatting')
  await expect(formats.locator('[data-field="value"]').getByRole('textbox', { name: locale === 'en' ? 'Display label' : '展示名称', exact: true })).toHaveValue('重叠比例')
  await expect(formats.locator('[data-field="value"]').getByRole('spinbutton')).toHaveValue('0')
  await expect(formats.locator('[data-field="bucket"]').getByRole('combobox')).toBeVisible()
  await expect(formats.locator('details[open]')).toHaveCount(0)
  await page.getByRole('dialog').getByRole('button', { name: locale === 'en' ? 'Next step' : '下一步', exact: true }).click()
  const parameters = editor.locator('.parameter')
  await choose(page, parameters.nth(0), locale === 'en' ? 'Total' : '全期')
  await choose(page, parameters.nth(1), locale === 'en' ? 'Both directions' : '双向')
  await editor.getByTestId('component-query-action').click()
  await expect(editor.locator('tbody tr')).toHaveCount(2)
  await page.getByRole('dialog').getByRole('button', { name: locale === 'en' ? 'Apply component configuration' : '应用组件配置', exact: true }).click()
  await expect(page.getByTestId('application-start')).toHaveCount(0)
  await expect(page.getByTestId('runtime-component')).toHaveCount(1)
  await expect(page.getByTestId('application-creation-guide').getByRole('combobox')).toHaveCount(0)
  await page.getByTestId('draft-preview-action').click()
  const preview = page.getByRole('dialog')
  await choose(page, preview.locator('.parameter-field').first(), locale === 'en' ? 'Monthly' : '按月')
  await preview.getByTestId('apply-preview-defaults').click()
  await expect(preview).toHaveCount(0)
  expect(backend.writes).toHaveLength(0)
  await page.getByRole('button', { name: locale === 'en' ? 'Create draft' : '创建草稿', exact: true }).click()
  await expect.poll(() => backend.writes.length).toBe(1)
  expect(backend.writes[0].action).toBe('create')
  expect(backend.draft.snapshot.parameters.map(p => p.default_value)).toEqual(['month', 'both'])
  await expect(page).toHaveURL(new RegExp(applicationPath + '$'))
  expect(backend.unexpected).toEqual([])
})
}

for (const locale of ['zh-cn', 'en']) {
test(`field labels and formats preview immediately, restore defaults and survive save (${locale})`, async ({ page, context }) => {
  const english = locale === 'en'
  const backend = await installMetricApplicationBackend(context, { rebound: true, locale, configure(draft, descriptors) {
    draft.snapshot.components[0].default_parameter_values = { grain: 'total', directions: 'both' }
    descriptors[71].output_contract.fields.find(f => f.name === 'value').comment = '重叠比例'
    Object.assign(draft.snapshot.components[0].renderer_config.field_presentations.find(p => p.field === 'value'), {
      width: 180, unit: '原单位', state_rules: [{ operator: 'gt', operand: 0, label: '有交集', tone: 'success' }],
    })
    draft.snapshot.components[0].renderer_config.field_presentations.find(p => p.field === 'direction').value_labels = [{ value: 'forward', label: '正向' }]
  } })
  await page.goto(applicationPath)
  const cards = page.getByTestId('runtime-component')
  await expect(cards.first().locator('tbody tr')).toHaveCount(2)
  const original = backend.draft
  const openEditor = () => page.getByTestId('component-inspector').getByRole('button', { name: english ? 'Fields and display settings' : '字段与展示设置', exact: true }).click()
  await openEditor()
  const editor = page.getByTestId('application-component-editor')
  const formats = editor.getByTestId('field-formatting')
  const value = formats.locator('[data-field="value"]')
  const label = value.getByRole('textbox', { name: english ? 'Display label' : '展示名称', exact: true })
  const precision = value.getByPlaceholder(english ? 'Decimal places' : '小数位', { exact: true })
  const unit = value.getByRole('textbox', { name: english ? 'Unit (optional)' : '单位（可选）', exact: true })
  const restore = value.getByRole('button', { name: english ? 'Restore default label and format' : '恢复默认名称与格式', exact: true })
  await expect(value.locator('details')).toHaveAttribute('open', '')
  await label.fill('未应用名称')
  await restore.click()
  await expect(label).toHaveValue('重叠比例')
  await expect(precision).toHaveValue('0')
  await expect(unit).toHaveValue('')
  await page.getByRole('dialog').getByRole('button', { name: english ? 'Cancel' : '取消', exact: true }).click()
  expect(backend.draft).toEqual(original)
  await expect(cards.first().locator('thead')).toContainText('重叠率')

  await openEditor()
  await expect(label).toHaveValue('重叠率')
  await editor.getByTestId('component-query-action').click()
  await expect(editor.locator('tbody tr')).toHaveCount(2)
  const requests = backend.requests.length
  await restore.click()
  await label.fill('活动重叠比例')
  await unit.fill('倍')
  await precision.fill('2')
  await precision.press('Tab')
  await expect(editor.locator('thead')).toContainText('活动重叠比例')
  await expect(editor.locator('tbody tr').first()).toContainText('0.25 倍')
  await expect(editor.locator('tbody tr').first()).toContainText('有交集')
  const bucket = formats.locator('[data-field="bucket"]')
  await choose(page, bucket, english ? 'Month and year' : '年月')
  await expect(editor.locator('tbody tr').first()).toContainText(english ? 'January 2026' : '2026年1月')
  const direction = formats.locator('[data-field="direction"]')
  await direction.getByRole('button', { name: english ? 'Restore default label and format' : '恢复默认名称与格式', exact: true }).click()
  const valueLabel = direction.getByTestId('value-label-editor').getByRole('textbox', { name: english ? 'Display label' : '显示名称', exact: true })
  await expect(valueLabel).toHaveValue('正向')
  await valueLabel.fill('主体到比较对象')
  await expect(editor.locator('tbody tr').first()).toContainText('主体到比较对象')
  expect(backend.requests).toHaveLength(requests)

  await page.setViewportSize({ width: 680, height: 900 })
  expect(await formats.evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  await page.getByRole('dialog').getByRole('button', { name: english ? 'Apply component configuration' : '应用组件配置', exact: true }).click()
  await expect(cards.first().locator('tbody tr').first()).toContainText('0.25 倍')
  expect(backend.requests).toHaveLength(requests)
  await page.getByRole('button', { name: english ? 'Save draft' : '保存草稿', exact: true }).click()
  await expect.poll(() => backend.writes.length).toBe(1)
  const saved = backend.draft.snapshot.components[0]
  expect(saved.query_template).toEqual(original.snapshot.components[0].query_template)
  expect(saved.renderer_config.field_presentations.find(p => p.field === 'direction').value_labels).toEqual([{ value: 'forward', label: '主体到比较对象' }])
  expect(saved.renderer_config.field_presentations.find(p => p.field === 'value')).toEqual({
    field: 'value', label: '活动重叠比例', unit: '倍', precision: 2, width: 180,
    state_rules: [{ operator: 'gt', operand: 0, label: '有交集', tone: 'success' }],
  })
  expect(backend.published).toEqual(backend.originalPublished)
  await page.reload()
  await expect(cards.first().locator('thead')).toContainText('活动重叠比例')
  await expect(cards.first().locator('tbody tr').first()).toContainText('0.25 倍')
  await openEditor()
  await expect(label).toHaveValue('活动重叠比例')
  await expect(precision).toHaveValue('2')
  expect(backend.unexpected).toEqual([])
})
}

test('query changes invalidate canvas data; preview interactions stay out of the draft', async ({ page, context }) => {
  const backend = await installMetricApplicationBackend(context, { rebound: true })
  await page.goto(applicationPath)
  await expect(page.getByTestId('runtime-component').first().locator('tbody tr')).toHaveCount(2)
  const requests = backend.requests.length
  await page.getByRole('button', { name: '筛选条件', exact: true }).click()
  const drawer = page.getByRole('dialog')
  await choose(page, drawer.getByTestId('filter-card').first(), '按月')
  await drawer.getByRole('button', { name: '完成设置', exact: true }).click()
  await expect(page.getByTestId('runtime-component').first().locator('tbody tr')).toHaveCount(0)
  expect(backend.requests).toHaveLength(requests)
  await page.getByRole('button', { name: '刷新画布数据', exact: true }).click()
  await expect(page.getByTestId('runtime-component').first().locator('tbody tr')).toHaveCount(24)
  await page.getByTestId('draft-preview-action').click()
  const preview = page.getByRole('dialog')
  await expect(preview.getByTestId('query-all-action')).toBeVisible()
  await preview.getByTestId('query-all-action').click()
  await expect(preview.getByTestId('runtime-component').first().locator('tbody tr')).toHaveCount(24)
  expect(backend.writes).toHaveLength(0)
  expect(backend.published).toEqual(backend.originalPublished)
  expect(backend.unexpected).toEqual([])
})

test('narrow editor remains usable and protects unsaved changes on return', async ({ page, context }) => {
  await installMetricApplicationBackend(context, { rebound: true })
  await page.setViewportSize({ width: 680, height: 900 })
  await page.goto(applicationPath)
  const inspector = page.getByTestId('component-inspector')
  await inspector.getByRole('textbox', { name: '组件标题', exact: true }).fill('未保存标题')
  await page.getByRole('button', { name: '返回列表', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page).toHaveURL(new RegExp(applicationPath + '$'))
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)
})

test('dragging reorders layout and selecting a result never runs an interaction in edit mode', async ({ page, context }) => {
  const backend = await installMetricApplicationBackend(context, { rebound: true })
  await page.goto(applicationPath)
  const cards = page.getByTestId('runtime-component')
  await expect(cards.first().locator('tbody tr')).toHaveCount(2)
  const initialRequests = backend.requests.length
  await cards.first().locator('tbody tr').first().click({ force: true })
  await expect(cards.first()).toHaveAttribute('aria-pressed', 'true')
  expect(backend.requests).toHaveLength(initialRequests)
  const dragData = await page.evaluateHandle(() => new DataTransfer())
  await cards.nth(1).getByRole('button', { name: '拖动调整组件顺序' }).dispatchEvent('dragstart', { dataTransfer: dragData })
  await cards.first().dispatchEvent('dragover', { dataTransfer: dragData })
  await cards.first().dispatchEvent('drop', { dataTransfer: dragData })
  await expect(page.getByTestId('application-component').first()).toContainText('活动次数')
  expect(backend.requests).toHaveLength(initialRequests)
  await page.getByRole('button', { name: '保存草稿', exact: true }).click()
  await expect.poll(() => backend.writes.length).toBe(1)
  expect(backend.draft.snapshot.page.placements.map(p => p.component_id)).toEqual(['component-72', 'component-71'])
  expect(backend.unexpected).toEqual([])
})

async function personnelApplication(context, { locale = 'zh-cn', withSelection = false, comparisonPerson = 'person-a', lookupEnabled = false } = {}) {
  const backend = await installMetricApplicationBackend(context, { rebound: true, locale, configure(draft, descriptors) {
    const [metric, directory] = draft.snapshot.components
    descriptors[71].input_contract.named_parameters = [{ name: 'person_id', type: 'string', required: true }]
    metric.title = '参加活动次数'
    metric.parameter_definitions = [{ key: 'person', label: '人员', control_type: 'text', required: true }]
    metric.query_template.named_parameter_bindings = [{ name: 'person_id', parameter_key: 'person' }]
    metric.query_template.select = ['bucket', 'value']
    metric.renderer_type = 'chart'
    metric.renderer_config = { chart_type: 'bar', dimension: 'bucket', measures: ['value'] }
    const fields = [{ name: 'person_id', type: 'string', nullable: false }, { name: 'nickname', type: 'string', nullable: true }]
    descriptors[72].input_contract = { fields: fields.map(f => ({ ...f, selectable: true, filterable: f.name === 'nickname' || lookupEnabled, operators: f.name === 'nickname' ? ['eq', 'contains'] : lookupEnabled ? ['eq'] : [] })), page: { default_limit: 50, max_limit: 100 }, order: { stable_key: ['person_id'] } }
    descriptors[72].output_contract.fields = fields
    directory.title = '选择人员'
    directory.renderer_type = 'table'
    directory.renderer_config = { columns: ['nickname'], field_presentations: [{ field: 'person_id', label: '人员编号' }, { field: 'nickname', label: '昵称' }] }
    directory.parameter_definitions = []
    directory.query_template = { select: ['person_id', 'nickname'], named_parameter_bindings: [], parameter_filters: [], page_limit: 50, order_by: [{ field: 'person_id', direction: 'asc' }], format: 'json' }
    const other = structuredClone(metric)
    other.id = 'component-73'; other.title = '活动次数对比'
    draft.snapshot.components.push(other)
    draft.snapshot.parameters = ['person_a', 'person_b'].map((key, i) => ({ key, label: i ? '对比人员' : '人员', control_type: 'text', required: true, default_value: i ? comparisonPerson : 'person-a' }))
    draft.snapshot.parameter_bindings = [metric, other].map((c, i) => ({ component_id: c.id, component_parameter_key: 'person', application_parameter_key: i ? 'person_b' : 'person_a' }))
    draft.snapshot.page.placements = draft.snapshot.components.map((c, i) => ({ component_id: c.id, x: 0, y: i * 6, width: 12, height: 6 }))
    if (withSelection) draft.snapshot.selection_bindings = [{ source_component_id: directory.id, assignments: draft.snapshot.parameters.map(p => ({ source_field: 'person_id', application_parameter_key: p.key })) }]
    draft.snapshot.parameter_presets = [{ key: 'original', name: '原始人员', parameter_values: { person_a: 'person-a', person_b: 'person-a' } }]
  } })
  const queries = []
  await context.route('**/api/query/metric_71/query', route => {
    queries.push(route.request().postDataJSON())
    return route.fulfill({ json: { data: [{ bucket: '2026-01-01', value: 3 }], page: { has_more: false, next_cursor: '' } } })
  })
  const directoryQueries = []
  await context.route('**/api/query/metric_72/query', route => {
    directoryQueries.push(route.request().postDataJSON())
    return route.fulfill({ json: { data: [{ person_id: 'person-c', nickname: '阿青' }], page: { has_more: false, next_cursor: '' } } })
  })
  return { backend, queries, directoryQueries }
}

for (const locale of ['zh-cn', 'en']) {
test(`existing component trials use current application defaults without saving trial overrides (${locale})`, async ({ page, context }) => {
  const en = locale === 'en'
  const { backend, queries } = await personnelApplication(context, { locale, comparisonPerson: 'person-b' })
  const original = backend.draft.snapshot
  await page.goto(applicationPath)
  const openEditor = () => page.getByTestId('component-inspector').getByRole('button', { name: en ? 'Fields and display settings' : '字段与展示设置', exact: true }).click()
  await openEditor()
  const editor = page.getByTestId('application-component-editor')
  const query = editor.getByTestId('component-query-action')
  await expect(query).toBeEnabled()
  await query.click()
  await expect.poll(() => queries.at(-1)?.parameters.person_id).toBe('person-a')
  await editor.getByRole('tab', { name: en ? '3. Set query inputs' : '3. 设置查询条件' }).click()
  const value = editor.getByRole('textbox', { name: en ? 'Test value' : '试查值', exact: true })
  await expect(value).toHaveValue('person-a')
  await value.fill('person-c')
  await query.click()
  await expect.poll(() => queries.at(-1)?.parameters.person_id).toBe('person-c')
  await page.getByRole('dialog').getByRole('button', { name: en ? 'Cancel' : '取消', exact: true }).click()
  await expect(editor).not.toBeVisible()
  expect(backend.draft.snapshot).toEqual(original)
  await openEditor()
  await editor.getByRole('tab', { name: en ? '3. Set query inputs' : '3. 设置查询条件' }).click()
  await expect(value).toHaveValue('person-a')
  await value.fill('person-c')
  await editor.getByRole('tab', { name: en ? '2. Configure display' : '2. 配置展示' }).click()
  await editor.locator('[data-field="value"]').getByRole('textbox', { name: en ? 'Display label' : '展示名称', exact: true }).fill('参加次数')
  const requestCount = queries.length
  await page.getByRole('dialog').getByRole('button', { name: en ? 'Apply component configuration' : '应用组件配置', exact: true }).click()
  await expect(editor).not.toBeVisible()
  await page.getByRole('button', { name: en ? 'Save draft' : '保存草稿', exact: true }).click()
  await expect.poll(() => backend.writes.length).toBe(1)
  const saved = backend.draft.snapshot
  expect(saved.parameters).toEqual(original.parameters)
  expect(saved.parameter_presets).toEqual(original.parameter_presets)
  expect(saved.components[0].default_parameter_values).toEqual(original.components[0].default_parameter_values)
  expect(saved.components[0].query_template).toEqual(original.components[0].query_template)
  expect(queries).toHaveLength(requestCount)

  // Unsaved filter edits are the next trial's source of truth.
  await page.getByRole('button', { name: en ? 'Filters' : '筛选条件', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByTestId('filter-card').first().getByRole('textbox').nth(1).fill('person-c')
  await dialog.getByRole('button', { name: en ? 'Done' : '完成设置', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await openEditor()
  await editor.getByRole('tab', { name: en ? '3. Set query inputs' : '3. 设置查询条件' }).click()
  await expect(value).toHaveValue('person-c')
  await query.click()
  await expect.poll(() => queries.at(-1)?.parameters.person_id).toBe('person-c')
  await value.fill('')
  await expect(query).toBeDisabled()
  await dialog.getByRole('button', { name: en ? 'Cancel' : '取消', exact: true }).click()
  await expect(editor).not.toBeVisible()
  await page.getByRole('button', { name: en ? 'Save draft' : '保存草稿', exact: true }).click()
  await expect.poll(() => backend.writes.length).toBe(2)
  await page.reload()
  await openEditor()
  await editor.getByRole('tab', { name: en ? '3. Set query inputs' : '3. 设置查询条件' }).click()
  await expect(value).toHaveValue('person-c')
  expect(backend.draft.snapshot.parameters.map(p => p.default_value)).toEqual(['person-c', 'person-b'])
  expect(backend.published).toEqual(backend.originalPublished)
  expect(backend.unexpected).toEqual([])
})
}

test('explicit personnel interaction can be cancelled, applied, edited and tried without publishing', async ({ page, context }) => {
  const { backend, queries } = await personnelApplication(context)
  await page.goto(applicationPath)
  await page.getByRole('button', { name: '点击联动', exact: true }).click()
  const drawer = page.getByRole('dialog')
  await drawer.getByRole('button', { name: '添加选择联动', exact: true }).click()
  const builder = drawer.getByTestId('interaction-builder')
  const apply = builder.getByRole('button', { name: '应用联动', exact: true })
  await expect(apply).toBeDisabled()
  await choose(page, builder.getByTestId('interaction-source'), '选择人员')
  await expect(apply).toBeDisabled()
  await choose(page, builder.getByTestId('interaction-field'), '人员编号 (person_id)')
  await expect(apply).toBeDisabled()
  await choose(page, builder.getByTestId('interaction-target'), '人员 · 参加活动次数')
  await expect(builder.getByTestId('interaction-impact')).toHaveText('将刷新：参加活动次数')
  await builder.getByRole('button', { name: '取消', exact: true }).click()
  await expect(drawer.getByTestId('interaction-card')).toHaveCount(0)
  await drawer.getByRole('button', { name: '添加选择联动', exact: true }).click()
  await choose(page, builder.getByTestId('interaction-source'), '选择人员')
  await choose(page, builder.getByTestId('interaction-field'), '人员编号 (person_id)')
  await choose(page, builder.getByTestId('interaction-target'), '人员 · 参加活动次数')
  await apply.click()
  await expect(drawer.getByTestId('interaction-card')).toContainText('人员编号 (person_id)')
  await drawer.getByRole('button', { name: '编辑联动', exact: true }).click()
  await builder.getByRole('button', { name: '添加字段映射', exact: true }).click()
  const second = builder.getByTestId('interaction-assignment').nth(1)
  // One source field can explicitly update two different filters; a target cannot be duplicated.
  await choose(page, second.getByTestId('interaction-field'), '人员编号 (person_id)')
  await choose(page, second.getByTestId('interaction-target'), '对比人员 · 活动次数对比')
  await expect(builder.getByTestId('interaction-impact')).toContainText('活动次数对比')
  await apply.click()
  await drawer.getByRole('button', { name: '完成设置', exact: true }).click()
  await page.getByTestId('draft-preview-action').click()
  const preview = page.getByRole('dialog')
  await preview.getByTestId('query-all-action').click()
  await preview.getByTestId('runtime-component').nth(1).getByRole('row', { name: '阿青', exact: true }).click()
  await expect.poll(() => queries.filter(q => q.parameters.person_id === 'person-c').length).toBe(2)
  expect(queries.some(q => q.parameters.person_id === '阿青')).toBe(false)
  await preview.getByRole('button', { name: '关闭此对话框', exact: true }).click()
  await page.getByRole('button', { name: '保存草稿', exact: true }).click()
  await expect.poll(() => backend.writes.length).toBe(1)
  expect(backend.draft.snapshot.selection_bindings).toEqual([{ source_component_id: 'component-72', assignments: [{ source_field: 'person_id', application_parameter_key: 'person_a' }, { source_field: 'person_id', application_parameter_key: 'person_b' }] }])
  await page.reload()
  await page.getByRole('button', { name: '点击联动', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: '编辑联动', exact: true }).click()
  await expect(page.getByTestId('interaction-builder').getByTestId('interaction-assignment')).toHaveCount(2)
  expect(backend.draft.snapshot.parameters.map(p => p.default_value)).toEqual(['person-a', 'person-a'])
  expect(backend.published).toEqual(backend.originalPublished)
  expect(backend.unexpected).toEqual([])
})

for (const locale of ['zh-cn', 'en']) {
test(`filter opens the existing interaction builder with its target selected (${locale})`, async ({ page, context }) => {
  const { backend } = await personnelApplication(context, { locale })
  await page.goto(applicationPath)
  await page.getByRole('button', { name: locale === 'en' ? 'Filters' : '筛选条件', exact: true }).click()
  await page.getByTestId('filter-card').last().getByRole('button', { name: locale === 'en' ? 'Choose this filter by clicking a component' : '通过点击组件选择此条件', exact: true }).click()
  const builder = page.getByTestId('interaction-builder')
  const apply = builder.getByRole('button', { name: locale === 'en' ? 'Apply interaction' : '应用联动', exact: true })
  await expect(apply).toBeDisabled()
  await expect(builder.getByTestId('interaction-target')).toContainText('对比人员')
  await choose(page, builder.getByTestId('interaction-source'), '选择人员')
  await choose(page, builder.getByTestId('interaction-field'), '人员编号 (person_id)')
  await expect(builder.getByTestId('interaction-target')).toContainText('对比人员 · 活动次数对比')
  await expect(apply).toBeEnabled()
  // A nullable nickname cannot fill a required ID filter; field changes must clear it.
  await choose(page, builder.getByTestId('interaction-field'), '昵称 (nickname)')
  await expect(apply).toBeDisabled()
  await builder.getByRole('button', { name: locale === 'en' ? 'Cancel' : '取消', exact: true }).click()
  await expect(page.getByTestId('interaction-card')).toHaveCount(0)
  expect(backend.writes).toEqual([])
  expect(backend.unexpected).toEqual([])
})
}

test('sharing a filter shows its scope and keeps both metric queries on the same original value', async ({ page, context }) => {
  const { backend, queries } = await personnelApplication(context)
  await page.goto(applicationPath)
  await page.getByRole('button', { name: '筛选条件', exact: true }).click()
  const drawer = page.getByRole('dialog')
  await choose(page, drawer.getByTestId('filter-binding-group').filter({ hasText: '活动次数对比' }), '人员 · 参加活动次数')
  const shared = drawer.getByTestId('filter-card').first()
  await expect(shared).toContainText('参加活动次数')
  await expect(shared).toContainText('活动次数对比')
  await shared.getByRole('textbox').nth(1).fill('person-c')
  await page.setViewportSize({ width: 560, height: 800 })
  expect(await drawer.evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
  await drawer.getByRole('button', { name: '完成设置', exact: true }).click()
  await page.getByRole('button', { name: '保存草稿', exact: true }).click()
  await expect.poll(() => backend.writes.length).toBe(1)
  expect(backend.draft.snapshot.parameters).toHaveLength(1)
  expect(backend.draft.snapshot.parameter_bindings.map(b => b.application_parameter_key)).toEqual(['person_a', 'person_a'])
  await page.getByRole('button', { name: '刷新画布数据', exact: true }).click()
  await expect.poll(() => queries.filter(q => q.parameters.person_id === 'person-c').length).toBeGreaterThanOrEqual(2)
  expect(backend.published).toEqual(backend.originalPublished)
  expect(backend.unexpected).toEqual([])
})

for (const locale of ['zh-cn', 'en']) {
test(`preview explicitly copies selected person IDs into initial values and preserves scenarios (${locale})`, async ({ page, context }) => {
  const { backend, queries } = await personnelApplication(context, { locale, withSelection: true })
  await page.goto(applicationPath)
  await page.getByTestId('draft-preview-action').click()
  const preview = page.getByRole('dialog')
  await expect(preview.getByTestId('apply-preview-defaults')).toHaveText(locale === 'en' ? 'Use as initial values' : '设为应用初始值')
  await page.setViewportSize({ width: 560, height: 800 })
  expect(await preview.evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
  const previewCanvas = preview.getByTestId('data-application-canvas')
  expect(await previewCanvas.evaluate(el => el.getBoundingClientRect().bottom <= window.innerHeight)).toBe(true)
  await preview.getByTestId('query-all-action').click()
  await preview.getByTestId('runtime-component').nth(1).getByRole('row', { name: '阿青', exact: true }).click()
  await expect.poll(() => queries.filter(q => q.parameters.person_id === 'person-c').length).toBe(2)
  // Ordinary close still discards interactive changes.
  await preview.getByRole('button', { name: locale === 'en' ? 'Close this dialog' : '关闭此对话框', exact: true }).click()
  await page.getByTestId('draft-preview-action').click()
  await expect(preview.locator('.parameters-card').getByRole('textbox')).toHaveCount(0)
  await preview.getByTestId('query-all-action').click()
  await expect.poll(() => queries.at(-1)?.parameters.person_id).toBe('person-a')
  await preview.getByTestId('query-all-action').click()
  await preview.getByTestId('runtime-component').nth(1).getByRole('row', { name: '阿青', exact: true }).click()
  await preview.getByTestId('apply-preview-defaults').click()
  await expect(preview).toHaveCount(0)
  expect(backend.writes).toHaveLength(0)
  await page.getByRole('button', { name: locale === 'en' ? 'Save draft' : '保存草稿', exact: true }).click()
  await expect.poll(() => backend.writes.length).toBe(1)
  expect(backend.draft.snapshot.parameters.map(p => p.default_value)).toEqual(['person-c', 'person-c'])
  expect(backend.draft.snapshot.parameter_presets[0].parameter_values).toEqual({ person_a: 'person-a', person_b: 'person-a' })
  expect(backend.published).toEqual(backend.originalPublished)
  await page.reload()
  await page.getByTestId('draft-preview-action').click()
  await expect(preview.locator('.parameters-card').getByRole('textbox')).toHaveCount(0)
  await preview.getByTestId('query-all-action').click()
  await expect.poll(() => queries.at(-1)?.parameters.person_id).toBe('person-c')
  expect(backend.unexpected).toEqual([])
})
}

test('preview refuses incomplete initial values without mutating the draft', async ({ page, context }) => {
  const { backend } = await personnelApplication(context)
  await page.goto(applicationPath)
  await page.getByTestId('draft-preview-action').click()
  const preview = page.getByRole('dialog')
  const person = preview.locator('.parameters-card').getByRole('textbox').first()
  await expect(person).toHaveValue('person-a')
  await person.fill('')
  await person.blur()
  await preview.getByTestId('apply-preview-defaults').click()
  await expect(page.getByText('暂时无法设为初始值：请补全必填条件，并确认数据服务契约已加载且条件值有效。', { exact: true })).toBeVisible()
  await expect(preview).toBeVisible()
  await preview.getByRole('button', { name: '关闭此对话框', exact: true }).click()
  await page.getByRole('button', { name: '保存草稿', exact: true }).click()
  await expect.poll(() => backend.writes.length).toBe(1)
  expect(backend.draft.snapshot.parameters.map(p => p.default_value)).toEqual(['person-a', 'person-a'])
  expect(backend.published).toEqual(backend.originalPublished)
})

for (const locale of ['zh-cn', 'en']) {
test(`new component explicitly reuses an existing filter for its test query and saved binding (${locale})`, async ({ page, context }) => {
  const backend = await installMetricApplicationBackend(context, { rebound: true, locale })
  await page.goto(applicationPath)
  const originalParameters = backend.draft.snapshot.parameters
  const add = page.getByRole('button', { name: locale === 'en' ? 'Add data service component' : '添加数据服务组件', exact: true })
  await add.click()
  const editor = page.getByTestId('application-component-editor')
  const serviceField = editor.locator('.el-form-item').filter({ hasText: locale === 'en' ? 'Data service' : '数据服务' })
  await choose(page, serviceField, '计数服务')
  await editor.getByRole('tab', { name: locale === 'en' ? '3. Set query inputs' : '3. 设置查询条件' }).click()
  const reuse = editor.getByTestId('parameter-reuse')
  await expect(reuse).toHaveCount(1)
  await expect(reuse).toContainText(locale === 'en' ? 'Create an independent filter' : '新建独立条件')
  await reuse.locator('.el-select__wrapper').click()
  const optionList = page.locator(`#${await reuse.getByRole('combobox').getAttribute('aria-controls')}`)
  await expect(optionList.getByRole('option', { name: '查询方向 · 双方重叠率', exact: true })).toHaveAttribute('aria-disabled', 'true')
  await optionList.getByRole('option', { name: '统计粒度 · 双方重叠率' + (locale === 'en' ? ', ' : '、') + '活动次数', exact: true }).click()
  await editor.getByTestId('component-query-action').click()
  await expect(editor.locator('tbody tr')).toHaveCount(1)
  expect(backend.requests.at(-1).body.parameters).toEqual({ grain: 'total' })
  await page.getByRole('dialog').getByRole('button', { name: locale === 'en' ? 'Cancel' : '取消', exact: true }).click()
  await expect(page.getByTestId('runtime-component')).toHaveCount(2)
  expect(backend.writes).toHaveLength(0)
  await add.click()
  await choose(page, serviceField, '计数服务')
  await editor.getByRole('tab', { name: locale === 'en' ? '3. Set query inputs' : '3. 设置查询条件' }).click()
  await expect(reuse).toContainText(locale === 'en' ? 'Create an independent filter' : '新建独立条件')
  await choose(page, reuse, '统计粒度 · 双方重叠率' + (locale === 'en' ? ', ' : '、') + '活动次数')
  await page.getByRole('dialog').getByRole('button', { name: locale === 'en' ? 'Apply component configuration' : '应用组件配置', exact: true }).click()
  await expect(page.getByTestId('runtime-component')).toHaveCount(3)
  await page.getByRole('button', { name: locale === 'en' ? 'Save draft' : '保存草稿', exact: true }).click()
  await expect.poll(() => backend.writes.length).toBe(1)
  expect(backend.draft.snapshot.parameters).toEqual(originalParameters)
  const newComponent = backend.draft.snapshot.components[2]
  expect(backend.draft.snapshot.parameter_bindings.filter(b => b.component_id === newComponent.id)).toEqual([{ component_id: newComponent.id, component_parameter_key: newComponent.parameter_definitions[0].key, application_parameter_key: 'shared_grain' }])
  expect(JSON.stringify(newComponent)).not.toContain('applicationParameterKey')
  expect(backend.published).toEqual(backend.originalPublished)
  await page.reload()
  await expect(page.getByTestId('runtime-component')).toHaveCount(3)
  await page.getByRole('button', { name: locale === 'en' ? 'Filters' : '筛选条件', exact: true }).click()
  await expect(page.getByTestId('filter-card').first()).toContainText('计数服务')
  expect(backend.unexpected).toEqual([])
})
}


for (const locale of ['zh-cn', 'en']) {
test(`duplicate a chart and switch its person filter without changing the source (${locale})`, async ({ page, context }) => {
  const { backend, queries } = await personnelApplication(context, { locale, withSelection: true, comparisonPerson: 'person-b' })
  const original = backend.draft.snapshot
  await page.goto(applicationPath)
  const inspector = page.getByTestId('component-inspector')
  await inspector.getByRole('button', { name: locale === 'en' ? 'Half' : '半宽', exact: true }).click()
  const duplicate = inspector.getByRole('button', { name: locale === 'en' ? 'Duplicate component' : '复制组件', exact: true })
  await duplicate.click()
  const editor = page.getByTestId('application-component-editor')
  await expect(editor.getByRole('tab', { name: locale === 'en' ? '3. Set query inputs' : '3. 设置查询条件' })).toHaveAttribute('aria-selected', 'true')
  const reuse = editor.getByTestId('parameter-reuse')
  await expect(reuse).toContainText('人员 · 参加活动次数')
  await expect(editor.locator('.parameter').getByRole('textbox')).toHaveCount(0)
  await editor.getByTestId('component-query-action').click()
  await expect.poll(() => queries.at(-1)?.parameters.person_id).toBe('person-a')
  await choose(page, reuse, '对比人员 · 活动次数对比')
  await page.getByRole('dialog').getByRole('button', { name: locale === 'en' ? 'Cancel' : '取消', exact: true }).click()
  await expect(page.getByTestId('runtime-component')).toHaveCount(3)
  expect(backend.writes).toHaveLength(0)
  await duplicate.click()
  await expect(reuse).toContainText('人员 · 参加活动次数')
  await choose(page, reuse, '对比人员 · 活动次数对比')
  await editor.getByRole('textbox', { name: locale === 'en' ? 'Component title' : '组件标题', exact: true }).filter({ visible: true }).fill('人员 B 活动次数')
  await editor.getByTestId('component-query-action').click()
  await expect.poll(() => queries.at(-1)?.parameters.person_id).toBe('person-b')
  if (locale === 'en') await page.setViewportSize({ width: 680, height: 900 })
  expect(await page.getByRole('dialog').evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
  await page.screenshot({ path: test.info().outputPath('duplicate-component.png') })
  await page.getByRole('dialog').getByRole('button', { name: locale === 'en' ? 'Apply component configuration' : '应用组件配置', exact: true }).click()
  await expect(page.getByTestId('runtime-component')).toHaveCount(4)
  await page.getByRole('button', { name: locale === 'en' ? 'Save draft' : '保存草稿', exact: true }).click()
  await expect.poll(() => backend.writes.length).toBe(1)
  const snapshot = backend.draft.snapshot
  const copied = snapshot.components.at(-1)
  expect(copied.id).not.toBe(original.components[0].id)
  expect(copied.title).toBe('人员 B 活动次数')
  expect(copied.renderer_type).toBe('chart')
  expect(copied.renderer_config).toMatchObject(original.components[0].renderer_config)
  expect(copied.query_template).toEqual(original.components[0].query_template)
  expect(snapshot.components.slice(0, 3)).toEqual(original.components)
  expect(snapshot.parameters).toEqual(original.parameters)
  expect(snapshot.parameter_presets).toEqual(original.parameter_presets)
  expect(snapshot.selection_bindings).toEqual(original.selection_bindings)
  expect(snapshot.parameter_bindings.at(-1)).toEqual({ component_id: copied.id, component_parameter_key: 'person', application_parameter_key: 'person_b' })
  expect(snapshot.page.placements.slice(0, 2)).toEqual([
    { component_id: 'component-71', x: 0, y: 0, width: 6, height: 6 },
    { component_id: copied.id, x: 6, y: 0, width: 6, height: 6 },
  ])
  expect(backend.published).toEqual(backend.originalPublished)
  await page.reload()
  await expect(page.getByTestId('application-component').nth(1)).toContainText('人员 B 活动次数')
  expect(backend.unexpected).toEqual([])
})
}

for (const locale of ['zh-cn', 'en']) {
test(`independent copied filter exposes its name and persists separately (${locale})`, async ({ page, context }) => {
  const { backend, queries } = await personnelApplication(context, { locale })
  const original = backend.draft.snapshot
  await page.goto(applicationPath)
  await page.getByTestId('component-inspector').getByRole('button', { name: locale === 'en' ? 'Duplicate component' : '复制组件', exact: true }).click()
  const editor = page.getByTestId('application-component-editor')
  const name = editor.getByRole('textbox', { name: locale === 'en' ? 'Filter name' : '筛选名称', exact: true })
  await expect(name).toHaveCount(0)
  await choose(page, editor.getByTestId('parameter-reuse'), locale === 'en' ? 'Create an independent filter' : '新建独立条件')
  await expect(name).toBeVisible()
  await name.fill('人员 C')
  await editor.getByRole('textbox', { name: locale === 'en' ? 'Value on opening' : '打开应用时的值', exact: true }).fill('person-c')
  await editor.getByTestId('component-query-action').click()
  await expect.poll(() => queries.at(-1)?.parameters.person_id).toBe('person-c')
  await page.getByRole('dialog').getByRole('button', { name: locale === 'en' ? 'Apply component configuration' : '应用组件配置', exact: true }).click()
  await page.getByRole('button', { name: locale === 'en' ? 'Save draft' : '保存草稿', exact: true }).click()
  await expect.poll(() => backend.writes.length).toBe(1)
  const snapshot = backend.draft.snapshot
  expect(snapshot.parameters.slice(0, 2)).toEqual(original.parameters)
  expect(snapshot.parameters.at(-1)).toMatchObject({ label: '人员 C', default_value: 'person-c' })
  expect(snapshot.parameter_bindings.at(-1).application_parameter_key).toBe(snapshot.parameters.at(-1).key)
  expect(snapshot.components.slice(0, 3)).toEqual(original.components)
  expect(backend.published).toEqual(backend.originalPublished)
  await page.reload()
  await page.getByRole('button', { name: locale === 'en' ? 'Filters' : '筛选条件', exact: true }).click()
  await expect(page.getByRole('textbox', { name: locale === 'en' ? 'Filter name' : '筛选名称', exact: true }).last()).toHaveValue('人员 C')
  expect(backend.unexpected).toEqual([])
})
}

test('duplicating a selection source adds no click interaction and creates a fresh identity each time', async ({ page, context }) => {
  const { backend } = await personnelApplication(context, { withSelection: true })
  await page.goto(applicationPath)
  await page.getByTestId('application-component').filter({ hasText: '选择人员' }).locator('.outline-select').click()
  const inspector = page.getByTestId('component-inspector')
  const duplicate = inspector.getByRole('button', { name: '复制组件', exact: true })
  for (let i = 0; i < 2; i++) {
    await duplicate.click()
    await expect(page.getByTestId('application-component-editor').getByTestId('parameter-reuse')).toHaveCount(0)
    await page.getByRole('dialog').getByRole('button', { name: '应用组件配置', exact: true }).click()
    await expect(page.getByTestId('runtime-component')).toHaveCount(4 + i)
  }
  await page.getByRole('button', { name: '保存草稿', exact: true }).click()
  await expect.poll(() => backend.writes.length).toBe(1)
  const snapshot = backend.draft.snapshot
  expect(new Set(snapshot.components.map(c => c.id)).size).toBe(5)
  expect(snapshot.selection_bindings).toEqual(backend.originalPublished.snapshot.selection_bindings)
  expect(snapshot.parameters).toEqual(backend.originalPublished.snapshot.parameters)
  expect(backend.unexpected).toEqual([])
})

test('copying a stale contract requires explicit reconfiguration before trial or apply', async ({ page, context }) => {
  const backend = await installMetricApplicationBackend(context)
  backend.rebindServices()
  await page.goto(applicationPath)
  await page.getByTestId('component-inspector').getByRole('button', { name: '复制组件', exact: true }).click()
  const editor = page.getByTestId('application-component-editor')
  await expect(editor.getByTestId('contract-changed-alert')).toBeVisible()
  await expect(editor.getByTestId('component-query-action')).toBeDisabled()
  const apply = page.getByRole('dialog').getByRole('button', { name: '应用组件配置', exact: true })
  await expect(apply).toBeDisabled()
  await editor.getByRole('button', { name: '按当前服务契约重新配置', exact: true }).click()
  await expect(editor.getByTestId('contract-changed-alert')).toHaveCount(0)
  for (const reuse of await editor.getByTestId('parameter-reuse').all()) await expect(reuse).toContainText('新建独立条件')
  const parameters = editor.locator('.parameter')
  await choose(page, parameters.nth(0).locator('.el-select').last(), '全期')
  await choose(page, parameters.nth(1).locator('.el-select').last(), '双向')
  await editor.getByTestId('component-query-action').click()
  await expect(editor.locator('tbody tr')).toHaveCount(2)
  await expect(apply).toBeEnabled()
  await page.getByRole('dialog').getByRole('button', { name: '取消', exact: true }).click()
  await expect(page.getByTestId('runtime-component')).toHaveCount(2)
  expect(backend.writes).toHaveLength(0)
  expect(backend.unexpected).toEqual([])
})


for (const locale of ['zh-cn', 'en']) {
test(`new application uses an explicit field suggestion and queries only after required inputs (${locale})`, async ({ page, context }) => {
  const backend = await installMetricApplicationBackend(context, { rebound: true, locale })
  await page.goto('/workbench/applications/new')
  await page.getByTestId('start-table').click()
  const editor = page.getByTestId('application-component-editor')
  await choose(page, editor.locator('.el-form-item').filter({ hasText: locale === 'en' ? 'Data service' : '数据服务' }), '定向重叠率服务')
  await expect(editor.getByTestId('suggestion-line')).toContainText('bucket → value')
  await expect(editor.getByTestId('suggestion-bar')).toContainText('direction → value')
  await expect(editor.getByTestId('suggestion-map')).toHaveCount(0)
  expect(backend.requests).toHaveLength(0)
  await editor.getByTestId('suggestion-line').click()
  await expect(editor.getByRole('tab', { name: locale === 'en' ? '3. Set query inputs' : '3. 设置查询条件' })).toHaveAttribute('aria-selected', 'true')
  expect(backend.requests).toHaveLength(0)
  const parameters = editor.locator('.parameter')
  await choose(page, parameters.nth(0), locale === 'en' ? 'Total' : '全期')
  await choose(page, parameters.nth(1), locale === 'en' ? 'Both directions' : '双向')
  await editor.getByTestId('component-query-action').click()
  await expect(editor.locator('canvas')).toBeVisible()
  expect(backend.requests.at(-1).body.select).toEqual(['bucket', 'value'])
  expect(backend.requests.at(-1).body.parameters).toEqual({ grain: 'total', directions: 'both' })
  await page.getByRole('dialog').getByRole('button', { name: locale === 'en' ? 'Apply component configuration' : '应用组件配置', exact: true }).click()
  await page.getByRole('button', { name: locale === 'en' ? 'Create draft' : '创建草稿', exact: true }).click()
  await expect.poll(() => backend.writes.length).toBe(1)
  const component = backend.draft.snapshot.components[0]
  expect(component.renderer_type).toBe('chart')
  expect(component.renderer_config).toMatchObject({ chart_type: 'line', dimension: 'bucket', measures: ['value'] })
  expect(JSON.stringify(component)).not.toContain('suggestion')
  await expect(page).toHaveURL(new RegExp(applicationPath + '$'))
  await page.reload()
  await expect(page.getByTestId('runtime-component').locator('canvas')).toBeVisible()
  expect(backend.unexpected).toEqual([])
})
}

test('choosing a display queries valid service defaults and switching services clears the result', async ({ page, context }) => {
  const backend = await installMetricApplicationBackend(context, { rebound: true, configure(_draft, descriptors) {
    descriptors[72].input_contract.named_parameters[0].default = 'total'
  } })
  await page.setViewportSize({ width: 680, height: 900 })
  await page.goto('/workbench/applications/new')
  await page.getByTestId('start-value').click()
  const editor = page.getByTestId('application-component-editor')
  const service = editor.locator('.el-form-item').filter({ hasText: '数据服务' })
  await choose(page, service, '计数服务')
  expect(backend.requests).toHaveLength(0)
  await expect(editor.getByTestId('suggestion-bar')).toHaveCount(0)
  expect(await page.getByRole('dialog').evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
  await page.screenshot({ path: test.info().outputPath('display-suggestions.png') })
  await editor.getByTestId('suggestion-line').click()
  await expect(editor.locator('canvas')).toBeVisible()
  expect(backend.requests).toHaveLength(1)
  expect(backend.requests[0].body.page.limit).toBe(50)
  await editor.getByRole('tab', { name: '1. 选择数据' }).click()
  await choose(page, service, '定向重叠率服务')
  await expect(editor.locator('canvas')).toHaveCount(0)
  await expect(editor.getByTestId('suggestion-bar')).toBeVisible()
  expect(backend.requests).toHaveLength(1)
  await page.getByRole('dialog').getByRole('button', { name: '取消', exact: true }).click()
  await expect(page.getByTestId('application-start')).toBeVisible()
  expect(backend.writes).toHaveLength(0)
  expect(backend.unexpected).toEqual([])
})


for (const locale of ['zh-cn', 'en']) {
test(`search-list wizard creates search and ID selection together (${locale})`, async ({ page, context }) => {
  const { backend, queries, directoryQueries } = await personnelApplication(context, { locale })
  const original = backend.draft.snapshot
  await page.goto(applicationPath)
  await page.getByRole('button', { name: locale === 'en' ? 'Filters' : '筛选条件', exact: true }).click()
  await page.getByTestId('filter-card').last().getByRole('button', { name: locale === 'en' ? 'Create a search list' : '创建搜索列表', exact: true }).click()
  const editor = page.getByTestId('application-component-editor')
  await choose(page, editor.locator('.el-form-item').filter({ hasText: locale === 'en' ? 'Data service' : '数据服务' }), '计数服务')
  await expect(editor.getByTestId('display-suggestions')).toHaveCount(0)
  await page.getByRole('dialog').getByRole('button', { name: locale === 'en' ? 'Next step' : '下一步', exact: true }).click()
  await choose(page, editor.getByTestId('selection-list-search'), 'nickname')
  await choose(page, editor.getByTestId('selection-list-label'), 'nickname')
  await choose(page, editor.getByTestId('selection-list-value'), 'person_id')
  await page.getByRole('dialog').getByRole('button', { name: locale === 'en' ? 'Next step' : '下一步', exact: true }).click()
  await editor.getByRole('textbox', { name: locale === 'en' ? 'Value on opening' : '打开应用时的值', exact: true }).fill('阿')
  await editor.getByTestId('component-query-action').click()
  await expect.poll(() => directoryQueries.at(-1)?.filter).toEqual({ field: 'nickname', op: 'contains', value: '阿' })
  await page.setViewportSize({ width: 680, height: 900 })
  expect(await page.getByRole('dialog').evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
  await page.getByRole('dialog').getByRole('button', { name: locale === 'en' ? 'Apply component configuration' : '应用组件配置', exact: true }).click()
  await page.getByRole('button', { name: locale === 'en' ? 'Save draft' : '保存草稿', exact: true }).click()
  await expect.poll(() => backend.writes.length).toBe(1)
  const snapshot = backend.draft.snapshot
  const source = snapshot.components.at(-1)
  expect(snapshot.components.slice(0, 3)).toEqual(original.components)
  expect(snapshot.parameters.slice(0, 2)).toEqual(original.parameters)
  expect(snapshot.selection_bindings).toEqual([{ source_component_id: source.id, assignments: [{ source_field: 'person_id', application_parameter_key: 'person_b' }] }])
  expect(source.query_template.parameter_filters).toEqual([{ parameter_key: source.parameter_definitions[0].key, field: 'nickname', operator: 'contains' }])
  expect(source.query_template.select).toEqual(['nickname', 'person_id'])
  await page.reload()
  await page.getByTestId('draft-preview-action').click()
  const preview = page.getByRole('dialog')
  await preview.getByTestId('query-all-action').click()
  await preview.getByTestId('runtime-component').last().getByRole('row').filter({ hasText: '阿青' }).click()
  await expect.poll(() => queries.filter(q => q.parameters.person_id === 'person-c').length).toBe(1)
  expect(backend.published).toEqual(backend.originalPublished)
  expect(backend.unexpected).toEqual([])
})
}

test('search-list wizard clears fields on service change and cancellation leaves no partial component', async ({ page, context }) => {
  const { backend } = await personnelApplication(context)
  await page.goto(applicationPath)
  await page.getByRole('button', { name: '筛选条件', exact: true }).click()
  await page.getByTestId('filter-card').first().getByRole('button', { name: '创建搜索列表', exact: true }).click()
  const editor = page.getByTestId('application-component-editor')
  const service = editor.locator('.el-form-item').filter({ hasText: '数据服务' })
  await choose(page, service, '计数服务')
  await page.getByRole('dialog').getByRole('button', { name: '下一步', exact: true }).click()
  await choose(page, editor.getByTestId('selection-list-search'), 'nickname')
  await choose(page, editor.getByTestId('selection-list-label'), 'nickname')
  await choose(page, editor.getByTestId('selection-list-value'), 'person_id')
  await editor.getByTestId('component-query-action').click()
  await expect(editor.locator('tbody tr')).toHaveCount(1)
  await editor.getByRole('tab', { name: '1. 选择数据', exact: true }).click()
  await choose(page, service, '定向重叠率服务')
  await expect(editor.locator('tbody tr')).toHaveCount(0)
  await editor.getByRole('tab', { name: '2. 配置展示', exact: true }).click()
  await expect(editor.getByTestId('selection-list-fields')).not.toContainText('nickname')
  await expect(editor.getByTestId('component-query-action')).toBeDisabled()
  await page.getByRole('dialog').getByRole('button', { name: '取消', exact: true }).click()
  await expect(page.getByTestId('runtime-component')).toHaveCount(3)
  await page.getByRole('button', { name: '点击联动', exact: true }).click()
  await expect(page.getByTestId('interaction-card')).toHaveCount(0)
  expect(backend.writes).toEqual([])
  expect(backend.unexpected).toEqual([])
})

for (const locale of ['zh-cn', 'en']) {
test(`new application continues from first chart through search selection to initial values (${locale})`, async ({ page, context }) => {
  const { backend, queries } = await personnelApplication(context, { locale })
  const isEnglish = locale === 'en'
  await page.goto('/workbench/applications/new')
  await page.getByTestId('start-chart').click()
  const editor = page.getByTestId('application-component-editor')
  const dialog = page.getByRole('dialog')
  const service = editor.locator('.el-form-item').filter({ hasText: isEnglish ? 'Data service' : '数据服务' })
  await choose(page, service, '定向重叠率服务')
  await editor.getByTestId('suggestion-line').click()
  await expect(editor.getByTestId('component-query-action')).toBeDisabled()
  await dialog.getByRole('button', { name: isEnglish ? 'Apply component configuration' : '应用组件配置', exact: true }).click()
  const guide = page.getByTestId('application-creation-guide')
  await expect(guide).toBeVisible()
  await choose(page, guide.locator('.el-form-item'), 'person_id · 定向重叠率服务')
  await guide.getByRole('button', { name: isEnglish ? 'Create a search list' : '创建搜索列表', exact: true }).click()
  await dialog.getByRole('button', { name: isEnglish ? 'Cancel' : '取消', exact: true }).click()
  await expect(page.getByTestId('runtime-component')).toHaveCount(1)
  await guide.getByRole('button', { name: isEnglish ? 'Create a search list' : '创建搜索列表', exact: true }).click()
  await choose(page, service, '计数服务')
  await dialog.getByRole('button', { name: isEnglish ? 'Next step' : '下一步', exact: true }).click()
  await choose(page, editor.getByTestId('selection-list-search'), 'nickname')
  await choose(page, editor.getByTestId('selection-list-label'), 'nickname')
  await choose(page, editor.getByTestId('selection-list-value'), 'person_id')
  await dialog.getByRole('button', { name: isEnglish ? 'Next step' : '下一步', exact: true }).click()
  await dialog.getByRole('button', { name: isEnglish ? 'Apply component configuration' : '应用组件配置', exact: true }).click()
  await expect(guide.getByRole('combobox')).toHaveCount(0)
  await expect(guide).toContainText(isEnglish ? '1 search selectors configured.' : '已配置 1 个搜索选值入口。')
  await page.setViewportSize({ width: 680, height: 900 })
  expect(await guide.evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
  await guide.getByRole('button', { name: isEnglish ? 'Preview and set initial values' : '预览并设置初始值', exact: true }).click()
  const source = dialog.getByTestId('runtime-component').first()
  await expect(source).toContainText(isEnglish ? 'Search and select person_id' : '搜索并选择person_id')
  await source.getByRole('button', { name: isEnglish ? 'Query' : '查询', exact: true }).click()
  await source.getByRole('row').filter({ hasText: '阿青' }).click()
  await expect.poll(() => queries.at(-1)?.parameters.person_id).toBe('person-c')
  await dialog.getByTestId('apply-preview-defaults').click()
  await page.getByRole('button', { name: isEnglish ? 'Create draft' : '创建草稿', exact: true }).click()
  await expect.poll(() => backend.writes.length).toBe(1)
  expect(backend.writes[0].action).toBe('create')
  const snapshot = backend.draft.snapshot
  expect(snapshot.components).toHaveLength(2)
  const targetKey = snapshot.selection_bindings[0].assignments[0].application_parameter_key
  expect(snapshot.parameters.find(parameter => parameter.key === targetKey).default_value).toBe('person-c')
  expect(snapshot.page.placements[0].component_id).toBe(snapshot.selection_bindings[0].source_component_id)
  expect(backend.published).toEqual(backend.originalPublished)
  await expect(page).toHaveURL(new RegExp(applicationPath + '$'))
  await page.reload()
  await expect(page.getByTestId('application-creation-guide')).toHaveCount(0)
  await expect(page.getByTestId('runtime-component')).toHaveCount(2)
  expect(backend.unexpected).toEqual([])
})
}

for (const locale of ['zh-cn', 'en']) {
test(`bound values use a result picker for trials, defaults and presets without manual identifiers (${locale})`, async ({ page, context }) => {
  const en = locale === 'en'
  const { backend, queries } = await personnelApplication(context, { locale, withSelection: true, comparisonPerson: 'person-b' })
  await page.goto(applicationPath)
  const openEditor = () => page.getByTestId('component-inspector').getByRole('button', { name: en ? 'Fields and display settings' : '字段与展示设置', exact: true }).click()
  await openEditor()
  const editor = page.getByTestId('application-component-editor')
  await editor.getByRole('tab', { name: en ? '3. Set query inputs' : '3. 设置查询条件' }).click()
  await expect(editor.getByRole('textbox', { name: en ? 'Test value' : '试查值', exact: true })).toHaveCount(0)
  const picker = () => page.getByRole('dialog', { name: en ? 'Select 人员' : '选择人员', exact: true })
  const query = editor.getByTestId('component-query-action')
  await editor.getByTestId('selection-value').getByRole('button').click()
  await expect(picker().getByRole('row', { name: '阿青', exact: true })).toBeVisible()
  const count = queries.length
  await picker().getByRole('button', { name: en ? 'Cancel' : '取消', exact: true }).click()
  await expect(picker()).toHaveCount(0)
  await query.click()
  await expect.poll(() => queries.at(-1)?.parameters.person_id).toBe('person-a')
  expect(queries).toHaveLength(count + 1)
  await editor.getByTestId('selection-value').getByRole('button').click()
  await picker().getByRole('row', { name: '阿青', exact: true }).click()
  await expect(picker()).toHaveCount(0)
  await query.click()
  await expect.poll(() => queries.at(-1)?.parameters.person_id).toBe('person-c')
  await page.getByRole('dialog').getByRole('button', { name: en ? 'Apply component configuration' : '应用组件配置', exact: true }).click()
  await expect(editor).not.toBeVisible()
  await page.getByRole('button', { name: en ? 'Save draft' : '保存草稿', exact: true }).click()
  await expect.poll(() => backend.writes.length).toBe(1)
  expect(backend.draft.snapshot.parameters.map(p => p.default_value)).toEqual(['person-a', 'person-b'])
  expect(backend.draft.snapshot.components[0].default_parameter_values).toEqual({})

  await page.getByRole('button', { name: en ? 'Filters' : '筛选条件', exact: true }).click()
  const filter = page.getByTestId('filter-card').first()
  await expect(filter.getByRole('textbox')).toHaveCount(1) // Only the editable label remains.
  await filter.getByTestId('selection-value').getByRole('button').click()
  await page.setViewportSize({ width: 560, height: 800 })
  await expect(picker().getByTestId('runtime-component')).toHaveCount(1)
  expect(await picker().evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
  await picker().getByRole('row', { name: '阿青', exact: true }).click()
  await expect(picker()).toHaveCount(0)
  await page.getByRole('dialog').getByRole('button', { name: en ? 'Done' : '完成设置', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: en ? 'Save draft' : '保存草稿', exact: true }).click()
  await expect.poll(() => backend.writes.length).toBe(2)
  expect(backend.draft.snapshot.parameters.map(p => p.default_value)).toEqual(['person-c', 'person-b'])
  expect(backend.draft.snapshot.parameter_presets[0].parameter_values).toEqual({ person_a: 'person-a', person_b: 'person-a' })

  await page.getByRole('button', { name: en ? 'Scenarios' : '场景预设', exact: true }).click()
  const preset = page.locator('.parameter-preset-card')
  await expect(preset.getByRole('textbox')).toHaveCount(2) // Scenario name and key only.
  await preset.getByTestId('selection-value').first().getByRole('button').click()
  await picker().getByRole('row', { name: '阿青', exact: true }).click()
  await expect(picker()).toHaveCount(0)
  await page.getByRole('dialog').getByRole('button', { name: en ? 'Done' : '完成设置', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: en ? 'Save draft' : '保存草稿', exact: true }).click()
  await expect.poll(() => backend.writes.length).toBe(3)
  expect(backend.draft.snapshot.parameter_presets[0].parameter_values).toEqual({ person_a: 'person-c', person_b: 'person-a' })
  expect(backend.draft.snapshot.parameters.map(p => p.default_value)).toEqual(['person-c', 'person-b'])
  expect(backend.published).toEqual(backend.originalPublished)
  expect(backend.unexpected).toEqual([])
})
}

for (const locale of ['zh-cn', 'en']) {
test(`explicit live names survive reload, isolate trial and preset values, and never come from the current directory page (${locale})`, async ({ page, context }) => {
  const en = locale === 'en'
  const { backend, queries } = await personnelApplication(context, { locale, withSelection: true, lookupEnabled: true, comparisonPerson: 'person-b' })
  const names = { 'person-a': '最新甲', 'person-b': '最新乙', 'person-c': '最新阿青' }
  const lookups = []
  await context.route('**/api/query/metric_72/query', route => {
    const body = route.request().postDataJSON()
    if (body.filter?.field === 'person_id' && body.filter.op === 'eq') {
      lookups.push(body)
      return route.fulfill({ json: { data: [{ person_id: body.filter.value, nickname: names[body.filter.value] }], page: { has_more: false } } })
    }
    return route.fulfill({ json: { data: [{ person_id: 'person-c', nickname: '目录旧昵称' }], page: { has_more: false } } })
  })
  await page.goto(applicationPath)
  await page.getByRole('button', { name: en ? 'Filters' : '筛选条件', exact: true }).click()
  const filter = page.getByTestId('filter-card').first()
  await choose(page, filter.getByTestId('display-source'), '选择人员')
  await choose(page, filter.getByTestId('display-label-field'), '昵称 (nickname)')
  await expect(filter.getByRole('status')).toHaveText('最新甲')
  expect(lookups.at(-1).page).toEqual({ limit: 2, cursor: '' })
  await page.getByRole('dialog').getByRole('button', { name: en ? 'Done' : '完成设置', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: en ? 'Save draft' : '保存草稿', exact: true }).click()
  await expect.poll(() => backend.writes.length).toBe(1)
  expect(backend.draft.snapshot.parameters[0].display_source).toEqual({ source_component_id: 'component-72', label_field: 'nickname' })
  expect(JSON.stringify(backend.draft.snapshot)).not.toContain('最新甲')
  names['person-a'] = '改名后的甲'
  await page.reload()
  await page.getByRole('button', { name: en ? 'Fields and display settings' : '字段与展示设置', exact: true }).click()
  const editor = page.getByTestId('application-component-editor')
  await editor.getByRole('tab', { name: en ? '3. Set query inputs' : '3. 设置查询条件', exact: true }).click()
  await expect(editor.getByRole('status')).toHaveText('改名后的甲')
  await editor.getByTestId('selection-value').getByRole('button').click()
  const picker = page.getByRole('dialog', { name: en ? 'Select 人员' : '选择人员', exact: true })
  await picker.getByRole('row', { name: '目录旧昵称', exact: true }).click()
  await expect(picker).toHaveCount(0)
  await expect(editor.getByRole('status')).toHaveText('最新阿青')
  await editor.getByTestId('component-query-action').click()
  await expect.poll(() => queries.at(-1)?.parameters.person_id).toBe('person-c')
  await page.getByRole('dialog').getByRole('button', { name: en ? 'Cancel' : '取消', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByTestId('draft-preview-action').click()
  const preview = page.getByRole('dialog')
  await expect(preview.getByRole('status').first()).toHaveText('改名后的甲')
  await preview.getByTestId('query-all-action').click()
  await preview.getByRole('row', { name: '目录旧昵称', exact: true }).click()
  await expect(preview.getByRole('status').first()).toHaveText('最新阿青')
  await choose(page, preview.getByTestId('parameter-preset-select'), '原始人员')
  await expect(preview.getByRole('status').first()).toHaveText('改名后的甲')
  await expect.poll(() => queries.at(-1)?.parameters.person_id).toBe('person-a')
  await preview.getByRole('button', { name: en ? 'Close this dialog' : '关闭此对话框', exact: true }).click()
  await expect(preview).toHaveCount(0)
  await page.getByRole('button', { name: en ? 'Scenarios' : '场景预设', exact: true }).click()
  await expect(page.locator('.parameter-preset-card').getByRole('status').first()).toHaveText('改名后的甲')
  expect(backend.draft.snapshot.parameters.map(p => p.default_value)).toEqual(['person-a', 'person-b'])
  expect(backend.draft.snapshot.parameter_presets[0].parameter_values).toEqual({ person_a: 'person-a', person_b: 'person-a' })
  expect(backend.published).toEqual(backend.originalPublished)
  expect(backend.unexpected).toEqual([])
})
}
