import { test, expect } from '@playwright/test'
import { applicationPath, installMetricApplicationBackend } from './fixtures/metricApplication.js'

async function choose(page, field, label) {
  await field.locator('.el-select__wrapper').click()
  const id = await field.getByRole('combobox').getAttribute('aria-controls')
  await page.locator(`#${id}`).getByRole('option', { name: label, exact: true }).click()
}

test('canvas selection, title, layout and formatting edit one draft without changing its publication', async ({ page, context }) => {
  const backend = await installMetricApplicationBackend(context, { rebound: true })
  await page.goto(applicationPath)
  const cards = page.getByTestId('runtime-component')
  const inspector = page.getByTestId('component-inspector')
  await expect(cards.first().locator('tbody tr')).toHaveCount(2)
  const initialRequests = backend.requests.length
  await cards.first().click()
  await inspector.getByRole('textbox', { name: '组件标题', exact: true }).fill('新的结果标题')
  await expect(cards.first().locator('.component-title')).toContainText('新的结果标题')
  await inspector.getByRole('button', { name: '整行', exact: true }).click()
  await expect(cards.first()).toHaveCSS('grid-column-end', 'span 12')
  await inspector.getByRole('button', { name: '后移', exact: true }).click()
  await expect(cards.first().locator('.component-title')).toContainText('活动次数')
  expect(backend.requests).toHaveLength(initialRequests)
  await inspector.getByRole('button', { name: '字段与展示设置', exact: true }).click()
  const editor = page.getByTestId('application-component-editor')
  await expect(editor.getByRole('tab', { name: '2. 配置展示' })).toHaveAttribute('aria-selected', 'true')
  // The persisted table's numeric presentation has the only precision input.
  await editor.getByPlaceholder('小数位', { exact: true }).fill('2')
  await page.getByRole('dialog').getByRole('button', { name: '应用组件配置', exact: true }).click()
  await expect(cards.nth(1).locator('tbody tr')).toHaveCount(2)
  await expect(cards.nth(1).locator('tbody tr').first()).toContainText('0.25')
  expect(backend.requests).toHaveLength(initialRequests)
  await page.getByRole('button', { name: '保存草稿', exact: true }).click()
  await expect.poll(() => backend.writes.length).toBe(1)
  expect(backend.draft.snapshot.components[0].title).toBe('新的结果标题')
  expect(backend.draft.snapshot.components[0].renderer_config.field_presentations.find(p => p.field === 'value').precision).toBe(2)
  expect(backend.draft.snapshot.page.placements[0].component_id).toBe('component-72')
  expect(backend.published).toEqual(backend.originalPublished)
  await page.reload()
  await expect(page.getByTestId('application-component').first()).toContainText('活动次数')
  expect(backend.unexpected).toEqual([])
})

for (const locale of ['zh-cn', 'en']) {
test(`new application goes from a service through query inputs to a saved draft (${locale})`, async ({ page, context }) => {
  const backend = await installMetricApplicationBackend(context, { rebound: true, locale })
  await page.goto('/workbench/applications/new')
  await expect(page.getByTestId('application-start')).toBeVisible()
  await expect(page.getByTestId('component-inspector')).toHaveCount(0)
  await page.getByTestId('start-table').click()
  const editor = page.getByTestId('application-component-editor')
  await choose(page, editor.locator('.el-form-item').filter({ hasText: locale === 'en' ? 'Data service' : '数据服务' }), '定向重叠率服务')
  await page.getByRole('dialog').getByRole('button', { name: locale === 'en' ? 'Next step' : '下一步', exact: true }).click()
  await expect(editor.getByRole('tab', { name: locale === 'en' ? '2. Configure display' : '2. 配置展示' })).toHaveAttribute('aria-selected', 'true')
  await page.getByRole('dialog').getByRole('button', { name: locale === 'en' ? 'Next step' : '下一步', exact: true }).click()
  const parameters = editor.locator('.parameter')
  await choose(page, parameters.nth(0), locale === 'en' ? 'Total' : '全期')
  await choose(page, parameters.nth(1), locale === 'en' ? 'Both directions' : '双向')
  await editor.getByTestId('component-query-action').click()
  await expect(editor.locator('tbody tr')).toHaveCount(2)
  await page.getByRole('dialog').getByRole('button', { name: locale === 'en' ? 'Apply component configuration' : '应用组件配置', exact: true }).click()
  await expect(page.getByTestId('application-start')).toHaveCount(0)
  await expect(page.getByTestId('runtime-component')).toHaveCount(1)
  await page.getByTestId('draft-preview-action').click()
  const preview = page.getByRole('dialog')
  await choose(page, preview.locator('.parameter-field').first(), locale === 'en' ? 'Monthly' : '按月')
  await preview.getByTestId('apply-preview-defaults').click()
  await expect(preview).toHaveCount(0)
  expect(backend.writes).toHaveLength(0)
  await page.getByRole('button', { name: locale === 'en' ? 'Create draft' : '创建草稿', exact: true }).click()
  await expect.poll(() => backend.writes.length).toBe(1)
  expect(backend.writes[0].action).toBe('create')
  expect(backend.draft.snapshot.parameters.map(p => p.default_value)).toEqual(['month', 'both'])
  await expect(page).toHaveURL(new RegExp(applicationPath + '$'))
  expect(backend.unexpected).toEqual([])
})
}

test('query changes invalidate canvas data; preview interactions stay out of the draft', async ({ page, context }) => {
  const backend = await installMetricApplicationBackend(context, { rebound: true })
  await page.goto(applicationPath)
  await expect(page.getByTestId('runtime-component').first().locator('tbody tr')).toHaveCount(2)
  const requests = backend.requests.length
  await page.getByRole('button', { name: '筛选条件', exact: true }).click()
  const drawer = page.getByRole('dialog')
  await choose(page, drawer.getByTestId('filter-card').first(), '按月')
  await drawer.getByRole('button', { name: '完成设置', exact: true }).click()
  await expect(page.getByTestId('runtime-component').first().locator('tbody tr')).toHaveCount(0)
  expect(backend.requests).toHaveLength(requests)
  await page.getByRole('button', { name: '刷新画布数据', exact: true }).click()
  await expect(page.getByTestId('runtime-component').first().locator('tbody tr')).toHaveCount(24)
  await page.getByTestId('draft-preview-action').click()
  const preview = page.getByRole('dialog')
  await expect(preview.getByTestId('query-all-action')).toBeVisible()
  await preview.getByTestId('query-all-action').click()
  await expect(preview.getByTestId('runtime-component').first().locator('tbody tr')).toHaveCount(24)
  expect(backend.writes).toHaveLength(0)
  expect(backend.published).toEqual(backend.originalPublished)
  expect(backend.unexpected).toEqual([])
})

test('narrow editor remains usable and protects unsaved changes on return', async ({ page, context }) => {
  await installMetricApplicationBackend(context, { rebound: true })
  await page.setViewportSize({ width: 680, height: 900 })
  await page.goto(applicationPath)
  const inspector = page.getByTestId('component-inspector')
  await inspector.getByRole('textbox', { name: '组件标题', exact: true }).fill('未保存标题')
  await page.getByRole('button', { name: '返回列表', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page).toHaveURL(new RegExp(applicationPath + '$'))
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)
})

test('dragging reorders layout and selecting a result never runs an interaction in edit mode', async ({ page, context }) => {
  const backend = await installMetricApplicationBackend(context, { rebound: true })
  await page.goto(applicationPath)
  const cards = page.getByTestId('runtime-component')
  await expect(cards.first().locator('tbody tr')).toHaveCount(2)
  const initialRequests = backend.requests.length
  await cards.first().locator('tbody tr').first().click({ force: true })
  await expect(cards.first()).toHaveAttribute('aria-pressed', 'true')
  expect(backend.requests).toHaveLength(initialRequests)
  const dragData = await page.evaluateHandle(() => new DataTransfer())
  await cards.nth(1).getByRole('button', { name: '拖动调整组件顺序' }).dispatchEvent('dragstart', { dataTransfer: dragData })
  await cards.first().dispatchEvent('dragover', { dataTransfer: dragData })
  await cards.first().dispatchEvent('drop', { dataTransfer: dragData })
  await expect(page.getByTestId('application-component').first()).toContainText('活动次数')
  expect(backend.requests).toHaveLength(initialRequests)
  await page.getByRole('button', { name: '保存草稿', exact: true }).click()
  await expect.poll(() => backend.writes.length).toBe(1)
  expect(backend.draft.snapshot.page.placements.map(p => p.component_id)).toEqual(['component-72', 'component-71'])
  expect(backend.unexpected).toEqual([])
})

async function personnelApplication(context, { locale = 'zh-cn', withSelection = false } = {}) {
  const backend = await installMetricApplicationBackend(context, { rebound: true, locale, configure(draft, descriptors) {
    const [metric, directory] = draft.snapshot.components
    descriptors[71].input_contract.named_parameters = [{ name: 'person_id', type: 'string', required: true }]
    metric.title = '参加活动次数'
    metric.parameter_definitions = [{ key: 'person', label: '人员', control_type: 'text', required: true }]
    metric.query_template.named_parameter_bindings = [{ name: 'person_id', parameter_key: 'person' }]
    metric.query_template.select = ['bucket', 'value']
    metric.renderer_type = 'chart'
    metric.renderer_config = { chart_type: 'bar', dimension: 'bucket', measures: ['value'] }
    const fields = [{ name: 'person_id', type: 'string', nullable: false }, { name: 'nickname', type: 'string', nullable: true }]
    descriptors[72].input_contract = { fields: fields.map(f => ({ ...f, selectable: true })), page: { default_limit: 50, max_limit: 100 }, order: { stable_key: ['person_id'] } }
    descriptors[72].output_contract.fields = fields
    directory.title = '选择人员'
    directory.renderer_type = 'table'
    directory.renderer_config = { columns: ['nickname'], field_presentations: [{ field: 'person_id', label: '人员编号' }, { field: 'nickname', label: '昵称' }] }
    directory.parameter_definitions = []
    directory.query_template = { select: ['person_id', 'nickname'], named_parameter_bindings: [], parameter_filters: [], page_limit: 50, order_by: [{ field: 'person_id', direction: 'asc' }], format: 'json' }
    const other = structuredClone(metric)
    other.id = 'component-73'; other.title = '活动次数对比'
    draft.snapshot.components.push(other)
    draft.snapshot.parameters = ['person_a', 'person_b'].map((key, i) => ({ key, label: i ? '对比人员' : '人员', control_type: 'text', required: true, default_value: 'person-a' }))
    draft.snapshot.parameter_bindings = [metric, other].map((c, i) => ({ component_id: c.id, component_parameter_key: 'person', application_parameter_key: i ? 'person_b' : 'person_a' }))
    draft.snapshot.page.placements = draft.snapshot.components.map((c, i) => ({ component_id: c.id, x: 0, y: i * 6, width: 12, height: 6 }))
    if (withSelection) draft.snapshot.selection_bindings = [{ source_component_id: directory.id, assignments: draft.snapshot.parameters.map(p => ({ source_field: 'person_id', application_parameter_key: p.key })) }]
    draft.snapshot.parameter_presets = [{ key: 'original', name: '原始人员', parameter_values: { person_a: 'person-a', person_b: 'person-a' } }]
  } })
  const queries = []
  await context.route('**/api/query/metric_71/query', route => {
    queries.push(route.request().postDataJSON())
    return route.fulfill({ json: { data: [{ bucket: '2026-01-01', value: 3 }], page: { has_more: false, next_cursor: '' } } })
  })
  await context.route('**/api/query/metric_72/query', route => route.fulfill({ json: { data: [{ person_id: 'person-c', nickname: '阿青' }], page: { has_more: false, next_cursor: '' } } }))
  return { backend, queries }
}

test('explicit personnel interaction can be cancelled, applied, edited and tried without publishing', async ({ page, context }) => {
  const { backend, queries } = await personnelApplication(context)
  await page.goto(applicationPath)
  await page.getByRole('button', { name: '点击联动', exact: true }).click()
  const drawer = page.getByRole('dialog')
  await drawer.getByRole('button', { name: '添加选择联动', exact: true }).click()
  const builder = drawer.getByTestId('interaction-builder')
  const apply = builder.getByRole('button', { name: '应用联动', exact: true })
  await expect(apply).toBeDisabled()
  await choose(page, builder.getByTestId('interaction-source'), '选择人员')
  await expect(apply).toBeDisabled()
  await choose(page, builder.getByTestId('interaction-field'), '人员编号 (person_id)')
  await expect(apply).toBeDisabled()
  await choose(page, builder.getByTestId('interaction-target'), '人员 · 参加活动次数')
  await expect(builder.getByTestId('interaction-impact')).toHaveText('将刷新：参加活动次数')
  await builder.getByRole('button', { name: '取消', exact: true }).click()
  await expect(drawer.getByTestId('interaction-card')).toHaveCount(0)
  await drawer.getByRole('button', { name: '添加选择联动', exact: true }).click()
  await choose(page, builder.getByTestId('interaction-source'), '选择人员')
  await choose(page, builder.getByTestId('interaction-field'), '人员编号 (person_id)')
  await choose(page, builder.getByTestId('interaction-target'), '人员 · 参加活动次数')
  await apply.click()
  await expect(drawer.getByTestId('interaction-card')).toContainText('人员编号 (person_id)')
  await drawer.getByRole('button', { name: '编辑联动', exact: true }).click()
  await builder.getByRole('button', { name: '添加字段映射', exact: true }).click()
  const second = builder.getByTestId('interaction-assignment').nth(1)
  // One source field can explicitly update two different filters; a target cannot be duplicated.
  await choose(page, second.getByTestId('interaction-field'), '人员编号 (person_id)')
  await choose(page, second.getByTestId('interaction-target'), '对比人员 · 活动次数对比')
  await expect(builder.getByTestId('interaction-impact')).toContainText('活动次数对比')
  await apply.click()
  await drawer.getByRole('button', { name: '完成设置', exact: true }).click()
  await page.getByTestId('draft-preview-action').click()
  const preview = page.getByRole('dialog')
  await preview.getByTestId('query-all-action').click()
  await preview.getByTestId('runtime-component').nth(1).getByRole('row', { name: '阿青', exact: true }).click()
  await expect.poll(() => queries.filter(q => q.parameters.person_id === 'person-c').length).toBe(2)
  expect(queries.some(q => q.parameters.person_id === '阿青')).toBe(false)
  await preview.getByRole('button', { name: '关闭此对话框', exact: true }).click()
  await page.getByRole('button', { name: '保存草稿', exact: true }).click()
  await expect.poll(() => backend.writes.length).toBe(1)
  expect(backend.draft.snapshot.selection_bindings).toEqual([{ source_component_id: 'component-72', assignments: [{ source_field: 'person_id', application_parameter_key: 'person_a' }, { source_field: 'person_id', application_parameter_key: 'person_b' }] }])
  expect(backend.draft.snapshot.parameters.map(p => p.default_value)).toEqual(['person-a', 'person-a'])
  expect(backend.published).toEqual(backend.originalPublished)
  expect(backend.unexpected).toEqual([])
})

test('sharing a filter shows its scope and keeps both metric queries on the same original value', async ({ page, context }) => {
  const { backend, queries } = await personnelApplication(context)
  await page.goto(applicationPath)
  await page.getByRole('button', { name: '筛选条件', exact: true }).click()
  const drawer = page.getByRole('dialog')
  await choose(page, drawer.getByTestId('filter-binding-group').filter({ hasText: '活动次数对比' }), '人员 · 参加活动次数')
  const shared = drawer.getByTestId('filter-card').first()
  await expect(shared).toContainText('参加活动次数')
  await expect(shared).toContainText('活动次数对比')
  await shared.getByRole('textbox').nth(1).fill('person-c')
  await page.setViewportSize({ width: 560, height: 800 })
  expect(await drawer.evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
  await drawer.getByRole('button', { name: '完成设置', exact: true }).click()
  await page.getByRole('button', { name: '保存草稿', exact: true }).click()
  await expect.poll(() => backend.writes.length).toBe(1)
  expect(backend.draft.snapshot.parameters).toHaveLength(1)
  expect(backend.draft.snapshot.parameter_bindings.map(b => b.application_parameter_key)).toEqual(['person_a', 'person_a'])
  await page.getByRole('button', { name: '刷新画布数据', exact: true }).click()
  await expect.poll(() => queries.filter(q => q.parameters.person_id === 'person-c').length).toBeGreaterThanOrEqual(2)
  expect(backend.published).toEqual(backend.originalPublished)
  expect(backend.unexpected).toEqual([])
})

for (const locale of ['zh-cn', 'en']) {
test(`preview explicitly copies selected person IDs into initial values and preserves scenarios (${locale})`, async ({ page, context }) => {
  const { backend, queries } = await personnelApplication(context, { locale, withSelection: true })
  await page.goto(applicationPath)
  await page.getByTestId('draft-preview-action').click()
  const preview = page.getByRole('dialog')
  await expect(preview.getByTestId('apply-preview-defaults')).toHaveText(locale === 'en' ? 'Use as initial values' : '设为应用初始值')
  await page.setViewportSize({ width: 560, height: 800 })
  expect(await preview.evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
  const previewCanvas = preview.getByTestId('data-application-canvas')
  expect(await previewCanvas.evaluate(el => el.getBoundingClientRect().bottom <= window.innerHeight)).toBe(true)
  await preview.getByTestId('query-all-action').click()
  await preview.getByTestId('runtime-component').nth(1).getByRole('row', { name: '阿青', exact: true }).click()
  await expect.poll(() => queries.filter(q => q.parameters.person_id === 'person-c').length).toBe(2)
  // Ordinary close still discards interactive changes.
  await preview.getByRole('button', { name: locale === 'en' ? 'Close this dialog' : '关闭此对话框', exact: true }).click()
  await page.getByTestId('draft-preview-action').click()
  await expect(preview.locator('.parameters-card').getByRole('textbox').first()).toHaveValue('person-a')
  await preview.getByTestId('query-all-action').click()
  await preview.getByTestId('runtime-component').nth(1).getByRole('row', { name: '阿青', exact: true }).click()
  await preview.getByTestId('apply-preview-defaults').click()
  await expect(preview).toHaveCount(0)
  expect(backend.writes).toHaveLength(0)
  await page.getByRole('button', { name: locale === 'en' ? 'Save draft' : '保存草稿', exact: true }).click()
  await expect.poll(() => backend.writes.length).toBe(1)
  expect(backend.draft.snapshot.parameters.map(p => p.default_value)).toEqual(['person-c', 'person-c'])
  expect(backend.draft.snapshot.parameter_presets[0].parameter_values).toEqual({ person_a: 'person-a', person_b: 'person-a' })
  expect(backend.published).toEqual(backend.originalPublished)
  await page.reload()
  await page.getByTestId('draft-preview-action').click()
  await expect(preview.locator('.parameters-card').getByRole('textbox').first()).toHaveValue('person-c')
  expect(backend.unexpected).toEqual([])
})
}

test('preview refuses incomplete initial values without mutating the draft', async ({ page, context }) => {
  const { backend } = await personnelApplication(context, { withSelection: true })
  await page.goto(applicationPath)
  await page.getByTestId('draft-preview-action').click()
  const preview = page.getByRole('dialog')
  const person = preview.locator('.parameters-card').getByRole('textbox').first()
  await expect(person).toHaveValue('person-a')
  await person.fill('')
  await person.blur()
  await preview.getByTestId('apply-preview-defaults').click()
  await expect(page.getByText('暂时无法设为初始值：请补全必填条件，并确认数据服务契约已加载且条件值有效。', { exact: true })).toBeVisible()
  await expect(preview).toBeVisible()
  await preview.getByRole('button', { name: '关闭此对话框', exact: true }).click()
  await page.getByRole('button', { name: '保存草稿', exact: true }).click()
  await expect.poll(() => backend.writes.length).toBe(1)
  expect(backend.draft.snapshot.parameters.map(p => p.default_value)).toEqual(['person-a', 'person-a'])
  expect(backend.published).toEqual(backend.originalPublished)
})

for (const locale of ['zh-cn', 'en']) {
test(`new component explicitly reuses an existing filter for its test query and saved binding (${locale})`, async ({ page, context }) => {
  const backend = await installMetricApplicationBackend(context, { rebound: true, locale })
  await page.goto(applicationPath)
  const originalParameters = backend.draft.snapshot.parameters
  const add = page.getByRole('button', { name: locale === 'en' ? 'Add data service component' : '添加数据服务组件', exact: true })
  await add.click()
  const editor = page.getByTestId('application-component-editor')
  const serviceField = editor.locator('.el-form-item').filter({ hasText: locale === 'en' ? 'Data service' : '数据服务' })
  await choose(page, serviceField, '计数服务')
  await editor.getByRole('tab', { name: locale === 'en' ? '3. Set query inputs' : '3. 设置查询条件' }).click()
  const reuse = editor.getByTestId('parameter-reuse')
  await expect(reuse).toHaveCount(1)
  await expect(reuse).toContainText(locale === 'en' ? 'Create an independent filter' : '新建独立条件')
  await reuse.locator('.el-select__wrapper').click()
  const optionList = page.locator(`#${await reuse.getByRole('combobox').getAttribute('aria-controls')}`)
  await expect(optionList.getByRole('option', { name: '查询方向 · 双方重叠率', exact: true })).toHaveAttribute('aria-disabled', 'true')
  await optionList.getByRole('option', { name: '统计粒度 · 双方重叠率' + (locale === 'en' ? ', ' : '、') + '活动次数', exact: true }).click()
  await editor.getByTestId('component-query-action').click()
  await expect(editor.locator('tbody tr')).toHaveCount(1)
  expect(backend.requests.at(-1).body.parameters).toEqual({ grain: 'total' })
  await page.getByRole('dialog').getByRole('button', { name: locale === 'en' ? 'Cancel' : '取消', exact: true }).click()
  await expect(page.getByTestId('runtime-component')).toHaveCount(2)
  expect(backend.writes).toHaveLength(0)
  await add.click()
  await choose(page, serviceField, '计数服务')
  await editor.getByRole('tab', { name: locale === 'en' ? '3. Set query inputs' : '3. 设置查询条件' }).click()
  await expect(reuse).toContainText(locale === 'en' ? 'Create an independent filter' : '新建独立条件')
  await choose(page, reuse, '统计粒度 · 双方重叠率' + (locale === 'en' ? ', ' : '、') + '活动次数')
  await page.getByRole('dialog').getByRole('button', { name: locale === 'en' ? 'Apply component configuration' : '应用组件配置', exact: true }).click()
  await expect(page.getByTestId('runtime-component')).toHaveCount(3)
  await page.getByRole('button', { name: locale === 'en' ? 'Save draft' : '保存草稿', exact: true }).click()
  await expect.poll(() => backend.writes.length).toBe(1)
  expect(backend.draft.snapshot.parameters).toEqual(originalParameters)
  const newComponent = backend.draft.snapshot.components[2]
  expect(backend.draft.snapshot.parameter_bindings.filter(b => b.component_id === newComponent.id)).toEqual([{ component_id: newComponent.id, component_parameter_key: newComponent.parameter_definitions[0].key, application_parameter_key: 'shared_grain' }])
  expect(JSON.stringify(newComponent)).not.toContain('applicationParameterKey')
  expect(backend.published).toEqual(backend.originalPublished)
  await page.reload()
  await expect(page.getByTestId('runtime-component')).toHaveCount(3)
  await page.getByRole('button', { name: locale === 'en' ? 'Filters' : '筛选条件', exact: true }).click()
  await expect(page.getByTestId('filter-card').first()).toContainText('计数服务')
  expect(backend.unexpected).toEqual([])
})
}
