import { expect, test } from '@playwright/test'
import { mockModuleQueryAPI, moduleQueryLink } from '../../../system/frontend/e2e/module-query.fixture'

test('Console module instance links synchronize without reloading the iframe and restore shared queries', async ({ page, context }) => {
  const queries = await mockModuleQueryAPI(page)
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto(`/system/modules${moduleQueryLink}`)
  const system = page.frameLocator('iframe[data-testid="module-iframe"]')
  const list = system.locator('.module-instances')
  await expect(list.getByText('page-2-0', { exact: true })).toBeVisible()
  await expect.poll(() => queries.at(-1)?.page_size).toBe('20')
  const frame = page.frames().find(frame => frame.parentFrame())
  const initialDocument = await frame.evaluate(() => performance.timeOrigin)
  const historyLength = await page.evaluate(() => history.length)
  await list.locator('.el-select').filter({ has: system.getByRole('combobox', { name: '运行状态', exact: true }) }).click()
  await system.getByRole('option', { name: 'DOWN · 离线', exact: true }).click()
  await expect.poll(() => new URL(page.url()).searchParams.get('status')).toBe('down')
  await expect.poll(() => queries.at(-1)?.status).toBe('down')
  expect(new URL(page.url()).searchParams.has('page')).toBe(false)
  expect(await frame.evaluate(() => performance.timeOrigin)).toBe(initialDocument)
  expect(await page.evaluate(() => history.length)).toBe(historyLength)
  await list.locator('.el-pagination .btn-next').click()
  await expect.poll(() => new URL(page.url()).searchParams.get('page')).toBe('2')
  await expect(list.getByText('page-2-0', { exact: true })).toBeVisible()
  const sharedURL = page.url()
  await page.reload()
  await expect(list.getByText('page-2-0', { exact: true })).toBeVisible()
  await expect(list.getByPlaceholder('登记主机名或 IP')).toHaveValue('manager.local')
  await expect(list.getByPlaceholder('宿主节点或运行环境主机名')).toHaveValue('host-a')
  await page.screenshot({ path: '/tmp/addp-module-query-url-verified.png', fullPage: true })
  const sharedPage = await context.newPage()
  const sharedQueries = await mockModuleQueryAPI(sharedPage)
  await sharedPage.goto(sharedURL)
  await expect(sharedPage.frameLocator('iframe[data-testid="module-iframe"]').getByText('page-2-0', { exact: true })).toBeVisible()
  await expect.poll(() => sharedQueries.at(-1)?.status).toBe('down')
  await sharedPage.close()
  await page.goto('/system/modules')
  await expect(system.getByRole('tab', { name: '模块概览' })).toHaveAttribute('aria-selected', 'true')
  await page.goBack()
  await expect(page).toHaveURL(sharedURL)
  await expect(list.getByText('page-2-0', { exact: true })).toBeVisible()
  await page.goForward()
  await expect(system.getByRole('tab', { name: '模块概览' })).toHaveAttribute('aria-selected', 'true')
  await page.goBack()
  await expect(list.getByText('page-2-0', { exact: true })).toBeVisible()
  await list.getByRole('button', { name: '重置', exact: true }).click()
  await expect(page).toHaveURL('http://127.0.0.1:4170/system/modules?tab=instances')
  await expect.poll(() => queries.at(-1)).toEqual({ page: '1', page_size: '10', status: 'up' })
  expect(errors).toEqual([])
})
