import { expect, test } from '@playwright/test'
import { backend, permissions } from '../../../monitor/frontend/e2e/process-resources.fixture'
import { identity } from '../../../monitor/frontend/e2e/monitoring-targets.fixture'

test('Console service monitoring uses one iframe and restores System filters after paging and reload', async ({ page }) => {
  const state = await backend(page)
  await page.goto('/monitor/service-resources?module_name=monitor&role=worker')
  const monitor = page.frameLocator('iframe[data-testid="module-iframe"]')
  await expect(monitor.getByTestId('process-list')).toContainText('1.50 核')
  await expect(page.locator('.sidebar .el-menu-item.is-active')).toContainText('服务监控')
  const documentOrigin = () => monitor.locator('body').evaluate(() => performance.timeOrigin)
  const documentID = await documentOrigin()
  await monitor.locator('.el-pagination button.btn-next').click()
  await expect(page).toHaveURL(url => url.pathname === '/monitor/service-resources' && url.searchParams.get('page') === '2' && url.searchParams.get('module_name') === 'monitor' && url.searchParams.get('role') === 'worker')
  expect(await documentOrigin()).toBe(documentID)
  await page.reload()
  await expect.poll(() => state.listCalls.at(-1)?.page).toBe('2')
  await expect(monitor.getByTestId('process-list')).not.toContainText('mac-process-1')
  const restoredDocumentID = await documentOrigin()
  const roleControl = monitor.locator('.el-select:has(input[aria-label="实例角色"])')
  const statusControl = monitor.locator('.el-select:has(input[aria-label="在线状态"])')
  await roleControl.click()
  await monitor.getByRole('option', { name: '后端服务', exact: true }).click()
  await statusControl.click()
  await monitor.getByRole('option', { name: '在线', exact: true }).click()
  await monitor.getByRole('button', { name: '搜索', exact: true }).click()
  await expect(page).toHaveURL(url => url.pathname === '/monitor/service-resources' && url.searchParams.get('role') === 'backend' && url.searchParams.get('status') === 'up' && !url.searchParams.has('page'))
  await expect(monitor.getByTestId('process-list')).toContainText('1.50 核')
  expect(state.listCalls.at(-1)).toMatchObject({ module_name: 'monitor', role: 'backend', status: 'up', page: '1' })
  expect(await documentOrigin()).toBe(restoredDocumentID)
  await page.reload()
  await expect(roleControl).toContainText('后端服务')
  await expect(statusControl).toContainText('在线')
  await expect(monitor.getByTestId('process-list')).toContainText('1.50 核')
})

test('reloaded Console opens the collapsed monitoring group and service-page refresh preserves its active iframe', async ({ page }) => {
  const state = await backend(page)
  await page.goto('/monitor/service-resources?page=2')
  const monitor = page.frameLocator('iframe[data-testid="module-iframe"]')
  await expect(monitor.getByTestId('process-list')).toBeVisible()
  await expect.poll(() => state.listCalls.at(-1)?.page).toBe('2')
  await page.reload()
  await expect(monitor.getByTestId('process-list')).toBeVisible()
  const serviceMenu = page.locator('.sidebar .el-menu-item').filter({ hasText: /^服务监控$/ })
  const monitoringGroup = page.locator('.sidebar .el-sub-menu__title').filter({ hasText: /^运行监控$/ })
  if (await serviceMenu.isVisible()) await monitoringGroup.click()
  await expect(serviceMenu).not.toBeVisible()
  await monitoringGroup.click()
  await expect(serviceMenu).toBeVisible()
  await serviceMenu.click()
  await expect(page).toHaveURL(url => url.pathname === '/monitor/service-resources' && !url.searchParams.has('page'))
  await expect(monitor.getByTestId('process-list')).toContainText('1.50 核')
  await expect.poll(() => state.listCalls.at(-1)?.page).toBe('1')
  await expect(page.locator('iframe[data-testid="module-iframe"]')).toHaveCount(1)
  const documentID = await monitor.locator('body').evaluate(() => performance.timeOrigin)
  const beforeRefresh = state.calls.length
  await monitor.getByRole('button', { name: '刷新', exact: true }).click()
  await expect.poll(() => state.calls.length).toBeGreaterThan(beforeRefresh)
  await expect(monitor.getByTestId('process-list')).toContainText('1.50 核')
  expect(await monitor.locator('body').evaluate(() => performance.timeOrigin)).toBe(documentID)
})

test('Tenant cannot open service monitoring even with platform permission strings', async ({ page }) => {
  const state = await backend(page, { identity: identity(permissions, { type: 'tenant', tenant_id: '7' }) })
  await page.goto('/monitor/service-resources')
  await expect(page.locator('.el-result')).toBeVisible()
  await expect(page.locator('iframe.module-iframe')).toHaveCount(0)
  expect(state.listCalls).toHaveLength(0)
  expect(state.calls).toHaveLength(0)
})
