// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/capabilities": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "返回 Transfer 当前可用于表格传输的格式能力，来源于 common format descriptor 与已加载 plugin 的接口实现状态 | Returns table transfer format capabilities backed by common format descriptors and loaded plugin implementations",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "传输能力 | Capabilities"
                ],
                "summary": "获取传输能力 | Get transfer capabilities",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api.TransferCapabilitiesResponse"
                        }
                    }
                }
            }
        },
        "/executions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "执行管理 | Execution Management"
                ],
                "summary": "获取执行列表 | List executions",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "任务ID | Task ID",
                        "name": "task_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "执行状态 | Status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码 | Page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量 | Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/executions/statistics": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "执行管理 | Execution Management"
                ],
                "summary": "获取执行统计 | Get execution statistics",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "任务ID | Task ID",
                        "name": "task_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "开始时间 | Start time",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "结束时间 | End time",
                        "name": "end_time",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/executions/{execution_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "执行管理 | Execution Management"
                ],
                "summary": "获取执行详情 | Get execution detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "执行ID | Execution ID",
                        "name": "execution_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/executions/{execution_id}/logs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "执行管理 | Execution Management"
                ],
                "summary": "获取执行日志 | Get execution logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "执行ID | Execution ID",
                        "name": "execution_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "最多返回行数 | Line limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/executions/{execution_id}/progress": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "执行管理 | Execution Management"
                ],
                "summary": "获取执行进度 | Get execution progress",
                "parameters": [
                    {
                        "type": "string",
                        "description": "执行ID | Execution ID",
                        "name": "execution_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/executions/{execution_id}/retry": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "为失败执行创建新的 retry 执行记录，并按 restartable 语义从头重新入队执行 | Create a new retry execution for a failed execution and enqueue it from the beginning with restartable semantics",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "执行管理 | Execution Management"
                ],
                "summary": "重试执行 | Retry execution",
                "parameters": [
                    {
                        "type": "string",
                        "description": "执行ID | Execution ID",
                        "name": "execution_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transfer"
                ],
                "summary": "Ping",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/system-engines": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "返回当前租户可见且启用的 System 引擎，用于 Transfer 任务选择 | Returns active System engines visible to the current tenant for Transfer task configuration",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统引擎 | System Engines"
                ],
                "summary": "列出系统引擎 | List system engines",
                "parameters": [
                    {
                        "type": "string",
                        "description": "引擎类型 | Engine type",
                        "name": "engine_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_addp_transfer_internal_models.SystemEngineDoc"
                            }
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/task-definitions": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "创建 bounded Transfer 任务。配置必须使用 runtime.boundary、load.mode 和 target.policy.apply_mode；PostgreSQL watermark 增量需声明复合游标与目标 keys。旧 mode/write_mode 字段会被拒绝。| Create a bounded Transfer task using runtime.boundary, load.mode, and target.policy.apply_mode. PostgreSQL watermark incremental tasks must declare a composite cursor and target keys. Legacy mode/write_mode fields are rejected.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务管理 | Task Management"
                ],
                "summary": "创建数据传输任务 | Create data transfer task",
                "parameters": [
                    {
                        "description": "任务创建请求 | Task creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_addp_transfer_internal_models.CreateTaskRequestDoc"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "任务创建成功 | Task created successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_addp_transfer_internal_models.TransferTask"
                        }
                    },
                    "400": {
                        "description": "请求参数错误 | Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "未授权 | Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "服务器内部错误 | Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/task-definitions/statistics": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前租户的任务统计数据（各状态任务数量等）| Get task statistics for the current tenant (task counts by status, etc.)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务管理 | Task Management"
                ],
                "summary": "获取任务统计信息 | Get task statistics",
                "responses": {
                    "200": {
                        "description": "统计信息 | Statistics",
                        "schema": {
                            "$ref": "#/definitions/github_com_addp_transfer_internal_models.TaskStatistics"
                        }
                    },
                    "500": {
                        "description": "服务器错误 | Server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/task-definitions/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据任务ID获取任务的详细信息 | Get detailed task information by task ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务管理 | Task Management"
                ],
                "summary": "获取任务详情 | Get task detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "任务ID | Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功 | Retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_addp_transfer_internal_models.TransferTask"
                        }
                    },
                    "400": {
                        "description": "参数错误 | Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "任务不存在 | Task not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "服务器错误 | Server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "更新任务的配置信息。source 指向已入库 Meta item 时使用 config.source.locator 的 item_id；target 使用 parent_locator + name；不支持在任务配置中直接传递 endpoint attributes。| Update task configuration. Use config.source.locator item_id for persisted Meta items; target uses parent_locator + name; endpoint attributes are not accepted in task config.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务管理 | Task Management"
                ],
                "summary": "更新任务 | Update task",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "任务ID | Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "任务更新请求 | Task update request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_addp_transfer_internal_models.UpdateTaskRequestDoc"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功 | Updated successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_addp_transfer_internal_models.TransferTask"
                        }
                    },
                    "400": {
                        "description": "参数错误 | Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "服务器错误 | Server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "删除指定的任务及相关执行记录 | Delete a specific task and its execution records",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务管理 | Task Management"
                ],
                "summary": "删除任务 | Delete task",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "任务ID | Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功 | Deleted successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "参数错误 | Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "服务器错误 | Server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/task-definitions/{id}/executions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "执行管理 | Execution Management"
                ],
                "summary": "获取任务执行列表 | List task executions",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "任务ID | Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码 | Page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量 | Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/task-definitions/{id}/pause": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "关闭任务自身定时调度，不中断当前 active execution | Disable the task-owned schedule without interrupting an active execution",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务管理 | Task Management"
                ],
                "summary": "暂停任务 | Pause task",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "任务ID | Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/task-definitions/{id}/resume": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "恢复任务自身定时调度；watermark execution resume 由新 execution 自动读取 committed position 完成 | Re-enable the task-owned schedule; watermark execution resume is handled by a new execution reading the committed position",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务管理 | Task Management"
                ],
                "summary": "恢复任务 | Resume task",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "任务ID | Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/task-definitions/{id}/start": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "启动任务执行，创建新的执行记录 | Start task execution and create a new execution record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务管理 | Task Management"
                ],
                "summary": "启动任务 | Start task",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "任务ID | Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "启动成功，返回执行记录 | Started successfully, returns execution record",
                        "schema": {
                            "$ref": "#/definitions/github_com_addp_transfer_internal_models.TaskExecution"
                        }
                    },
                    "400": {
                        "description": "参数错误或任务已在运行 | Bad request or task already running",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "服务器错误 | Server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tasks": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "分页获取任务列表，支持按类型、状态过滤 | Get paginated task list with type and status filtering",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务管理 | Task Management"
                ],
                "summary": "获取任务列表 | List tasks",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码 | Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页大小 | Page size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "任务类型，当前固定为 sync | Task type, currently fixed to sync",
                        "name": "task_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "任务定义状态: idle, running | Task definition status",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功 | Retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_addp_transfer_internal_models.ListProviderTasksResponse"
                        }
                    },
                    "400": {
                        "description": "不支持的任务类型 | Unsupported task type",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "服务器错误 | Server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tasks/{task_type}/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "按标准 TaskProvider 路径获取 Transfer 任务详情；task_type 仅支持 sync。| Get Transfer task detail through the standard TaskProvider path; task_type only supports sync.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务管理 | Task Management"
                ],
                "summary": "获取 TaskProvider 任务详情 | Get TaskProvider task detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务类型，固定为 sync | Task type, fixed to sync",
                        "name": "task_type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "任务ID | Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "任务详情 | Task detail",
                        "schema": {
                            "$ref": "#/definitions/github_com_addp_transfer_internal_models.TransferTask"
                        }
                    },
                    "400": {
                        "description": "参数错误 | Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "任务不存在 | Task not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tasks/{task_type}/{id}/execute": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "按标准 TaskProvider 协议启动 Transfer 任务；task_type 仅支持 sync，parameters 当前不支持覆盖。| Start a Transfer task through the standard TaskProvider protocol; task_type only supports sync and parameters overrides are not supported.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务管理 | Task Management"
                ],
                "summary": "执行 TaskProvider Transfer 任务 | Execute TaskProvider Transfer task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务类型，固定为 sync | Task type, fixed to sync",
                        "name": "task_type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "任务ID | Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "TaskProvider 执行请求 | TaskProvider execution request",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ProviderExecuteRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "执行记录 | Execution",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ProviderExecuteResponse"
                        }
                    },
                    "400": {
                        "description": "参数错误 | Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "服务器错误 | Server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_addp_transfer_internal_models.CreateTaskRequestDoc": {
            "type": "object",
            "properties": {
                "auto_scan_metadata": {
                    "type": "boolean",
                    "example": true
                },
                "batch_size": {
                    "type": "integer",
                    "example": 1000
                },
                "config": {
                    "$ref": "#/definitions/github_com_addp_transfer_internal_models.TableTransferTaskConfigDoc"
                },
                "description": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "example": "导入道路 Shapefile"
                },
                "schedule": {
                    "type": "string"
                },
                "task_type": {
                    "type": "string",
                    "example": "sync"
                }
            }
        },
        "github_com_addp_transfer_internal_models.ExecutionStatus": {
            "type": "string",
            "enum": [
                "pending",
                "running",
                "success",
                "failed"
            ],
            "x-enum-comments": {
                "ExecutionStatusFailed": "失败",
                "ExecutionStatusPending": "待执行",
                "ExecutionStatusRunning": "运行中",
                "ExecutionStatusSuccess": "成功"
            },
            "x-enum-descriptions": [
                "待执行",
                "运行中",
                "成功",
                "失败"
            ],
            "x-enum-varnames": [
                "ExecutionStatusPending",
                "ExecutionStatusRunning",
                "ExecutionStatusSuccess",
                "ExecutionStatusFailed"
            ]
        },
        "github_com_addp_transfer_internal_models.FieldMappingSpecDoc": {
            "type": "object",
            "properties": {
                "default": {},
                "format": {
                    "type": "string"
                },
                "nullable": {
                    "type": "boolean",
                    "example": true
                },
                "source": {
                    "type": "string",
                    "example": "geom"
                },
                "target": {
                    "type": "string",
                    "example": "geometry"
                },
                "target_type": {
                    "type": "string",
                    "example": "geometry"
                }
            }
        },
        "github_com_addp_transfer_internal_models.JSONMap": {
            "type": "object",
            "additionalProperties": true
        },
        "github_com_addp_transfer_internal_models.ListProviderTasksResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_addp_transfer_internal_models.TransferTask"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "github_com_addp_transfer_internal_models.LocalTime": {
            "type": "object",
            "properties": {
                "time.Time": {
                    "type": "string"
                }
            }
        },
        "github_com_addp_transfer_internal_models.SystemEngineDoc": {
            "type": "object",
            "properties": {
                "check_message": {
                    "type": "string"
                },
                "connection_info": {
                    "type": "object",
                    "additionalProperties": true
                },
                "connection_status": {
                    "type": "string",
                    "example": "online"
                },
                "description": {
                    "type": "string"
                },
                "engine_origin": {
                    "type": "string",
                    "example": "general"
                },
                "engine_type": {
                    "type": "string",
                    "example": "minio"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "is_builtin": {
                    "type": "boolean",
                    "example": false
                },
                "name": {
                    "type": "string",
                    "example": "Business MinIO"
                },
                "tenant_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "github_com_addp_transfer_internal_models.TableTransferTaskConfigDoc": {
            "type": "object",
            "properties": {
                "batch_size": {
                    "type": "integer",
                    "example": 1000
                },
                "load": {
                    "$ref": "#/definitions/github_com_addp_transfer_internal_models.TransferLoadDoc"
                },
                "runtime": {
                    "$ref": "#/definitions/github_com_addp_transfer_internal_models.TransferRuntimeDoc"
                },
                "source": {
                    "$ref": "#/definitions/github_com_addp_transfer_internal_models.TransferSourceEndpointDoc"
                },
                "target": {
                    "$ref": "#/definitions/github_com_addp_transfer_internal_models.TransferTargetEndpointDoc"
                },
                "transforms": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_addp_transfer_internal_models.TransferTransformDoc"
                    }
                }
            }
        },
        "github_com_addp_transfer_internal_models.TaskExecution": {
            "type": "object",
            "properties": {
                "bytes_read": {
                    "type": "integer"
                },
                "bytes_written": {
                    "type": "integer"
                },
                "checkpoint_offset": {
                    "type": "integer"
                },
                "checkpoint_state": {
                    "$ref": "#/definitions/github_com_addp_transfer_internal_models.JSONMap"
                },
                "end_time": {
                    "$ref": "#/definitions/github_com_addp_transfer_internal_models.LocalTime"
                },
                "error_msg": {
                    "type": "string"
                },
                "execution_id": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "logs": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/github_com_addp_transfer_internal_models.JSONMap"
                },
                "records_read": {
                    "type": "integer"
                },
                "records_written": {
                    "type": "integer"
                },
                "start_time": {
                    "$ref": "#/definitions/github_com_addp_transfer_internal_models.LocalTime"
                },
                "status": {
                    "$ref": "#/definitions/github_com_addp_transfer_internal_models.ExecutionStatus"
                },
                "task_id": {
                    "type": "integer"
                },
                "trigger_by": {
                    "type": "integer"
                },
                "trigger_type": {
                    "type": "string"
                }
            }
        },
        "github_com_addp_transfer_internal_models.TaskStatistics": {
            "type": "object",
            "properties": {
                "failed_tasks": {
                    "type": "integer"
                },
                "last_failed_tasks": {
                    "type": "integer"
                },
                "last_running_tasks": {
                    "type": "integer"
                },
                "last_success_tasks": {
                    "type": "integer"
                },
                "not_executed_tasks": {
                    "type": "integer"
                },
                "pending_tasks": {
                    "type": "integer"
                },
                "running_tasks": {
                    "type": "integer"
                },
                "success_tasks": {
                    "type": "integer"
                },
                "total_bytes": {
                    "type": "integer"
                },
                "total_executions": {
                    "type": "integer"
                },
                "total_records": {
                    "type": "integer"
                },
                "total_tasks": {
                    "type": "integer"
                }
            }
        },
        "github_com_addp_transfer_internal_models.TaskStatus": {
            "type": "string",
            "enum": [
                "idle",
                "running"
            ],
            "x-enum-comments": {
                "TaskStatusIdle": "空闲（未执行或执行完成）",
                "TaskStatusRunning": "执行中"
            },
            "x-enum-descriptions": [
                "空闲（未执行或执行完成）",
                "执行中"
            ],
            "x-enum-varnames": [
                "TaskStatusIdle",
                "TaskStatusRunning"
            ]
        },
        "github_com_addp_transfer_internal_models.TransferChangeDetectionDoc": {
            "type": "object",
            "properties": {
                "end": {
                    "type": "string",
                    "enum": [
                        "execution_upper_bound"
                    ],
                    "example": "execution_upper_bound"
                },
                "field": {
                    "type": "string",
                    "example": "updated_at"
                },
                "start": {
                    "type": "string",
                    "enum": [
                        "committed"
                    ],
                    "example": "committed"
                },
                "tie_breaker": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "id"
                    ]
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "watermark"
                    ],
                    "example": "watermark"
                }
            }
        },
        "github_com_addp_transfer_internal_models.TransferLoadDoc": {
            "type": "object",
            "properties": {
                "change_detection": {
                    "$ref": "#/definitions/github_com_addp_transfer_internal_models.TransferChangeDetectionDoc"
                },
                "mode": {
                    "type": "string",
                    "enum": [
                        "snapshot",
                        "incremental"
                    ],
                    "example": "snapshot"
                }
            }
        },
        "github_com_addp_transfer_internal_models.TransferRuntimeDoc": {
            "type": "object",
            "properties": {
                "boundary": {
                    "type": "string",
                    "enum": [
                        "bounded"
                    ],
                    "example": "bounded"
                }
            }
        },
        "github_com_addp_transfer_internal_models.TransferSourceEndpointDoc": {
            "type": "object",
            "properties": {
                "data_type": {
                    "type": "string",
                    "example": "table"
                },
                "format": {
                    "type": "string",
                    "example": "shapefile"
                },
                "locator": {
                    "type": "string",
                    "example": "addp://engine/9/path/manager/a3.shp?type=object"
                },
                "options": {
                    "type": "object",
                    "additionalProperties": true
                },
                "policy": {
                    "type": "object",
                    "additionalProperties": true
                },
                "representation": {
                    "type": "string",
                    "enum": [
                        "native",
                        "encoded"
                    ],
                    "example": "encoded"
                }
            }
        },
        "github_com_addp_transfer_internal_models.TransferTargetEndpointDoc": {
            "type": "object",
            "properties": {
                "data_type": {
                    "type": "string",
                    "example": "table"
                },
                "format": {
                    "type": "string",
                    "example": "csv"
                },
                "name": {
                    "type": "string",
                    "example": "roads_imported"
                },
                "options": {
                    "type": "object",
                    "additionalProperties": true
                },
                "parent_locator": {
                    "type": "string",
                    "example": "addp://engine/10/path/public?type=schema"
                },
                "policy": {
                    "$ref": "#/definitions/github_com_addp_transfer_internal_models.TransferTargetPolicyDoc"
                },
                "representation": {
                    "type": "string",
                    "enum": [
                        "native",
                        "encoded"
                    ],
                    "example": "native"
                }
            }
        },
        "github_com_addp_transfer_internal_models.TransferTargetPolicyDoc": {
            "type": "object",
            "properties": {
                "apply_mode": {
                    "type": "string",
                    "enum": [
                        "replace",
                        "append",
                        "upsert"
                    ],
                    "example": "replace"
                },
                "keys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "id"
                    ]
                }
            }
        },
        "github_com_addp_transfer_internal_models.TransferTask": {
            "type": "object",
            "properties": {
                "auto_scan_metadata": {
                    "type": "boolean"
                },
                "batch_size": {
                    "type": "integer"
                },
                "config": {
                    "description": "Reader-Transform-Writer 管道配置",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_addp_transfer_internal_models.JSONMap"
                        }
                    ]
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "integer"
                },
                "deleted_at": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "description": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "last_execution_id": {
                    "description": "BaseTask 基类字段",
                    "type": "string"
                },
                "last_execution_status": {
                    "type": "string"
                },
                "last_run_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "next_run_at": {
                    "type": "string"
                },
                "progress": {
                    "type": "number"
                },
                "schedule": {
                    "description": "Cron 表达式",
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_addp_transfer_internal_models.TaskStatus"
                },
                "task_type": {
                    "description": "Transfer 当前统一任务类型，固定为 sync",
                    "type": "string"
                },
                "tenant_id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_addp_transfer_internal_models.TransferTransformDoc": {
            "type": "object",
            "properties": {
                "config": {
                    "type": "object",
                    "additionalProperties": true
                },
                "fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_addp_transfer_internal_models.FieldMappingSpecDoc"
                    }
                },
                "mode": {
                    "type": "string",
                    "example": "project"
                },
                "type": {
                    "type": "string",
                    "example": "field_mapping"
                },
                "version": {
                    "type": "string",
                    "example": "v1"
                }
            }
        },
        "github_com_addp_transfer_internal_models.UpdateTaskRequestDoc": {
            "type": "object",
            "properties": {
                "auto_scan_metadata": {
                    "type": "boolean"
                },
                "batch_size": {
                    "type": "integer"
                },
                "config": {
                    "$ref": "#/definitions/github_com_addp_transfer_internal_models.TableTransferTaskConfigDoc"
                },
                "description": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "schedule": {
                    "type": "string"
                },
                "task_type": {
                    "type": "string"
                }
            }
        },
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "internal_api.ProviderExecuteRequest": {
            "type": "object",
            "properties": {
                "parameters": {
                    "type": "object",
                    "additionalProperties": true
                },
                "parent_execution_id": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "trigger_type": {
                    "type": "string"
                }
            }
        },
        "internal_api.ProviderExecuteResponse": {
            "type": "object",
            "properties": {
                "execution_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "internal_api.TransferCapabilitiesResponse": {
            "type": "object",
            "properties": {
                "raw_copy_formats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_api.TransferRawCopyFormatSupport"
                    }
                },
                "table_formats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_api.TransferTableFormatSupport"
                    }
                }
            }
        },
        "internal_api.TransferRawCopyFormatSupport": {
            "type": "object",
            "properties": {
                "data_type": {
                    "type": "string"
                },
                "extension": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "layouts": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "internal_api.TransferTableFormatSupport": {
            "type": "object",
            "properties": {
                "backend_type": {
                    "type": "string"
                },
                "extension": {
                    "type": "string"
                },
                "group": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "layouts": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "multi_file": {
                    "type": "boolean"
                },
                "options": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "provider_kind": {
                    "type": "string"
                },
                "read": {
                    "type": "boolean"
                },
                "spatial": {
                    "type": "boolean"
                },
                "value": {
                    "type": "string"
                },
                "write": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8083",
	BasePath:         "/api/v1/transfer",
	Schemes:          []string{},
	Title:            "ADDP Transfer API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
