// Code generated by common/authorization/cmd/manifest; DO NOT EDIT.
// Source: model/authorization/permissions.yaml (manifest_version=2).

package authorization

const (
	PermissionModelDwLayerCreate        = "model.dw_layer.create"
	PermissionModelDwLayerDelete        = "model.dw_layer.delete"
	PermissionModelDwLayerRead          = "model.dw_layer.read"
	PermissionModelDwLayerUpdate        = "model.dw_layer.update"
	PermissionModelEntityApprove        = "model.entity.approve"
	PermissionModelEntityCreate         = "model.entity.create"
	PermissionModelEntityDelete         = "model.entity.delete"
	PermissionModelEntityRead           = "model.entity.read"
	PermissionModelEntityUpdate         = "model.entity.update"
	PermissionModelEntityRelationCreate = "model.entity_relation.create"
	PermissionModelEntityRelationDelete = "model.entity_relation.delete"
	PermissionModelEntityRelationRead   = "model.entity_relation.read"
	PermissionModelEntityRelationUpdate = "model.entity_relation.update"
	PermissionModelLogicalModelCreate   = "model.logical_model.create"
	PermissionModelLogicalModelDelete   = "model.logical_model.delete"
	PermissionModelLogicalModelRead     = "model.logical_model.read"
	PermissionModelLogicalModelUpdate   = "model.logical_model.update"
)

var permissionKeys = [...]string{
	"model.dw_layer.create",
	"model.dw_layer.delete",
	"model.dw_layer.read",
	"model.dw_layer.update",
	"model.entity.approve",
	"model.entity.create",
	"model.entity.delete",
	"model.entity.read",
	"model.entity.update",
	"model.entity_relation.create",
	"model.entity_relation.delete",
	"model.entity_relation.read",
	"model.entity_relation.update",
	"model.logical_model.create",
	"model.logical_model.delete",
	"model.logical_model.read",
	"model.logical_model.update",
}

// PermissionKeys returns the active owner-local Permission keys in stable order.
func PermissionKeys() []string {
	return append([]string(nil), permissionKeys[:]...)
}
