// Code generated by common/authorization/cmd/manifest; DO NOT EDIT.
// Source: model/authorization/permissions.yaml (manifest_version=1).

package authorization

const (
	PermissionModelLogicalModelCreate = "model.logical_model.create"
	PermissionModelLogicalModelDelete = "model.logical_model.delete"
	PermissionModelLogicalModelRead   = "model.logical_model.read"
	PermissionModelLogicalModelUpdate = "model.logical_model.update"
)

var permissionKeys = [...]string{
	"model.logical_model.create",
	"model.logical_model.delete",
	"model.logical_model.read",
	"model.logical_model.update",
}

// PermissionKeys returns the active owner-local Permission keys in stable order.
func PermissionKeys() []string {
	return append([]string(nil), permissionKeys[:]...)
}
