// Code generated by common/authorization/cmd/manifest; DO NOT EDIT.
// Source: transfer/authorization/permissions.yaml (manifest_version=4).

package authorization

const (
	PermissionTransferConfigurationRead   = "transfer.configuration.read"
	PermissionTransferConfigurationUpdate = "transfer.configuration.update"
	PermissionTransferTaskCreate          = "transfer.task.create"
	PermissionTransferTaskDelete          = "transfer.task.delete"
	PermissionTransferTaskExecute         = "transfer.task.execute"
	PermissionTransferTaskRead            = "transfer.task.read"
	PermissionTransferTaskUpdate          = "transfer.task.update"
	PermissionTransferTaskProviderExecute = "transfer.task_provider.execute"
	PermissionTransferTaskProviderRead    = "transfer.task_provider.read"
)

var permissionKeys = [...]string{
	"transfer.configuration.read",
	"transfer.configuration.update",
	"transfer.task.create",
	"transfer.task.delete",
	"transfer.task.execute",
	"transfer.task.read",
	"transfer.task.update",
	"transfer.task_provider.execute",
	"transfer.task_provider.read",
}

// PermissionKeys returns the active owner-local Permission keys in stable order.
func PermissionKeys() []string {
	return append([]string(nil), permissionKeys[:]...)
}
